
all:		tfor


clean:
		rm *.exe log *.log *.err

ppg_prg01:	ppg_prg01.c
		gcc -o ppg_prg01 ppg_prg01.c

cnv_f07:	cnv_f07.c
		gcc -o cnv_f07 cnv_f07.c

cnv_f08:	cnv_f08.c
		gcc -o cnv_f08 cnv_f08.c

tfor:		tfor.c
		gcc -o tfor tfor.c


