msgmmsb6.for                  ,grep -i "ARO_Liabilities"                            ~/wrk/Midas/ABBICAP/*.* 
msgmmsb6.for                  ,grep -i "ARO_Net_Assets"                             ~/wrk/Midas/ABBICAP/*.* 
msgmmsb6.for                  ,grep -i "Other_Deferred_Credits"                     ~/wrk/Midas/ABBICAP/*.* 
msgmmsb6.for                  ,grep -i "Reaquired_Debt_Gain"                        ~/wrk/Midas/ABBICAP/*.* 
msgmmsb6.for                  ,grep -i "Regulatory_Deferred_Credits"                ~/wrk/Midas/ABBICAP/*.* 
namescom.f90                  ,grep -i "ARO_Liabilities"                            ~/wrk/Midas/ABBICAP/*.* 
namescom.f90                  ,grep -i "ARO_Net_Assets"                             ~/wrk/Midas/ABBICAP/*.* 
namescom.f90                  ,grep -i "Other_Deferred_Credits"                     ~/wrk/Midas/ABBICAP/*.* 
namescom.f90                  ,grep -i "Reaquired_Debt_Gain"                        ~/wrk/Midas/ABBICAP/*.* 
namescom.f90                  ,grep -i "Regulatory_Deferred_Credits"                ~/wrk/Midas/ABBICAP/*.* 
