module dsf2
  use dsf1
implicit none
 ! From dsmfncom.mon F77 include file
 integer (kind=2) :: SERVICEMO(MAX_DSM_FINANCIAL_RECORDS), & 
     ONGO_PROG_EXP_ESCAL(MAX_DSM_FINANCIAL_RECORDS), & 
     ONGO_CUST_EXP_ESCAL(MAX_DSM_FINANCIAL_RECORDS), & 
     ONGO_KWH_EXP_ESCAL(MAX_DSM_FINANCIAL_RECORDS), & 
     ONGO_KW_EXP_ESCAL(MAX_DSM_FINANCIAL_RECORDS), & 
     ONGO_PROG_CAP_ESCAL(MAX_DSM_FINANCIAL_RECORDS), & 
     ONGO_CUST_CAP_ESCAL(MAX_DSM_FINANCIAL_RECORDS), & 
     ONGO_NEW_CUST_CAP_ESCAL(MAX_DSM_FINANCIAL_RECORDS), & 
     ONGO_KWH_CAP_ESCAL(MAX_DSM_FINANCIAL_RECORDS), & 
     ONGO_KW_CAP_ESCAL(MAX_DSM_FINANCIAL_RECORDS), & 
     ONGO_NEW_CUST_EXP_ESCAL(MAX_DSM_FINANCIAL_RECORDS), & 
     REBATE_EXP_ESCAL(MAX_DSM_FINANCIAL_RECORDS), & 
     REBATE_CAP_ESCAL(MAX_DSM_FINANCIAL_RECORDS), & 
     DEVICE_APPLIED_TO(MAX_DSM_FINANCIAL_RECORDS), & 
     PARTICIPANT_COST_ESCAL(MAX_DSM_FINANCIAL_RECORDS), & 
     UTIL_NON_ELEC_COST_ESCAL(MAX_DSM_FINANCIAL_RECORDS), & 
     THIRD_PARTY_COST_ESCAL(MAX_DSM_FINANCIAL_RECORDS), & 
     OTH_PARTICIPANT_COST_ESCAL(MAX_DSM_FINANCIAL_RECORDS), & 
     START_PROG_EXP_ESCAL(MAX_DSM_FINANCIAL_RECORDS), & 
     BASE_CUST_EXP_ESCAL(MAX_DSM_FINANCIAL_RECORDS), & 
     REBATE_NEW_EXP_ESCAL(MAX_DSM_FINANCIAL_RECORDS), & 
     START_PROG_CAP_ESCAL(MAX_DSM_FINANCIAL_RECORDS), & 
     BASE_CUST_CAP_ESCAL(MAX_DSM_FINANCIAL_RECORDS), & 
     REBATE_NEW_CAP_ESCAL(MAX_DSM_FINANCIAL_RECORDS), & 
     PARTICIPANT_NEW_COST_ESCAL(MAX_DSM_FINANCIAL_RECORDS), & 
     UTIL_NON_ELEC_NEW_COST_ESCAL(MAX_DSM_FINANCIAL_RECORDS), & 
     THIRD_PARTY_NEW_COST_ESCAL(MAX_DSM_FINANCIAL_RECORDS), & 
     OTH_PARTICIPANT_NEW_COST_ESCAL(MAX_DSM_FINANCIAL_RECORDS), & 
     DSM_ASSET_CLASS_NUM(MAX_DSM_FINANCIAL_RECORDS), & 
     DSM_ASSET_CLASS_VECTOR(MAX_DSM_FINANCIAL_RECORDS)


end module dsf2
