module dsmfrcom
use prod_arrays_dimensions
implicit none
      real :: DSM_EXPENSE_COLECTION(3),DSM_REBATE_COLECTION(3)
      real :: DSM_BOOK_DEP(MAX_FINANCIAL_SIMULATION_YEARS),DSM_CASH,&
           DSM_GPV,DSM_AFUDC, &
           DSM_TAX_DEP(MAX_FINANCIAL_SIMULATION_YEARS), &
           
           DSM_TAX_EXPENSE, &
           DSM_SL_TAX_DEP(MAX_FINANCIAL_SIMULATION_YEARS), &
           DSM_AMORT(MAX_FINANCIAL_SIMULATION_YEARS),&
           DSM_DEFERRED_DEBIT, &
           DSM_DEFERRED_TAX_BASIS(MAX_FINANCIAL_SIMULATION_YEARS), &
           DSM_TAX_PREF_DEP(MAX_FINANCIAL_SIMULATION_YEARS)
           
!  RATE BASE DSM ITEMS &
       real ::RB_DSM_AMORT(MAX_FINANCIAL_SIMULATION_YEARS), &
           RB_DSM_DEFERRED_TAX_BASIS(MAX_FINANCIAL_SIMULATION_YEARS), &
           RB_DSM_AFUDC,RB_DSM_TAX_EXPENSE, &
           DSM_REGULATED_BOOK_DEP(MAX_FINANCIAL_SIMULATION_YEARS), &
           DSM_REGULATED_TAX_DEP(MAX_FINANCIAL_SIMULATION_YEARS), &
           DSM_REGULATED_DEFERRED_DEBIT,DSM_REGULATED_NPV 
		   
!  PARTICIPANT DSM COSTS 
       real :: TOTAL_PARTICIPANT_COSTS, &
           TOTAL_UTIL_NON_ELEC_COSTS, &
           TOTAL_THIRD_PARTY_COSTS, &
           TOTAL_OTH_PARTICIPANT_COSTS
		   
!  PROPERTY TAX BASID 
       real :: DSM_GPV_PROPERTY_TAX(MAX_FINANCIAL_SIMULATION_YEARS), &
           DSM_NPV_PROPERTY_TAX(MAX_FINANCIAL_SIMULATION_YEARS)
             
      REAL :: TOTAL_DSM_ADJ_CLAUSE_COLLECTONS, &
           TOTAL_DSM_BTL_EXPENSES, &
           TOTAL_DSM_BTL_INCOME

!      COMMON: DSM_FINANCIAL_RESULTS

end module dsmfrcom
