grep -i "Monthly_Common_Dividends"                   ~/wrk/Midas/ABBICAP/*.* 
grep -i "Monthly_EBIT"                               ~/wrk/Midas/ABBICAP/*.* 
grep -i "Monthly_EBITAD"                             ~/wrk/Midas/ABBICAP/*.* 
grep -i "Monthly_INCOME_AFTER_INTEREST"              ~/wrk/Midas/ABBICAP/*.* 
grep -i "Monthly_Net_Income"                         ~/wrk/Midas/ABBICAP/*.* 
grep -i "Monthly_Other"                              ~/wrk/Midas/ABBICAP/*.* 
grep -i "Monthly_RETAINED_EARNINGS"                  ~/wrk/Midas/ABBICAP/*.* 
grep -i "Quarterly_Earnings_per_Share"               ~/wrk/Midas/ABBICAP/*.* 
grep -i "WVPA_Member_Energy_Sales"                   ~/wrk/Midas/ABBICAP/*.* 
grep -i "WVPA_Member_Margin"                         ~/wrk/Midas/ABBICAP/*.* 
grep -i "WVPA_Member_Rates_with_SDI"                 ~/wrk/Midas/ABBICAP/*.* 
grep -i "WVPA_Member_Rates_without_SDI"              ~/wrk/Midas/ABBICAP/*.* 
grep -i "WVPA_Non_Member_Margin"                     ~/wrk/Midas/ABBICAP/*.* 
grep -i "WVPA_SDI_Energy_Sales"                      ~/wrk/Midas/ABBICAP/*.* 
