      REAL (kind=4) ::    EMC_ENERGY_REVENUE
      REAL (kind=4) ::  ANN_EMC_ENERGY_REVENUE/0./
      REAL (kind=4) ::  R_EMC_RATE
      REAL (kind=4) ::  ANN_EMC_ENERGY_SALES/0./
      REAL (kind=4) ::  EMC_SALES
      REAL (kind=4) ::  NON_COIN_PEAK
      REAL (kind=4) ::  ANN_NON_COIN_PEAK/0./
      REAL (kind=4) ::  R_ANN_EMC_ENERGY_SALES
      REAL (kind=4) ::  R_ANN_NON_COIN_PEAK
      REAL (kind=4) ::  R_ANN_EMC_ENERGY_REVENUE
      REAL (kind=4) ::  R_ANN_EMC_CAP_REVENUE
      REAL (kind=4) ::  R_ANN_EMC_TRAN_REVENUE
      REAL (kind=4) ::  ANN_SUM_NON_COIN_PEAK/0./
      REAL (kind=4) ::  EMC_TRANS_RATE
      REAL (kind=4) ::  R_ANN_SUM_TRAN_PEAK
      REAL (kind=4) ::
     +   EMC_RESOURCE_CAP/1012./, ! CALC
     +   EMC_EXCESS_OR_DEFICIT, ! CALC
     +   NCEMC_COIN_PEAK, ! AREA FORECASTS
     +   NCEMC_NON_COIN_PEAK, ! AREA FORECASTS
     +   CPS_N_NCPS, ! CALC
     +   CP_DIVIDED_BY_NCP(12), ! DATA
!

     +   SEPA_ALLOCATION/44.885/, ! PER SEEKAMP FAX.
     +   NCEMC_SUPP_BILLING_CPS, ! CALC
! SERVICE OBLIGATION RESOURCES
     +   SOR_A_RESOURCE, ! PER CONTRACT
     +   SOR_B_RESOURCE, ! PER CONTRACT
     +   SOR_C_RESOURCE, ! PER CONTRACT
     +   SOR_D_RESOURCE, ! PER CONTRACT
     +   SOR_E_RESOURCE, ! PER CONTRACT
     +   TOTAL_SERVED_BY_CPL, ! CALC
     +   LOAD_POSS_SERVE_BY_OTHERS, ! CALC
!
     +   ANN_CPS_N_NCPS/0./, ! ACCUMULATED MONTHLY
     +   ANN_NCEMC_SUPP_BILLING_CPS/0./, ! ACCUMULATED MONTHLY
     +   ANN_SOR_A_RESOURCE/0./, ! ACCUMULATED MONTHLY
     +   ANN_SOR_B_RESOURCE/0./, ! ACCUMULATED MONTHLY
     +   ANN_SOR_C_RESOURCE/0./, ! ACCUMULATED MONTHLY
     +   ANN_SOR_D_RESOURCE/0./, ! ACCUMULATED MONTHLY
     +   ANN_SOR_E_RESOURCE/0./, ! ACCUMULATED MONTHLY
     +   ANN_SEPA_ALLOCATION/0./, ! ???
     +   ANN_TOTAL_SERVED_BY_CPL/0./, ! ACCUMULATED MONTHLY
     +   ANN_LOAD_POSS_SERVE_BY_OTHERS/0./, ! ACCUMULATED MONTHLY
! SERVICE OBLIGATION RESOURCE RATES
     +   SOR_A_RATE/0./, ! PER CONTRACT
     +   SOR_B_RATE/0./, ! PER CONTRACT
     +   SOR_C_RATE/0./, ! PER CONTRACT
     +   SOR_D_RATE/0./, ! PER CONTRACT
     +   SOR_E_RATE/0./, ! PER CONTRACT
! SERVICE OBLIGATION RESOURCE REVENUES
     +   SOR_A_REVENUE, ! CALC
     +   SOR_B_REVENUE, ! CALC
     +   SOR_C_REVENUE, ! CALC
     +   SOR_D_REVENUE, ! CALC
     +   SOR_E_REVENUE, ! CALC
     +   TOTAL_EMC_CAP_REVENUE, ! CALC
!
     +   ANN_SOR_A_REVENUE/0./, ! ACCUMULATED MONTHLY
     +   ANN_SOR_B_REVENUE/0./, ! ACCUMULATED MONTHLY
     +   ANN_SOR_C_REVENUE/0./, ! ACCUMULATED MONTHLY
     +   ANN_SOR_D_REVENUE/0./, ! ACCUMULATED MONTHLY
     +   ANN_SOR_E_REVENUE/0./, ! ACCUMULATED MONTHLY
     +   ANN_TOTAL_EMC_CAP_REVENUE/0./ ! CALC
      DATA CP_DIVIDED_BY_NCP
     +            /0.967327,0.933236,0.891418,0.91152,0.890577,0.882076,
     +            0.931185,0.947181,0.936194,0.881214,0.888394,0.899382/
!
! DETAILED REPORT OVERHEAD
!
      LOGICAL (kind=1) ::    ECAP_REPORT_NOT_OPEN/.TRUE./
