module canadian
implicit none
    real :: PROVINCIAL_CAPITAL_TAX,FEDERAL_CAPITAL_TAX
    real :: PROVINCIAL_CAPITAL_TAX_RATE,FEDERAL_CAPITAL_TAX_RATE
    real :: PROVINCIAL_CAP_TAX_DEDUCTION
    real :: FEDERAL_CAPITAL_TAX_DEDUCTION
    real :: PROVINCIAL_CAP_TAX_ADDENDUM
    real :: FEDERAL_CAPITAL_TAX_ADDENDUM
end module canadian
