
module class_parameters
! from finaccom.mon
implicit none
    type t_ns_class_parameters
      REAL :: ADDENUM_2_ASSETS_NEC,ADDENUM_2_LIBS_NEC, &
      ADDENDUM_2_RATE_BASE, &
           CLASS_ADDENDUM_2_OTHER_TAXES, &
           NEW_SUBSIDIARY_INVESTMENT,COMMON_PAYOUT_RATIO, &
           DIVIDEND_PER_SHARE, &
           CSMAX,CSMIN,CSUNIT,EQRATO,FEDERAL_TAX_RATE, &
           ITC_AMORTIZATION_RATE,LDLIFE,LDSINK, &
           LDUNIT,LTDMAX,LTDMIN,LTDRTE,MARKET_2_BOOK,MIN_COV_RATIO, &
           TARGET_EQUITY_RATIO,NPV_IN_ASSETS_NEC,NPV_IN_LIBS_NEC, &
           OPREV_IN_ASSETS_NEC,OPREV_IN_LIBS_NEC, &
          PSMAX,PSMIN,PSRATE,PSRATO,PSSINK,PSUNIT,RBANEC,RBDFTX,RBITC, &
           ROEQU,RETURN_ON_NPV,STD_MAX,STDMIN,STATE_TAX_RATE, &
           SUBSIDIARY_DIVIDEND, &
           SUBSIDIARY_INCOME,OPREV_TAX_RATE,PROPERTY_TAX_RATE, &
           CLASS_OTHER_TAXES_RATE, &
           ADJAFC,ADJDFT,AFDC2,AMTEXP, &
           MNEXP,NFAFC1,NFAFC2, &
           NFCE,NFES,NFEXP,NOPINC,OPEXP, &
           OPEXPT,OPEXTX,PPEXP,PSISS, &
           TAFDCB,TAFEXP,TITCPY, &
           TXOTH,TXPROP,TXSS,WCCHAN,SL_TAX_DEP, &
           TPCAPINSRT,TTXPREFDEP, &
           MAXIMUM_RATE_CHANGE, &
           ADD_CLAUSE_EXP,BASE_RATE_EXP,NOT_COLLECTED_EXP, &
           INC_OTHER1_EXPENSE,INC_OTHER2_EXPENSE, &
           INC_OTHER3_EXPENSE,NF_OWNED,NF_LEASED, &
           NF_EXPENSE_RATEBASE,LEASED_NFCE, &
           AMT_PREP_DEPRE_ADDEN, &
           NUC_DEOM_FUND_RATEBASE, &
           OM_CAPITALIZATION_RATE, &
! ADDED 9/29/92 FOR SR & !  ADDED 9/29/92 FOR SRP
           CLASS_ADDENDUM_TO_PROPERTY_TAX,ADDENDUM_TO_ITC_AMORTIZATED, &
           CASH_OTH_ASSET,NUCL_DECOM_FUND,NUCL_FUND_RETURN, &
           BTL_STATE_EXEXP_TAX_BENEFIT, &
           BTL_FEDERAL_EXEXP_TAX_BENEFIT, &
! ADDED 10/28/92 FOR KEPC & !  ADDED 10/28/92 FOR KEPCO
           DEFERRED_EXPENSE_AMORT_PERIOD, &
           DEFERRED_EXPENSE_CASH, &
           DEFERRED_EXPENSE_AMORT, &
! ADDED 3/26/93 FOR UPA AND OTHER & !  ADDED 3/26/93 FOR UPA AND OTHERS
           MAX_EQUITY_IN_CAP_STRUCTURE, &
           CLASS_BTL_EXPENSES, &
           CASH_FROM_SALE_OF_ASSETS, &
           GROSS_VALUE_OF_SOLD_ASSETS, &
           CUMULATIVE_DEP_ON_SOLD_ASSETS, &
           ADJUSTMENT_TO_DEFERRED_TAXES, &
           ATL_AMORT_OF_BOOK, &
           BTL_AMORT_OF_BOOK, &
           LEASE_PAYMENTS_IN_TIER, &
           CAPITIALIZED_LEASE_ADDITIONS, &
           ATL_LEASE_PAYMENTS, &
           BTL_LEASE_PAYMENTS, &
           BTL_EMISSION_CREDIT_EXPENSE, &
           BTL_EMISSION_CREDIT_REVENUE, &
           ADJ_CLAUSE_REVENUE_ALLOCATION, &
           ADJ_CLAUSE_EXPENSE_ALLOCATION, &
           NET_ADJ_CLAUS_EMIS_AMT, &
           CAPITAL_RECOVERY_NOT_IN_OPAT, &
           BTL_MISC_DEDUCTIONS
           
      REAL :: RB_PCAPINRST,RB_TXEXP, &
           RB_TXPREFDEP,RB_AMRTE,RB_ITCPY,RB_ITC,RB_DDAMRTE, &
           REGULATED_BOOK_DEP, &
           RB_AFDC1,DEFERRED_REVENUES,AMORT_DEF_REVENUES, &
           MIN_ST_INVESTMENTS,RETURN_ON_ST_INVEST, &
           STD_INTEREST_RATE, &
           CLASS_SALES, &
           CLASS_BASE_REVENUE, &
           CLASS_ADJ_CLAUSE_REVENUE, &
           CLASS_OTHER_REVENUE, &
           PARM_AMORTIZATION_ADJUSTMENT, &
           CLASS_BTL_REVENUES, &
           NUCL_DECOM_FUND_RETURN
!  ADDED 5/5/93 FOR FP&L TC WORK     ITEMS 93-100
      REAL :: CUSTOMER_DEPOSITS_PERCENT_REVS, &
           ADDENDUM_TO_CUSTOMER_DEPOSITS, &
           INTEREST_ON_CUSTOMER_DEPOSITS, &
           STD_IN_WEIGHTED_COST_PERCENT, &
           CUSTOMER_DEPOSITS_IN_WC_PERCENT, &
           DEF_ITC_IN_WC_PERCENT, &
           DEF_TAX_CR_IN_WC_PERCENT, &
           MAX_COMMON_BUY_BACK, &
! ADDED 7/15/93 FOR WKP ITEMS 105-10 & !  ADDED 7/15/93 FOR WKP ITEMS 105-108
           CIAC_CASH, &
           CIAC_AMORTIZATION_RATE, &
           CIAC_AMORTIZATION_ADDENDUM, &
           CIAC_EXCLUDED_FROM_RATEBASE, &
! ITEMS 120-122 3/9/95 ADDED FOR SHAREHOLDER VALU & !  ITEMS 120-122 3/9/95 ADDED FOR SHAREHOLDER VALUE
           COST_OF_CAPITAL_RISK_ADJUSTMENT, &
           ADJUSTMENT_2_ECONOMIC_ASSETS, &
           ADJUSTMENT_TO_OPERATING_PROFITS, &
           DEFERRED_TAX_ADJUSTMENT, &
           LTD_SINKING_FUND_LAG, &
           PS_SINKING_FUND_LAG, &
           CAP_LEASES_IN_RATEBASE, &
           INCOME_TAX_DEPRECIATION, &
           ACE_TAX_DEPRECIATION, &
           TAX_PREFERENCE_DEPRECIATION, &
           CIAC_BALANCE_IN_WC_PERCENT, &
           MINIMUM_COMMON_STOCK_BALANCE, &
           DEPOSITS_EXCLUDED_FROM_RATEBASE
!
!  ITEMS 133-140 10/16/96 ADDED FOR SRP AND GENERAL
      REAL*4 :: MAX_SHORT_TERM_INVESTMENT, &
             MIN_LONG_TERM_INVESTMENT, &
             MAX_LONG_TERM_INVESTMENT, &
             CHANGE_IN_LONG_TERM_INVESTMENTS, &
             RETURN_ON_LONG_TERM_INVESTMENTS, &
             RETIREE_MEDICAL_PAYMENTS, &
             RETURN_RETIREMENT_MEDICAL_FUND, &
             CHANGE_2_DECOMMISSIONING_LIAB, &
             ADJUSTMENT_2_OP_REV_TAX, & !  144
             OTHER_TAXES_PERCENT_OF_EXPENSES, & !  145
             ADDENDUM_2_SHARES_ISSUED, &
             STATE_DEDUC_PERCT_OF_TIB4DEDUC, &
             FED_DEDUC_PERCT_OF_TIB4DEDUC, &
             REA_MARGIN_ADDENDUM
!  ADDED 3/21/05
      REAL*4 RB_INCLUDED_DEF_TAXES_DR_RATE, & !  155
             RB_EXCLUDED_PENSION_LIABILITY_RATE, & !  156
             RB_EXCLUDED_Deferred_Gain_RATE, & !  157
             RB_EXCLUDED_Storm_Reserve_RATE, & !  158
             RB_EXCLUDED_Accrued_Vacation_Pay_RATE, & ! 159
             RB_INCLUDED_DEFERRED_REVENUES_RATE,  & !  160
             ODEC_MaxEquityRatio, & !  161
             ODEC_MinPayoutRatio, & !  162
             ODEC_MaxPayoutRatio, & !  163
             ODEC_PercentREReduction, & !  164
             ODEC_DollarREReduction  ! 165
     end type t_ns_class_parameters
     
     ! SAVE required by Lahey, and should be implicit per the Fortran standard.
     type(t_ns_class_parameters), save :: ns_class_parameters ! namespace
!



end module class_parameters
