      MODULE coal_cnw_files_read_input
! COAL_CONTRACTS_READ_DATA
         ! OUTPUT FILE RECORD LENGTH
         INTEGER (KIND=2), PARAMETER :: COAL_CONTRACTS_LRECL=512
         CHARACTER (LEN=40), PARAMETER :: &
                  COAL_CONTRACTS_BINARY_FILE_NAME ="COAL_CONTRACTS.BIN"
        LOGICAL (KIND=4),SAVE ::COAL_CONTRACTS_DATA_FILE_EXISTS=.FALSE.
        CHARACTER (LEN=2),SAVE ::PROCESSING_COALCONTRACTS_FILEOL='BC'
        INTEGER (KIND=2),SAVE :: ACTIVE_COALCONTRACTS_IN_BF=0, &
                                   ACTIVE_COALCONTRACTS_IN_OVL=0
! PLANT_DEMAND_READ_DATA
         ! OUTPUT FILE RECORD LENGTH
         INTEGER (KIND=2), PARAMETER :: PLANT_DEMAND_LRECL=512
         CHARACTER (LEN=40), PARAMETER :: &
                 PLANT_DEMAND_BINARY_FILE_NAME ="PLANT_COAL_DEMAND.BIN"
        LOGICAL (KIND=4), SAVE :: PLANT_DEMAND_DATA_FILE_EXISTS=.FALSE.
        CHARACTER (LEN=2), SAVE :: PROCESSING_PLANT_DEMAND_FILE_OL='BC'
         INTEGER (KIND=2), SAVE :: ACTIVE_PLANT_DEMAND_IN_BASEFILE=0, &
                                   ACTIVE_PLANT_DEMAND_IN_OVERLAY=0
! GENERIC_DEMAND_READ_DATA
         ! OUTPUT FILE RECORD LENGTH
         INTEGER (KIND=2), PARAMETER :: GENERIC_DEMAND_LRECL=256
         CHARACTER (LEN=40), PARAMETER :: &
             GENERIC_DEMAND_BINARY_FILE_NAME ="GENERIC_COAL_DEMAND.BIN"
        LOGICAL(KIND=4),SAVE :: GENERIC_DEMAND_DATA_FILE_EXISTS=.FALSE.
        CHARACTER(LEN=2),SAVE :: PROCESSING_GENERIC_DEMAND_FILE_OL='BC'
       INTEGER (KIND=2), SAVE :: ACTIVE_GENERIC_DEMAND_IN_BASEFILE=0, &
                                   ACTIVE_GENERICDEMAND_IN_OVERLAY=0
! COAL_TRANSPORTATION_READ_DATA
         INTEGER (KIND=2), PARAMETER :: COAL_LINK_LRECL=256
         CHARACTER (LEN=40) :: COAL_LINK_BINARY_FILE_NAME(2)=(/ &
                                        "COAL_TRANSPORTATION.BIN   ", &
                                         "COAL_TRANSPORT_GENERIC.BIN"/)
         LOGICAL (KIND=4) ::  COAL_LINK_DATA_FILE_EXISTS=.FALSE., &
                                  GENERIC_LINK_DATA_FILE_EXISTS=.FALSE.
         CHARACTER (LEN=2) :: &
                          PROCESSING_COAL_LINK_FILE_OL(2)=(/"BC","BC"/)
         INTEGER (KIND=2) :: ACTIVE_COAL_LINK_IN_BASEFILE(2)=2*0, &
                                 ACTIVE_COAL_LINK_IN_OVERLAY(2)=2*0, &
                                   COAL_TRANSPORT_RECORDS(2)=2*0
         INTEGER (KIND=4) :: MAX_EV_PLANT_ID_BASEFILE(2)=2*0, &
                             MIN_EV_PLANT_ID_BASEFILE(2)=2*99999999, &
                             MAX_EV_PLANT_ID_OVLFILE(2)=2*0, &
                             MIN_EV_PLANT_ID_OVLFILE(2)=2*99999999
! COAL_BASIN_READ_DATA
         INTEGER (KIND=2), PARAMETER :: BASIN_LRECL=128
         CHARACTER (LEN=40), PARAMETER :: &
                          BASIN_BINARY_FILE_NAME ="COAL_BASIN.BIN"
         LOGICAL (KIND=4), SAVE ::  BASIN_DATA_FILE_EXISTS=.FALSE.
         CHARACTER (LEN=2), SAVE :: PROCESSING_BASIN_FILE_OL='BC'
         INTEGER (KIND=4), SAVE :: ACTIVE_BASINS_IN_BASEFILE=0, &
                                   ACTIVE_BASINS_IN_OVERLAY=0, &
                                   MAX_BASIN_ID_BASEFILE=0, &
                                   MAX_BASIN_ID_OVLFILE=0
! COAL_SUPPLY_READ_DATA
         INTEGER (KIND=2), PARAMETER :: COAL_SUPPLY_LRECL=256
         CHARACTER (LEN=40), PARAMETER :: &
                        COAL_SUPPLY_BINARY_FILE_NAME ="COAL_SUPPLY.BIN"
        LOGICAL (KIND=4), SAVE ::  COAL_SUPPLY_DATA_FILE_EXISTS=.FALSE.
         CHARACTER (LEN=2), SAVE :: PROCESSING_COAL_SUPPLY_FILE_OL='BC'
         INTEGER (KIND=4), SAVE :: ACTIVE_FUEL_SUPPLY_BASEFILE=0, &
                                   ACTIVE_FUEL_SUPPLY_OVERLAY=0, &
                                   MAX_SUPPLY_BASIN_ID_BASEFILE=0, &
                                   MAX_SUPPLY_BASIN_ID_OVLFILE=0
! COAL_SO2_Scrubber_READ_DATA
         INTEGER (KIND=2), PARAMETER :: COAL_SO2_Scrubber_LRECL=128
         CHARACTER (LEN=40), PARAMETER :: &
             COAL_SO2_Scrubber_BINARY_FILE ="COAL_SO2_Scrubber.BIN"
        LOGICAL (KIND=4), SAVE :: COAL_SO2_Scrubber_FILE_EXISTS=.FALSE.
         CHARACTER (LEN=2), SAVE :: &
                              PROCESSING_COAL_SO2Scrbr_FILEOL='BC'
         INTEGER (KIND=2), SAVE :: ACTIVE_SO2_Scrubber_BASEFILE=0, &
                                   ACTIVE_SO2_Scrubber_OVERLAY=0
      END MODULE COAL_cnw_FILES_READ_INPUT
!     ****************************************************************
