module elrptcom
! Used to be COMMON BLOCK FOR ELRPT ITEMS. Now it's a module
!
implicit none
integer (kind=4) :: SEASONAL_ENRG_LIMITED_CAPACITY, &
                ANNUAL_PEAK1,ANNUAL_PEAK2,ANNUAL_BASE1,ANNUAL_BASE2, &
                MONTHLY_BEFORE_PEAK(12),MONTHLY_AFTER_PEAK(12), &
                MONTHLY_BEFORE_BASE(12),MONTHLY_AFTER_BASE(12), &
                ANNUAL_BEFORE_ENRG,ANNUAL_AFTER_ENRG, &
                ANNUAL_DEFERENCE_ENRG,MONTHLY_ENERGY_COSTS(12), &
                MONTHLY_BEFORE_ENERGY(12),MONTHLY_AFTER_ENERGY(12)
end module elrptcom
