module palo_alto_mod
! from paltocom.mon
implicit none
    real :: RETURN_ON_RESERVES,CPA_SHARE_OF_NCPA_DS
    real :: CPA_SHARE_OF_TANC_DS
    real :: OTHER_DEBT_SERVICE,MINIMUM_RESERVE_BALANCE
    real :: MAXIMUM_RESERVE_BALANCE,TARGET_RESERVE_BALANCE
    real :: MINIMUM_ANNUAL_RATE_ADJUSTMENT
    real :: MAXIMUM_ANNUAL_RATE_ADJUSTMENT,ADDENDUM_TO_SALES_REVENUE
    real :: ADDENDUM_TO_INTEREST_REVENUE,OTHER_REVENUE
    real :: REVENUE_CONTRACTING_AGENCIES,BOND_REVENUE
    real :: ADDENDUM_TO_PURCHASE_EXPENSES,PURCHASE_EXPENSES_IN_WC
    real :: OPERATING_EXPENSES,OPERATING_EXPENSES_IN_WC
    real :: CONTINGENCY_EXPENSES,CONTINGENCY_EXPENSES_IN_WC
    real :: ADMINISTRATION_EXPENSES,ADMINISTRATION_EXPENSES_IN_WC
    real :: ALLOCATED_EXPENSES,ALLOCATED_EXPENSES_IN_WC
    real :: OTHER_EXPENSE,OTHER_EXPENSE_IN_WC
    real :: CIP_TO_GENERAL_FUND,RENT_EXPENSE
    real :: RENT_IN_WORKING_CAPITAL,ALLOCATED_CHARGES
    real :: ALLOCATED_CHARGES_IN_WC,OTHER_TRANSFER
    real :: OTHER_TRANSFER_IN_WC,TOTAL_CIP_EXPENDITURES
    real :: CIP_ALLOCATED_TO_RATE_BASE,DEPRECIATION_RATE
    real :: ADDENDUM_TO_DEPRECIATION,ADDENDUM_TO_WORKING_CAPITAL
    real :: TRANSFER_TO_GENERAL_FUND_RATE,CIP_ALLOCATED_TO_WC
    real :: DSM_EXPENDITURES,DSM_IN_WC
    real :: LOAD_MANAGEMENT_EXPENDITURES,LOAD_MANAGEMENT_IN_WC
    real :: X_PRICE_MUNI_1,X_PRICE_MUNI_2,X_PRICE_MUNI_3
    real :: CALAVERAS_RESERVE_BALANCE
    
    ! INITIZATION FILE
    real :: TOTAL_RESERVE_BALANCE(2),FIXED_ASSETS(2)
    real :: SYSTEM_AVERAGE_RATE(2),SPECIAL_RESERVE_BALANCE(2)
    
    ! INTERNAL VARIABLES
    real :: EXPENSES,CASH_TRANSFERS,DEBT_SERVICE
    real :: DEPRECIATION,CONTRIBUTED_CIP_IN_RB,AVERAGE_FIXED_ASSETS
    real :: WORKING_CAPITAL_IN_RB,RATE_BASE,TRANSFER_TO_GENERAL_FUND
    real :: INTEREST_REVENUE,REVENUES
    real :: TOTAL_DSM_EXPENDITURES,SALES_REVENUES,TOTAL_USES
    real :: CHANGE_IN_RESERVES,TO_SPECIAL_RESERVE,FROM_RESERVES
    real :: TO_RESERVES,RATE_CHANGE,ADDITIONAL_REVENUES
    real :: DESIRED_RESERVE_BALANCE,PURCHASED_EXPENSES
    real :: BONDS_ISSUED
end module palo_alto_mod
