./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/8800com.f90" -out="repo4/8800com.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/ABBCapacityMarketRept.f90" -out="repo4/ABBCapacityMarketRept.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/ACRSLCOM.MON" -out="repo4/ACRSLCOM.MON" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/Abb_CapMarketRptData.f90" -out="repo4/Abb_CapMarketRptData.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/Ac_equiv.MON" -out="repo4/Ac_equiv.MON" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/COAL_VECTOR_OBJ.F90" -out="repo4/COAL_VECTOR_OBJ.F90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/CapacityOptionsFileResourceIndexes.f90" -out="repo4/CapacityOptionsFileResourceIndexes.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/Coal_Model_Modules.f90" -out="repo4/Coal_Model_Modules.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/Coal_modules_makeovl.F90" -out="repo4/Coal_modules_makeovl.F90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/DSMCOM.MON" -out="repo4/DSMCOM.MON" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/DSMFNCOM.MON" -out="repo4/DSMFNCOM.MON" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/FINACCOM.MON" -out="repo4/FINACCOM.MON" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/FINANCOM.MON" -out="repo4/FINANCOM.MON" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/LDPROB01.FOR" -out="repo4/LDPROB01.FOR" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/MIDASFileIndexingRoutines.f90" -out="repo4/MIDASFileIndexingRoutines.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/ReadEnergyProductsData.f90" -out="repo4/ReadEnergyProductsData.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/SPINLIB.MON" -out="repo4/SPINLIB.MON" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/WinFileFindData.for" -out="repo4/WinFileFindData.for" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/aa_objt.f90" -out="repo4/aa_objt.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/ac_elmeq.mon" -out="repo4/ac_elmeq.mon" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/aitvafin.f90" -out="repo4/aitvafin.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/aitvaprod.f90" -out="repo4/aitvaprod.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/andecomp.f90" -out="repo4/andecomp.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/annl_nuc.f90" -out="repo4/annl_nuc.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/annual_cl_unit.f90" -out="repo4/annual_cl_unit.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/annual_contracts.f90" -out="repo4/annual_contracts.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/annual_output_report_preparer.f90" -out="repo4/annual_output_report_preparer.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/annual_trans_report_handler.f90" -out="repo4/annual_trans_report_handler.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/bfil_obj.f90" -out="repo4/bfil_obj.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/block_summary_items_handler.f90" -out="repo4/block_summary_items_handler.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/cal_marginal_interface.f90" -out="repo4/cal_marginal_interface.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/calendar.f90" -out="repo4/calendar.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/cap_objt.f90" -out="repo4/cap_objt.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/cap_prod_costs.f90" -out="repo4/cap_prod_costs.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/capacity_arrays.f90" -out="repo4/capacity_arrays.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/capacity_options_alloc_vars.f90" -out="repo4/capacity_options_alloc_vars.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/capacity_options_fixed_variables.f90" -out="repo4/capacity_options_fixed_variables.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/cat2objt.f90" -out="repo4/cat2objt.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/catawba.f90" -out="repo4/catawba.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/cf_objt.f90" -out="repo4/cf_objt.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/check_alloc_status_mod.f90" -out="repo4/check_alloc_status_mod.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/cl_data.f90" -out="repo4/cl_data.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/cl_screen_data.f90" -out="repo4/cl_screen_data.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/cl_unit_vars.f90" -out="repo4/cl_unit_vars.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/cl_units_read_data.f90" -out="repo4/cl_units_read_data.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/cla_decs.f90" -out="repo4/cla_decs.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/cla_fuel.f90" -out="repo4/cla_fuel.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/cla_objt.for" -out="repo4/cla_objt.for" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/cla_objt_arrays.f90" -out="repo4/cla_objt_arrays.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/class_run_switchesc.f90" -out="repo4/class_run_switchesc.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/class_run_switchesl1.f90" -out="repo4/class_run_switchesl1.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/class_run_switchesl4.f90" -out="repo4/class_run_switchesl4.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/clgetter.f90" -out="repo4/clgetter.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/clm_objt.f90" -out="repo4/clm_objt.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/closfile.f90" -out="repo4/closfile.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/clreport.for" -out="repo4/clreport.for" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/clreport_decs.f90" -out="repo4/clreport_decs.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/clreport_routines.f90" -out="repo4/clreport_routines.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/cls_load.f90" -out="repo4/cls_load.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/cls_runs.f90" -out="repo4/cls_runs.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/cn_objt.f90" -out="repo4/cn_objt.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/cnwmsubs.f90" -out="repo4/cnwmsubs.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/co2_cap_n_trade.f90" -out="repo4/co2_cap_n_trade.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/co2_data.f90" -out="repo4/co2_data.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/co2_market_abatement_curves.f90" -out="repo4/co2_market_abatement_curves.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/co_objt.for" -out="repo4/co_objt.for" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/coal_main_prg.f90" -out="repo4/coal_main_prg.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/contract_handler.f90" -out="repo4/contract_handler.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/contracts_data.f90" -out="repo4/contracts_data.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/conversion_routines.f90" -out="repo4/conversion_routines.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/cpl_objt.f90" -out="repo4/cpl_objt.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/csvdat.f90" -out="repo4/csvdat.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/ct_objt.f90" -out="repo4/ct_objt.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/de_objt.f90" -out="repo4/de_objt.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/derivatives_report_handler.f90" -out="repo4/derivatives_report_handler.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/dr_booth.f90" -out="repo4/dr_booth.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/dr_both2.f90" -out="repo4/dr_both2.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/dreptcom.f90" -out="repo4/dreptcom.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/drilling_rept_params.f90" -out="repo4/drilling_rept_params.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/dsex_data.f90" -out="repo4/dsex_data.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/dsex_obj.f90" -out="repo4/dsex_obj.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/dsm_objt.for" -out="repo4/dsm_objt.for" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/dsmfrcom.f90" -out="repo4/dsmfrcom.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/dsscreen.f90" -out="repo4/dsscreen.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/dsslam.f90" -out="repo4/dsslam.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/duplicate_name_checker.f90" -out="repo4/duplicate_name_checker.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/ec_objt.f90" -out="repo4/ec_objt.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/eco.f90" -out="repo4/eco.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/econintr.f90" -out="repo4/econintr.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/el_objt.f90" -out="repo4/el_objt.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/elreport.for" -out="repo4/elreport.for" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/elrptcom.f90" -out="repo4/elrptcom.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/en_objt.f90" -out="repo4/en_objt.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/end_routine.f90" -out="repo4/end_routine.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/endpoint.f90" -out="repo4/endpoint.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/enrg_prod_costs.f90" -out="repo4/enrg_prod_costs.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/enrg_prod_costsi4.f90" -out="repo4/enrg_prod_costsi4.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/enrg_prod_costsr8.f90" -out="repo4/enrg_prod_costsr8.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/enrglimt.f90" -out="repo4/enrglimt.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/enrglimt.for" -out="repo4/enrglimt.for" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/envircom.f90" -out="repo4/envircom.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/error_central.f90" -out="repo4/error_central.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/errormsg.f90" -out="repo4/errormsg.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/escalation_variables.f90" -out="repo4/escalation_variables.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/esrn_decs.f90" -out="repo4/esrn_decs.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/esrn_obj.f90" -out="repo4/esrn_obj.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/expansion.f90" -out="repo4/expansion.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/facalg.f90" -out="repo4/facalg.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/fainpt.f90" -out="repo4/fainpt.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/faintcom.f90" -out="repo4/faintcom.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/fc_objt.f90" -out="repo4/fc_objt.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/fe_objt.f90" -out="repo4/fe_objt.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/fi_objt.f90" -out="repo4/fi_objt.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/file_existence.f90" -out="repo4/file_existence.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/file_units.f90" -out="repo4/file_units.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/filemod.f90" -out="repo4/filemod.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/filename_tracker.f90" -out="repo4/filename_tracker.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/finacelm.for" -out="repo4/finacelm.for" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/finaclp2.for" -out="repo4/finaclp2.for" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/finanbse.for" -out="repo4/finanbse.for" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/findovls.f90" -out="repo4/findovls.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/finnucfl.f90" -out="repo4/finnucfl.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/fiscal_reporting_season_handler.f90" -out="repo4/fiscal_reporting_season_handler.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/flusher.f90" -out="repo4/flusher.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/fn_objt.f90" -out="repo4/fn_objt.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/foshydi2com.f90" -out="repo4/foshydi2com.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/fp_objt.f90" -out="repo4/fp_objt.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/frc2.f90" -out="repo4/frc2.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/ft_interfaces.f90" -out="repo4/ft_interfaces.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/fuel_types.f90" -out="repo4/fuel_types.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/fuelcat.f90" -out="repo4/fuelcat.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/fuelused.f90" -out="repo4/fuelused.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/fuelused_decs.f90" -out="repo4/fuelused_decs.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/gas_objt.for" -out="repo4/gas_objt.for" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/globecom.f90" -out="repo4/globecom.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/group_prod.f90" -out="repo4/group_prod.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/grx_captrade.f90" -out="repo4/grx_captrade.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/grx_data.f90" -out="repo4/grx_data.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/grx_electric.f90" -out="repo4/grx_electric.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/grx_extend.f90" -out="repo4/grx_extend.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/grx_planning_routines.f90" -out="repo4/grx_planning_routines.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/grxmodules.f90" -out="repo4/grxmodules.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/hesi.f90" -out="repo4/hesi.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/hesi_el.f90" -out="repo4/hesi_el.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/hesi_gendecs.f90" -out="repo4/hesi_gendecs.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/hesi_i4.f90" -out="repo4/hesi_i4.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/hourly_products_data.f90" -out="repo4/hourly_products_data.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/hourlyproductsdata.f90" -out="repo4/hourlyproductsdata.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/icap_results.f90" -out="repo4/icap_results.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/icap_summary_report.f90" -out="repo4/icap_summary_report.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/in_objt.f90" -out="repo4/in_objt.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/interg82.f90" -out="repo4/interg82.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/internal_operation_switches.f90" -out="repo4/internal_operation_switches.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/iostatmsg.f90" -out="repo4/iostatmsg.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/irec_endpoint_control.f90" -out="repo4/irec_endpoint_control.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/kepcocom.f90" -out="repo4/kepcocom.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/lcarry.f90" -out="repo4/lcarry.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/lmg_objt.f90" -out="repo4/lmg_objt.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/logging.f90" -out="repo4/logging.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/logging_decs.f90" -out="repo4/logging_decs.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/lpintcom.f90" -out="repo4/lpintcom.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/lpmatinv.f90" -out="repo4/lpmatinv.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/lpsolver.f90" -out="repo4/lpsolver.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/mainovl.f90" -out="repo4/mainovl.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/margnobj.f90" -out="repo4/margnobj.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/mcbtnmcom.f90" -out="repo4/mcbtnmcom.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/midas_decs.f90" -out="repo4/midas_decs.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/midasmod.for" -out="repo4/midasmod.for" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/midasxp.f90" -out="repo4/midasxp.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/miscmod.f90" -out="repo4/miscmod.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/mk_file_exist_manager.f90" -out="repo4/mk_file_exist_manager.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/mmrev_decs.f90" -out="repo4/mmrev_decs.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/modules.f90" -out="repo4/modules.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/monthly_icap.f90" -out="repo4/monthly_icap.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/monthly_pw_report_handler.f90" -out="repo4/monthly_pw_report_handler.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/monthly_trans_report_handler.f90" -out="repo4/monthly_trans_report_handler.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/msg_win_api_calls.f90" -out="repo4/msg_win_api_calls.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/msgandec.for" -out="repo4/msgandec.for" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/msgindex.f90" -out="repo4/msgindex.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/msgmmadm.f90" -out="repo4/msgmmadm.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/msgmmasb.for" -out="repo4/msgmmasb.for" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/msgmmcom.f90" -out="repo4/msgmmcom.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/msgmmdbt.for" -out="repo4/msgmmdbt.for" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/msgmmdfd.f90" -out="repo4/msgmmdfd.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/msgmmea.f90" -out="repo4/msgmmea.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/msgmmexprevcash.f90" -out="repo4/msgmmexprevcash.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/msgmmfa.f90" -out="repo4/msgmmfa.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/msgmmfv.f90" -out="repo4/msgmmfv.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/msgmminp.for" -out="repo4/msgmminp.for" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/msgmmout.for" -out="repo4/msgmmout.for" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/msgmmpyb.f90" -out="repo4/msgmmpyb.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/msgmmrev.f90" -out="repo4/msgmmrev.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/msgmmsb6.for" -out="repo4/msgmmsb6.for" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/msgmmsb6b.f90" -out="repo4/msgmmsb6b.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/msgmmtax.f90" -out="repo4/msgmmtax.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/msgnorm.f90" -out="repo4/msgnorm.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/msgold95rw.f90" -out="repo4/msgold95rw.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/msgoutpt.for" -out="repo4/msgoutpt.for" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/msgprosymrevexp.f90" -out="repo4/msgprosymrevexp.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/mthnmcom.f90" -out="repo4/mthnmcom.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/mwunih.f90" -out="repo4/mwunih.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/namescom.f90" -out="repo4/namescom.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/newfred2.for" -out="repo4/newfred2.for" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/newpkshf.f90" -out="repo4/newpkshf.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/objtfunc.f90" -out="repo4/objtfunc.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/p_fuel.f90" -out="repo4/p_fuel.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/palo_alto_mod.f90" -out="repo4/palo_alto_mod.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/params.f90" -out="repo4/params.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/pf_objt.f90" -out="repo4/pf_objt.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/picadisp.f90" -out="repo4/picadisp.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/pms.f90" -out="repo4/pms.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/pn_objt.f90" -out="repo4/pn_objt.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/poolcom.f90" -out="repo4/poolcom.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/postfix.f90" -out="repo4/postfix.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/pp_objt.f90" -out="repo4/pp_objt.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/prim_mover_idx.f90" -out="repo4/prim_mover_idx.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/prngener.f90" -out="repo4/prngener.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/pro_cost.f90" -out="repo4/pro_cost.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/procost_data.f90" -out="repo4/procost_data.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/prod2com.f90" -out="repo4/prod2com.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/prod_arrays_dimensions.f90" -out="repo4/prod_arrays_dimensions.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/prodcom.f90" -out="repo4/prodcom.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/prosymmodule.f90" -out="repo4/prosymmodule.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/rdi_objt.f90" -out="repo4/rdi_objt.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/reaenrg.for" -out="repo4/reaenrg.for" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/reference_loads.f90" -out="repo4/reference_loads.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/reference_loadsi2.f90" -out="repo4/reference_loadsi2.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/retslcom.f90" -out="repo4/retslcom.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/rollscom.f90" -out="repo4/rollscom.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/rps_data.f90" -out="repo4/rps_data.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/rps_index_translate_mod.f90" -out="repo4/rps_index_translate_mod.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/rpth_obj.f90" -out="repo4/rpth_obj.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/rptreccontrol.f90" -out="repo4/rptreccontrol.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/screen_initialization.f90" -out="repo4/screen_initialization.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/servcom.f90" -out="repo4/servcom.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/servicac.f90" -out="repo4/servicac.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/sf_objt.f90" -out="repo4/sf_objt.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/shared_vars_interg82.f90" -out="repo4/shared_vars_interg82.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/sizecom.f90" -out="repo4/sizecom.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/snszmds.f90" -out="repo4/snszmds.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/spindriftlib.f90" -out="repo4/spindriftlib.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/spinfunc.f90" -out="repo4/spinfunc.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/start_stop_outage.f90" -out="repo4/start_stop_outage.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/startovl.f90" -out="repo4/startovl.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/startup_tasks.f90" -out="repo4/startup_tasks.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/string.f90" -out="repo4/string.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/tastgp.f90" -out="repo4/tastgp.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/tf_objt.f90" -out="repo4/tf_objt.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/tf_objt2.f90" -out="repo4/tf_objt2.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/tf_objt_vars.f90" -out="repo4/tf_objt_vars.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/tim.f90" -out="repo4/tim.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/tran2.f90" -out="repo4/tran2.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/tran_c_variables.f90" -out="repo4/tran_c_variables.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/trans_peak_info.f90" -out="repo4/trans_peak_info.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/trans_slope.f90" -out="repo4/trans_slope.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/trans_weekend_peak_days.f90" -out="repo4/trans_weekend_peak_days.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/transact_fuel_report_handler.f90" -out="repo4/transact_fuel_report_handler.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/transobj.f90" -out="repo4/transobj.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/transobj2.f90" -out="repo4/transobj2.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/transobj2_vars.f90" -out="repo4/transobj2_vars.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/trnsfrm3.f90" -out="repo4/trnsfrm3.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/up_objt.f90" -out="repo4/up_objt.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/weekscom.f90" -out="repo4/weekscom.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/wh_objt.f90" -out="repo4/wh_objt.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/wkarry.f90" -out="repo4/wkarry.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/wvpa_data_bases.f90" -out="repo4/wvpa_data_bases.f90" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/wvpacooprevenuecals.for" -out="repo4/wvpacooprevenuecals.for" -aux=p.err -log=p.log --chgalo > log2
./tfor -v -opciones=d5 -debug=1 -tool=6 -inp="repo1/wvpartrk.f90" -out="repo4/wvpartrk.f90" -aux=p.err -log=p.log --chgalo > log2
