module kepcocom
      use prod_arrays_dimensions
implicit none

      INTEGER(kind=2) :: MAX_CONTROL_AREA_ALLOCATIONS
      PARAMETER (MAX_CONTROL_AREA_ALLOCATIONS=90) 
      INTEGER(kind=2) :: CLASS_CONTROL_AREA(6)
      LOGICAL(kind=1) :: KEPCO,CAPACITY_ALLOCATION_ABSOLUTE, &
                ENERGY_ALLOCATION_ABSOLUTE,PRINT_HEADER, &
                REALLY_KEPCO, &
                WABASH_VALLEY, &
                WABASH_IM_NIPSCO_PSI, &
                WABASH_IM_NIPSCO
      INTEGER(kind=2) :: NUMBER_OF_AREAS
      INTEGER(kind=1) :: AREA_LAST_RESOURCE(6), &
                EMERGENCY_ENERGY_CONTRACT, &
                MAINTENANCE_ENERGY_CONTRACT
      INTEGER(kind=2) :: CL_ALLOCATE_POINTR(MAX_CL_UNITS), &
                FIRST_MAINTENANCE_PERIOD
      INTEGER(kind=2) :: GIBSON_POINTER, &
                GIBSON_BACKUP_POINTER, &
                PSI_AREA_LAST_RESOURCE_POINTER, &
                MARKET_PURCHASE_POINTER
!
!  OUTPUTS BY AREA
!
      
      REAL &
           KEPCO_ANNUAL_AREA_SALES(6)!
!  INPUTS FOR KEPCO
!
      REAL :: AREA_RESOURCE_LOSES(6,12,MAX_CONTROL_AREA_ALLOCATIONS)
      real :: KEPCO_ANNUAL_DUMP_ENERGY(6)
      CHARACTER (len=2) :: RESOURCE_FILE(MAX_CONTROL_AREA_ALLOCATIONS)
      CHARACTER (len=1) :: AREA_ALLOCATION_METHOD( &
          MAX_CONTROL_AREA_ALLOCATIONS)


  real :: CL_RESOURCE_ANNUAL_AREA_ENRG(6,MAX_CONTROL_AREA_ALLOCATIONS)
  integer (kind=2) :: CT_ALLOCATE_POINTR(MAX_CONTRACTS)
  integer (kind=2) :: EL_ALLOCATE_POINTR(MAX_EL_UNITS)
  REAL &
        AREA_CAPACITY_LOSSES(6,12,MAX_CONTROL_AREA_ALLOCATIONS), &
        AREA_ENRG_ALLOCATORS(6,12,MAX_CONTROL_AREA_ALLOCATIONS), &
        AREA_CAP_ALLOCATORS(6,12,MAX_CONTROL_AREA_ALLOCATIONS), &
        AREA_ENERGY(6,12),AREA_CAPACITY(6,12), &
        CAPACITY_LAST_RESOURCE(6,12),ENRG_LAST_RESOURCE(6,12), &
        AREA_SURPLUS(6,12), &
        AREA_SURPLUS_CAPACITY(6,12), &
        CT_RESOURCE_ANNUAL_AREA_ENRG(6,MAX_CONTROL_AREA_ALLOCATIONS), &
        EL_RESOURCE_ANNUAL_AREA_ENRG(6,MAX_CONTROL_AREA_ALLOCATIONS), &
        CL_RESOURCE_ANNUAL_AREA_CAP(6,MAX_CONTROL_AREA_ALLOCATIONS), &
        CT_RESOURCE_ANNUAL_AREA_CAP(6,MAX_CONTROL_AREA_ALLOCATIONS), &
        EL_RESOURCE_ANNUAL_AREA_CAP(6,MAX_CONTROL_AREA_ALLOCATIONS), &
        ANNUAL_AREA_ENERGY(6), &
        ANNUAL_AREA_SURPLUS_ENERGY(6), &
        EMERGENCY_ENERGY, &
        MAINTENANCE_ENERGY, &
        AREA_ENERGY_LOSSES, &
        CL_ANNUAL_EMERGENCY_ENERGY(MAX_CONTROL_AREA_ALLOCATIONS), &
        CT_ANNUAL_EMERGENCY_ENERGY(MAX_CONTROL_AREA_ALLOCATIONS), &
        EL_ANNUAL_EMERGENCY_ENERGY(MAX_CONTROL_AREA_ALLOCATIONS), &
        CL_ANNUAL_MAINTENANCE_ENERGY(MAX_CONTROL_AREA_ALLOCATIONS), &
        CT_ANNUAL_MAINTENANCE_ENERGY(MAX_CONTROL_AREA_ALLOCATIONS), &
        EL_ANNUAL_MAINTENANCE_ENERGY(MAX_CONTROL_AREA_ALLOCATIONS), &
        CL_ANNUAL_ENERGY_LOSSES(MAX_CONTROL_AREA_ALLOCATIONS), &
        CT_ANNUAL_ENERGY_LOSSES(MAX_CONTROL_AREA_ALLOCATIONS), &
        EL_ANNUAL_ENERGY_LOSSES(MAX_CONTROL_AREA_ALLOCATIONS), &
        TOTAL_EMERGENCY_ENERGY, &
        TOTAL_MAINTENANCE_ENERGY, &
        TOTAL_AREA_RESOURCE_LOSSES, &
        ANNUAL_COINCIDENT_PEAK(6), &
        ANNUAL_NONCOINCIDENT_PEAK(6), &
        KEPCO_WC_DEF_MAINT_ENRG_COST, &
        KEPCO_WC_DEF_MAINT_ENRG_AMORT, &
        KEPCO_WC_CURENT_MAINT_ENRG_COST

end module kepcocom
