module amt1
implicit none
    real :: AMTBKINC,AMTUNADJINC,AMTINCOME,AMTCREDIT,CREDITUSED
    real ::    AMTOFFSETINC,AMTFORWARDLOSS,AMTNOLTAKEN,AMTITCUSED
    real :: ALTMINTAX
    real ::    ENVIRONMENTAL_TAX,ACE_DEP
end module amt1