
!COMMON /PARMS/ 
 module parms
 implicit none
 type t_ns_parms

 real :: ADEMCA, ADEMCL, ADEMRB, ADEMSS, ABANDS, CEIOA
 real :: CSDPR, CSDPS, CSMAX, CSMIN
 real :: CSUNIT,EQRATO,FDTXR,ITCRT,LDLIFE,LDSINK
 real :: LDUNIT,LTDMAX,LTDMIN,LTDRTE,MBRATO,MIN_COV_RATIO
 real :: TARGET_EQUITY_RATIO,NPVICA,NPVICL,OPRICA,OPRICL,OTHINC
 real :: PSMAX,PSMIN,PSRATE,PSRATO,PSSINK,PSUNIT,RBANEC,RBDFTX,RBITC
 real :: ROEQU,RONPV,STDMAX,STDMIN,STTXR,SUBDIV
 real :: SUBINC,TXOPR,TXPRPR,TXSSR, MAXIMUM_RATE_CHANGE
 real :: DEF_REVENUES,AMORT_DEF_REVENUES
 real :: MIN_ST_INVESTMENTS,RETURN_ON_ST_INVEST, INTINC
 real :: SALVAGE_TRANSACTIONS,AMT_PREP_DEPRE_ADDEN
 real :: CASH_OTH_ASSET,NUCL_DECOM_FUND,NUCL_FUND_RETURN
 real :: NUC_DEOM_FUND_RATEBASE, OM_CAPITALIZATION_RATE
 ! SRP
 real :: ADDENDUM_TO_PROPERTY_TAX,ADDENDUM_TO_ITC_AMORTIZATED

 ! KEPCO
 real :: DEFERRED_EXPENSE_AMORT_PERIOD, DEFERRED_EXPENSE_CASH
 real :: DEFERRED_EXPENSE_AMORT

 real :: GROSS_VALUE_OF_SOLD_ASSETS
 real :: CUMULATIVE_DEP_ON_SOLD_ASSETS
 real :: ADJUSTMENT_TO_DEFERRED_TAXES
 real :: ATL_AMORT_OF_BOOK
 real :: BTL_AMORT_OF_BOOK
 real :: LEASE_PAYMENTS_IN_TIER
 real :: CAPITIALIZED_LEASE_ADDITIONS
 real :: ATL_LEASE_PAYMENTS
 real :: BTL_LEASE_PAYMENTS
 real :: BTL_EMISSION_CREDIT_EXPENSE
 real :: BTL_EMISSION_CREDIT_REVENUE
 real :: ADJ_CLAUSE_REVENUE_ALLOCATION
 real :: ADJ_CLAUSE_EXPENSE_ALLOCATION
 real :: NET_ADJ_CLAUS_EMIS_AMT
 real :: LTD_SINKING_FUND_LAG
 real :: PS_SINKING_FUND_LAG
 real :: CAP_LEASES_IN_RATEBASE
 real :: INCOME_TAX_DEPRECIATION
 real :: ACE_TAX_DEPRECIATION
    ! SET PARMS_COMMON_BLOCK_ITEMS=87 IN SIZECOM.MON <- original code comment
 real :: BTL_MISC_DEDUCTIONS 
 real :: MAX_EQUITY_IN_CAP_STRUCTURE
 real :: BTL_EXPENSES
 real :: CASH_FROM_SALE_OF_ASSETS

 end type t_ns_parms
 
    ! SAVE required by Lahey, and should be implicit per the Fortran standard.
    type(t_ns_parms), save :: ns_parms
    
 end module parms