module clreport_routines
implicit none
contains
subroutine update_start_costs(ANNUAL_UNIT_START_COSTS, MAX_CL_UNITS, MONTH_UNIT_START_COSTS, &
    MONTHLY_START_COSTS, MONTHLY_CAPACITY_REVENUE, &
    CAP_MARKET_REVENUE, ANNUAL_UNIT_CAPACITY_REVENUE, ANNUAL_UNIT_STARTS, MONTHLY_STARTS, &
    MONTH_UNIT_STARTS, ANNUAL_P_FUEL_CONSUMPTION, ANNUAL_S_FUEL_CONSUMPTION, &
    ANNUAL_E_FUEL_CONSUMPTION, E_FUEL_CONSUMPTION, WHOLESALE_PRODUCTION_COST, &
    ANNUAL_WHOLESALE_PROD_COST, I, P_FUEL_CONSUMPTION, S_FUEL_CONSUMPTION, UNITNO, &
    AVG_PROD_COSTS, MON_ECO_SALES_ENRG_FROM)
    
integer :: MAX_CL_UNITS, I, UNITNO
real*4 :: ANNUAL_UNIT_START_COSTS(MAX_CL_UNITS), MONTH_UNIT_START_COSTS(MAX_CL_UNITS), &
    MONTHLY_START_COSTS, MONTHLY_CAPACITY_REVENUE, &
    ANNUAL_UNIT_CAPACITY_REVENUE(MAX_CL_UNITS), ANNUAL_E_FUEL_CONSUMPTION(MAX_CL_UNITS)
real*4 :: ANNUAL_WHOLESALE_PROD_COST(MAX_CL_UNITS), &
    WHOLESALE_PRODUCTION_COST, ANNUAL_S_FUEL_CONSUMPTION(MAX_CL_UNITS), &
    ANNUAL_P_FUEL_CONSUMPTION(MAX_CL_UNITS), MON_ECO_SALES_ENRG_FROM(MAX_CL_UNITS)
real :: CAP_MARKET_REVENUE, E_FUEL_CONSUMPTION, P_FUEL_CONSUMPTION, S_FUEL_CONSUMPTION, &
    AVG_PROD_COSTS
integer*2 :: MONTHLY_STARTS, ANNUAL_UNIT_STARTS(MAX_CL_UNITS), &
    MONTH_UNIT_STARTS(MAX_CL_UNITS)



          ANNUAL_UNIT_START_COSTS(I) = ANNUAL_UNIT_START_COSTS(I) + MONTH_UNIT_START_COSTS(I)
               MONTHLY_START_COSTS = MONTHLY_START_COSTS + MONTH_UNIT_START_COSTS(I)

               MONTHLY_CAPACITY_REVENUE = MONTHLY_CAPACITY_REVENUE + CAP_MARKET_REVENUE
               ANNUAL_UNIT_CAPACITY_REVENUE(I) = ANNUAL_UNIT_CAPACITY_REVENUE(I) + CAP_MARKET_REVENUE
!
               ANNUAL_UNIT_STARTS(I) = ANNUAL_UNIT_STARTS(I) + MONTH_UNIT_STARTS(I)
            MONTHLY_STARTS = MONTHLY_STARTS + MONTH_UNIT_STARTS(I)
!
               ANNUAL_P_FUEL_CONSUMPTION(I) = ANNUAL_P_FUEL_CONSUMPTION(I) + P_FUEL_CONSUMPTION
               ANNUAL_S_FUEL_CONSUMPTION(I) = ANNUAL_S_FUEL_CONSUMPTION(I) + S_FUEL_CONSUMPTION
               ANNUAL_E_FUEL_CONSUMPTION(I) = ANNUAL_E_FUEL_CONSUMPTION(I) + E_FUEL_CONSUMPTION
               WHOLESALE_PRODUCTION_COST = AVG_PROD_COSTS * MON_ECO_SALES_ENRG_FROM(UNITNO)/1000000.
               ANNUAL_WHOLESALE_PROD_COST(I) = ANNUAL_WHOLESALE_PROD_COST(I) + WHOLESALE_PRODUCTION_COST
end subroutine update_start_costs
subroutine collect_energy_data(AVERAGE_HEATRATE, AVERAGE_FUEL_COST_PER_MWH, &
    AVG_PROD_COSTS, enrg, CANADA, HEAT, HEAT_CONVERSION, UNITNO, &
    MAX_CL_UNITS, VCPMWH)
    
integer :: MAX_CL_UNITS

real :: AVERAGE_HEATRATE, AVERAGE_FUEL_COST_PER_MWH, AVG_PROD_COSTS, enrg, HEAT_CONVERSION, VCPMWH(MAX_CL_UNITS)
logical*1 :: CANADA
real*8 :: FUEL_COST, HEAT
integer*2 UNITNO 
    IF(ENRG > 0.45) THEN
      AVERAGE_HEATRATE = HEAT_CONVERSION*HEAT/ENRG
      AVERAGE_FUEL_COST_PER_MWH = FUEL_COST / ENRG

      AVG_PROD_COSTS = SNGL((FUEL_COST))/ENRG+VCPMWH(UNITNO)
      IF(.NOT. CANADA) then 
        AVERAGE_HEATRATE = AVERAGE_HEATRATE + .5
      endif
    ELSE
      FUEL_COST = 0.0 D0
      HEAT = 0.0 D0
      AVERAGE_HEATRATE = 0.0
      AVERAGE_FUEL_COST_PER_MWH = 0.0
      AVG_PROD_COSTS = 0.0
    ENDIF
end subroutine collect_energy_data
subroutine collect_monthly_unit_emissions(MONTHLY_UNIT_EMISSIONS, UNIT_EMISSIONS)
real*4, intent(inout) :: MONTHLY_UNIT_EMISSIONS(5), UNIT_EMISSIONS(5)
integer :: index, ub
    ub=ubound(MONTHLY_UNIT_EMISSIONS,1)
    do index=1, ub ! Was explicitly setting elements, 1..5
        MONTHLY_UNIT_EMISSIONS(index)=MONTHLY_UNIT_EMISSIONS(index)+UNIT_EMISSIONS(index)
    enddo
    
end subroutine collect_monthly_unit_emissions
subroutine update_energy_in_prod_arrays(PROD_BY_MK_BY_MWH, MK, MW, ANNUAL_PROD_BY_MK_BY_MWH, ENRG, I, MAX_CL_UNITS)
real :: PROD_BY_MK_BY_MWH(:,:), MW(:,:), ANNUAL_PROD_BY_MK_BY_MWH(:,:)
real :: enrg
integer :: mk
integer :: I, MAX_CL_UNITS

    PROD_BY_MK_BY_MWH(MK,1) = PROD_BY_MK_BY_MWH(MK,1) + ENRG
    PROD_BY_MK_BY_MWH(MK,2) = PROD_BY_MK_BY_MWH(MK,2) + MW(2,I)
    PROD_BY_MK_BY_MWH(MK,3) = PROD_BY_MK_BY_MWH(MK,3) + 1
    ANNUAL_PROD_BY_MK_BY_MWH(MK,1) = ANNUAL_PROD_BY_MK_BY_MWH(MK,1) + ENRG
    ANNUAL_PROD_BY_MK_BY_MWH(MK,2) = ANNUAL_PROD_BY_MK_BY_MWH(MK,2) + MW(2,I)
    ANNUAL_PROD_BY_MK_BY_MWH(MK,3) = ANNUAL_PROD_BY_MK_BY_MWH(MK,3) + 1
end subroutine update_energy_in_prod_arrays

end module clreport_routines