grep -i "BTL_Monthly_Interest_Income"                ~/wrk/Midas/ABBICAP/*.* 
grep -i "BTL_Monthly_Total_Other_Income"             ~/wrk/Midas/ABBICAP/*.* 
grep -i "Cash_Interest_on_Notes_Payable"             ~/wrk/Midas/ABBICAP/*.* 
grep -i "IPL_Monthy_OandM_Expenses"                  ~/wrk/Midas/ABBICAP/*.* 
grep -i "IPL_Operating_Income"                       ~/wrk/Midas/ABBICAP/*.* 
grep -i "IPL_Total_Operating_Expenses"               ~/wrk/Midas/ABBICAP/*.* 
grep -i "Monthly_Dividend_70_Earnings"               ~/wrk/Midas/ABBICAP/*.* 
grep -i "Monthly_ITC_Amortization"                   ~/wrk/Midas/ABBICAP/*.* 
grep -i "Monthly_Investment_Earnings"                ~/wrk/Midas/ABBICAP/*.* 
grep -i "Monthly_Issue_Expense_Amorts"               ~/wrk/Midas/ABBICAP/*.* 
grep -i "Monthly_LTD_Booked_Interest"                ~/wrk/Midas/ABBICAP/*.* 
grep -i "Monthly_LTD_Premium_Amort"                  ~/wrk/Midas/ABBICAP/*.* 
grep -i "Monthly_LTD_Total_Interest"                 ~/wrk/Midas/ABBICAP/*.* 
grep -i "Monthly_Operating_Revenue_Tax"              ~/wrk/Midas/ABBICAP/*.* 
grep -i "Monthly_PS_Amort_Dividends"                 ~/wrk/Midas/ABBICAP/*.* 
grep -i "Monthly_PS_Premium_Amort"                   ~/wrk/Midas/ABBICAP/*.* 
grep -i "Monthly_Property_Taxes"                     ~/wrk/Midas/ABBICAP/*.* 
grep -i "Monthly_Total_PS_Dividends"                 ~/wrk/Midas/ABBICAP/*.* 
