!
!     
      subroutine pepe()
      use caca

!  TIPO-9 sl sv - t09 g09
      sentencia1
!      allocate(www1(xx1))
      sentencia2


!  TIPO-11 sl mv - t09 g09
      sentencia3
!      allocate(ttt1(xx1),ttt2(xx2))
      sentencia4


! TIPO-13 ml sv -
      sentencia5
!      allocate(rrr(1:100, &
!                   1:100))
      sentencia6
      sentencia7


! TIPO-15 mv mv -
      sentencia8
!      allocate(var1(xx1), &
!               var2(xx2))
      sentencia9



! TIPO-15 mv mv - con comentarios intermedios !!!
      sentencia 10
      ALLOCATE(TDDB(0:12,0:FINANCIAL_SIMULATION_YEARS,0:NUM_OF_ASSET_CLASSES,0:BAL_SHEET_OPTIONS,UNIQUE_ACCT_TYPE), &
               TDDRBB(0:12,0:FINANCIAL_SIMULATION_YEARS,0:NUM_OF_ASSET_CLASSES,UNIQUE_ACCT_TYPE), &
               TAMRTE(0:12,0:FINANCIAL_SIMULATION_YEARS,0:NUM_OF_ASSET_CLASSES,UNIQUE_ACCT_TYPE), &
               TNDB(0:12,0:FINANCIAL_SIMULATION_YEARS,0:NUM_OF_ASSET_CLASSES,0:BAL_SHEET_OPTIONS,UNIQUE_ACCT_TYPE), &
               NET_CHANGE_IN_DB(0:12,0:FINANCIAL_SIMULATION_YEARS,0:NUM_OF_ASSET_CLASSES,0:BAL_SHEET_OPTIONS,UNIQUE_ACCT_TYPE), &
               TCAMRT(0:12,0:FINANCIAL_SIMULATION_YEARS,0:NUM_OF_ASSET_CLASSES,UNIQUE_ACCT_TYPE), &
               RB_DD_AMRTE(0:12,0:FINANCIAL_SIMULATION_YEARS,0:NUM_OF_ASSET_CLASSES,UNIQUE_ACCT_TYPE), &
               INTEREST_AMORTIZATION(0:12,0:FINANCIAL_SIMULATION_YEARS,0:NUM_OF_ASSET_CLASSES,UNIQUE_ACCT_TYPE), &
!
               BTL_AMORTIZATION(0:12,0:FINANCIAL_SIMULATION_YEARS,0:NUM_OF_ASSET_CLASSES,UNIQUE_ACCT_TYPE), &
               ATL_AMORTIZATION(0:12,0:FINANCIAL_SIMULATION_YEARS,0:NUM_OF_ASSET_CLASSES,UNIQUE_ACCT_TYPE), &
               ATL_AMORT_SUB_ITEMS(0:12,0:FINANCIAL_SIMULATION_YEARS,0:NUM_OF_ASSET_CLASSES,0:BAL_SHEET_OPTIONS,UNIQUE_ACCT_TYPE), &
               ATL_DEF_TAX(0:12,0:FINANCIAL_SIMULATION_YEARS,0:NUM_OF_ASSET_CLASSES,UNIQUE_ACCT_TYPE), &
               BTL_DEF_TAX(0:12,0:FINANCIAL_SIMULATION_YEARS,0:NUM_OF_ASSET_CLASSES,UNIQUE_ACCT_TYPE), &
               DEFERRED_CASH_ADDITIONS(0:12,0:FINANCIAL_SIMULATION_YEARS,0:NUM_OF_ASSET_CLASSES,UNIQUE_ACCT_TYPE), &
               ATL_CURRENT_TAX_EXPENSE(0:12,0:FINANCIAL_SIMULATION_YEARS,0:NUM_OF_ASSET_CLASSES,UNIQUE_ACCT_TYPE), &
               BTL_CURRENT_TAX_EXPENSE(0:12,0:FINANCIAL_SIMULATION_YEARS,0:NUM_OF_ASSET_CLASSES,UNIQUE_ACCT_TYPE), &
               VARIABLE_OM_AMORT(0:12,0:FINANCIAL_SIMULATION_YEARS,0:NUM_OF_ASSET_CLASSES,UNIQUE_ACCT_TYPE), &
               OTHER_OM_AMORT(0:12,0:FINANCIAL_SIMULATION_YEARS,0:NUM_OF_ASSET_CLASSES,UNIQUE_ACCT_TYPE), &
               PURCHASE_POWER_AMORT(0:12,0:FINANCIAL_SIMULATION_YEARS,0:NUM_OF_ASSET_CLASSES,UNIQUE_ACCT_TYPE), &
               TAX_TIMING_DIFFERENCES(0:FINANCIAL_SIMULATION_YEARS,0:NUM_OF_ASSET_CLASSES,2,2,UNIQUE_ACCT_TYPE))
!
      sentencia 10


      end
!
!
