!
!     
      subroutine pepe()
      use caca


      exte1
      allocate(var1(xx1),var2(xx2))
      extr2

      exte1
      allocate(var1(xx1), &
               var2(xx2))
      exte2


      ALLOCATE(TDDB(0:12,0:FINANCIAL_SIMULATION_YEARS,0:NUM_OF_ASSET_CLASSES,0:BAL_SHEET_OPTIONS,UNIQUE_ACCT_TYPE), &
               TDDRBB(0:12,0:FINANCIAL_SIMULATION_YEARS,0:NUM_OF_ASSET_CLASSES,UNIQUE_ACCT_TYPE), &
               TAMRTE(0:12,0:FINANCIAL_SIMULATION_YEARS,0:NUM_OF_ASSET_CLASSES,UNIQUE_ACCT_TYPE), &
               TNDB(0:12,0:FINANCIAL_SIMULATION_YEARS,0:NUM_OF_ASSET_CLASSES,0:BAL_SHEET_OPTIONS,UNIQUE_ACCT_TYPE), &
               NET_CHANGE_IN_DB(0:12,0:FINANCIAL_SIMULATION_YEARS,0:NUM_OF_ASSET_CLASSES,0:BAL_SHEET_OPTIONS,UNIQUE_ACCT_TYPE), &
               TCAMRT(0:12,0:FINANCIAL_SIMULATION_YEARS,0:NUM_OF_ASSET_CLASSES,UNIQUE_ACCT_TYPE), &
               RB_DD_AMRTE(0:12,0:FINANCIAL_SIMULATION_YEARS,0:NUM_OF_ASSET_CLASSES,UNIQUE_ACCT_TYPE), &
               INTEREST_AMORTIZATION(0:12,0:FINANCIAL_SIMULATION_YEARS,0:NUM_OF_ASSET_CLASSES,UNIQUE_ACCT_TYPE), &
               BTL_AMORTIZATION(0:12,0:FINANCIAL_SIMULATION_YEARS,0:NUM_OF_ASSET_CLASSES,UNIQUE_ACCT_TYPE), &
               ATL_AMORTIZATION(0:12,0:FINANCIAL_SIMULATION_YEARS,0:NUM_OF_ASSET_CLASSES,UNIQUE_ACCT_TYPE), &
               ATL_AMORT_SUB_ITEMS(0:12,0:FINANCIAL_SIMULATION_YEARS,0:NUM_OF_ASSET_CLASSES,0:BAL_SHEET_OPTIONS,UNIQUE_ACCT_TYPE), &
               ATL_DEF_TAX(0:12,0:FINANCIAL_SIMULATION_YEARS,0:NUM_OF_ASSET_CLASSES,UNIQUE_ACCT_TYPE), &
               BTL_DEF_TAX(0:12,0:FINANCIAL_SIMULATION_YEARS,0:NUM_OF_ASSET_CLASSES,UNIQUE_ACCT_TYPE), &
               DEFERRED_CASH_ADDITIONS(0:12,0:FINANCIAL_SIMULATION_YEARS,0:NUM_OF_ASSET_CLASSES,UNIQUE_ACCT_TYPE), &
               ATL_CURRENT_TAX_EXPENSE(0:12,0:FINANCIAL_SIMULATION_YEARS,0:NUM_OF_ASSET_CLASSES,UNIQUE_ACCT_TYPE), &
               BTL_CURRENT_TAX_EXPENSE(0:12,0:FINANCIAL_SIMULATION_YEARS,0:NUM_OF_ASSET_CLASSES,UNIQUE_ACCT_TYPE), &
               VARIABLE_OM_AMORT(0:12,0:FINANCIAL_SIMULATION_YEARS,0:NUM_OF_ASSET_CLASSES,UNIQUE_ACCT_TYPE), &
               OTHER_OM_AMORT(0:12,0:FINANCIAL_SIMULATION_YEARS,0:NUM_OF_ASSET_CLASSES,UNIQUE_ACCT_TYPE), &
               PURCHASE_POWER_AMORT(0:12,0:FINANCIAL_SIMULATION_YEARS,0:NUM_OF_ASSET_CLASSES,UNIQUE_ACCT_TYPE), &
               TAX_TIMING_DIFFERENCES(0:FINANCIAL_SIMULATION_YEARS,0:NUM_OF_ASSET_CLASSES,2,2,UNIQUE_ACCT_TYPE))
!
      sent2

      end
!
!
