module clreport_routines
implicit none
contains
subroutine update_start_costs(ANNUAL_UNIT_START_COSTS, MAX_CL_UNITS, MONTH_UNIT_START_COSTS, &
    MONTHLY_START_COSTS, MONTHLY_CAPACITY_REVENUE, &
    CAP_MARKET_REVENUE, ANNUAL_UNIT_CAPACITY_REVENUE, ANNUAL_UNIT_STARTS, MONTHLY_STARTS, &
    MONTH_UNIT_STARTS, ANNUAL_P_FUEL_CONSUMPTION, ANNUAL_S_FUEL_CONSUMPTION, &
    ANNUAL_E_FUEL_CONSUMPTION, E_FUEL_CONSUMPTION, WHOLESALE_PRODUCTION_COST, &
    ANNUAL_WHOLESALE_PROD_COST, I, P_FUEL_CONSUMPTION, S_FUEL_CONSUMPTION, UNITNO, &
    AVG_PROD_COSTS, MON_ECO_SALES_ENRG_FROM)
    
integer :: MAX_CL_UNITS, I, UNITNO
real (kind=4) :: ANNUAL_UNIT_START_COSTS(MAX_CL_UNITS), MONTH_UNIT_START_COSTS(MAX_CL_UNITS), &
    MONTHLY_START_COSTS, MONTHLY_CAPACITY_REVENUE, &
    ANNUAL_UNIT_CAPACITY_REVENUE(MAX_CL_UNITS), ANNUAL_E_FUEL_CONSUMPTION(MAX_CL_UNITS)
real (kind=4) :: ANNUAL_WHOLESALE_PROD_COST(MAX_CL_UNITS), &
    WHOLESALE_PRODUCTION_COST, ANNUAL_S_FUEL_CONSUMPTION(MAX_CL_UNITS), &
    ANNUAL_P_FUEL_CONSUMPTION(MAX_CL_UNITS), MON_ECO_SALES_ENRG_FROM(MAX_CL_UNITS)
real :: CAP_MARKET_REVENUE, E_FUEL_CONSUMPTION, P_FUEL_CONSUMPTION, S_FUEL_CONSUMPTION, &
    AVG_PROD_COSTS
integer (kind=2) :: MONTHLY_STARTS, ANNUAL_UNIT_STARTS(MAX_CL_UNITS), &
    MONTH_UNIT_STARTS(MAX_CL_UNITS)



          ANNUAL_UNIT_START_COSTS(I) = ANNUAL_UNIT_START_COSTS(I) + MONTH_UNIT_START_COSTS(I)
               MONTHLY_START_COSTS = MONTHLY_START_COSTS + MONTH_UNIT_START_COSTS(I)

               MONTHLY_CAPACITY_REVENUE = &
			   MONTHLY_CAPACITY_REVENUE + CAP_MARKET_REVENUE
               ANNUAL_UNIT_CAPACITY_REVENUE(I) = &
			   ANNUAL_UNIT_CAPACITY_REVENUE(I) + CAP_MARKET_REVENUE
!
               ANNUAL_UNIT_STARTS(I) = ANNUAL_UNIT_STARTS(I) + &
			   MONTH_UNIT_STARTS(I)
            MONTHLY_STARTS = MONTHLY_STARTS + MONTH_UNIT_STARTS(I)
!
               ANNUAL_P_FUEL_CONSUMPTION(I) = &
               ANNUAL_P_FUEL_CONSUMPTION(I) + P_FUEL_CONSUMPTION
               ANNUAL_S_FUEL_CONSUMPTION(I) = &
               ANNUAL_S_FUEL_CONSUMPTION(I) + S_FUEL_CONSUMPTION
               ANNUAL_E_FUEL_CONSUMPTION(I) = &
               ANNUAL_E_FUEL_CONSUMPTION(I) + E_FUEL_CONSUMPTION
               WHOLESALE_PRODUCTION_COST = AVG_PROD_COSTS * &
               MON_ECO_SALES_ENRG_FROM(UNITNO)/1000000.
               ANNUAL_WHOLESALE_PROD_COST(I) = &
               ANNUAL_WHOLESALE_PROD_COST(I) +WHOLESALE_PRODUCTION_COST
end subroutine update_start_costs
subroutine collect_energy_data(AVERAGE_HEATRATE, &
    AVERAGE_FUEL_COST_PER_MWH, &
    AVG_PROD_COSTS, enrg, CANADA, HEAT, HEAT_CONVERSION, UNITNO, &
    MAX_CL_UNITS, VCPMWH)
    
integer :: MAX_CL_UNITS

real :: AVERAGE_HEATRATE, AVERAGE_FUEL_COST_PER_MWH, AVG_PROD_COSTS, &
      enrg, HEAT_CONVERSION, VCPMWH(MAX_CL_UNITS)
logical (kind=1) :: CANADA
real (kind=8) :: FUEL_COST, HEAT
integer (kind=2) :: UNITNO 
    IF(ENRG > 0.45) THEN
      AVERAGE_HEATRATE = HEAT_CONVERSION*HEAT/ENRG
      AVERAGE_FUEL_COST_PER_MWH = FUEL_COST / ENRG

      AVG_PROD_COSTS = SNGL((FUEL_COST))/ENRG+VCPMWH(UNITNO)
      IF(.NOT. CANADA) then 
        AVERAGE_HEATRATE = AVERAGE_HEATRATE + .5
      endif
    ELSE
      FUEL_COST = 0.0
      HEAT = 0.0
      AVERAGE_HEATRATE = 0.0
      AVERAGE_FUEL_COST_PER_MWH = 0.0
      AVG_PROD_COSTS = 0.0
    ENDIF
end subroutine collect_energy_data
subroutine collect_monthly_unit_emissions(MONTHLY_UNIT_EMISSIONS, UNIT_EMISSIONS)
real (kind=4), intent(inout) :: MONTHLY_UNIT_EMISSIONS(5), UNIT_EMISSIONS(5)
integer :: index, ub
    ub=ubound(MONTHLY_UNIT_EMISSIONS,1)
    do index=1, ub ! Was explicitly setting elements, 1..5
        MONTHLY_UNIT_EMISSIONS(index)=MONTHLY_UNIT_EMISSIONS(index)+UNIT_EMISSIONS(index)
    enddo
    
end subroutine collect_monthly_unit_emissions
subroutine update_energy_in_prod_arrays(PROD_BY_MK_BY_MWH, MK, MW, ANNUAL_PROD_BY_MK_BY_MWH, ENRG, I, MAX_CL_UNITS)
real :: PROD_BY_MK_BY_MWH(:,:), MW(:,:), ANNUAL_PROD_BY_MK_BY_MWH(:,:)
real :: enrg
integer :: mk
integer :: I, MAX_CL_UNITS

    PROD_BY_MK_BY_MWH(MK,1) = PROD_BY_MK_BY_MWH(MK,1) + ENRG
    PROD_BY_MK_BY_MWH(MK,2) = PROD_BY_MK_BY_MWH(MK,2) + MW(2,I)
    PROD_BY_MK_BY_MWH(MK,3) = PROD_BY_MK_BY_MWH(MK,3) + 1
    ANNUAL_PROD_BY_MK_BY_MWH(MK,1) = ANNUAL_PROD_BY_MK_BY_MWH(MK,1) + ENRG
    ANNUAL_PROD_BY_MK_BY_MWH(MK,2) = ANNUAL_PROD_BY_MK_BY_MWH(MK,2) + MW(2,I)
    ANNUAL_PROD_BY_MK_BY_MWH(MK,3) = ANNUAL_PROD_BY_MK_BY_MWH(MK,3) + 1
end subroutine update_energy_in_prod_arrays

subroutine nox_data_collector(I,UNIT_EMISSIONS, &
ANNUAL_NOX_SEASON_EMISSIONS,ANNUAL_NOX_SEASON_THERMAL,HEAT, &
FISCAL_NOX_SEASON_EMISSIONS,FISCAL_NOX_SEASON_THERMAL,TOTAL_NOX_HEAT)

USE hesi_gendecs

INTEGER(kind=2) :: I
REAL(kind=4) :: UNIT_EMISSIONS(5)
REAL(kind=4) :: ANNUAL_NOX_SEASON_EMISSIONS(MAX_CL_UNITS)
REAL(kind=4) :: ANNUAL_NOX_SEASON_THERMAL(MAX_CL_UNITS)
REAL(kind=4) :: FISCAL_NOX_SEASON_EMISSIONS(MAX_CL_UNITS)
REAL(kind=4) :: FISCAL_NOX_SEASON_THERMAL(MAX_CL_UNITS)
REAL(kind=8) :: HEAT
REAL(kind=4) :: TOTAL_NOX_HEAT
IF(UNIT_EMISSIONS(2) > 0.) THEN
   ANNUAL_NOX_SEASON_EMISSIONS(I) = &
                              ANNUAL_NOX_SEASON_EMISSIONS(I) &
                              + UNIT_EMISSIONS(2)
   ANNUAL_NOX_SEASON_THERMAL(I) = HEAT &
                              + ANNUAL_NOX_SEASON_THERMAL(I)
!
   FISCAL_NOX_SEASON_EMISSIONS(I) = &
                              FISCAL_NOX_SEASON_EMISSIONS(I) &
                              + UNIT_EMISSIONS(2)
   FISCAL_NOX_SEASON_THERMAL(I) = HEAT &
                              + FISCAL_NOX_SEASON_THERMAL(I)
!
   TOTAL_NOX_HEAT = TOTAL_NOX_HEAT + HEAT
endif
end subroutine nox_data_collector
!
! Function TOTAL_PRODUCTION_COSTS(YR)
!
! EXTRACT_METHOD: accumulate_production_costs
!
! TOTAL_PRODUCTION_COSTS, YR are defined as it is in origin
! FUELCOST(:) and VARCOST(:) are defined in module PROCSAVE_COMMON 
! TOTAL_NUCLEAR_FUEL_EXPENSE, FIXED_OM_COSTS, PURCHASE_COSTS are defined in module cap_prod_costs
! ANNUAL_ECONOMY_COST, ANNUAL_ECONOMY_REVENUE are defined in module GROUP_PROD
! CLASS_ASS_FOSSIL_COST(),CLASS_ASS_NUCLEAR_COST(),CLASS_ASSIGNED_VARIABLE_COST(),CLASS_ASSIGNED_FIXED_COST(),
! CLASS_ASS_PURCHASE_COST() are defined in module POOLCOM


function total_production_cost(YR)

USE PROCSAVE_COMMON
use cap_prod_costs
USE GROUP_PROD
USE POOLCOM

REAL :: TOTAL_PRODUCTION_COST
INTEGER (kind=2), INTENT(IN) :: YR


      TOTAL_PRODUCTION_COST = &
                  FUELCOST(YR) + TOTAL_NUCLEAR_FUEL_EXPENSE + &
                  VARCOST(YR) + FIXED_OM_COSTS + &
                  PURCHASE_COSTS + ANNUAL_ECONOMY_COST - &
                  ANNUAL_ECONOMY_REVENUE + &
!
! ADDED 9/5/97 FOR GETTING TOTAL COST CONSISTENT WITH THE INDIVIDUAL
!  UNIT INFO
!
                  CLASS_ASS_FOSSIL_COST(2) + &
                  CLASS_ASS_NUCLEAR_COST(2) + & 
                  CLASS_ASSIGNED_VARIABLE_COST(2) + &
                  CLASS_ASSIGNED_FIXED_COST(2) + &
                  CLASS_ASS_PURCHASE_COST(2)

end function total_production_cost

subroutine collect_emissions_costs(EMISSIONS_COST_BY_SP,UNIT_EMISSIONS_COST,SP)

      REAL (kind=4), INTENT(INOUT) ::  EMISSIONS_COST_BY_SP(:,:) 
      REAL (kind=4), INTENT(IN) ::  UNIT_EMISSIONS_COST(5)
      INTEGER (kind=2) :: SP

      EMISSIONS_COST_BY_SP(SP,1) = EMISSIONS_COST_BY_SP(SP,1) + UNIT_EMISSIONS_COST(1)
      EMISSIONS_COST_BY_SP(SP,2) = EMISSIONS_COST_BY_SP(SP,2) + UNIT_EMISSIONS_COST(2)
      EMISSIONS_COST_BY_SP(SP,3) = EMISSIONS_COST_BY_SP(SP,3) + UNIT_EMISSIONS_COST(3)
      EMISSIONS_COST_BY_SP(SP,4) = EMISSIONS_COST_BY_SP(SP,4) + UNIT_EMISSIONS_COST(4)
      EMISSIONS_COST_BY_SP(SP,5) = EMISSIONS_COST_BY_SP(SP,5) + UNIT_EMISSIONS_COST(5)

end subroutine collect_emissions_costs
subroutine set_emission_report_titles(EMISSIONS_TITLES,EMISSIONS_CAP_TITLES,ANNUAL_AI_INVESTMENT,CANADA)

      use prod_arrays_dimensions
      CHARACTER (len=1) :: COUNTRY   ! This variable is used to host COUNTRY() function's result 
      LOGICAL (kind=1), INTENT(OUT) :: CANADA
      CHARACTER (LEN=26), INTENT(INOUT) :: EMISSIONS_TITLES(NUMBER_OF_EMISSION_TYPES)
      CHARACTER (LEN=28), INTENT(INOUT) :: EMISSIONS_CAP_TITLES(NUMBER_OF_EMISSION_TYPES)
      REAL (kind=4), INTENT(OUT) :: ANNUAL_AI_INVESTMENT

      CANADA = COUNTRY() == 'C'
      ANNUAL_AI_INVESTMENT = 0.
      EMISSIONS_TITLES(1) = 'SO2 Emissions (tons)      '
      EMISSIONS_TITLES(2) = 'NOx Emissions (tons)      '
      EMISSIONS_TITLES(3) = 'CO2 Emissions (tons)      '
      EMISSIONS_TITLES(4) = 'Other 1 Emissions (tons)  '
      EMISSIONS_TITLES(5) = 'Other 2 Emissions (tons)  '
      EMISSIONS_CAP_TITLES(1) = 'SO2 Emissions Cap (tons)    '
      EMISSIONS_CAP_TITLES(2) = 'NOx Emissions Cap (tons)    '
      EMISSIONS_CAP_TITLES(3) = 'CO2 Emissions Cap (tons)    '
      EMISSIONS_CAP_TITLES(4) = 'Other 1 Emissions Cap (tons)'
      EMISSIONS_CAP_TITLES(5) = 'Other 2 Emissions Cap (tons)'
  
end subroutine set_emission_report_titles

subroutine handle_annual_output_report(I,J,TOTAL_COST,CL_UNIT_ANNUAL_FIXED_COST, &
                                       CL_UNIT_ANNUAL_FUEL_COST,CL_UNIT_ANNUAL_VAR_COST, &
                                       ANNUAL_OUTPUT_REPORT,AVERAGE_COST,AVERAGE_HEATRATE,CAP_FACTOR,UNIT_NAME, &
                                       SAVE_YEAR,ANN_CL_UNIT_REC,ANN_CL_UNIT_NO)

      USE prod_arrays_dimensions
      USE grx_data
      use aitvafin
      use annual_cl_unit
      use endpoint
      use prodcom
      USE globecom

      LOGICAL (kind=1) :: ANNUAL_OUTPUT_REPORT
      INTEGER (kind=2) :: I,J,SAVE_YEAR
      INTEGER (kind=2) :: ANN_CL_UNIT_NO
      INTEGER :: ANN_CL_UNIT_REC
      REAL (kind=4) :: TOTAL_COST,AVERAGE_COST
      REAL ::  CL_UNIT_ANNUAL_FIXED_COST
      REAL ::  CL_UNIT_ANNUAL_FUEL_COST
      REAL ::  CL_UNIT_ANNUAL_VAR_COST, &
               AVERAGE_HEATRATE, &
               CAP_FACTOR
      CHARACTER (len=20) :: UNIT_NAME
      CHARACTER (len=2) :: GREEN_MRX_METHOD,CAPACITY_PLANNING_METHOD
      
            IF(ANNUAL_OUTPUT_REPORT) THEN
               IF(CAPACITY_PLANNING_METHOD() == 'MX'  .AND. GREEN_MRX_METHOD() == 'GX') THEN
                  WRITE(ANN_CL_UNIT_NO,REC=ANN_CL_UNIT_REC) &   ! VARIABLE = 11 + # OF EMIS
                    PRT_ENDPOINT(), &
                    FLOAT(SAVE_YEAR+BASE_YEAR), &
                    UNIT_NAME, &
                    FLOAT(GRX_ITERATIONS), &
                    FLOAT(I), &
                    MW(2,I), &
                    CAP_FACTOR, &
                    ANNUAL_CL_UNIT_ENERGY(I)/1000., &
                    AVERAGE_HEATRATE, &
                    AVERAGE_COST, &
                    CL_UNIT_ANNUAL_FUEL_COST, &
                    CL_UNIT_ANNUAL_VAR_COST, &
                    CL_UNIT_ANNUAL_FIXED_COST, &
                    TOTAL_COST, &
                    (ANNUAL_CL_UNIT_EMISSIONS(J,I),J=1,NUMBER_OF_EMISSION_TYPES), &
                    CL_AI_INVESTMENT(I)/1000000.
               ELSE
                  WRITE(ANN_CL_UNIT_NO,REC=ANN_CL_UNIT_REC) & ! VARIABLE = 11 + # OF EMIS
                       PRT_ENDPOINT(), &
                       FLOAT(SAVE_YEAR+BASE_YEAR), &
                       UNIT_NAME, &
                       FLOAT(I), &
                       MW(2,I), &
                       CAP_FACTOR, &
                       ANNUAL_CL_UNIT_ENERGY(I)/1000., &
                       AVERAGE_HEATRATE, &
                       AVERAGE_COST, &
                       CL_UNIT_ANNUAL_FUEL_COST, &
                       CL_UNIT_ANNUAL_VAR_COST, &
                       CL_UNIT_ANNUAL_FIXED_COST, &
                       TOTAL_COST, &
                       (ANNUAL_CL_UNIT_EMISSIONS(J,I),J=1,NUMBER_OF_EMISSION_TYPES), &
                       CL_AI_INVESTMENT(I)/1000000.
               ENDIF
               ANN_CL_UNIT_REC = ANN_CL_UNIT_REC + 1
            ENDIF

end subroutine handle_annual_output_report

subroutine collect_fiscal_data(I,UNITNO,FISCAL_ECO_SALES_REV_FROM,FISCAL_ECO_SALES_ENRG_FROM,FISCAL_ECO_PUCH_COST_FROM, &
                               FISCAL_ECO_PUCH_ENRG_FROM,FISCAL_P_FUEL_CONSUMPTION,FISCAL_S_FUEL_CONSUMPTION, &
                               FISCAL_E_FUEL_CONSUMPTION,P_FUEL_CONSUMPTION,FISCAL_UNIT_STARTS,FISCAL_UNIT_START_COSTS, &
                               MONTH_UNIT_STARTS,MONTH_UNIT_START_COSTS,FISCAL_WHOLESALE_PROD_COST,WHOLESALE_PRODUCTION_COST, &
                               FISCAL_UNIT_EMISSIONS_COST,UNIT_EMISSIONS_COST)

USE hesi_gendecs
USE eco

REAL (kind=4), INTENT(INOUT) :: FISCAL_ECO_SALES_REV_FROM(MAX_CL_UNITS)
REAL (kind=4), INTENT(INOUT) :: FISCAL_ECO_SALES_ENRG_FROM(MAX_CL_UNITS)
REAL (kind=4), INTENT(INOUT) :: FISCAL_ECO_PUCH_COST_FROM(MAX_CL_UNITS)
REAL (kind=4), INTENT(INOUT) :: FISCAL_ECO_PUCH_ENRG_FROM(MAX_CL_UNITS)
REAL (kind=4), INTENT(INOUT) :: FISCAL_P_FUEL_CONSUMPTION(MAX_CL_UNITS)
REAL (kind=4), INTENT(INOUT) :: FISCAL_S_FUEL_CONSUMPTION(MAX_CL_UNITS)
REAL (kind=4), INTENT(INOUT) :: FISCAL_E_FUEL_CONSUMPTION(MAX_CL_UNITS)
REAL (kind=4), INTENT(INOUT) :: FISCAL_UNIT_START_COSTS(MAX_CL_UNITS)
REAL (kind=4) :: MONTH_UNIT_START_COSTS(MAX_CL_UNITS)
REAL (kind=4), INTENT(INOUT) :: FISCAL_WHOLESALE_PROD_COST(MAX_CL_UNITS)
REAL (kind=4), INTENT(INOUT) :: FISCAL_UNIT_EMISSIONS_COST(MAX_CL_UNITS,5)
REAL (kind=4) :: UNIT_EMISSIONS_COST(5)
REAL (kind=4) :: WHOLESALE_PRODUCTION_COST


REAL :: P_FUEL_CONSUMPTION

INTEGER (kind=2) :: UNITNO,I
INTEGER (kind=2), INTENT(INOUT) :: FISCAL_UNIT_STARTS(MAX_CL_UNITS)
INTEGER (kind=2) :: MONTH_UNIT_STARTS(MAX_CL_UNITS)

        FISCAL_ECO_SALES_REV_FROM(UNITNO) = FISCAL_ECO_SALES_REV_FROM(UNITNO) + MON_ECO_SALES_REV_FROM(UNITNO)
        FISCAL_ECO_SALES_ENRG_FROM(UNITNO) = FISCAL_ECO_SALES_ENRG_FROM(UNITNO) + MON_ECO_SALES_ENRG_FROM(UNITNO)
        FISCAL_ECO_PUCH_COST_FROM(UNITNO) = FISCAL_ECO_PUCH_COST_FROM(UNITNO) + MON_ECO_PUCH_COST_FROM(UNITNO)
        FISCAL_ECO_PUCH_ENRG_FROM(UNITNO) = FISCAL_ECO_PUCH_ENRG_FROM(UNITNO) + MON_ECO_PUCH_ENRG_FROM(UNITNO)
!
        FISCAL_P_FUEL_CONSUMPTION(I) = FISCAL_P_FUEL_CONSUMPTION(I) + P_FUEL_CONSUMPTION
        FISCAL_S_FUEL_CONSUMPTION(I) = FISCAL_S_FUEL_CONSUMPTION(I) + P_FUEL_CONSUMPTION
        FISCAL_E_FUEL_CONSUMPTION(I) = FISCAL_E_FUEL_CONSUMPTION(I) + P_FUEL_CONSUMPTION

        FISCAL_UNIT_STARTS(I) = FISCAL_UNIT_STARTS(I) + MONTH_UNIT_STARTS(I)
        FISCAL_UNIT_START_COSTS(I) = FISCAL_UNIT_START_COSTS(I) + MONTH_UNIT_START_COSTS(I)
        FISCAL_WHOLESALE_PROD_COST(I) = FISCAL_WHOLESALE_PROD_COST(I) + WHOLESALE_PRODUCTION_COST
!
        FISCAL_UNIT_EMISSIONS_COST(I,1) = FISCAL_UNIT_EMISSIONS_COST(I,1) + UNIT_EMISSIONS_COST(1)
        FISCAL_UNIT_EMISSIONS_COST(I,2) = FISCAL_UNIT_EMISSIONS_COST(I,2) + UNIT_EMISSIONS_COST(2)
        FISCAL_UNIT_EMISSIONS_COST(I,3) = FISCAL_UNIT_EMISSIONS_COST(I,3) + UNIT_EMISSIONS_COST(3)
        FISCAL_UNIT_EMISSIONS_COST(I,4) = FISCAL_UNIT_EMISSIONS_COST(I,4) + UNIT_EMISSIONS_COST(4)
        FISCAL_UNIT_EMISSIONS_COST(I,5) = FISCAL_UNIT_EMISSIONS_COST(I,5) + UNIT_EMISSIONS_COST(5)

end subroutine collect_fiscal_data

subroutine collect_group_data(I,SP,CAPBLK,ENRG,HEAT,UNITNO,FUEL_COST,GROUP_VAR_BY_SP,ANNUAL_GROUP_VAR_BY_SP, &
                              CL_UNIT_MONTHLY_FIXED_COST,UNIT_EMISSIONS,TOTAL_UNIT_COST) 

USE prodcom
USE eco

REAL, INTENT(INOUT) :: GROUP_VAR_BY_SP(:,:)
REAL, INTENT(INOUT) :: ANNUAL_GROUP_VAR_BY_SP(:,:)
REAL :: CAPBLK,ENRG
REAL :: CL_UNIT_MONTHLY_FIXED_COST(*)
REAL (kind=8) :: HEAT,FUEL_COST
REAL (kind=4) :: UNIT_EMISSIONS(5)
REAL (kind=4) :: TOTAL_UNIT_COST
INTEGER (kind=2) :: SP,I,UNITNO,EM

          GROUP_VAR_BY_SP(SP,1) = GROUP_VAR_BY_SP(SP,1) + MW(2,I)
          ANNUAL_GROUP_VAR_BY_SP(SP,1) = ANNUAL_GROUP_VAR_BY_SP(SP,1) + MW(2,I)
          GROUP_VAR_BY_SP(SP,2) = GROUP_VAR_BY_SP(SP,2) + CAPBLK
          ANNUAL_GROUP_VAR_BY_SP(SP,2) = ANNUAL_GROUP_VAR_BY_SP(SP,2) + CAPBLK
          GROUP_VAR_BY_SP(SP,3) = GROUP_VAR_BY_SP(SP,3) + ENRG/1000.
          ANNUAL_GROUP_VAR_BY_SP(SP,3) = ANNUAL_GROUP_VAR_BY_SP(SP,3) + ENRG/1000.
          GROUP_VAR_BY_SP(SP,4) = GROUP_VAR_BY_SP(SP,4) + SNGL(HEAT)
          ANNUAL_GROUP_VAR_BY_SP(SP,4) = ANNUAL_GROUP_VAR_BY_SP(SP,4) + SNGL(HEAT)
          GROUP_VAR_BY_SP(SP,5) = GROUP_VAR_BY_SP(SP,5) + SNGL(FUEL_COST)/1000000.
          ANNUAL_GROUP_VAR_BY_SP(SP,5) = ANNUAL_GROUP_VAR_BY_SP(SP,5) + SNGL(FUEL_COST)/1000000.
          GROUP_VAR_BY_SP(SP,6) = GROUP_VAR_BY_SP(SP,6) + VCPMWH(UNITNO)*ENRG/1000000.
          ANNUAL_GROUP_VAR_BY_SP(SP,6) = ANNUAL_GROUP_VAR_BY_SP(SP,6) + VCPMWH(UNITNO)*ENRG/1000000.
          GROUP_VAR_BY_SP(SP,7) = GROUP_VAR_BY_SP(SP,7) + CL_UNIT_MONTHLY_FIXED_COST(UNITNO)/1000000.
          ANNUAL_GROUP_VAR_BY_SP(SP,7) = ANNUAL_GROUP_VAR_BY_SP(SP,7) + CL_UNIT_MONTHLY_FIXED_COST(UNITNO)/1000000.
          DO EM = 1, 5
             GROUP_VAR_BY_SP(SP,7+EM) = GROUP_VAR_BY_SP(SP,7+EM) + UNIT_EMISSIONS(EM)
             ANNUAL_GROUP_VAR_BY_SP(SP,7+EM) = ANNUAL_GROUP_VAR_BY_SP(SP,7+EM) + UNIT_EMISSIONS(EM)
          ENDDO
          GROUP_VAR_BY_SP(SP,13) = GROUP_VAR_BY_SP(SP,13) + MON_ECO_SALES_REV_FROM(UNITNO)/1000000.
          ANNUAL_GROUP_VAR_BY_SP(SP,13) = ANNUAL_GROUP_VAR_BY_SP(SP,13) + MON_ECO_SALES_REV_FROM(UNITNO)/1000000.
          GROUP_VAR_BY_SP(SP,14) = GROUP_VAR_BY_SP(SP,14) + MON_ECO_SALES_ENRG_FROM(UNITNO)/1000.
          ANNUAL_GROUP_VAR_BY_SP(SP,14) = ANNUAL_GROUP_VAR_BY_SP(SP,14) + MON_ECO_SALES_ENRG_FROM(UNITNO)/1000.
          GROUP_VAR_BY_SP(SP,15) = GROUP_VAR_BY_SP(SP,15) + MON_ECO_PUCH_COST_FROM(UNITNO)/1000000.
          ANNUAL_GROUP_VAR_BY_SP(SP,15) = ANNUAL_GROUP_VAR_BY_SP(SP,15) + MON_ECO_PUCH_COST_FROM(UNITNO)/1000000.
          GROUP_VAR_BY_SP(SP,16) = GROUP_VAR_BY_SP(SP,16) + MON_ECO_PUCH_ENRG_FROM(UNITNO)/1000.
          ANNUAL_GROUP_VAR_BY_SP(SP,16) = ANNUAL_GROUP_VAR_BY_SP(SP,16) + MON_ECO_PUCH_ENRG_FROM(UNITNO)/1000.
          GROUP_VAR_BY_SP(SP,17) = GROUP_VAR_BY_SP(SP,17) + MON_ECO_SALES_REV_FROM(UNITNO)/1000000. - TOTAL_UNIT_COST
          ANNUAL_GROUP_VAR_BY_SP(SP,17) = ANNUAL_GROUP_VAR_BY_SP(SP,17) + MON_ECO_SALES_REV_FROM(UNITNO)/1000000. - TOTAL_UNIT_COST


end subroutine collect_group_data
  
end module clreport_routines
