      MODULE ANNLCOMMON
         USE PROD_ARRAYS_DIMENSIONS
         REAL (KIND=4) :: ANNUAL_CL_UNIT_EMISSIONS(&
            NUMBER_OF_EMISSION_TYPES,MAX_CL_UNITS)
         REAL (KIND=4) :: CO2_EMISSIONS_FOR_SYSTEM, &
                                P_FUEL_DELIVERY_1(MAX_CL_UNITS), &
                                P_FUEL_DELIVERY_2(MAX_CL_UNITS), &
                                P_FUEL_DELIVERY_3(MAX_CL_UNITS)
         INTEGER (KIND=8) :: HESI_UNIT_ID_NUM(MAX_CL_UNITS)
         INTEGER (KIND=2) :: EXPANSION_UNIT_LOCATION(MAX_CL_UNITS)=&
         MAX_CL_UNITS*(-1)
         REAL (KIND=4) :: EMISSION_RATES(6,3,MAX_CL_UNITS)
 
      END MODULE ANNLCOMMON
