! aca hago los cambios 
! y destruyo el viejo MON
!

C  COMMON BLOCK VARIABLES FOR /MWUNIH/
      REAL MINLOD,SO2,NOX,PARTICULATES,EMIS_OTH2,EMIS_OTH3,INHEAT,
     +     FUEL_BTU_COST
C SECONDARY FUEL EMISSIONS ADDED 12/10/92 
      REAL SEC_SO2,SEC_NOX_BK1,SEC_NOX_BK2,SEC_CO2,SEC_OTH2,SEC_OTH3,
     +     PRIM_NOX_BK2
      INTEGER*2 UNIT,BLKNO,SHADOW_UNIT_NUMBER,
     +          TIE_CONSTRAINT_GROUP
C
C MONTHLY FUEL LIMITS ADDED 12/30/92 M.S.G.
C
      INTEGER*2 FUEL_LIMITED
C
C CHANGED TO REAL ON 5/14/92
C
      REAL MWBLOK
      LOGICAL*1 MAINT
      COMMON /MWUNIH/SO2(MAX_CL_UNITS),NOX(MAX_CL_UNITS),
     +  PARTICULATES(MAX_CL_UNITS),
     +  EMIS_OTH2(MAX_CL_UNITS),EMIS_OTH3(MAX_CL_UNITS),
     +  MINLOD,INHEAT(MAX_DISPATCH_BLOCKS),
     +  FUEL_BTU_COST(MAX_CL_UNITS),MWBLOK(MAX_DISPATCH_BLOCKS),
     +  SEC_SO2(MAX_CL_UNITS),SEC_NOX_BK1(MAX_CL_UNITS),
     +  SEC_NOX_BK2(MAX_CL_UNITS),SEC_CO2(MAX_CL_UNITS),
     +  SEC_OTH2(MAX_CL_UNITS),SEC_OTH3(MAX_CL_UNITS),
     +  PRIM_NOX_BK2(MAX_CL_UNITS)
C INTEGER*2
      COMMON /MWUNIH_I2/
     +  UNIT(MAX_DISPATCH_BLOCKS),BLKNO(MAX_DISPATCH_BLOCKS),
     +  SHADOW_UNIT_NUMBER(MAX_CL_UNITS),
     +  TIE_CONSTRAINT_GROUP(MAX_CL_UNITS)
C LOGICAL*1
      COMMON /MWUNIH_L1/
     +  MAINT(MAX_CL_UNITS)
C
      COMMON/MONTHLY_LIMITED_FUEL/
C INTEGER*2 
     +  FUEL_LIMITED(MAX_DISPATCH_BLOCKS)

