!
module CLASS_RUN_SWITCHESL1
    implicit none
    logical(kind=1) :: NORMALIZE_FEDERAL_TAXES
    logical(kind=1) :: NORMALIZE_STATE_TAXES
    logical(kind=1) :: MORTGAGE_DEBT
    logical(kind=1) :: CALCULATE_BTL_INCOME_TAXES
    logical(kind=1) :: USE_BURN_4_NUC_FUEL_TAX_EXP
    logical(kind=1) :: PLACE_HOLDER
    logical(kind=1) :: USE_BUDGET_VARIABLE_OM
    logical(kind=1) :: USE_NF_BURN_4_EXPENSE
    logical(kind=1) :: USE_FED_TAX_TABLE
    logical(kind=1) :: USE_DEFERRED_FUEL_ACCOUNTING
    logical(kind=1) :: USE_FASB_109_ACCOUNTING
    logical(kind=1) :: USE_BUDGET_FUEL_PURCHASE
    logical(kind=1) :: USE_ALL_FED_TAX_BENEFITS
    logical(kind=1) :: USE_STATE_TAX_BENEFITS_NOW
    logical(kind=1) :: USE_PRODUCTION_MODULE_EXPENSE
    logical(kind=1) :: USE_PGA_ACCOUNTING
    logical(kind=1) :: USE_PURCHASE_POWER_ACCOUNTING
    save :: NORMALIZE_FEDERAL_TAXES, NORMALIZE_STATE_TAXES, &
           MORTGAGE_DEBT, CALCULATE_BTL_INCOME_TAXES, &
           USE_BURN_4_NUC_FUEL_TAX_EXP, PLACE_HOLDER, &
           USE_BUDGET_VARIABLE_OM, USE_NF_BURN_4_EXPENSE, &
           USE_FED_TAX_TABLE, USE_DEFERRED_FUEL_ACCOUNTING, &
           USE_FASB_109_ACCOUNTING, USE_BUDGET_FUEL_PURCHASE, &
           USE_ALL_FED_TAX_BENEFITS, USE_STATE_TAX_BENEFITS_NOW, &
           USE_PRODUCTION_MODULE_EXPENSE, USE_PGA_ACCOUNTING, &
           USE_PURCHASE_POWER_ACCOUNTING
end module CLASS_RUN_SWITCHESL1
!
!
