!***********************************************************************
!
      FUNCTION CL_SCREEN_DATA()
      use prim_mover_idx
      use esrn_decs
      use miscmod
      use cla_decs
      use cla_fuel
!
!***********************************************************************
! DECLARATION FOR LOCAL VARIABLES
      INTEGER (KIND=2) :: SUNITS,CL_OPTIONS,M,S,RETURN_CL_OPTIONS_NO
      INTEGER (KIND=2) :: PRODUCTION_DATA_POINTER(*),DELETE
      INTEGER (KIND=2) :: TOTAL_ALL_OPTIONS,OPTIONS_COUNTER
      INTEGER (KIND=2) :: PROD_PNTR_BY_CL_UNITS(:),PROD_POINTER
      INTEGER (KIND=2) :: R_YEAR,UPDATE_CL_SCREEN_COSTS,R_MO,R_NUNITS
      INTEGER (KIND=2) :: R_DATE,YR,R_MONTH
      character(len=1024) :: file_name
      LOGICAL (KIND=1) :: CL_SCREEN_DATA,READ_CL_SCREEN_DATA
      LOGICAL (KIND=1) :: IS_A_HARD_WIRED_UNIT(*)
      LOGICAL (KIND=1) :: SCREEN_NOX_ACTIVE_FOR_UNIT
      LOGICAL (KIND=1) :: GET_SCREEN_NOX_CONTROL_FOR_UNIT
      LOGICAL (KIND=1) :: GET_SCREEN_SOX_CONTROL_FOR_UNIT
      LOGICAL (KIND=1) :: GET_SCREEN_CO2_CONTROL_FOR_UNIT
      LOGICAL (KIND=1) :: GET_SCREEN_HG_CONTROL_FOR_UNIT
      LOGICAL (KIND=1) :: GET_SCREEN_OTHER3_CTRL_FOR_UNIT
      LOGICAL (KIND=1) :: R_SEASON_IS_NOX_SEASON,R_CALCULATE_NOX
      LOGICAL (KIND=1) :: YES_GSP_IS_ST_TG,GET_S_BLOCK_CAP_AND_HR
      LOGICAL (KIND=1) :: VECTOR_IS_VALUE,S_YES_MONTHLY_MUST_RUN
      REAL :: RETURN_CL_SCREEN_FIXED_COST,RETURN_CL_SCREEN_VARI_COST
      REAL :: RETURN_CL_SCREEN_FUEL_COST,RETURN_CL_SCREEN_EMIS_COST
      REAL :: GET_CL_CO2_TON_PER_MWH,GET_VAR,FUEL_COMPONENT
      REAL :: OTHER_VARIABLE_COMPONENT=0,RETURN_OTHER_VAR_COMPONENT
      REAL :: FUEL_MIX_FACTOR,EMIS_DISPATCH_1,EMIS_DISPATCH_2
      REAL :: EMIS_DISPATCH_3,EMIS_DISPATCH_4,EMIS_DISPATCH_5
      REAL :: TRANS_DISPATCH_EMIS_ADDER,TRANS_MRX_DISPATCH_EMIS_ADDER
      REAL :: TEMP_R4,TEMP_MO_VAL,R_NOX_MULT,R_SOX_MULT,R_CO2_MULT
      REAL :: R_HG_MULT,R_OTHER3_MULT,R_CO2_RETIREMENT_PRICE
      REAL :: GET_SCENARIO_CO2_PRICES
!
! DECLARATIONS FOR THE EXPANSION PLANT OPERATIONS FILE
!
      CHARACTER (LEN=20) :: S_UNITNM(:)
      CHARACTER (LEN=30) :: CO2_BASIN_NAME
      CHARACTER (LEN=1) :: LDTYPE(:)
      CHARACTER (LEN=2) :: CL_LOAD_TYPE,RESOURCE_TYPE(*),TEMP_STATE
      CHARACTER (LEN=2) :: UNIT_TYPE,UNIT_TYPE_CATEGORY
      CHARACTER (LEN=6) :: PRIM_FUEL_TYPE
      INTEGER (KIND=2) :: GENGRP,ONLIMO,OFLIMO,S_PFESCR(:),S_SFESCR(:)
      INTEGER (KIND=2) :: S_OMESCR(:),S_FIXED_COST_ESCALATOR(:)
      INTEGER (KIND=2) :: CL_AI_CAPACITY_ESCALATOR
      INTEGER (KIND=2) :: CL_AI_ENERGY_ESCALATOR
      INTEGER (KIND=2) :: CL_RESOURCE_ID,FUEL_SUPPLY_ID
      INTEGER (KIND=2) :: EMISS_FUEL_EMISS_PTR,PRIM_FUEL_EMISS_PTR
      INTEGER (KIND=2) :: PROD_PNTR=5000,TIE_CONSTRAINT_GROUP   ! 030310.
      INTEGER (KIND=2) :: S_MONTHLY_CAPACITY_POINTER(:) ! INT*2
      INTEGER (KIND=2) :: S_ANNUAL_CL_FIXED_COST_ESC(:) ! INT*2
      INTEGER (KIND=2) :: SEC_FUEL_EMISS_PTR,EMISS_FUEL_ESCAL
      INTEGER (KIND=2) :: NOX_SEASON_DATE(:),GET_BELONGS_TO_GROUP
      INTEGER (KIND=2) :: ISEAS,STATE_2_GAS_REGION_LOOKUP,TEMP_I2
      INTEGER (KIND=2) :: FIRST_RETIREMENT_YEAR
      INTEGER (KIND=2) :: GET_S_RPS_PROGRAM_NUMBER
      INTEGER (KIND=2) :: S_RPS_PROGRAM_NUMBER(:),R_RPS_PROGRAM
      INTEGER (KIND=8) :: HESI_UNIT_ID_NUM,TRANS_BUS_ID
      INTEGER (KIND=8) :: THERMAL_PARENT_ID,H2_UNIT_ID_NUM
      INTEGER (KIND=4) :: POWERDAT_PLANT_ID
      REAL (KIND=4) :: CAP_FRAC_OWN,S_FUELMX(:),S_PBTUCT(:),S_SBTUCT(:)
      REAL (KIND=4) :: S_FUELADJ_IN(:),S_EFOR(:),S_FUELADJ(:)
      REAL (KIND=4) :: S_MNRATE(:,:),S_VCPMWH_IN(:),S_FIXED_COST_IN(:)
      REAL (KIND=4) :: DISPADJ,S_HR_FACTOR(:),S_INPUT_MW(:,:)
      REAL (KIND=4) :: S_CAP_PLANNING_FAC(:),S_COEFF(:,:)
      REAL (KIND=4) :: CL_AI_CAPACITY_RATE,CL_AI_ENERGY_RATE,P_SO2(:)
      REAL (KIND=4) :: P_NOX(:),P_PARTICULATES(:),CL_POOL_FRAC_OWN
      REAL (KIND=4) :: P_EMIS_OTH2(:),P_EMIS_OTH3(:),DISPADJ2,P_NOX_BK2
      REAL (KIND=4) :: EMISS_FUEL_COST,EMISS_BLENDING_RATE
      REAL (KIND=4) :: S_ANNUAL_CL_FIXED_COST(:),MAINT_DAYS,NOX_VOM(:)
      REAL (KIND=4) :: NOX_FOM(:),SOX_VOM(:),SOX_FOM(:),CO2_VOM(:)
      REAL (KIND=4) :: CO2_FOM(:),HG_VOM(:),HG_FOM(:),OTHER3_VOM(:)
      REAL (KIND=4) :: OTHER3_FOM(:),GET_SCREEN_NOX_VOM
      REAL (KIND=4) :: GET_SCREEN_NOX_FOM,GET_SCREEN_SOX_VOM
      REAL (KIND=4) :: GET_SCREEN_SOX_FOM,GET_SCREEN_CO2_VOM
      REAL (KIND=4) :: GET_SCREEN_CO2_FOM,GET_SCREEN_HG_VOM
      REAL (KIND=4) :: GET_SCREEN_HG_FOM,GET_SCREEN_OTHER3_VOM
      REAL (KIND=4) :: GET_SCREEN_OTHER3_FOM,LATITUDE,LONGITUDE
      REAL (KIND=4) :: MW_INSIDE_FENCE,S_INTER_BLOCKS(:,:),MARKET_FLOOR
      REAL (KIND=4) :: MARKET_CEILING,START_UP_COSTS_ESCALATION(:)
      REAL (KIND=4) :: RTEMP,R_BLOCK_CAPACITY(5),R_BLOCK_HEAT_RATE(5)
      REAL (KIND=4) :: A_HR,B_HR,INC_CAP,GET_S_CAP_PLANNING_FAC
      REAL (KIND=4) :: GET_S_RPS_PERCENT
      INTEGER (KIND=2) :: capacity_market_pointer_ocl
      INTEGER (KIND=2) :: RETROFIT_PROJECT_ID
      REAL (KIND=4) :: CAPACITY_MARKET_COIN_ADJ_FACT,S_RPS_PERCENT(:)
      REAL (KIND=4) :: CO2_PIPELINE_DISTANCE,CO2_RETRO_HEAT_MULT
      REAL (KIND=4) :: CO2_RETRO_CAP_MULT
      CHARACTER (LEN=5) :: CAPACITY_MARKET_TYPE,CAPACITY_MARKET_MONTH
      CHARACTER (LEN=5) :: CAPACITY_MARKET_EXP_COLLECT
      CHARACTER (LEN=20) :: CAPACITY_MARKET_COST_ASSIGN,STATE_PROV_NAME
      CHARACTER (LEN=36) :: THERMAL_GUID
      CHARACTER (LEN=1) :: APPLY_NOX_SEASON_DATE(:)
      CHARACTER (LEN=1) :: THERMAL_AGGREGATED_UNIT
      CHARACTER (LEN=18) :: EXPENSE_ASSIGNMENT,EXPENSE_COLLECTION
      CHARACTER (LEN=10) SEC_FUEL_TYPE,EMISS_FUEL_TYPE
      CHARACTER (LEN=5) :: AGGREGATE_THIS_UNIT,LINKED_BETTERMENT_OPTION
      CHARACTER (LEN=9) :: EMISSION_DATA_UNITS
      CHARACTER (LEN=5) :: TEMP_APPLY_NOX_SEASON_DATE,UNIT_ACTIVE
      CHARACTER (LEN=5) :: REPORT_THIS_UNIT
      CHARACTER (LEN=15) :: UTILITY_OWNED
      CHARACTER (LEN=3) :: INTRA_COMPANY_TRANSACTION
      CHARACTER (LEN=20) :: SPECIAL_UNIT_ID
      CHARACTER (LEN=9) :: START_UP_LOGIC
      CHARACTER (LEN=5) :: CONTRIBUTES_TO_SPIN
      CHARACTER (LEN=6) :: MARKET_RESOURCE
      CHARACTER (LEN=5) :: USE_POLY_HEAT_RATES
      CHARACTER (LEN=20) :: WVPA_RATE_TRACKER,WVPA_RES_TRACKER
      CHARACTER (LEN=20) :: WVPA_FUEL_TRACKER,MONTE_OR_FREQ
      CHARACTER (LEN=20) :: WVPA_MEM_TRACKER
      CHARACTER (LEN=5) :: ALLOW_DECOMMIT
      CHARACTER (LEN=20) :: PRIMARY_FUEL_CATEGORY
      CHARACTER (LEN=20) :: SECONDARY_FUEL_CATEGORY
      CHARACTER (LEN=20) :: EMISSIONS_FUEL_CATEGORY
      CHARACTER (LEN=20) :: RETIREMENT_CANDIDATE
      CHARACTER (LEN=20) :: RETROFIT_CANDIDATE
      CHARACTER (LEN=6) :: BASECASE_PLANT_ID,BASECASE_UNIT_ID
      CHARACTER (LEN=6) :: BASECASE_MARKET_AREA_ID
      CHARACTER (LEN=6) :: BASECASE_TRANS_AREA_ID
      CHARACTER (LEN=6) :: BASECASE_PLANT_NERC_SUB_ID
      CHARACTER (LEN=6) :: BASECASE_PLANT_OWNER_ID
      CHARACTER (LEN=6) :: TEMP_PRIM_FUEL_TYPE_STR
      CHARACTER (LEN=6) :: PRIMARY_MOVER_STR(:),PRIM_FUEL_TYPE_STR
      CHARACTER (LEN=20) :: COUNTY,NEWGEN_UNIT_STATUS
      CHARACTER (LEN=6) :: STATE_PROVINCE,TEMP_CHAR6
      INTEGER (KIND=2) :: AI_CL_REMAINING_LIFE,ASSET_CLASS_NUM
      INTEGER (KIND=2) :: ASSET_CLASS_VECTOR,INTRA_COMPANY_CLASS_ID
      INTEGER (KIND=2) :: S_TRANSACTION_GROUP_ID(:),MONTHLY_FUEL_INDEX
      INTEGER (KIND=2) :: DAY_TYPE_ID,RETURN_S_TRANS_GROUP_ID
      INTEGER (KIND=2) :: S_PRIMARY_MOVER(:),S_UNIT_GAS_REGION_INDEX(:)
      INTEGER (KIND=2) :: GET_SCRN_UNIT_GAS_REGION_INDEX,State_Index(:)
      INTEGER (KIND=2) :: GET_SCREEN_STATE_INDEX,GET_S_PRIMARY_MOVER
      INTEGER (KIND=2) :: NOX_CONTROL_DATE(:),SOX_CONTROL_DATE(:)
      INTEGER (KIND=2) :: CO2_CONTROL_DATE(:),HG_CONTROL_DATE(:)
      INTEGER (KIND=2) :: OTHER3_CONTROL_DATE(:)
      INTEGER (KIND=2) :: MONTHLY_MUST_RUN_VECTOR(:)
      INTEGER (KIND=2) :: MONTHLY_DECOMMIT_VECTOR
      INTEGER (KIND=2) :: S_EMISSION_MARKET_LINK(:)
      INTEGER (KIND=2) :: FT,GET_PRIMARY_MOVER,MO,L_S,I,PM
      INTEGER (KIND=2) :: GET_MRX_EMISSION_MARKET_LINK,STATE_ID_LOOKUP
      INTEGER (KIND=2) :: ST_TG,BASE_PN_RECORDS
      INTEGER (KIND=2) :: GET_S_PRIMARY_MOVER_INDEX
      REAL (KIND=4) :: DISPATCH_MULT,EXCESS_ENERGY_SALES
      REAL (KIND=4) :: MINIMUM_CAPACITY_FACTOR,MAXIMUM_CAPACITY_FACTOR
      REAL (KIND=4) :: AI_CL_TAX_LIFE,AI_CL_ADR_LIFE,RAMP_RATE
      REAL (KIND=4) :: RAMP_DOWN_RATE,P_FUEL_DELIVERY(:)
      REAL (KIND=4) :: START_UP_COSTS(:),GET_S_START_UP_COSTS
      REAL (KIND=4) :: ESCAL_RATE,MIN_DOWN_TIME(:),GET_S_MIN_DOWN_TIME
      REAL (KIND=4) :: MIN_UP_TIME(:),GET_S_MIN_UP_TIME
      REAL (KIND=4) :: S_FUEL_DELIVERY(:),S_FUEL_DELIVERY_2(:)
      REAL (KIND=4) :: S_FUEL_DELIVERY_3(:),CONSTANT_POLY,FIRST_POLY
      REAL (KIND=4) :: SECOND_POLY,THIRD_POLY,MIN_SPIN_CAP,MAX_SPIN_CAP
      REAL (KIND=4) :: FOR_FREQUENCY,FOR_DURATION,WINTER_TOTAL_CAPACITY
      REAL (KIND=4) :: R_FUEL_DELIVERY_1,R_FUEL_DELIVERY_2
      REAL (KIND=4) :: R_FUEL_DELIVERY_3,GET_NEW_UNIT_FUEL_DELIVERY
      REAL (KIND=4) :: R_DELIVERY_COST,SAVE_DELIVERY_COST=0.
      REAL (KIND=4) :: PUT_MRX_DELIVERY_COST,RETURN_CL_SCREEN_EFOR
      REAL (KIND=4) :: R_MONTHLY(12),NOX_CONTROL_PERCENT(:)
      REAL (KIND=4) :: SOX_CONTROL_PERCENT(:),CO2_CONTROL_PERCENT(:)
      REAL (KIND=4) :: HG_CONTROL_PERCENT(:),OTHER3_CONTROL_PERCENT(:)
      REAL (KIND=4) :: R_NOX_CONTROL_PERCENT,R_SOX_CONTROL_PERCENT
      REAL (KIND=4) :: R_CO2_CONTROL_PERCENT,R_HG_CONTROL_PERCENT
      REAL (KIND=4) :: R_OTHER3_CONTROL_PERCENT,EMERGENCY_CAPACITY
      REAL (KIND=4) :: EMERGENCY_HEATRATE,FUEL_SCEN_MULT
      REAL (KIND=4) :: GET_SCENARIO_COAL_PRICES,GET_SCENARIO_GAS_PRICES
      REAL (KIND=4) :: GET_SCENARIO_OIL_PRICES
      REAL (KIND=4) :: GET_SCENARIO_URANIUM_PRICES,R_HEAT_RATE
      REAL (KIND=4) :: R_FUEL_COST,ESCALATED_MONTHLY_VALUE
      REAL (KIND=4) :: START_UP_COST_ESCALAT_MTHLY_VAL
      REAL (KIND=4) :: RET_VAL_FROM_ESCALATION_VECTOR
! DECLARATIONS FOR SCREENING VARIABLES
!
      REAL (KIND=4) :: AHR(:),HEAT_RATE_FACTOR=0.
!
! OPERATIONS FILE
      ALLOCATABLE :: S_FUELMX,S_PBTUCT,S_PFESCR,S_SBTUCT,S_RPS_PROGRAM_NUMBER,S_RPS_PERCENT,P_FUEL_DELIVERY,START_UP_COSTS, &
                     START_UP_COSTS_ESCALATION,MIN_DOWN_TIME,MIN_UP_TIME,S_FUEL_DELIVERY,S_FUEL_DELIVERY_2,S_FUEL_DELIVERY_3, &
                     APPLY_NOX_SEASON_DATE,S_PRIMARY_MOVER,S_UNIT_GAS_REGION_INDEX,State_Index,NOX_SEASON_DATE,NOX_CONTROL_PERCENT,&
                     PRIMARY_MOVER_STR,CO2_CONTROL_PERCENT,HG_CONTROL_PERCENT,OTHER3_CONTROL_PERCENT,NOX_CONTROL_DATE, &
                     CO2_CONTROL_DATE,HG_CONTROL_DATE,MONTHLY_MUST_RUN_VECTOR,OTHER3_CONTROL_DATE,SOX_CONTROL_PERCENT, &
                     SOX_CONTROL_DATE,SOX_VOM,SOX_FOM,NOX_VOM,NOX_FOM,CO2_VOM,CO2_FOM,HG_VOM,HG_FOM,OTHER3_VOM,OTHER3_FOM
      ALLOCATABLE :: S_SFESCR,S_FUELADJ_IN,S_FUELADJ,S_VCPMWH_IN,S_OMESCR,S_EFOR,S_MNRATE,S_INTER_BLOCKS
      ALLOCATABLE :: S_FIXED_COST_IN,S_FIXED_COST_ESCALATOR,S_MONTHLY_CAPACITY_POINTER
      ALLOCATABLE :: S_HR_FACTOR,S_INPUT_MW
      ALLOCATABLE :: S_CAP_PLANNING_FAC,S_COEFF,P_SO2,P_NOX,P_PARTICULATES,P_EMIS_OTH2,P_EMIS_OTH3
      ALLOCATABLE :: PROD_PNTR_BY_CL_UNITS
      ALLOCATABLE :: AHR,S_UNITNM,LDTYPE
      ALLOCATABLE :: S_ANNUAL_CL_FIXED_COST,S_TRANSACTION_GROUP_ID,S_EMISSION_MARKET_LINK
      ALLOCATABLE :: S_ANNUAL_CL_FIXED_COST_ESC
!
      SAVE &
! OPERATIONS FILE
            S_FUELMX,S_PBTUCT,S_PFESCR,S_SBTUCT,S_RPS_PROGRAM_NUMBER,S_RPS_PERCENT,START_UP_COSTS,START_UP_COSTS_ESCALATION, &
            MIN_DOWN_TIME,MIN_UP_TIME,S_FUEL_DELIVERY,S_FUEL_DELIVERY_2,S_FUEL_DELIVERY_3,APPLY_NOX_SEASON_DATE,S_PRIMARY_MOVER, &
            S_UNIT_GAS_REGION_INDEX,State_Index,NOX_SEASON_DATE,NOX_CONTROL_PERCENT,PRIMARY_MOVER_STR,CO2_CONTROL_PERCENT, &
            HG_CONTROL_PERCENT,OTHER3_CONTROL_PERCENT,NOX_CONTROL_DATE,CO2_CONTROL_DATE,HG_CONTROL_DATE,OTHER3_CONTROL_DATE, &
            MONTHLY_MUST_RUN_VECTOR,SOX_CONTROL_PERCENT,SOX_CONTROL_DATE,SOX_VOM,SOX_FOM,NOX_VOM,NOX_FOM,CO2_VOM,CO2_FOM,HG_VOM, &
            HG_FOM,OTHER3_VOM,OTHER3_FOM,S_SFESCR,S_FUELADJ_IN,S_FUELADJ,S_MNRATE,S_INTER_BLOCKS,S_VCPMWH_IN,S_OMESCR,S_EFOR, &
            S_FIXED_COST_IN,S_FIXED_COST_ESCALATOR,S_MONTHLY_CAPACITY_POINTER,S_HR_FACTOR,S_INPUT_MW,S_CAP_PLANNING_FAC,S_COEFF, &
            AHR,S_UNITNM,LDTYPE,P_SO2,P_NOX,P_PARTICULATES,P_EMIS_OTH2,P_EMIS_OTH3,S_ANNUAL_CL_FIXED_COST,S_TRANSACTION_GROUP_ID, &
            S_EMISSION_MARKET_LINK,S_ANNUAL_CL_FIXED_COST_ESC, &
! LOCAL VARIABLES
            PROD_PNTR_BY_CL_UNITS,SUNITS
! SPCapEx additions Nov. 2005
      CHARACTER (LEN=20) :: TECH_TYPE
      LOGICAL (KIND=1) :: SP_CAPEX_ACTIVE,SPCapExOption
      CHARACTER (LEN=15),DIMENSION(155) :: CL_VARIABLES
      REAL (KIND=4) :: FIRST_YEAR_DECOMM_AVAIALABLE
      REAL (KIND=4) :: DECOMMISSIONING_BASE_YR_COST,DECOMMISSIONING_COST_ESCALATION,ANNUAL_ENERGY_PLANNING_FACTOR, &
                       NAME_PLATE_CAPACITY,FuelRatio(5),BlendableFuelsPtr(4),FuelTransportationCost(4),BlendedEnthalpyUp, &
                       BlendedEnthalpyLo,BlendedSO2Up,BettermentProjectID,DECOM_CONTINUING_COST,DECOM_CONTINUING_COST_ESCALATN, &
                       EnrgPatternPointer,EmissRedRate(5),EmissMaxRate(5),MaxEnergyLimit(3)
      CHARACTER (LEN=10) :: FUEL_BLENDING_IS
!
! END OF DATA DECLARATIONS
!
      CL_SCREEN_DATA = .TRUE.
!
!***********************************************************************
      ENTRY READ_CL_SCREEN_DATA(PRODUCTION_DATA_POINTER,RESOURCE_TYPE,CL_OPTIONS,TOTAL_ALL_OPTIONS,IS_A_HARD_WIRED_UNIT)
!***********************************************************************
         CALL GET_BASE_PN_RECORDS(BASE_PN_RECORDS)
         PROD_PNTR = MAX(PROD_PNTR,TOTAL_ALL_OPTIONS,BASE_PN_RECORDS)
         IF(ALLOCATED(S_FUELMX)) then
         
            deallocate(P_FUEL_DELIVERY)
            deallocate(P_FUEL_DELIVERY_2)
            deallocate(P_FUEL_DELIVERY_3)
         
! ...
       DEALLOCATE(S_FUELMX,S_PBTUCT,S_PFESCR,S_SBTUCT,S_RPS_PROGRAM_NUMBER,S_RPS_PERCENT,S_SFESCR,S_FUELADJ_IN,S_FUELADJ,S_MNRATE, &
                  S_INTER_BLOCKS,S_EFOR,S_VCPMWH_IN,S_OMESCR,S_FIXED_COST_IN,S_FIXED_COST_ESCALATOR,S_MONTHLY_CAPACITY_POINTER, &
                  S_HR_FACTOR,S_INPUT_MW,S_CAP_PLANNING_FAC,S_COEFF,P_SO2,P_NOX,P_PARTICULATES,P_EMIS_OTH2,P_EMIS_OTH3,AHR, & 
                  PROD_PNTR_BY_CL_UNITS,S_UNITNM,LDTYPE,S_ANNUAL_CL_FIXED_COST,S_TRANSACTION_GROUP_ID,S_EMISSION_MARKET_LINK, &
                  S_ANNUAL_CL_FIXED_COST_ESC,START_UP_COSTS,START_UP_COSTS_ESCALATION,MIN_DOWN_TIME,MIN_UP_TIME,S_FUEL_DELIVERY, &
                  S_FUEL_DELIVERY_2,S_FUEL_DELIVERY_3,APPLY_NOX_SEASON_DATE,S_PRIMARY_MOVER,S_UNIT_GAS_REGION_INDEX,State_Index, &
                  NOX_SEASON_DATE,NOX_CONTROL_PERCENT,PRIMARY_MOVER_STR,CO2_CONTROL_PERCENT,HG_CONTROL_PERCENT, &
                  OTHER3_CONTROL_PERCENT,NOX_CONTROL_DATE,CO2_CONTROL_DATE,HG_CONTROL_DATE,OTHER3_CONTROL_DATE, &
                  MONTHLY_MUST_RUN_VECTOR,SOX_CONTROL_PERCENT,SOX_CONTROL_DATE,SOX_VOM,SOX_FOM,NOX_VOM,NOX_FOM,CO2_VOM,CO2_FOM, & 
                  HG_VOM,HG_FOM,OTHER3_VOM,OTHER3_FOM)
       endif
! OPERATIONS FILE
         ALLOCATE(S_FUELMX(CL_OPTIONS))
         ALLOCATE(S_PBTUCT(CL_OPTIONS))
         ALLOCATE(S_PFESCR(CL_OPTIONS))
         ALLOCATE(S_SBTUCT(CL_OPTIONS))
         ALLOCATE(S_RPS_PROGRAM_NUMBER(CL_OPTIONS))
         ALLOCATE(S_RPS_PERCENT(CL_OPTIONS))
         ALLOCATE(S_SFESCR(CL_OPTIONS))
         ALLOCATE(S_FUELADJ_IN(CL_OPTIONS))
         ALLOCATE(S_MNRATE(CL_OPTIONS,12))
         ALLOCATE(S_INTER_BLOCKS(CL_OPTIONS,3))
         ALLOCATE(S_FUELADJ(CL_OPTIONS))
         ALLOCATE(S_EFOR(CL_OPTIONS))
         ALLOCATE(S_VCPMWH_IN(CL_OPTIONS))
         ALLOCATE(S_OMESCR(CL_OPTIONS))
         ALLOCATE(S_FIXED_COST_IN(CL_OPTIONS))
         ALLOCATE(S_FIXED_COST_ESCALATOR(CL_OPTIONS))
         ALLOCATE(S_MONTHLY_CAPACITY_POINTER(CL_OPTIONS))
         ALLOCATE(S_HR_FACTOR(CL_OPTIONS))
         ALLOCATE(S_INPUT_MW(2,CL_OPTIONS))
         ALLOCATE(S_CAP_PLANNING_FAC(CL_OPTIONS))
         ALLOCATE(S_COEFF(3,CL_OPTIONS),P_SO2(CL_OPTIONS),P_NOX(CL_OPTIONS),P_PARTICULATES(CL_OPTIONS),P_EMIS_OTH2(CL_OPTIONS), &
                     P_EMIS_OTH3(CL_OPTIONS))
         ALLOCATE(AHR(CL_OPTIONS))
         ALLOCATE(PROD_PNTR_BY_CL_UNITS(PROD_PNTR))
         ALLOCATE(S_UNITNM(CL_OPTIONS))
         ALLOCATE(LDTYPE(CL_OPTIONS))
         ALLOCATE(S_ANNUAL_CL_FIXED_COST(CL_OPTIONS))
         ALLOCATE(S_TRANSACTION_GROUP_ID(CL_OPTIONS))
         ALLOCATE(S_EMISSION_MARKET_LINK(CL_OPTIONS))
         ALLOCATE(S_ANNUAL_CL_FIXED_COST_ESC(CL_OPTIONS))
         ALLOCATE(P_FUEL_DELIVERY(CL_OPTIONS))
         ALLOCATE(START_UP_COSTS(CL_OPTIONS))
         ALLOCATE(START_UP_COSTS_ESCALATION(CL_OPTIONS))
         ALLOCATE(MIN_DOWN_TIME(CL_OPTIONS))
         ALLOCATE(MIN_UP_TIME(CL_OPTIONS))
         ALLOCATE(P_FUEL_DELIVERY_2(CL_OPTIONS))
         ALLOCATE(P_FUEL_DELIVERY_3(CL_OPTIONS))
         ALLOCATE(S_FUEL_DELIVERY(CL_OPTIONS))
         ALLOCATE(S_FUEL_DELIVERY_2(CL_OPTIONS))
         ALLOCATE(s_fuel_delivery_3(CL_OPTIONS))
         ALLOCATE(APPLY_NOX_SEASON_DATE(CL_OPTIONS),S_PRIMARY_MOVER(CL_OPTIONS),S_UNIT_GAS_REGION_INDEX(CL_OPTIONS), &
                  State_Index(CL_OPTIONS),NOX_SEASON_DATE(CL_OPTIONS),NOX_CONTROL_PERCENT(CL_OPTIONS), &
                  PRIMARY_MOVER_STR(CL_OPTIONS),CO2_CONTROL_PERCENT(CL_OPTIONS),HG_CONTROL_PERCENT(CL_OPTIONS), &
                  OTHER3_CONTROL_PERCENT(CL_OPTIONS),NOX_CONTROL_DATE(CL_OPTIONS),CO2_CONTROL_DATE(CL_OPTIONS), &
                  HG_CONTROL_DATE(CL_OPTIONS),OTHER3_CONTROL_DATE(CL_OPTIONS),MONTHLY_MUST_RUN_VECTOR(CL_OPTIONS), &
                  SOX_CONTROL_PERCENT(CL_OPTIONS),SOX_CONTROL_DATE(CL_OPTIONS),SOX_VOM(CL_OPTIONS),SOX_FOM(CL_OPTIONS), &
                  NOX_VOM(CL_OPTIONS),NOX_FOM(CL_OPTIONS),CO2_VOM(CL_OPTIONS),CO2_FOM(CL_OPTIONS),HG_VOM(CL_OPTIONS), &
                  HG_FOM(CL_OPTIONS),OTHER3_VOM(CL_OPTIONS),OTHER3_FOM(CL_OPTIONS))
! READ THE CORRESPONDING EXPANSION PLANT RECORDS
         S_FUEL_DELIVERY=0.0
 
         S_UNIT_GAS_REGION_INDEX = 0
         SUNITS = 0
         S_INTER_BLOCKS = 0.0
         PROD_PNTR_BY_CL_UNITS = -1 ! 111413.
         inquire(unit=13, NAME=file_name)
               call write_log_entry("cla_objt:0019","Reading " // trim(just_the_filename(file_name)) // " (unit 13) ")     
         DO OPTIONS_COUNTER = 1, TOTAL_ALL_OPTIONS
            IF(RESOURCE_TYPE(OPTIONS_COUNTER) /= 'CL' .OR. IS_A_HARD_WIRED_UNIT(OPTIONS_COUNTER)) CYCLE
            SUNITS = SUNITS + 1
!

            PROD_PNTR_BY_CL_UNITS(PRODUCTION_DATA_POINTER(OPTIONS_COUNTER)) = SUNITS


            READ(13,REC=PRODUCTION_DATA_POINTER(OPTIONS_COUNTER)) &
                 DELETE,S_UNITNM(SUNITS),CL_LOAD_TYPE,EXPENSE_ASSIGNMENT,EXPENSE_COLLECTION,GENGRP,CAP_FRAC_OWN,ONLIMO,OFLIMO, &
                 S_FUELMX(SUNITS),S_PBTUCT(SUNITS),S_PFESCR(SUNITS),S_SBTUCT(SUNITS),S_SFESCR(SUNITS),S_FUELADJ_IN(SUNITS), &
                 S_EFOR(SUNITS),(S_MNRATE(SUNITS,M),M=1,12),S_VCPMWH_IN(SUNITS),S_OMESCR(SUNITS),S_FIXED_COST_IN(SUNITS), &
                 S_FIXED_COST_ESCALATOR(SUNITS),DISPADJ,S_HR_FACTOR(SUNITS),(S_INPUT_MW(M,SUNITS),M=1,2), &
                 S_CAP_PLANNING_FAC(SUNITS),(S_COEFF(M,SUNITS),M=1,3),CL_AI_CAPACITY_RATE,CL_AI_CAPACITY_ESCALATOR, &
                 CL_AI_ENERGY_RATE,CL_AI_ENERGY_ESCALATOR,P_SO2(SUNITS),P_NOX(SUNITS),P_PARTICULATES(SUNITS),CL_POOL_FRAC_OWN, &
                 P_EMIS_OTH2(SUNITS),P_EMIS_OTH3(SUNITS),DISPADJ2,CL_RESOURCE_ID,FUEL_SUPPLY_ID,P_NOX_BK2,SEC_FUEL_EMISS_PTR, &
                 EMISS_FUEL_COST,EMISS_FUEL_ESCAL,EMISS_FUEL_EMISS_PTR,EMISS_BLENDING_RATE,PRIM_FUEL_EMISS_PTR, &
                 TEMP_PRIM_FUEL_TYPE_STR,SEC_FUEL_TYPE,EMISS_FUEL_TYPE,TIE_CONSTRAINT_GROUP,S_MONTHLY_CAPACITY_POINTER(SUNITS), & 
                 S_ANNUAL_CL_FIXED_COST(SUNITS),S_ANNUAL_CL_FIXED_COST_ESC(SUNITS),MAINT_DAYS,DISPATCH_MULT,EXCESS_ENERGY_SALES, & 
                 AI_CL_REMAINING_LIFE,AI_CL_TAX_LIFE,AI_CL_ADR_LIFE,ASSET_CLASS_NUM,ASSET_CLASS_VECTOR,INTRA_COMPANY_CLASS_ID, &
                 INTRA_COMPANY_TRANSACTION,SPECIAL_UNIT_ID,MINIMUM_CAPACITY_FACTOR,MAXIMUM_CAPACITY_FACTOR, &
                 S_TRANSACTION_GROUP_ID(SUNITS),DAY_TYPE_ID,UNIT_ACTIVE,BASECASE_PLANT_ID,BASECASE_UNIT_ID, &
                 BASECASE_MARKET_AREA_ID,BASECASE_TRANS_AREA_ID,BASECASE_PLANT_NERC_SUB_ID,BASECASE_PLANT_OWNER_ID,UTILITY_OWNED, &
                 MONTHLY_FUEL_INDEX,START_UP_COSTS(SUNITS),START_UP_LOGIC,RAMP_RATE,MIN_DOWN_TIME(SUNITS),REPORT_THIS_UNIT, &
                 P_FUEL_DELIVERY(SUNITS),P_FUEL_DELIVERY_2(SUNITS),P_FUEL_DELIVERY_3(SUNITS),MIN_UP_TIME(SUNITS),HESI_UNIT_ID_NUM, &
                 FOR_FREQUENCY,FOR_DURATION,WINTER_TOTAL_CAPACITY,CONTRIBUTES_TO_SPIN,H2_UNIT_ID_NUM,POWERDAT_PLANT_ID, &
                 TEMP_APPLY_NOX_SEASON_DATE,NOX_SEASON_DATE(SUNITS),RAMP_DOWN_RATE,NOX_CONTROL_PERCENT(SUNITS), &
                 NOX_CONTROL_DATE(SUNITS),EMERGENCY_CAPACITY,EMERGENCY_HEATRATE,MARKET_RESOURCE,PRIMARY_MOVER_STR(SUNITS),COUNTY, &
                 STATE_PROVINCE,NOX_VOM(SUNITS),NOX_FOM(SUNITS),S_FUEL_DELIVERY(SUNITS),S_FUEL_DELIVERY_2(SUNITS), &
                 S_FUEL_DELIVERY_3(SUNITS),CONSTANT_POLY,FIRST_POLY,SECOND_POLY,THIRD_POLY,USE_POLY_HEAT_RATES,NEWGEN_UNIT_STATUS, &
                 MONTHLY_MUST_RUN_VECTOR(SUNITS),S_EMISSION_MARKET_LINK(SUNITS),WVPA_RATE_TRACKER,ALLOW_DECOMMIT,MIN_SPIN_CAP, & 
                 MAX_SPIN_CAP,WVPA_RES_TRACKER,WVPA_FUEL_TRACKER,MONTE_OR_FREQ,WVPA_MEM_TRACKER,MONTHLY_DECOMMIT_VECTOR, & 
                 TRANS_BUS_ID,SOX_CONTROL_PERCENT(SUNITS),SOX_CONTROL_DATE(SUNITS),SOX_VOM(SUNITS),SOX_FOM(SUNITS), & 
                 LATITUDE,LONGITUDE,MW_INSIDE_FENCE,S_INTER_BLOCKS(SUNITS,1),S_INTER_BLOCKS(SUNITS,2),S_INTER_BLOCKS(SUNITS,3), &
                 FIRST_YEAR_DECOMM_AVAIALABLE,DECOMMISSIONING_BASE_YR_COST,DECOM_CONTINUING_COST_ESCALATN, &
                 ANNUAL_ENERGY_PLANNING_FACTOR,AGGREGATE_THIS_UNIT,NAME_PLATE_CAPACITY,FUEL_BLENDING_IS,FuelRatio(1),FuelRatio(2), &
                 FuelRatio(3),FuelRatio(4),FuelRatio(5),BlendableFuelsPtr(1),BlendableFuelsPtr(2),BlendableFuelsPtr(3), &
                 BlendableFuelsPtr(4),FuelTransportationCost(1),FuelTransportationCost(2),FuelTransportationCost(3), &
                 FuelTransportationCost(4),BlendedEnthalpyUp,BlendedEnthalpyLo,BlendedSO2Up,BettermentProjectID, &
                 DECOM_CONTINUING_COST,DECOM_CONTINUING_COST_ESCALATN,EnrgPatternPointer,EMISSION_DATA_UNITS,EmissRedRate(1), &
                 EmissRedRate(2),EmissRedRate(3),EmissRedRate(4),EmissRedRate(5),EmissMaxRate(1),EmissMaxRate(2),EmissMaxRate(3), &
                 EmissMaxRate(4),EmissMaxRate(5),MaxEnergyLimit(1),MaxEnergyLimit(2),MaxEnergyLimit(3),TECH_TYPE, &
                 LINKED_BETTERMENT_OPTION,CO2_CONTROL_PERCENT(SUNITS),HG_CONTROL_PERCENT(SUNITS),OTHER3_CONTROL_PERCENT(SUNITS), &
                 CO2_CONTROL_DATE(SUNITS),HG_CONTROL_DATE(SUNITS),OTHER3_CONTROL_DATE(SUNITS),CO2_VOM(SUNITS),CO2_FOM(SUNITS), &
                 HG_VOM(SUNITS),HG_FOM(SUNITS),OTHER3_VOM(SUNITS),OTHER3_FOM(SUNITS),MARKET_FLOOR,MARKET_CEILING, &
                 START_UP_COSTS_ESCALATION(SUNITS),CAPACITY_MARKET_TYPE,CAPACITY_MARKET_MONTH,capacity_market_pointer_ocl, &
                 CAPACITY_MARKET_COST_ASSIGN,CAPACITY_MARKET_EXP_COLLECT,CAPACITY_MARKET_COIN_ADJ_FACT,PRIMARY_FUEL_CATEGORY, &
                 SECONDARY_FUEL_CATEGORY,EMISSIONS_FUEL_CATEGORY,S_RPS_PERCENT(SUNITS),RETIREMENT_CANDIDATE,RETROFIT_CANDIDATE, &
                 RETROFIT_PROJECT_ID,CO2_BASIN_NAME,CO2_PIPELINE_DISTANCE,STATE_PROV_NAME,CO2_RETRO_HEAT_MULT,CO2_RETRO_CAP_MULT, &
                 THERMAL_GUID,THERMAL_PARENT_ID,THERMAL_AGGREGATED_UNIT,FIRST_RETIREMENT_YEAR,UNIT_TYPE,UNIT_TYPE_CATEGORY, &
                 S_RPS_PROGRAM_NUMBER(SUNITS)
!
            if(cla_ord_bad(int(capacity_market_pointer_ocl))) then
                call end_program("cla_objt:00013 - capacity_market" //"_pointer contains invalid value after read.")
            endif

            CALL UPC(TEMP_PRIM_FUEL_TYPE_STR,PRIM_FUEL_TYPE_STR)

            TEMP_I2 = STATE_2_GAS_REGION_LOOKUP(STATE_PROVINCE)
            IF(YES_GSP_IS_ST_TG(TEMP_I2)) THEN
               TEMP_CHAR6 = STATE_PROVINCE
            ELSE
               TEMP_CHAR6 = STATE_PROVINCE(1:2)
            ENDIF
            S_UNIT_GAS_REGION_INDEX(SUNITS) = STATE_2_GAS_REGION_LOOKUP(TEMP_CHAR6)
            TEMP_CHAR6 = State_Province(1:2)
            ST_TG = STATE_ID_LOOKUP(TEMP_CHAR6)
            State_Index(SUNITS) = ST_TG

            S_PRIMARY_MOVER(SUNITS) = FUEL_TYPE_2_PRIM_MOVER(PRIM_FUEL_TYPE_STR)
!
! 10/03/02. FOR REGIONAL CONSOLIDATION. NOTE REASSIGNMENT.
!
            APPLY_NOX_SEASON_DATE(SUNITS) = TEMP_APPLY_NOX_SEASON_DATE(1:1)
            S_TRANSACTION_GROUP_ID(SUNITS) = GET_BELONGS_TO_GROUP(S_TRANSACTION_GROUP_ID(SUNITS))
!
            AHR(SUNITS) = (S_COEFF(1,SUNITS)*S_INPUT_MW(1,SUNITS) + (S_COEFF(2,SUNITS)+S_COEFF(3,SUNITS))* &
               (S_INPUT_MW(2,SUNITS) - S_INPUT_MW(1,SUNITS))/2.) / S_INPUT_MW(2,SUNITS)

            NOX_SEASON_DATE(SUNITS) = NOX_SEASON_DATE(SUNITS) + 10000

            NOX_CONTROL_PERCENT(SUNITS) = MIN(100.,MAX(0.,1.-NOX_CONTROL_PERCENT(SUNITS)/100.))
            NOX_CONTROL_DATE(SUNITS) = NOX_CONTROL_DATE(SUNITS) + 10000
!
            SOX_CONTROL_PERCENT(SUNITS) = MIN(100.,MAX(0.,1.-SOX_CONTROL_PERCENT(SUNITS)/100.))
            SOX_CONTROL_DATE(SUNITS) = SOX_CONTROL_DATE(SUNITS) + 10000
!
            CO2_CONTROL_PERCENT(SUNITS) = MIN(100.,MAX(0.,1.-CO2_CONTROL_PERCENT(SUNITS)/100.))
            CO2_CONTROL_DATE(SUNITS) = CO2_CONTROL_DATE(SUNITS) + 10000
            HG_CONTROL_PERCENT(SUNITS) = MIN(100.,MAX(0.,1.-HG_CONTROL_PERCENT(SUNITS)/100.))
            HG_CONTROL_DATE(SUNITS) = HG_CONTROL_DATE(SUNITS) + 10000
            OTHER3_CONTROL_PERCENT(SUNITS) = MIN(100.,MAX(0.,1.-OTHER3_CONTROL_PERCENT(SUNITS)/100.))
            OTHER3_CONTROL_DATE(SUNITS) = OTHER3_CONTROL_DATE(SUNITS) + 10000
            LDTYPE(SUNITS) = CL_LOAD_TYPE(1:1)
!
         ENDDO
         READ_CL_SCREEN_DATA = .TRUE.
      RETURN
!***********************************************************************
      ENTRY GET_S_RPS_PROGRAM_NUMBER(PROD_POINTER)
!***********************************************************************
         L_S = PROD_PNTR_BY_CL_UNITS(PROD_POINTER)
         IF(L_S > 0) THEN
            GET_S_RPS_PROGRAM_NUMBER = S_RPS_PROGRAM_NUMBER(L_S)
         ELSE
            GET_S_RPS_PROGRAM_NUMBER = 0
         ENDIF
      RETURN
!***********************************************************************
      ENTRY GET_S_RPS_PERCENT(PROD_POINTER,R_YEAR)
!***********************************************************************
         L_S = PROD_PNTR_BY_CL_UNITS(PROD_POINTER)
         IF(S_RPS_PERCENT(L_S) < -0.0001) THEN
            GET_S_RPS_PERCENT = 0.01*ESCALATED_MONTHLY_VALUE(GET_S_RPS_PERCENT,ABS(INT(S_RPS_PERCENT(L_S),2)), &
                                               R_YEAR,INT(1,2),INT(1,2))
         ELSE
            GET_S_RPS_PERCENT = S_RPS_PERCENT(L_S)*0.01
         ENDIF
      RETURN
!***********************************************************************
      ENTRY GET_S_BLOCK_CAP_AND_HR(PROD_POINTER,R_BLOCK_CAPACITY,R_BLOCK_HEAT_RATE,R_YEAR)
!***********************************************************************
         L_S = PROD_PNTR_BY_CL_UNITS(PROD_POINTER)
         R_BLOCK_CAPACITY = 0.
         R_BLOCK_HEAT_RATE = 0.
         IF(L_S > 0) THEN
            GET_S_BLOCK_CAP_AND_HR = .TRUE.
            IF(S_HR_FACTOR(L_S) < 0.) THEN
               HEAT_RATE_FACTOR = GET_VAR(S_HR_FACTOR(L_S),R_YEAR,S_UNITNM(L_S))
            ELSE
               HEAT_RATE_FACTOR = S_HR_FACTOR(L_S)
            ENDIF
!
            IF(S_INPUT_MW(2,L_S) - S_INPUT_MW(1,L_S) < 0.0001 .OR. S_INPUT_MW(1,L_S) < 0.0001) THEN

               R_BLOCK_CAPACITY(1) = 0.0
               R_BLOCK_HEAT_RATE(1) = 0.0
               R_BLOCK_CAPACITY(2) = MAX(S_INPUT_MW(1,L_S),S_INPUT_MW(2,L_S))
               R_BLOCK_HEAT_RATE(2) = S_COEFF(1,L_S) * HEAT_RATE_FACTOR
            ELSE
! TWO BLOCK
               IF(S_INPUT_MW(1,L_S) < 1.0) THEN
                  R_BLOCK_CAPACITY(1) = S_INPUT_MW(1,L_S) * S_INPUT_MW(2,L_S)
               ELSE
                  R_BLOCK_CAPACITY(1) = S_INPUT_MW(1,L_S)
               ENDIF
               R_BLOCK_HEAT_RATE(1) = S_COEFF(1,L_S) * HEAT_RATE_FACTOR
               R_BLOCK_CAPACITY(2) = S_INPUT_MW(2,L_S)
               INC_CAP = S_INPUT_MW(2,L_S) - S_INPUT_MW(1,L_S)
               A_HR = (S_COEFF(3,L_S) - S_COEFF(2,L_S))/(2.*INC_CAP)
               B_HR = S_COEFF(3,L_S) - 2.* A_HR * INC_CAP
               R_BLOCK_HEAT_RATE(2) = (A_HR*INC_CAP + B_HR) * HEAT_RATE_FACTOR
            ENDIF

         ELSE
            GET_S_BLOCK_CAP_AND_HR = .FALSE.
         ENDIF
      RETURN
      
!***********************************************************************
      ENTRY GET_SCRN_UNIT_GAS_REGION_INDEX(PROD_POINTER)
!***********************************************************************
         L_S = PROD_PNTR_BY_CL_UNITS(PROD_POINTER)
         GET_SCRN_UNIT_GAS_REGION_INDEX = S_UNIT_GAS_REGION_INDEX(L_S)
      RETURN
!***********************************************************************
      ENTRY GET_SCREEN_STATE_INDEX(PROD_POINTER)
!***********************************************************************
         L_S = PROD_PNTR_BY_CL_UNITS(PROD_POINTER)
         GET_SCREEN_STATE_INDEX = State_Index(L_S)
      RETURN
!***********************************************************************
      ENTRY SCREEN_NOX_ACTIVE_FOR_UNIT(PROD_POINTER,R_DATE,R_SEASON_IS_NOX_SEASON,R_CALCULATE_NOX)
!***********************************************************************
         L_S = PROD_PNTR_BY_CL_UNITS(PROD_POINTER)
!
         SCREEN_NOX_ACTIVE_FOR_UNIT = .TRUE.
         IF(APPLY_NOX_SEASON_DATE(PROD_POINTER) == 'T') THEN
            IF(R_DATE >= NOX_SEASON_DATE(PROD_POINTER) .AND. R_SEASON_IS_NOX_SEASON) THEN
               R_CALCULATE_NOX = .TRUE.
            ELSE
               R_CALCULATE_NOX = .FALSE.
            ENDIF
         ENDIF
      RETURN
!***********************************************************************
      ENTRY GET_SCREEN_NOX_CONTROL_FOR_UNIT(PROD_POINTER,R_DATE,R_NOX_CONTROL_PERCENT)
!***********************************************************************
         L_S = PROD_PNTR_BY_CL_UNITS(PROD_POINTER)
!
         GET_SCREEN_NOX_CONTROL_FOR_UNIT = .FALSE.
         R_NOX_CONTROL_PERCENT = 1.0
         IF(R_DATE >= NOX_CONTROL_DATE(L_S)) THEN
            GET_SCREEN_NOX_CONTROL_FOR_UNIT = .TRUE.
            R_NOX_CONTROL_PERCENT = NOX_CONTROL_PERCENT(L_S)
         ENDIF
      RETURN
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
      ENTRY GET_SCREEN_CO2_CONTROL_FOR_UNIT(PROD_POINTER,R_DATE,R_CO2_CONTROL_PERCENT)
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
         L_S = PROD_PNTR_BY_CL_UNITS(PROD_POINTER)
!
         GET_SCREEN_CO2_CONTROL_FOR_UNIT = .FALSE.
         R_CO2_CONTROL_PERCENT = 1.0
         IF(R_DATE >= CO2_CONTROL_DATE(L_S)) THEN
            GET_SCREEN_CO2_CONTROL_FOR_UNIT = .TRUE.
            R_CO2_CONTROL_PERCENT = CO2_CONTROL_PERCENT(L_S)
         ENDIF
      RETURN
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
      ENTRY GET_SCREEN_HG_CONTROL_FOR_UNIT(PROD_POINTER,R_DATE,R_HG_CONTROL_PERCENT)
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
         L_S = PROD_PNTR_BY_CL_UNITS(PROD_POINTER)
!
         GET_SCREEN_HG_CONTROL_FOR_UNIT = .FALSE.
         R_HG_CONTROL_PERCENT = 1.0
         IF(R_DATE >= HG_CONTROL_DATE(L_S)) THEN
            GET_SCREEN_HG_CONTROL_FOR_UNIT = .TRUE.
            R_HG_CONTROL_PERCENT = HG_CONTROL_PERCENT(L_S)
         ENDIF
      RETURN
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
      ENTRY GET_SCREEN_OTHER3_CTRL_FOR_UNIT(PROD_POINTER,R_DATE,R_OTHER3_CONTROL_PERCENT)
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
         L_S = PROD_PNTR_BY_CL_UNITS(PROD_POINTER)
!
         GET_SCREEN_OTHER3_CTRL_FOR_UNIT = .FALSE.
         R_OTHER3_CONTROL_PERCENT = 1.0
         IF(R_DATE >= OTHER3_CONTROL_DATE(L_S)) THEN
            GET_SCREEN_OTHER3_CTRL_FOR_UNIT = .TRUE.
            R_OTHER3_CONTROL_PERCENT = OTHER3_CONTROL_PERCENT(L_S)
         ENDIF
      RETURN
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
      ENTRY GET_SCREEN_SOX_CONTROL_FOR_UNIT(PROD_POINTER,R_DATE,R_SOX_CONTROL_PERCENT)
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
         L_S = PROD_PNTR_BY_CL_UNITS(PROD_POINTER)
!
         GET_SCREEN_SOX_CONTROL_FOR_UNIT = .FALSE.
         R_SOX_CONTROL_PERCENT = 1.0
         IF(R_DATE >= SOX_CONTROL_DATE(L_S)) THEN
            GET_SCREEN_SOX_CONTROL_FOR_UNIT = .TRUE.
            R_SOX_CONTROL_PERCENT = SOX_CONTROL_PERCENT(L_S)
         ENDIF
      RETURN
!***********************************************************************
      ENTRY GET_SCREEN_NOX_VOM(PROD_POINTER) ! R_NUNITS)  !R4
!***********************************************************************
         L_S = PROD_PNTR_BY_CL_UNITS(PROD_POINTER)
!
         GET_SCREEN_NOX_VOM = NOX_VOM(L_S)
      RETURN
!***********************************************************************
      ENTRY GET_SCREEN_NOX_FOM(PROD_POINTER) ! R_NUNITS)  !R4
!***********************************************************************
         L_S = PROD_PNTR_BY_CL_UNITS(PROD_POINTER)
!
         GET_SCREEN_NOX_FOM = NOX_FOM(L_S)
      RETURN
!***********************************************************************
      ENTRY GET_SCREEN_CO2_VOM(PROD_POINTER) ! R_NUNITS)  !R4
!***********************************************************************
         L_S = PROD_PNTR_BY_CL_UNITS(PROD_POINTER)
!
         GET_SCREEN_CO2_VOM = CO2_VOM(L_S)
      RETURN
!***********************************************************************
      ENTRY GET_SCREEN_CO2_FOM(PROD_POINTER) ! R_NUNITS)  !R4
!***********************************************************************
         L_S = PROD_PNTR_BY_CL_UNITS(PROD_POINTER)
!
         GET_SCREEN_CO2_FOM = CO2_FOM(L_S)
      RETURN
!***********************************************************************
      ENTRY GET_SCREEN_HG_VOM(PROD_POINTER) ! R_NUNITS)  !R4
!***********************************************************************
         L_S = PROD_PNTR_BY_CL_UNITS(PROD_POINTER)
!
         GET_SCREEN_HG_VOM = HG_VOM(L_S)
      RETURN
!***********************************************************************
      ENTRY GET_SCREEN_HG_FOM(PROD_POINTER) ! R_NUNITS)  !R4
!***********************************************************************
         L_S = PROD_PNTR_BY_CL_UNITS(PROD_POINTER)
!
         GET_SCREEN_HG_FOM = HG_FOM(L_S)
      RETURN
!***********************************************************************
      ENTRY GET_SCREEN_OTHER3_VOM(PROD_POINTER) ! R_NUNITS)  !R4
!***********************************************************************
         L_S = PROD_PNTR_BY_CL_UNITS(PROD_POINTER)
!
         GET_SCREEN_OTHER3_VOM = OTHER3_VOM(L_S)
      RETURN
!***********************************************************************
      ENTRY GET_SCREEN_OTHER3_FOM(PROD_POINTER) ! R_NUNITS)  !R4
!***********************************************************************
         L_S = PROD_PNTR_BY_CL_UNITS(PROD_POINTER)
!
         GET_SCREEN_OTHER3_FOM = OTHER3_FOM(L_S)
      RETURN
!***********************************************************************
      ENTRY GET_SCREEN_SOX_VOM(PROD_POINTER) ! R_NUNITS)  !R4
!***********************************************************************
         L_S = PROD_PNTR_BY_CL_UNITS(PROD_POINTER)
!
         GET_SCREEN_SOX_VOM = SOX_VOM(L_S)
      RETURN
!***********************************************************************
      ENTRY GET_SCREEN_SOX_FOM(PROD_POINTER) ! R_NUNITS)  !R4
!***********************************************************************
         L_S = PROD_PNTR_BY_CL_UNITS(PROD_POINTER)
!
         GET_SCREEN_SOX_FOM = SOX_FOM(L_S)
      RETURN
!***********************************************************************
      ENTRY GET_MRX_EMISSION_MARKET_LINK(PROD_POINTER)
!***********************************************************************
         GET_MRX_EMISSION_MARKET_LINK = S_EMISSION_MARKET_LINK(PROD_POINTER)
      RETURN
!***********************************************************************
!***********************************************************************
      ENTRY S_YES_MONTHLY_MUST_RUN(PROD_POINTER,R_MONTH)
!***********************************************************************
         L_S = PROD_PNTR_BY_CL_UNITS(PROD_POINTER)
         S_YES_MONTHLY_MUST_RUN = .FALSE.
         IF(LDTYPE(L_S) == 'N' .OR. LDTYPE(L_S) == 'M') THEN
            S_YES_MONTHLY_MUST_RUN = .TRUE.
         ELSEIF(MONTHLY_MUST_RUN_VECTOR(L_S) /= 0) THEN
            TEMP_R4 = GET_VAR(FLOAT(MONTHLY_MUST_RUN_VECTOR(L_S)),R_MONTH,S_UNITNM(L_S))
            IF(TEMP_R4 > 0.) THEN
               S_YES_MONTHLY_MUST_RUN = .TRUE.
            ENDIF
         ENDIF
      RETURN
!***********************************************************************
      ENTRY GET_S_CAP_PLANNING_FAC(PROD_POINTER,R_YEAR)
!***********************************************************************
         L_S = PROD_PNTR_BY_CL_UNITS(PROD_POINTER)
         IF(S_CAP_PLANNING_FAC(L_S) < 0.) THEN
            GET_S_CAP_PLANNING_FAC = GET_VAR(S_CAP_PLANNING_FAC(L_S),R_YEAR,S_UNITNM(L_S))
         ELSE
            GET_S_CAP_PLANNING_FAC = S_CAP_PLANNING_FAC(L_S)
         ENDIF
      RETURN
!***********************************************************************
      ENTRY GET_S_START_UP_COSTS(R_YEAR,PROD_POINTER,R_MONTH)
!***********************************************************************
         L_S = PROD_PNTR_BY_CL_UNITS(PROD_POINTER)
         IF(START_UP_COSTS(L_S) < 0.) THEN
            GET_S_START_UP_COSTS = START_UP_COST_ESCALAT_MTHLY_VAL(INT(ABS(START_UP_COSTS(L_S)),2),R_YEAR)
         ELSE
!
            IF(START_UP_COSTS_ESCALATION(L_S) < 0.) THEN
               GET_S_START_UP_COSTS = 1.
               VECTOR_IS_VALUE = .FALSE.
               DO YR = R_YEAR ,1,-1
                 TEMP_I2 = INT(START_UP_COSTS_ESCALATION(L_S),2)
                  ESCAL_RATE = RET_VAL_FROM_ESCALATION_VECTOR(YR,TEMP_I2,VECTOR_IS_VALUE,R_MONTH)
                  IF(VECTOR_IS_VALUE) THEN
                     GET_S_START_UP_COSTS = GET_S_START_UP_COSTS * ESCAL_RATE
                     EXIT
                  ELSE
                     GET_S_START_UP_COSTS = GET_S_START_UP_COSTS * (1.0 + ESCAL_RATE/100.)
                  ENDIF
               ENDDO ! YR
               IF(.NOT. VECTOR_IS_VALUE) THEN
                  GET_S_START_UP_COSTS = GET_S_START_UP_COSTS * START_UP_COSTS(L_S)
               ENDIF
            ELSEIF(START_UP_COSTS_ESCALATION(L_S) > 0.) THEN
               ESCAL_RATE =  START_UP_COSTS_ESCALATION(L_S)/100.
               GET_S_START_UP_COSTS = START_UP_COSTS(L_S)
               DO YR = 1, R_YEAR
                  GET_S_START_UP_COSTS = GET_S_START_UP_COSTS * (1.0 + ESCAL_RATE)
               ENDDO
            ELSE
               GET_S_START_UP_COSTS = START_UP_COSTS(L_S)
            ENDIF
         ENDIF
      RETURN
!***********************************************************************
      ENTRY GET_S_MIN_DOWN_TIME(PROD_POINTER)
!***********************************************************************
         L_S = PROD_PNTR_BY_CL_UNITS(PROD_POINTER)
         GET_S_MIN_DOWN_TIME = MIN_DOWN_TIME(L_S)
      RETURN
!***********************************************************************
      ENTRY GET_S_MIN_UP_TIME(PROD_POINTER)
!***********************************************************************
         L_S = PROD_PNTR_BY_CL_UNITS(PROD_POINTER)
         GET_S_MIN_UP_TIME = MIN_UP_TIME(L_S)
      RETURN
!***********************************************************************
      ENTRY GET_NEW_UNIT_FUEL_DELIVERY(PROD_POINTER,R_FUEL_DELIVERY_1,R_FUEL_DELIVERY_2,R_FUEL_DELIVERY_3)
!***********************************************************************
         L_S = PROD_PNTR_BY_CL_UNITS(PROD_POINTER)
         R_FUEL_DELIVERY_1 = P_FUEL_DELIVERY(L_S)
         R_FUEL_DELIVERY_2 = P_FUEL_DELIVERY_2(L_S)
         R_FUEL_DELIVERY_3 = P_FUEL_DELIVERY_3(L_S)
         GET_NEW_UNIT_FUEL_DELIVERY = S_PBTUCT(L_S)
      RETURN
!***********************************************************************
      ENTRY RETURN_S_TRANS_GROUP_ID(PROD_POINTER)
!***********************************************************************
         L_S = PROD_PNTR_BY_CL_UNITS(PROD_POINTER)
         RETURN_S_TRANS_GROUP_ID = S_TRANSACTION_GROUP_ID(L_S)
      RETURN
!***********************************************************************
      ENTRY UPDATE_CL_SCREEN_COSTS(R_YEAR)
!***********************************************************************
!
         DO S = 1, SUNITS
            S_FIXED_COST_IN(S) = get_escalated_value(int(S_FIXED_COST_IN(S),2),int(S_FIXED_COST_ESCALATOR(S),2))
            S_ANNUAL_CL_FIXED_COST(S) = get_escalated_value(int(S_ANNUAL_CL_FIXED_COST(S),2),S_ANNUAL_CL_FIXED_COST_ESC(S))
!
       S_PBTUCT(S) = get_escalated_value(int(S_PBTUCT(S),2),int(S_PFESCR(S),2))
       S_SBTUCT(S) = get_escalated_value(int(S_SBTUCT(S),2),int(S_SFESCR(S),2))
!
            S_VCPMWH_IN(S) = get_escalated_value(int(S_VCPMWH_IN(S),2), int(S_OMESCR(S),2))
            RTEMP = S_FUELADJ_IN(S)
            IF(RTEMP < 0.0) THEN
               RTEMP = GET_VAR(RTEMP,R_YEAR,S_UNITNM(S))
               IF(RTEMP < 0.) THEN
                  S_FUELADJ(S) = GET_VAR(RTEMP,ISEAS,S_UNITNM(S))
               ELSE
                  S_FUELADJ(S) = RTEMP
               ENDIF
            ELSE
               S_FUELADJ(S) = RTEMP
            ENDIF

         ENDDO
!
         UPDATE_CL_SCREEN_COSTS = SUNITS
      RETURN
!***********************************************************************
      ENTRY RETURN_CL_SCREEN_FIXED_COST(PROD_POINTER)
!***********************************************************************
         L_S = PROD_PNTR_BY_CL_UNITS(PROD_POINTER)
         RETURN_CL_SCREEN_FIXED_COST = S_FIXED_COST_IN(L_S) * (S_INPUT_MW(2,L_S)*1000.) + S_ANNUAL_CL_FIXED_COST(L_S) * 1000000.
      RETURN
!***********************************************************************
      ENTRY PUT_MRX_DELIVERY_COST(R_DELIVERY_COST)
!***********************************************************************
         SAVE_DELIVERY_COST = R_DELIVERY_COST
         PUT_MRX_DELIVERY_COST = R_DELIVERY_COST
      RETURN
!***********************************************************************
      ENTRY RETURN_CL_SCREEN_EFOR(PROD_POINTER,R_YEAR,R_MONTHLY)
!***********************************************************************
         L_S = PROD_PNTR_BY_CL_UNITS(PROD_POINTER)
!
         IF(S_EFOR(L_S) < 0.) THEN
            RETURN_CL_SCREEN_EFOR = GET_VAR(S_EFOR(L_S),R_YEAR,S_UNITNM(L_S))/100.
         ELSE
            RETURN_CL_SCREEN_EFOR = S_EFOR(L_S)/100.
         ENDIF
!
!  MONTH.
!
         TEMP_R4 = 0.0
         R_MONTHLY = 0.0
         DO I = 1, 12
            IF(S_MONTHLY_CAPACITY_POINTER(L_S) < 0) THEN
               TEMP_MO_VAL = GET_VAR(FLOAT(S_MONTHLY_CAPACITY_POINTER(L_S)),I,S_UNITNM(L_S))
            ELSE
               TEMP_MO_VAL = 1.0
            ENDIF

            TEMP_MO_VAL = TEMP_MO_VAL * (1.0 - MIN(100.,S_MNRATE(L_S,I))/100.)
            R_MONTHLY(I) = TEMP_MO_VAL
            TEMP_R4 = TEMP_R4 + TEMP_MO_VAL
         ENDDO
         RETURN_CL_SCREEN_EFOR = 1.0 - (1.0 - RETURN_CL_SCREEN_EFOR) * TEMP_R4/12.0
         RETURN_CL_SCREEN_EFOR = MAX(0.0,MIN(RETURN_CL_SCREEN_EFOR,0.9999))
!
      RETURN
!***********************************************************************
      ENTRY GET_S_PRIMARY_MOVER_INDEX(PROD_POINTER)
!***********************************************************************
         L_S = PROD_PNTR_BY_CL_UNITS(PROD_POINTER)
         GET_S_PRIMARY_MOVER_INDEX = PRIMARY_MOVER_INDEX_DB(PRIMARY_MOVER_STR(L_S))
         IF(GET_S_PRIMARY_MOVER_INDEX == 10 .AND. S_PRIMARY_MOVER(L_S) > 3 ) THEN
            GET_S_PRIMARY_MOVER_INDEX = 7
         ENDIF
      RETURN
!***********************************************************************
      ENTRY GET_S_PRIMARY_MOVER(PROD_POINTER)
!***********************************************************************
         IF(PROD_POINTER > PROD_PNTR) THEN
            WRITE(4,*)'MRX POINTER OUT OF RANGE WHEN FINDING PRIMARY MOVER'
         ENDIF
         L_S = PROD_PNTR_BY_CL_UNITS(PROD_POINTER)
         IF(L_S < 1) THEN
            WRITE(4,*)'MRX POINTER OUT OF RANGE WHEN FINDING PRIMARY MOVER.'
            WRITE(4,*)'MAY BE DUE TO HARD-WIRED UNIT. 111413.'
         ENDIF
         GET_S_PRIMARY_MOVER = S_PRIMARY_MOVER(L_S)
      RETURN
!***********************************************************************
      ENTRY RETURN_CL_SCREEN_VARI_COST(PROD_POINTER,R_YEAR,R_MO)
!***********************************************************************
         L_S = PROD_PNTR_BY_CL_UNITS(PROD_POINTER)
!
         IF(S_HR_FACTOR(L_S) < 0.) THEN
            HEAT_RATE_FACTOR = GET_VAR(S_HR_FACTOR(L_S),R_YEAR,S_UNITNM(L_S))
         ELSE
            HEAT_RATE_FACTOR = S_HR_FACTOR(L_S)
         ENDIF
         IF(S_FUELMX(L_S) <= -2.) THEN
            FUEL_MIX_FACTOR = GET_VAR(S_FUELMX(L_S),R_YEAR,S_UNITNM(L_S))
         ELSE
            FUEL_MIX_FACTOR = S_FUELMX(L_S)
         ENDIF
!
         FT = GET_PRIMARY_MOVER(L_S)
!
         IF(FT > 3 .OR. FT < 1) FT = 1
         MO = R_MO
!
         FUEL_SCEN_MULT = 1.0
         IF(FT == 1) THEN
            FUEL_SCEN_MULT = GET_SCENARIO_COAL_PRICES(R_YEAR,MO)
         ELSEIF(FT == 2) THEN
            FUEL_SCEN_MULT =  GET_SCENARIO_GAS_PRICES(R_YEAR,MO)
         ELSEIF(FT == 3) THEN
            FUEL_SCEN_MULT =  GET_SCENARIO_OIL_PRICES(R_YEAR,MO)
         ELSEIF(FT == 4) THEN
            FUEL_SCEN_MULT =  GET_SCENARIO_URANIUM_PRICES(R_YEAR,MO)
         ENDIF
!
         IF(SAVE_DELIVERY_COST == -999999.) THEN
            FUEL_COMPONENT = .001 * AHR(L_S) * HEAT_RATE_FACTOR * (ABS(FUEL_MIX_FACTOR) * S_PBTUCT(L_S) +  &
                           ABS(1.-FUEL_MIX_FACTOR) * S_SBTUCT(L_S))
         ELSE
            FUEL_COMPONENT = .001 * AHR(L_S) * HEAT_RATE_FACTOR * SAVE_DELIVERY_COST
         ENDIF
         OTHER_VARIABLE_COMPONENT = S_VCPMWH_IN(L_S) + S_FUELADJ(L_S)
!
         RETURN_CL_SCREEN_VARI_COST = 8.76*( FUEL_COMPONENT + OTHER_VARIABLE_COMPONENT )
!
      RETURN
!***********************************************************************
      ENTRY RETURN_OTHER_VAR_COMPONENT(PROD_POINTER)
!***********************************************************************
         L_S = PROD_PNTR_BY_CL_UNITS(PROD_POINTER)
         RETURN_OTHER_VAR_COMPONENT = S_VCPMWH_IN(L_S) + S_FUELADJ(L_S)
      RETURN
!***********************************************************************
      ENTRY RETURN_CL_SCREEN_EMIS_COST(PROD_POINTER,R_YEAR,R_MO,R_NOX_MULT,R_SOX_MULT,R_CO2_MULT,R_HG_MULT,R_OTHER3_MULT, &
                                      R_CO2_RETIREMENT_PRICE)
!***********************************************************************
         L_S = PROD_PNTR_BY_CL_UNITS(PROD_POINTER)                      ! TMS 03/28/05 added to get proper unit reference
         I = S_EMISSION_MARKET_LINK(L_S)
!
         EMIS_DISPATCH_1 = TRANS_MRX_DISPATCH_EMIS_ADDER(1,R_MO,R_YEAR,I)
         EMIS_DISPATCH_2 = TRANS_MRX_DISPATCH_EMIS_ADDER(2,R_MO,R_YEAR,I)
         IF(R_CO2_RETIREMENT_PRICE > -999.0) THEN
            EMIS_DISPATCH_3 = R_CO2_RETIREMENT_PRICE * GET_SCENARIO_CO2_PRICES(R_YEAR,R_MO)/2000.0
         ELSE 
            EMIS_DISPATCH_3 = TRANS_MRX_DISPATCH_EMIS_ADDER(3,R_MO,R_YEAR,I)
         ENDIF
         EMIS_DISPATCH_4 = TRANS_MRX_DISPATCH_EMIS_ADDER(4,R_MO,R_YEAR,I)
         EMIS_DISPATCH_5 = TRANS_MRX_DISPATCH_EMIS_ADDER(5,R_MO,R_YEAR,I)
!
         TEMP_R4 = EMIS_DISPATCH_1 * MAX(P_SO2(L_S)*R_SOX_MULT,0.) + EMIS_DISPATCH_2 * MAX(P_NOX(L_S)*R_NOX_MULT,0.) + &
                 EMIS_DISPATCH_3 * MAX(P_PARTICULATES(L_S)* R_CO2_MULT,0.) + EMIS_DISPATCH_4 * MAX(P_EMIS_OTH2(L_S)* &
                 R_HG_MULT,0.) + EMIS_DISPATCH_5 * MAX(P_EMIS_OTH3(L_S)* R_OTHER3_MULT,0.)
        IF(S_HR_FACTOR(L_S) < 0.) THEN
            HEAT_RATE_FACTOR = GET_VAR(S_HR_FACTOR(L_S),R_YEAR,S_UNITNM(L_S))
         ELSE
            HEAT_RATE_FACTOR = S_HR_FACTOR(L_S)
         ENDIF

         RETURN_CL_SCREEN_EMIS_COST = .001 * AHR(L_S) * HEAT_RATE_FACTOR * TEMP_R4

       RETURN
!***********************************************************************
      ENTRY GET_CL_CO2_TON_PER_MWH(R_YEAR,PROD_POINTER,R_DATE)
!***********************************************************************
         L_S = PROD_PNTR_BY_CL_UNITS(PROD_POINTER)
         IF(S_HR_FACTOR(L_S) < 0.) THEN
            HEAT_RATE_FACTOR = GET_VAR(S_HR_FACTOR(L_S),R_YEAR,S_UNITNM(L_S))
         ELSE
            HEAT_RATE_FACTOR = S_HR_FACTOR(L_S)
         ENDIF
         IF(R_DATE >= CO2_CONTROL_DATE(L_S)) THEN
            GET_CL_CO2_TON_PER_MWH = MAX(P_PARTICULATES(L_S)*CO2_CONTROL_PERCENT(L_S),0.)
         ELSE
            GET_CL_CO2_TON_PER_MWH = MAX(P_PARTICULATES(L_S),0.)
         ENDIF
            GET_CL_CO2_TON_PER_MWH = GET_CL_CO2_TON_PER_MWH * HEAT_RATE_FACTOR * 0.0000005 * AHR(L_S)
      RETURN
!***********************************************************************
      ENTRY RETURN_CL_SCREEN_FUEL_COST(PROD_POINTER,R_YEAR,R_HEAT_RATE,R_FUEL_COST)
!***********************************************************************
         L_S = PROD_PNTR_BY_CL_UNITS(PROD_POINTER)
!
         IF(S_HR_FACTOR(L_S) < 0.) THEN
            HEAT_RATE_FACTOR = GET_VAR(S_HR_FACTOR(L_S),R_YEAR,S_UNITNM(L_S))
         ELSE
            HEAT_RATE_FACTOR = S_HR_FACTOR(L_S)
         ENDIF
         IF(S_FUELMX(L_S) <= -2.) THEN
            FUEL_MIX_FACTOR = GET_VAR(S_FUELMX(L_S),R_YEAR,S_UNITNM(L_S))
         ELSE
            FUEL_MIX_FACTOR = S_FUELMX(L_S)
         ENDIF
         R_HEAT_RATE = AHR(L_S) * HEAT_RATE_FACTOR
         IF(SAVE_DELIVERY_COST == -999999.) THEN
            R_FUEL_COST = (ABS(FUEL_MIX_FACTOR) * S_PBTUCT(L_S) + ABS(1.-FUEL_MIX_FACTOR) * S_SBTUCT(L_S))
         ELSE
            R_FUEL_COST = SAVE_DELIVERY_COST
         ENDIF
         FUEL_COMPONENT = R_FUEL_COST * R_HEAT_RATE * .001
!
         RETURN_CL_SCREEN_FUEL_COST = FUEL_COMPONENT

      RETURN
      end function cl_screen_data