module clreport_routines
implicit none
contains
subroutine update_start_costs(ANNUAL_UNIT_START_COSTS, MAX_CL_UNITS, MONTH_UNIT_START_COSTS, &
    MONTHLY_START_COSTS, MONTHLY_CAPACITY_REVENUE, &
    CAP_MARKET_REVENUE, ANNUAL_UNIT_CAPACITY_REVENUE, ANNUAL_UNIT_STARTS, MONTHLY_STARTS, &
    MONTH_UNIT_STARTS, ANNUAL_P_FUEL_CONSUMPTION, ANNUAL_S_FUEL_CONSUMPTION, &
    ANNUAL_E_FUEL_CONSUMPTION, E_FUEL_CONSUMPTION, WHOLESALE_PRODUCTION_COST, &
    ANNUAL_WHOLESALE_PROD_COST, I, P_FUEL_CONSUMPTION, S_FUEL_CONSUMPTION, UNITNO, &
    AVG_PROD_COSTS, MON_ECO_SALES_ENRG_FROM)
    
integer :: MAX_CL_UNITS, I, UNITNO
real (kind=4) :: ANNUAL_UNIT_START_COSTS(MAX_CL_UNITS), MONTH_UNIT_START_COSTS(MAX_CL_UNITS), &
    MONTHLY_START_COSTS, MONTHLY_CAPACITY_REVENUE, &
    ANNUAL_UNIT_CAPACITY_REVENUE(MAX_CL_UNITS), ANNUAL_E_FUEL_CONSUMPTION(MAX_CL_UNITS)
real (kind=4) :: ANNUAL_WHOLESALE_PROD_COST(MAX_CL_UNITS), &
    WHOLESALE_PRODUCTION_COST, ANNUAL_S_FUEL_CONSUMPTION(MAX_CL_UNITS), &
    ANNUAL_P_FUEL_CONSUMPTION(MAX_CL_UNITS), MON_ECO_SALES_ENRG_FROM(MAX_CL_UNITS)
real :: CAP_MARKET_REVENUE, E_FUEL_CONSUMPTION, P_FUEL_CONSUMPTION, S_FUEL_CONSUMPTION, &
    AVG_PROD_COSTS
integer (kind=2) :: MONTHLY_STARTS, ANNUAL_UNIT_STARTS(MAX_CL_UNITS), &
    MONTH_UNIT_STARTS(MAX_CL_UNITS)



          ANNUAL_UNIT_START_COSTS(I) = ANNUAL_UNIT_START_COSTS(I) + MONTH_UNIT_START_COSTS(I)
               MONTHLY_START_COSTS = MONTHLY_START_COSTS + MONTH_UNIT_START_COSTS(I)

               MONTHLY_CAPACITY_REVENUE = &
			   MONTHLY_CAPACITY_REVENUE + CAP_MARKET_REVENUE
               ANNUAL_UNIT_CAPACITY_REVENUE(I) = &
			   ANNUAL_UNIT_CAPACITY_REVENUE(I) + CAP_MARKET_REVENUE
!
               ANNUAL_UNIT_STARTS(I) = ANNUAL_UNIT_STARTS(I) + &
			   MONTH_UNIT_STARTS(I)
            MONTHLY_STARTS = MONTHLY_STARTS + MONTH_UNIT_STARTS(I)
!
               ANNUAL_P_FUEL_CONSUMPTION(I) = &
               ANNUAL_P_FUEL_CONSUMPTION(I) + P_FUEL_CONSUMPTION
               ANNUAL_S_FUEL_CONSUMPTION(I) = &
               ANNUAL_S_FUEL_CONSUMPTION(I) + S_FUEL_CONSUMPTION
               ANNUAL_E_FUEL_CONSUMPTION(I) = &
               ANNUAL_E_FUEL_CONSUMPTION(I) + E_FUEL_CONSUMPTION
               WHOLESALE_PRODUCTION_COST = AVG_PROD_COSTS * &
               MON_ECO_SALES_ENRG_FROM(UNITNO)/1000000.
               ANNUAL_WHOLESALE_PROD_COST(I) = &
               ANNUAL_WHOLESALE_PROD_COST(I) +WHOLESALE_PRODUCTION_COST
end subroutine update_start_costs
subroutine collect_energy_data(AVERAGE_HEATRATE, &
    AVERAGE_FUEL_COST_PER_MWH, &
    AVG_PROD_COSTS, enrg, CANADA, HEAT, HEAT_CONVERSION, UNITNO, &
    MAX_CL_UNITS, VCPMWH)
    
integer :: MAX_CL_UNITS

real :: AVERAGE_HEATRATE, AVERAGE_FUEL_COST_PER_MWH, AVG_PROD_COSTS, &
      enrg, HEAT_CONVERSION, VCPMWH(MAX_CL_UNITS)
logical (kind=1) :: CANADA
real (kind=8) :: FUEL_COST, HEAT
integer (kind=2) :: UNITNO 
    IF(ENRG > 0.45) THEN
      AVERAGE_HEATRATE = HEAT_CONVERSION*HEAT/ENRG
      AVERAGE_FUEL_COST_PER_MWH = FUEL_COST / ENRG

      AVG_PROD_COSTS = SNGL((FUEL_COST))/ENRG+VCPMWH(UNITNO)
      IF(.NOT. CANADA) then 
        AVERAGE_HEATRATE = AVERAGE_HEATRATE + .5
      endif
    ELSE
      FUEL_COST = 0.0
      HEAT = 0.0
      AVERAGE_HEATRATE = 0.0
      AVERAGE_FUEL_COST_PER_MWH = 0.0
      AVG_PROD_COSTS = 0.0
    ENDIF
end subroutine collect_energy_data
subroutine collect_monthly_unit_emissions(MONTHLY_UNIT_EMISSIONS, UNIT_EMISSIONS)
real (kind=4), intent(inout) :: MONTHLY_UNIT_EMISSIONS(5), UNIT_EMISSIONS(5)
integer :: index, ub
    ub=ubound(MONTHLY_UNIT_EMISSIONS,1)
    do index=1, ub ! Was explicitly setting elements, 1..5
        MONTHLY_UNIT_EMISSIONS(index)=MONTHLY_UNIT_EMISSIONS(index)+UNIT_EMISSIONS(index)
    enddo
    
end subroutine collect_monthly_unit_emissions
subroutine update_energy_in_prod_arrays(PROD_BY_MK_BY_MWH, MK, MW, ANNUAL_PROD_BY_MK_BY_MWH, ENRG, I, MAX_CL_UNITS)
real :: PROD_BY_MK_BY_MWH(:,:), MW(:,:), ANNUAL_PROD_BY_MK_BY_MWH(:,:)
real :: enrg
integer :: mk
integer :: I, MAX_CL_UNITS

    PROD_BY_MK_BY_MWH(MK,1) = PROD_BY_MK_BY_MWH(MK,1) + ENRG
    PROD_BY_MK_BY_MWH(MK,2) = PROD_BY_MK_BY_MWH(MK,2) + MW(2,I)
    PROD_BY_MK_BY_MWH(MK,3) = PROD_BY_MK_BY_MWH(MK,3) + 1
    ANNUAL_PROD_BY_MK_BY_MWH(MK,1) = ANNUAL_PROD_BY_MK_BY_MWH(MK,1) + ENRG
    ANNUAL_PROD_BY_MK_BY_MWH(MK,2) = ANNUAL_PROD_BY_MK_BY_MWH(MK,2) + MW(2,I)
    ANNUAL_PROD_BY_MK_BY_MWH(MK,3) = ANNUAL_PROD_BY_MK_BY_MWH(MK,3) + 1
end subroutine update_energy_in_prod_arrays

subroutine nox_data_collector(MAX_CL_UNITS,I,UNIT_EMISSIONS, &
ANNUAL_NOX_SEASON_EMISSIONS,ANNUAL_NOX_SEASON_THERMAL,HEAT, &
FISCAL_NOX_SEASON_EMISSIONS,FISCAL_NOX_SEASON_THERMAL,TOTAL_NOX_HEAT)
INTEGER :: MAX_CL_UNITS
INTEGER(kind=2) :: I
REAL(kind=4) :: UNIT_EMISSIONS(5)
REAL(kind=4) :: ANNUAL_NOX_SEASON_EMISSIONS(MAX_CL_UNITS)
REAL(kind=4) :: ANNUAL_NOX_SEASON_THERMAL(MAX_CL_UNITS)
REAL(kind=4) :: FISCAL_NOX_SEASON_EMISSIONS(MAX_CL_UNITS)
REAL(kind=4) :: FISCAL_NOX_SEASON_THERMAL(MAX_CL_UNITS)
REAL(kind=8) :: HEAT
REAL(kind=4) :: TOTAL_NOX_HEAT
IF(UNIT_EMISSIONS(2) > 0.) THEN
   ANNUAL_NOX_SEASON_EMISSIONS(I) = &
                              ANNUAL_NOX_SEASON_EMISSIONS(I) &
                              + UNIT_EMISSIONS(2)
   ANNUAL_NOX_SEASON_THERMAL(I) = HEAT &
                              + ANNUAL_NOX_SEASON_THERMAL(I)
!
   FISCAL_NOX_SEASON_EMISSIONS(I) = &
                              FISCAL_NOX_SEASON_EMISSIONS(I) &
                              + UNIT_EMISSIONS(2)
   FISCAL_NOX_SEASON_THERMAL(I) = HEAT &
                              + FISCAL_NOX_SEASON_THERMAL(I)
!
   TOTAL_NOX_HEAT = TOTAL_NOX_HEAT + HEAT
endif
end subroutine nox_data_collector
!
! Function TOTAL_PRODUCTION_COSTS(YR)
!
! EXTRACT_METHOD: accumulate_production_costs
!
! TOTAL_PRODUCTION_COSTS, YR are defined as it is in origin
! FUELCOST(:) and VARCOST(:) are defined in module PROCSAVE_COMMON 
! TOTAL_NUCLEAR_FUEL_EXPENSE, FIXED_OM_COSTS, PURCHASE_COSTS are defined in module cap_prod_costs
! ANNUAL_ECONOMY_COST, ANNUAL_ECONOMY_REVENUE are defined in module GROUP_PROD
! CLASS_ASS_FOSSIL_COST(),CLASS_ASS_NUCLEAR_COST(),CLASS_ASSIGNED_VARIABLE_COST(),CLASS_ASSIGNED_FIXED_COST(),CLASS_ASS_PURCHASE_COST()
! are defined in module POOLCOM


function total_production_costs(YR)

USE PROCSAVE_COMMON
use cap_prod_costs
USE GROUP_PROD
USE POOLCOM

REAL ::  TOTAL_PRODUCTION_COSTS
INTEGER (kind=2) :: YR


      TOTAL_PRODUCTION_COSTS = &
                  FUELCOST(YR) + TOTAL_NUCLEAR_FUEL_EXPENSE + &
                  VARCOST(YR) + FIXED_OM_COSTS + &
                  PURCHASE_COSTS + ANNUAL_ECONOMY_COST - &
                  ANNUAL_ECONOMY_REVENUE + &
!
! ADDED 9/5/97 FOR GETTING TOTAL COST CONSISTENT WITH THE INDIVIDUAL
!  UNIT INFO
!
                  CLASS_ASS_FOSSIL_COST(2) + &
                  CLASS_ASS_NUCLEAR_COST(2) + & 
                  CLASS_ASSIGNED_VARIABLE_COST(2) + &
                  CLASS_ASSIGNED_FIXED_COST(2) + &
                  CLASS_ASS_PURCHASE_COST(2)

end function total_production_costs
end module clreport_routines
