grep Cash_AG_Maintenance               ~/wrk/Midas/ABBICAP/*.* >> m3_41
grep Cash_BTL_Lease_Cash               ~/wrk/Midas/ABBICAP/*.* >> m3_41
grep Cash_Fixed_OandM                  ~/wrk/Midas/ABBICAP/*.* >> m3_41
grep Cash_Fossil_Fuel                  ~/wrk/Midas/ABBICAP/*.* >> m3_41
grep Cash_Gas_Revenues                 ~/wrk/Midas/ABBICAP/*.* >> m3_41
grep Cash_Government                   ~/wrk/Midas/ABBICAP/*.* >> m3_41
grep Cash_Leased_Nuclear_Fuel          ~/wrk/Midas/ABBICAP/*.* >> m3_41
grep Cash_Other                        ~/wrk/Midas/ABBICAP/*.* >> m3_41
grep Cash_Paid_on_Accounts_Payable     ~/wrk/Midas/ABBICAP/*.* >> m3_41
grep Cash_Purchased_Power              ~/wrk/Midas/ABBICAP/*.* >> m3_41
grep Cash_Relationship_Revenues        ~/wrk/Midas/ABBICAP/*.* >> m3_41
grep Cash_Variable_OandM               ~/wrk/Midas/ABBICAP/*.* >> m3_41
grep WVPA_Cash_Member_Cost_of_Power    ~/wrk/Midas/ABBICAP/*.* >> m3_41
grep WVPA_Member_Cost_of_Services      ~/wrk/Midas/ABBICAP/*.* >> m3_41
grep WVPA_NonMember_Power_Sales        ~/wrk/Midas/ABBICAP/*.* >> m3_41
grep Cash_Other_Revenue                ~/wrk/Midas/ABBICAP/*.* >> m3_41
grep Cash_Other_OandM                  ~/wrk/Midas/ABBICAP/*.* >> m3_41
