!     ******************************************************************
!     DREPTCOM.MON
!     Copyright(c) Microsoft 2000
!
!     Created: 4/28/2011 2:50:40 PM
!     Author : Mark S GErber
!     Last change:
!            MSG 9/15/2015 12:39:45 PM
!     ******************************************************************

!
! 15/11/96. GAT.  REMOVED PARAMETERS FROM DSEX_OBJT.FOR
!                 STARTING IN VERSION 4.0A.
!
!
! NOTE: UNIT NUMBERS 2100-2199 RESERVED FOR TRANSACT LOAD FILES.
! NOTE: UNIT NUMBERS 2200-2299 RESERVED FOR SCENARIO HOURLY FILES.
! NOTE: UNIT NUMBERS 5286-5289 ARE USED FOR WVPA REPORTS
! NOTE: UNIT NUMBER 7337 USED IN CLASS_FINANCE_DETAIL_RPT
! NOTE: EXTENSION .XG AND UNIT 1337 ARE USED IN GRXModules BY MSG
! NOTE: EXTENSION .XH AND UNIT 1338 ARE USED IN GRXModules BY MSG
! NOTE: EXTENSION .XI AND UNIT 1339 ARE USED IN GRXModules BY MSG
! NOTE: IN COAL LP THE FOLLOWING EXTENSIONS AND UNIT NUMBERS ARE USED BY MSG
!   EXTENSIONS CZ, SS, UP, FS
!   UNIT NUMBERS 2700, 2701, 2702, 2703, 2704, 2710, 17337, 17373
! END COAL LP USAGE
! EXTENSION ABD AND UNIT 8327 IS USE IN ABB_CapacityMarketReport
      INTEGER (KIND=2) , PARAMETER ::  RES_TESTED_NO = 1501, ! File units
     +            RES_OPTION_NO = 1502,
     +            LM_COST_NO=1510,
     +            DSM_RATE_NO=1511,
     +            REV_ALLOC_NO=1512,
     +            REV_FUNC_NO=1513,
     +            MON_DSM_NO=1514,
     +            FORE_DAYS_NO=1520,
     +            FORE_MONTH_NO=1521,
     +            LDC_REPORT_NO=1522,
     +            LAST_ELDC_NO = 1523,
     +            LOLP_CURVE_NO = 1524,
     +            LOLP_REPORT_NO = 1525,
     +            FUEL_INVEN_NO=1530,
     +            ANN_CL_UNIT_NO=1540,
     +            ANN_CL_SUM_NO=1541,
     +            DISP_ORDER_NO=1542,
     +            ANN_POOL_SUM_NO=1543,
     +            MON_CL_UNIT_NO=1550,
     +            MON_CL_SUM_NO=1551,
     +            ANN_EL_UNIT_NO=1560,
     +            MON_EL_UNIT_NO=1561,
     +            MON_CT_UNIT_NO=1570,
     +            CL_MAINT_NO=1580,
     +            CM_MAINT_NO=5002,
     +            MAR_COST_NO = 1582,
     +            MAR_DATA_NO = 1583,
     +            MW_MAINT_NO = 1584,
     +            ECONOMY_INTER_NO = 1585,
     +            EXTERNAL_ECONOMY_INTER_NO=1587,
     +            RESERVE_MARGIN_NO=1590,
     +            EXPANSION_PATTERN_NO = 1591,
     +            SCREENING_NO = 1592,
     +            WABASH_VALLEY_POWER_COST_UNIT=1601,
     +            TG_RESERVE_MARGIN_NO=1593,
     +            LOAD_BY_BLOCK_NO=1594,
     +            HOURLY_CUST_MARGIN_NO=1596,
     +            IPL_FAC_NO = 1595,
     +            WV_AREA_UNIT=1602,
     +            WABASH_VALLEY_POWER_DSM_UNIT=1603,
     +            TRANS_NO= 1701,
     +            FUTURE_ASSETS_UNIT_NO = 1801,
     +            FLEX_PLANNING_ACTION_UNIT_NO = 1802,
     +            MX_ANNUAL_ALT_NO = 1803,
     +            CX_DAILY_NO = 1804,
     +            HX_HOURLY_NO = 1805,
     +               AJ_HOURLY_NO = 7045,
     +               AK_HOURLY_NO = 7046,
     +            XX_HOURLY_NO = 1810,
     +            KX_HOURLY_NO = 1909,
     +            QX_HOURLY_NO = 1908,
     +            WX_HOURLY_NO = 1910,
     +            HOURLY_FLOW_ANALYST_NO = 1831,
     +            HOURLY_FLOW_CONSTRAINT_NO = 1832,
     +            DX_HOURLY_NO = 1811,
     +            OX_HOURLY_NO = 1807,
     +            HEC_HOURLY_NO = 1806,
     +            HYDRO_AG_NO = 1808,
     +            MX_ICAP_ANNUAL_ALT_NO = 1809,
     +            EXTERNAL_PRODUCTION_NUM=1900,
     +            EXTERNAL_AI_NUM=1901,
     +            TRANS_TIE_UNIT = 1927,
     +            TRANS_DEL_UNIT = 1932,
     +            TRANS_PRI_UNIT = 1933,
     +            TRANS_SCA_UNIT = 1928,
     +            TRANS_MRK_UNIT = 1934,
     +            TRANS_LDS_UNIT = 1935,
     +            TRANS_LAS_UNIT = 1936,
     +            TRANS_ANN_UNIT = 1937,
     +            MON_TRANC_UNIT = 1938,
     +            MON_POSIT_UNIT = 1916,
     +            TRANS_CON_UNIT = 1939,
     +            TRANS_PB4_UNIT = 1941,
     +            TRANS_PAF_UNIT = 1943,
     +            TRANS_LBH_UNIT = 1944,
     +            TRANS_TRN_UNIT = 1949,
     +            TRANS_CAP_UNIT = 1966,
     +            TRANS_DER_UNIT = 1967,
     +            TRANS_EUE_UNIT = 1962,
     +            TRANS_INC_UNIT = 1945,
     +            TRANS_TRM_UNIT = 1946,
     +            TRANS_EXC_UNIT = 1954,
     +            TRANS_FUL_UNIT = 1963,
     +            TRANS_STATE_UNIT = 1983,
     +            TRANS_PROD_UNIT = 1987,
     +            TRANS_INTR_UNIT = 1988,
     +            TRANS_PROD_PROD_UNIT = 1989,
     +            TRANS_PROD_FUEL_UNIT = 1990,
     +            TRANS_PROD_MW_UNIT = 1992,
     +            DAY_WEEK_UNIT  = 1969,
     +            TRANS_MCB_UNIT = 1947,
     +            MARKET_AREA_UNIT = 1911,
     +            TRANS_HMP_UNIT = 1968,
     +            TRANS_LMD_UNIT = 1948,
     +            MON_CL_TRANS_NO = 1952,
     +               MON_DV_TRANS_NO = 1977,
     +            MON_NU_TRANS_NO = 1978,
     +            TECH_SCAR_NO = 1951,
     +            ECITY_OBJ_NO = 1851,
     +            MARKET_DURATION_NO = 1953,
     +            USER_DURATION_NO = 1965,
     +            TRANS_CLASS_SUM_UNIT = 1961,
     +            TRANS_CCO_UNIT = 1964,
     +            EVAL_HR_UNIT=1971,
     +            EVAL_DA_UNIT=1972,
     +            EVAL_MO_UNIT=1973,
     +            EVAL_OT_UNIT=1974,
     +            DAILY_PRODUCTS_UNIT = 1956,
     +            SCENARIO_MAKER_UNIT= 1957,
     +            REGIONAL_MAKER_UNIT =  1950,
     +            MONTHLY_FUEL_DERIV_UNIT = 1955,
     +            MONTH_GROUP_UNIT = 1958,
     +            TRANS_WH_UNIT = 1991,
     +            ASSET_INCOME_STATEMENT_NUM=5739,
     +            CATAWBA_NO=1605,
     +            CPL_ECAP_UNIT=4101,
     +            CPL_PAEN_UNIT=4102,
     +            CPL_DEFERRRED_FUEL_UNIT=4108,
     +            CPL_TAX_REPORTING_NO=4276,
     +            NUC_REPORTING_UNIT=4103,
     +            EA_REPORTING_UNIT=4104,
     +            FA_REPORTING_UNIT=4105,
     +            DD_REPORTING_UNIT=4106,
     +            DB_REPORTING_UNIT=4107,
     +            HOURLY_ECAP_UNIT=4111,
     +            HOUR_DIAG_UNIT = 4117,
     +            HOUR_JDA_UNIT = 5555,
     +            DEPTH_MARKET_UNIT = 4119,
     +            C_DEPTH_MARKET_UNIT = 4120,
     +            C_DEPTH_MARGIN_UNIT = 4112,
     +            C_HOURLY_COST_UNIT = 4121,
     +            C_HOURLY_MWH_COST_UNIT = 4122,
     +            C_HOURLY_SUMMARY_UNIT = 4123,
     +            C_TG_HOURLY_SUMMARY_UNIT = 4124,
     +            DEPTH_HOURLY_LAMBDA_UNIT = 4125,
     +            DYNAMIC_JURIS_UNIT=4113,
     +            CPL_SALES_GEN_UNIT=4114,
     +            MONTHLY_DISPATCH_RPT_NO=4118,
     +            ASSET_PRODUCTION_UNIT=5741,
     +            ANNUAL_TRANSACTIONS_UNIT=5742,
     +            RC_REV_FORECAST_NO=4268,
     +            FINANCIAL_INCOME_DRILLING_NO=4269,
     +            FINANCIAL_CASH_DRILLING_NO=4270,
     +            FINANCIAL_BALANCE_DRILLING_NO=4271,
     +            FINANCIAL_TAX_DRILLING_NO=4272,
     +            FINANCIAL_MONTHLY_INCOME_NO=4273,
     +            FINANCIAL_MONTHLY_CASH_NO=4274,
     +            FINANCIAL_MONTHLY_BALANCE_NO=4275,
     +            FINANCIAL_MONTHLY_TAX_NO=4277,
     +            WVPA_CONTROL_REPT_UNIT=4278,
     +            WVPA_MORTGAGE_SUMRY_REPT_UNIT=4280,
     +            WVPA_WO_EXPENSES_REPT_UNIT=4279,
     +            WVPA_WO_SUMMARY_REPT_UNIT=4283,
     +            T12MO_REPORTING_UNIT=4281,
     +            IPL_REG_REVENUE_UNIT=4282,
     +            MONTHLY_GAS_DEMAND_UNIT=7001,
     +            DAILY_CUST_GAS_UNIT = 7002,
     +            DAILY_TRANS_GAS_UNIT = 7003,
     +            MONTHLY_GAS_SUPPLY_UNIT = 7004,
     +            DAILY_GAS_SELL_BUY_UNIT = 7005,
     +            DAILY_GAS_PRICE_UNIT = 7006,
     +            DAILY_GAS_NODE_VOLUME_UNIT = 7017,
     +            DAILY_GAS_SUPPLY_UNIT = 7007,
     +            DAILY_GAS_UNSERVED_UNIT = 7008,
     +            MONTHLY_GAS_PRICE_UNIT = 7009,
     +            DAILY_GAS_LINK_UNIT = 7010,
     +            DAILY_GAS_LINK_LIMIT_UNIT = 7028,
     +            MONTHLY_GAS_DIFFER_UNIT = 7011,
     +            GAS_BASIN_UNIT = 7012,
     +            DAILY_GAS_DIFFER_UNIT = 7013,
     +            MONTHLY_GAS_BASIN_UNIT = 7014,
     +            MONTHLY_GAS_SELL_BUY_UNIT = 7015,
     +            MONTHLY_GAS_LINK_UNIT = 7016,
     +            MONTHLY_GAS_RESERVE_UNIT = 7018,
     +            DAILY_GAS_LINK_PRICE_UNIT = 7019,
     +            MONTHLY_GAS_LINK_PRICE_UNIT = 7020,
     +            DAILY_GAS_AVE_PRICE_UNIT = 7021,
     +            MONTHLY_GAS_BALANCE_UNIT = 7022,
     +            DAILY_GAS_STORAGE_UNIT = 7023,
     +            NEW_SUPPLY_CURVE_UNIT = 7024,
     +            DAILY_SURPLUS_DEFICIT_UNIT = 7025,
     +            DAILY_GAS_LINK_CF_UNIT = 7026,
     +            TRANS_DEPTH_MARKET_UNIT = 7027,
     +            STATE_RPS_UNIT = 7029,
     +            CO2_ABATEMENT_UNIT = 7030,
     +            GRX_DETAILED_RESOURCE_UNIT = 7031,
     +            GAS_PIPE_EXPANSION_UNIT = 7032,
     +            GRX_8761_UNIT = 7035,
     +            MARGINAL_UNIT_TECH_UNIT = 7034,
     +                DAILY_THERMAL_UNIT_NO = 7036,
     +                UV_HOURLY_NO = 7037,
     +               DAILY_TG_PM_NO = 7038,
     +            TRAN_PROD_FUEL_UNIT = 7039,
     +                RPS_PROGRAMS_UNIT = 7048,
     +            RPS_CURVE_UNIT = 7049,
     +                HOURLY_STORAGE_UNIT = 7050
!
! EXTENSION CODES FOR DETAILED REPORTS
!
! NOTE EXTENSIONS BCD USED IN CLASS_FINANCE_DETAIL_RPT
      CHARACTER (LEN=4) , PARAMETER :: CPL_ECAP_CODE=".CED",
     +          CPL_PAEN_CODE=".PED",
     +          CPL_DEFERRED_FUEL_CODE=".DFD",
     +          CPL_TAX_REPORTING_CODE=".TXD",
     +          WABASH_VALLEY_POWER_COST_CODE = ".WVD",
     +          WABASH_VALLEY_POWER_DSM_CODE = ".WDD",
     +          WV_AREA_CODE = ".WCD",
     +          WVPA_CONTROL_REPT_CODE = ".WOD",
     +          WVPA_MORTGAGE_SUMRY_REPT_CODE =".WSD",
     +          WVPA_WO_EXPENSES_REPT_CODE = ".WED",
     +          WVPA_WO_SUMMARY_REPT_CODE = ".WRD",
     +          TRANS_TIE_CODE = ".TID",
     +          DAILY_PROD_CODE = ".DPD",
     +          SCENARIO_MAKER_CODE = ".LGD",
     +          REGIONAL_MAKER_CODE = ".LRD",
     +          MONTHLY_FUEL_DERIV_CODE = ".ZOD",
     +             TRANS_DEL_CODE = ".TDD",
     +             TRANS_ANN_CODE = ".TBD",
     +          MON_TRANC_CODE = ".TVD",
     +          MON_POSIT_CODE = ".SVD",
     +             TRANS_PRI_CODE = ".TPD",
     +          TRANS_SCA_CODE = ".SDD",
     +             TRANS_MCB_CODE = ".TND",
     +          MARKET_AREA_CODE = ".MAD",
     +          TRANS_HMP_CODE = ".HMD",
     +          TRANS_LMD_CODE = ".LMD",
     +          TRANS_LBH_CODE = ".BHD",
     +          TRANS_WH_CODE  = ".WHD",
     +             TRANS_LDS_CODE = ".TLD",
     +             TRANS_LAS_CODE = ".TOD",
     +              TRANS_MRK_CODE = ".TKD",
     +          TRANS_CON_CODE = ".TCD",
     +          TRANS_PB4_CODE = ".PBD",
     +          TRANS_TRN_CODE = ".QRD",
     +          TRANS_PAF_CODE = ".PAD",
     +          TRANS_CAP_CODE = ".HCD",
     +          TRANS_DER_CODE = ".DVD",
     +          TRANS_EUE_CODE = ".EUD",
     +          TRANS_INC_CODE = ".PID",
     +          TRANS_TRM_CODE = ".TRD",
     +          TRANS_EXC_CODE = ".TQD",
     +          TRANS_FUL_CODE = ".TZD",
     +          TRANS_STATE_CODE = ".TWD",
     +          TRANS_PROD_CODE = ".UZD",
     +          NEW_SUPPLY_CURVE_CODE = ".UTD",
     +             DAILY_THERMAL_UNIT_CODE = ".UUD",
     +             DAILY_TG_PM_CODE = ".UKD",
     +             UV_HOURLY_CODE = ".UVD",
     +          TRANS_PROD_PROD_CODE = ".ZZD",
     +          TRANS_PROD_MW_CODE = ".ZBD",
     +          TRANS_PROD_FUEL_CODE = ".ZAD",
     +          TRANS_INTR_CODE = ".AZD",
     +          DAY_WEEK_CODE =  ".DWD",
     +          TRANS_CCO_CODE = ".COD",
     +          EVAL_HR_CODE = ".VHD",
     +          EVAL_DA_CODE = ".VDD",
     +          EVAL_MO_CODE = ".VMD",
     +          EVAL_OT_CODE = ".VOT",
     +          MONTH_GROUP_CODE = ".MZD",
     +          MON_CL_TRANS_CODE = ".TED",
     +             MON_DV_TRANS_CODE = ".TFD",
     +        MON_NU_TRANS_CODE = ".TGD",
     +          TECH_SCAR_CODE = ".THD",
     +          ECITY_OBJ_CODE = ".TJD",
     +          MARKET_DURATION_CODE = ".PDD",
     +          USER_DURATION_CODE = ".UDD",
     +          NUC_FUEL_REPORTING_CODE = ".NFD",
     +          EA_REPORTING_CODE = ".AED",
     +          FA_REPORTING_CODE = ".AFD",
     +          DD_REPORTING_CODE = ".DDD",
     +          DB_REPORTING_CODE = ".DBD",
     +          HOURLY_ECAP_CODE  = ".EHD",
     +          HOUR_DIAG_CODE = ".FHD",
     +          HOUR_JDA_CODE = ".JDD",
     +          DEPTH_MARKET_CODE = ".DMD",
     +          TRANS_DEPTH_MARKET_CODE = ".FMD",
     +          C_DEPTH_MARKET_CODE = ".XMD",
     +          C_DEPTH_MARGIN_CODE = ".YMD",
     +          C_HOURLY_COST_CODE = ".JXD",
     +          C_TG_HOURLY_SUMMARY_CODE = ".AXD",
     +          DEPTH_HOURLY_LAMBDA_CODE = ".GYD",
     +          C_HOURLY_MWH_COST_CODE = ".NXD",
     +          C_HOURLY_SUMMARY_CODE = ".PXD",
     +          DYNAMIC_JURIS_CODE = ".DJD",
     +          CPL_SALES_GEN_CODE = ".CZD",
     +          ASSET_PROD_CODE = ".APD",
     +          ANNUAL_TRANSACTIONS_CODE = ".SAD",
     +          FINANCIAL_INCOME_DRILLING_CODE = ".DID",
     +          FINANCIAL_CASH_DRILLING_CODE = ".CDD",
     +          FINANCIAL_TAX_DRILLING_CODE = ".XDD",
     +          FINANCIAL_BALANCE_DRILLING_CODE = ".BDD",
     +          FINANCIAL_MONTHLY_INCOME_CODE = ".MID",
     +          FINANCIAL_MONTHLY_CASH_CODE = ".MMD",
     +          FINANCIAL_MONTHLY_BALANCE_CODE = ".MBD",
     +          FINANCIAL_MONTHLY_TAX_CODE = ".MTD",
     +          MON_CUSTOMER_SUM_CODE = ".CCD",
     +          MX_ANNUAL_ALT_CODE = ".MXD",
     +          MX_ICAP_ANNUAL_ALT_CODE = ".IXD",
     +          CX_DAILY_CODE = ".CXD",
     +          HX_HOURLY_CODE = ".HXD",
     +            AJ_HOURLY_CODE = ".AJD",
     +            AK_HOURLY_CODE = ".AKD",
     +          XX_HOURLY_CODE = ".XXD",
     +          KX_HOURLY_CODE = ".KXD",
     +          QX_HOURLY_CODE = ".QXD",
     +          WX_HOURLY_CODE = ".WXD",
     +          CM_MAINT_CODE = ".CMD",
     +          HOURLY_FLOW_ANALYST_CODE = ".ZXD",
     +          HOURLY_FLOW_CONSTRAINT_CODE = ".YXD",
     +          DX_HOURLY_CODE = ".DXD",
     +          OX_HOURLY_CODE = ".OXD",
     +          HEC_HOURLY_CODE = ".HED",
     +          HYDRO_AG_HOURLY_CODE = ".HAD",
     +          MONTHLY_DISPATCH_RPT_CODE = ".MSD",
     +          RC_REV_FORECAST_CODE = ".RCD",
     +          TG_RESERVE_MARGIN_CODE=".RXD",
     +          LOAD_BY_BLOCK_CODE=".SXD",
     +          HOURLY_CUST_MARGIN_CODE=".BXD",
     +          IPL_FAC_CODE=".UXD",
     +          T12MO_REPORTING_CODE=".TMD",
     +          IPL_REG_REVENUE_CODE=".RRD",
     +          MONTHLY_GAS_DEMAND_CODE = ".GFD",
     +          DAILY_CUST_GAS_CODE = ".GGD",
     +          DAILY_TRANS_GAS_CODE = ".GHD",
     +          MONTHLY_GAS_SUPPLY_CODE = ".GSD",
     +          DAILY_GAS_SELL_BUY_CODE = ".GDD",
     +          DAILY_GAS_PRICE_CODE = ".GPD",
     +          DAILY_GAS_NODE_VOLUME_CODE = ".GTD",
     +          DAILY_GAS_SUPPLY_CODE = ".GQD",
     +          DAILY_GAS_LINK_LIMIT_CODE = ".GOD",
     +          MONTHLY_GAS_PRICE_CODE = ".GMD",
     +          DAILY_GAS_LINK_CODE = ".GJD",
     +          MONTHLY_GAS_DIFFER_CODE = ".GKD",
     +          GAS_BASIN_CODE = ".GLD",
     +          DAILY_GAS_DIFFER_CODE = ".GND",
     +          MONTHLY_GAS_BASIN_CODE =".GBD",
     +          MONTHLY_GAS_SELL_BUY_CODE = ".GCD",
     +          MONTHLY_GAS_LINK_CODE = ".GED",
     +          MONTHLY_GAS_RESERVE_CODE = ".GID",
     +          DAILY_GAS_LINK_PRICE_CODE = ".GWD",
     +          MONTHLY_GAS_LINK_PRICE_CODE = ".GXD",
     +          DAILY_GAS_AVE_PRICE_CODE = ".GZD",
     +          MONTHLY_GAS_BALANCE_CODE = ".GVD",
     +          DAILY_GAS_STORAGE_CODE = ".GAD",
     +          DAILY_SURPLUS_DEFICIT_CODE = ".GRD",
     +          DAILY_GAS_LINK_CF_CODE = ".GUD",
     +          STATE_RPS_CODE = ".RQD",
     +          CO2_ABATEMENT_CODE = ".CBD",
     +          GRX_DETAILED_RESOURCE_CODE = ".HQD",
     +          GAS_PIPE_EXPANSION_CODE = ".HPD",
     +          GRX_8761_CODE = ".VAD",
     +          MARGINAL_UNIT_TECH_CODE = ".VBD",
     +          TRAN_PROD_FUEL_CODE = ".VCD",
     +             RPS_PROGRAMS_CODE = ".VLD",
     +             RPS_CURVE_CODE = ".VND",
     +            HOURLY_STORAGE_CODE = ".VOD"

!
!
!
! CALCULATED ONCE, BEFORE THE END POINT OR YEAR LOOP
      CHARACTER (len=130) ::  BANNER_LINE,UTIL_STUDY_LINE
      CHARACTER (len=60) ::  STUDY
      CHARACTER (len=40) ::  UTILITY_NAME
      CHARACTER (len=8) ::  RUN_TIME
      CHARACTER (len=8) ::  RUN_DATE
! CALCULATED FOR EVERY NEW END POINT
      CHARACTER (len=20) ::  RUN_END_POINT
! CALCULATED FOR EVERY NEW YEAR
      CHARACTER (len=25) ::  FORECAST_YEAR
      CHARACTER (len=256) ::  RPT_BASE_FAMILY_NAME,RPT_PROJECT_NAME
!
      COMMON /REPORT_HEADER/ BANNER_LINE,UTILITY_NAME,
     +   STUDY,FORECAST_YEAR,RUN_DATE,RUN_END_POINT,RUN_TIME,
     +   UTIL_STUDY_LINE,RPT_BASE_FAMILY_NAME,RPT_PROJECT_NAME
!
! RESERVED LMP REPORT EXTENSIONS:
!       VXD, VYD, VZD
! RESERVED CAPEX EXTENSIONS:
!       XCD, XBD 3247, XED 3248, LUD, LYD, LZD
! RESERVED WEEKLY HYDRO EXTENSION 3246
! RESERVED CLREPORT EXTENSION 4444
! RESERVED GAS_OBJT EXTENSION 4433 NB, QS,
! RESERVED 7101 FOR SIMSTATUS.LOG
! RESERVED FQD FOR FORE_MONTH, FDD, RAD, FAD, DTD, MDD, DCD, ALD, AOD,
!                              ARD, LDD, LED, LOD, LCD, CAD, RMD, NAD,
!                              FXD, FID, TAD, TMD, TSD, CMD, PSD, TTD,
!                              STD, EAD, SCD, UMD, WMD, MCD, MGD,
!                              ECD, DOD, XCD, AID, WPD, CCD, WAD, WDD,
!                              RTD, EPD, RCD
! RESERVED EMD (WEATHER?)
!
! RESERVED K# WHERE # = 0-9 (K0D, K1D, K2D, K3D...K9D) SOD AND S1D FOR
!                       CAPEX
!
! RESERVED FOR HOROIZONS:
!
