!     ******************************************************************
!     DREPTCOM.MON
!     Copyright(c) Microsoft 2000
!
!     Created: 4/28/2011 2:50:40 PM
!     Author : Mark S GErber
!     Last change:
!            MSG 9/15/2015 12:39:45 PM
!     ******************************************************************

!
! 15/11/96. GAT.  REMOVED PARAMETERS FROM DSEX_OBJT.FOR
!                 STARTING IN VERSION 4.0A.
!
!
! NOTE: UNIT NUMBERS 2100-2199 RESERVED FOR TRANSACT LOAD FILES.
! NOTE: UNIT NUMBERS 2200-2299 RESERVED FOR SCENARIO HOURLY FILES.
! NOTE: UNIT NUMBERS 5286-5289 ARE USED FOR WVPA REPORTS
! NOTE: UNIT NUMBER 7337 USED IN CLASS_FINANCE_DETAIL_RPT
! NOTE: EXTENSION .XG AND UNIT 1337 ARE USED IN GRXModules BY MSG
! NOTE: EXTENSION .XH AND UNIT 1338 ARE USED IN GRXModules BY MSG
! NOTE: EXTENSION .XI AND UNIT 1339 ARE USED IN GRXModules BY MSG
! NOTE: IN COAL LP THE FOLLOWING EXTENSIONS AND UNIT NUMBERS ARE USED BY MSG
!   EXTENSIONS CZ, SS, UP, FS
!   UNIT NUMBERS 2700, 2701, 2702, 2703, 2704, 2710, 17337, 17373
! END COAL LP USAGE
! EXTENSION ABD AND UNIT 8327 IS USE IN ABB_CapacityMarketReport
      INTEGER (KIND=2) , PARAMETER ::  RES_TESTED_NO = 1501
      INTEGER (KIND=2) , PARAMETER ::  RES_OPTION_NO = 1502
      INTEGER (KIND=2) , PARAMETER ::  LM_COST_NO=1510
      INTEGER (KIND=2) , PARAMETER ::  DSM_RATE_NO=1511
      INTEGER (KIND=2) , PARAMETER ::  REV_ALLOC_NO=1512
      INTEGER (KIND=2) , PARAMETER ::  REV_FUNC_NO=1513
      INTEGER (KIND=2) , PARAMETER ::  MON_DSM_NO=1514
      INTEGER (KIND=2) , PARAMETER ::  FORE_DAYS_NO=1520
      INTEGER (KIND=2) , PARAMETER ::  FORE_MONTH_NO=1521
      INTEGER (KIND=2) , PARAMETER ::  LDC_REPORT_NO=1522
      INTEGER (KIND=2) , PARAMETER ::  LAST_ELDC_NO = 1523
      INTEGER (KIND=2) , PARAMETER ::  LOLP_CURVE_NO = 1524
      INTEGER (KIND=2) , PARAMETER ::  LOLP_REPORT_NO = 1525
      INTEGER (KIND=2) , PARAMETER ::  FUEL_INVEN_NO=1530
      INTEGER (KIND=2) , PARAMETER ::  ANN_CL_UNIT_NO=1540
      INTEGER (KIND=2) , PARAMETER ::  ANN_CL_SUM_NO=1541
      INTEGER (KIND=2) , PARAMETER ::  DISP_ORDER_NO=1542
      INTEGER (KIND=2) , PARAMETER ::  ANN_POOL_SUM_NO=1543
      INTEGER (KIND=2) , PARAMETER ::  MON_CL_UNIT_NO=1550
      INTEGER (KIND=2) , PARAMETER ::  MON_CL_SUM_NO=1551
      INTEGER (KIND=2) , PARAMETER ::  ANN_EL_UNIT_NO=1560
      INTEGER (KIND=2) , PARAMETER ::  MON_EL_UNIT_NO=1561
      INTEGER (KIND=2) , PARAMETER ::  MON_CT_UNIT_NO=1570
      INTEGER (KIND=2) , PARAMETER ::  CL_MAINT_NO=1580
      INTEGER (KIND=2) , PARAMETER ::  CM_MAINT_NO=5002
      INTEGER (KIND=2) , PARAMETER ::  MAR_COST_NO = 1582
      INTEGER (KIND=2) , PARAMETER ::  MAR_DATA_NO = 1583
      INTEGER (KIND=2) , PARAMETER ::  MW_MAINT_NO = 1584
      INTEGER (KIND=2) , PARAMETER ::  ECONOMY_INTER_NO = 1585
      INTEGER (KIND=2) , PARAMETER ::  EXTERNAL_ECONOMY_INTER_NO=1587
      INTEGER (KIND=2) , PARAMETER ::  RESERVE_MARGIN_NO=1590
      INTEGER (KIND=2) , PARAMETER ::  EXPANSION_PATTERN_NO = 1591
      INTEGER (KIND=2) , PARAMETER ::  SCREENING_NO = 1592
      INTEGER (KIND=2) , PARAMETER ::  WABASH_VALLEY_POWER_COST_UNIT=1601
      INTEGER (KIND=2) , PARAMETER ::  TG_RESERVE_MARGIN_NO=1593
      INTEGER (KIND=2) , PARAMETER ::  LOAD_BY_BLOCK_NO=1594
      INTEGER (KIND=2) , PARAMETER ::  HOURLY_CUST_MARGIN_NO=1596
      INTEGER (KIND=2) , PARAMETER ::  IPL_FAC_NO = 1595
      INTEGER (KIND=2) , PARAMETER ::  WV_AREA_UNIT=1602
      INTEGER (KIND=2) , PARAMETER ::  WABASH_VALLEY_POWER_DSM_UNIT=1603
      INTEGER (KIND=2) , PARAMETER ::  TRANS_NO= 1701
      INTEGER (KIND=2) , PARAMETER ::  FUTURE_ASSETS_UNIT_NO = 1801
      INTEGER (KIND=2) , PARAMETER ::  FLEX_PLANNING_ACTION_UNIT_NO = 1802
      INTEGER (KIND=2) , PARAMETER ::  MX_ANNUAL_ALT_NO = 1803
      INTEGER (KIND=2) , PARAMETER ::  CX_DAILY_NO = 1804
      INTEGER (KIND=2) , PARAMETER ::  HX_HOURLY_NO = 1805
      INTEGER (KIND=2) , PARAMETER ::  AJ_HOURLY_NO = 7045
      INTEGER (KIND=2) , PARAMETER ::  AK_HOURLY_NO = 7046
      INTEGER (KIND=2) , PARAMETER ::  XX_HOURLY_NO = 1810
      INTEGER (KIND=2) , PARAMETER ::  KX_HOURLY_NO = 1909
      INTEGER (KIND=2) , PARAMETER ::  QX_HOURLY_NO = 1908
      INTEGER (KIND=2) , PARAMETER ::  WX_HOURLY_NO = 1910
      INTEGER (KIND=2) , PARAMETER ::  HOURLY_FLOW_ANALYST_NO = 1831
      INTEGER (KIND=2) , PARAMETER ::  HOURLY_FLOW_CONSTRAINT_NO = 1832
      INTEGER (KIND=2) , PARAMETER ::  DX_HOURLY_NO = 1811
      INTEGER (KIND=2) , PARAMETER ::  OX_HOURLY_NO = 1807
      INTEGER (KIND=2) , PARAMETER ::  HEC_HOURLY_NO = 1806
      INTEGER (KIND=2) , PARAMETER ::  HYDRO_AG_NO = 1808
      INTEGER (KIND=2) , PARAMETER ::  MX_ICAP_ANNUAL_ALT_NO = 1809
      INTEGER (KIND=2) , PARAMETER ::  EXTERNAL_PRODUCTION_NUM=1900
      INTEGER (KIND=2) , PARAMETER ::  EXTERNAL_AI_NUM=1901
      INTEGER (KIND=2) , PARAMETER ::  TRANS_TIE_UNIT = 1927
      INTEGER (KIND=2) , PARAMETER ::  TRANS_DEL_UNIT = 1932
      INTEGER (KIND=2) , PARAMETER ::  TRANS_PRI_UNIT = 1933
      INTEGER (KIND=2) , PARAMETER ::  TRANS_SCA_UNIT = 1928
      INTEGER (KIND=2) , PARAMETER ::  TRANS_MRK_UNIT = 1934
      INTEGER (KIND=2) , PARAMETER ::  TRANS_LDS_UNIT = 1935
      INTEGER (KIND=2) , PARAMETER ::  TRANS_LAS_UNIT = 1936
      INTEGER (KIND=2) , PARAMETER ::  TRANS_ANN_UNIT = 1937
      INTEGER (KIND=2) , PARAMETER ::  MON_TRANC_UNIT = 1938
      INTEGER (KIND=2) , PARAMETER ::  MON_POSIT_UNIT = 1916
      INTEGER (KIND=2) , PARAMETER ::  TRANS_CON_UNIT = 1939
      INTEGER (KIND=2) , PARAMETER ::  TRANS_PB4_UNIT = 1941
      INTEGER (KIND=2) , PARAMETER ::  TRANS_PAF_UNIT = 1943
      INTEGER (KIND=2) , PARAMETER ::  TRANS_LBH_UNIT = 1944
      INTEGER (KIND=2) , PARAMETER ::  TRANS_TRN_UNIT = 1949
      INTEGER (KIND=2) , PARAMETER ::  TRANS_CAP_UNIT = 1966
      INTEGER (KIND=2) , PARAMETER ::  TRANS_DER_UNIT = 1967
      INTEGER (KIND=2) , PARAMETER ::  TRANS_EUE_UNIT = 1962
      INTEGER (KIND=2) , PARAMETER ::  TRANS_INC_UNIT = 1945
      INTEGER (KIND=2) , PARAMETER ::  TRANS_TRM_UNIT = 1946
      INTEGER (KIND=2) , PARAMETER ::  TRANS_EXC_UNIT = 1954
      INTEGER (KIND=2) , PARAMETER ::  TRANS_FUL_UNIT = 1963
      INTEGER (KIND=2) , PARAMETER ::  TRANS_STATE_UNIT = 1983
      INTEGER (KIND=2) , PARAMETER ::  TRANS_PROD_UNIT = 1987
      INTEGER (KIND=2) , PARAMETER ::  TRANS_INTR_UNIT = 1988
      INTEGER (KIND=2) , PARAMETER ::  TRANS_PROD_PROD_UNIT = 1989
      INTEGER (KIND=2) , PARAMETER ::  TRANS_PROD_FUEL_UNIT = 1990
      INTEGER (KIND=2) , PARAMETER ::  TRANS_PROD_MW_UNIT = 1992
      INTEGER (KIND=2) , PARAMETER ::  DAY_WEEK_UNIT  = 1969
      INTEGER (KIND=2) , PARAMETER ::  TRANS_MCB_UNIT = 1947
      INTEGER (KIND=2) , PARAMETER ::  MARKET_AREA_UNIT = 1911
      INTEGER (KIND=2) , PARAMETER ::  TRANS_HMP_UNIT = 1968
      INTEGER (KIND=2) , PARAMETER ::  TRANS_LMD_UNIT = 1948
      INTEGER (KIND=2) , PARAMETER ::  MON_CL_TRANS_NO = 1952
      INTEGER (KIND=2) , PARAMETER ::  MON_DV_TRANS_NO = 1977
      INTEGER (KIND=2) , PARAMETER ::  MON_NU_TRANS_NO = 1978
      INTEGER (KIND=2) , PARAMETER ::  TECH_SCAR_NO = 1951
      INTEGER (KIND=2) , PARAMETER ::  ECITY_OBJ_NO = 1851
      INTEGER (KIND=2) , PARAMETER ::  MARKET_DURATION_NO = 1953
      INTEGER (KIND=2) , PARAMETER ::  USER_DURATION_NO = 1965
      INTEGER (KIND=2) , PARAMETER ::  TRANS_CLASS_SUM_UNIT = 1961
      INTEGER (KIND=2) , PARAMETER ::  TRANS_CCO_UNIT = 1964
      INTEGER (KIND=2) , PARAMETER ::  EVAL_HR_UNIT=1971
      INTEGER (KIND=2) , PARAMETER ::  EVAL_DA_UNIT=1972
      INTEGER (KIND=2) , PARAMETER ::  EVAL_MO_UNIT=1973
      INTEGER (KIND=2) , PARAMETER ::  EVAL_OT_UNIT=1974
      INTEGER (KIND=2) , PARAMETER ::  DAILY_PRODUCTS_UNIT = 1956
      INTEGER (KIND=2) , PARAMETER ::  SCENARIO_MAKER_UNIT= 1957
      INTEGER (KIND=2) , PARAMETER ::  REGIONAL_MAKER_UNIT =  1950
      INTEGER (KIND=2) , PARAMETER ::  MONTHLY_FUEL_DERIV_UNIT = 1955
      INTEGER (KIND=2) , PARAMETER ::  MONTH_GROUP_UNIT = 1958
      INTEGER (KIND=2) , PARAMETER ::  TRANS_WH_UNIT = 1991
      INTEGER (KIND=2) , PARAMETER ::  ASSET_INCOME_STATEMENT_NUM=5739
      INTEGER (KIND=2) , PARAMETER ::  CATAWBA_NO=1605
      INTEGER (KIND=2) , PARAMETER ::  CPL_ECAP_UNIT=4101
      INTEGER (KIND=2) , PARAMETER ::  CPL_PAEN_UNIT=4102
      INTEGER (KIND=2) , PARAMETER ::  CPL_DEFERRRED_FUEL_UNIT=4108
      INTEGER (KIND=2) , PARAMETER ::  CPL_TAX_REPORTING_NO=4276
      INTEGER (KIND=2) , PARAMETER ::  NUC_REPORTING_UNIT=4103
      INTEGER (KIND=2) , PARAMETER ::  EA_REPORTING_UNIT=4104
      INTEGER (KIND=2) , PARAMETER ::  FA_REPORTING_UNIT=4105
      INTEGER (KIND=2) , PARAMETER ::  DD_REPORTING_UNIT=4106
      INTEGER (KIND=2) , PARAMETER ::  DB_REPORTING_UNIT=4107
      INTEGER (KIND=2) , PARAMETER ::  HOURLY_ECAP_UNIT=4111
      INTEGER (KIND=2) , PARAMETER ::  HOUR_DIAG_UNIT = 4117
      INTEGER (KIND=2) , PARAMETER ::  HOUR_JDA_UNIT = 5555
      INTEGER (KIND=2) , PARAMETER ::  DEPTH_MARKET_UNIT = 4119
      INTEGER (KIND=2) , PARAMETER ::  C_DEPTH_MARKET_UNIT = 4120
      INTEGER (KIND=2) , PARAMETER ::  C_DEPTH_MARGIN_UNIT = 4112
      INTEGER (KIND=2) , PARAMETER ::  C_HOURLY_COST_UNIT = 4121
      INTEGER (KIND=2) , PARAMETER ::  C_HOURLY_MWH_COST_UNIT = 4122
      INTEGER (KIND=2) , PARAMETER ::  C_HOURLY_SUMMARY_UNIT = 4123
      INTEGER (KIND=2) , PARAMETER ::  C_TG_HOURLY_SUMMARY_UNIT = 4124
      INTEGER (KIND=2) , PARAMETER ::  DEPTH_HOURLY_LAMBDA_UNIT = 4125
      INTEGER (KIND=2) , PARAMETER ::  DYNAMIC_JURIS_UNIT=4113
      INTEGER (KIND=2) , PARAMETER ::  CPL_SALES_GEN_UNIT=4114
      INTEGER (KIND=2) , PARAMETER ::  MONTHLY_DISPATCH_RPT_NO=4118
      INTEGER (KIND=2) , PARAMETER ::  ASSET_PRODUCTION_UNIT=5741
      INTEGER (KIND=2) , PARAMETER ::  ANNUAL_TRANSACTIONS_UNIT=5742
      INTEGER (KIND=2) , PARAMETER ::  RC_REV_FORECAST_NO=4268
      INTEGER (KIND=2) , PARAMETER ::  FINANCIAL_INCOME_DRILLING_NO=4269
      INTEGER (KIND=2) , PARAMETER ::  FINANCIAL_CASH_DRILLING_NO=4270
      INTEGER (KIND=2) , PARAMETER ::  FINANCIAL_BALANCE_DRILLING_NO=4271
      INTEGER (KIND=2) , PARAMETER ::  FINANCIAL_TAX_DRILLING_NO=4272
      INTEGER (KIND=2) , PARAMETER ::  FINANCIAL_MONTHLY_INCOME_NO=4273
      INTEGER (KIND=2) , PARAMETER ::  FINANCIAL_MONTHLY_CASH_NO=4274
      INTEGER (KIND=2) , PARAMETER ::  FINANCIAL_MONTHLY_BALANCE_NO=4275
      INTEGER (KIND=2) , PARAMETER ::  FINANCIAL_MONTHLY_TAX_NO=4277
      INTEGER (KIND=2) , PARAMETER ::  WVPA_CONTROL_REPT_UNIT=4278
      INTEGER (KIND=2) , PARAMETER ::  WVPA_MORTGAGE_SUMRY_REPT_UNIT=4280
      INTEGER (KIND=2) , PARAMETER ::  WVPA_WO_EXPENSES_REPT_UNIT=4279
      INTEGER (KIND=2) , PARAMETER ::  WVPA_WO_SUMMARY_REPT_UNIT=4283
      INTEGER (KIND=2) , PARAMETER ::  T12MO_REPORTING_UNIT=4281
      INTEGER (KIND=2) , PARAMETER ::  IPL_REG_REVENUE_UNIT=4282
      INTEGER (KIND=2) , PARAMETER ::  MONTHLY_GAS_DEMAND_UNIT=7001
      INTEGER (KIND=2) , PARAMETER ::  DAILY_CUST_GAS_UNIT = 7002
      INTEGER (KIND=2) , PARAMETER ::  DAILY_TRANS_GAS_UNIT = 7003
      INTEGER (KIND=2) , PARAMETER ::  MONTHLY_GAS_SUPPLY_UNIT = 7004
      INTEGER (KIND=2) , PARAMETER ::  DAILY_GAS_SELL_BUY_UNIT = 7005
      INTEGER (KIND=2) , PARAMETER ::  DAILY_GAS_PRICE_UNIT = 7006
      INTEGER (KIND=2) , PARAMETER ::  DAILY_GAS_NODE_VOLUME_UNIT = 7017
      INTEGER (KIND=2) , PARAMETER ::  DAILY_GAS_SUPPLY_UNIT = 7007
      INTEGER (KIND=2) , PARAMETER ::  DAILY_GAS_UNSERVED_UNIT = 7008
      INTEGER (KIND=2) , PARAMETER ::  MONTHLY_GAS_PRICE_UNIT = 7009
      INTEGER (KIND=2) , PARAMETER ::  DAILY_GAS_LINK_UNIT = 7010
      INTEGER (KIND=2) , PARAMETER ::  DAILY_GAS_LINK_LIMIT_UNIT = 7028
      INTEGER (KIND=2) , PARAMETER ::  MONTHLY_GAS_DIFFER_UNIT = 7011
      INTEGER (KIND=2) , PARAMETER ::  GAS_BASIN_UNIT = 7012
      INTEGER (KIND=2) , PARAMETER ::  DAILY_GAS_DIFFER_UNIT = 7013
      INTEGER (KIND=2) , PARAMETER ::  MONTHLY_GAS_BASIN_UNIT = 7014
      INTEGER (KIND=2) , PARAMETER ::  MONTHLY_GAS_SELL_BUY_UNIT = 7015
      INTEGER (KIND=2) , PARAMETER ::  MONTHLY_GAS_LINK_UNIT = 7016
      INTEGER (KIND=2) , PARAMETER ::  MONTHLY_GAS_RESERVE_UNIT = 7018
      INTEGER (KIND=2) , PARAMETER ::  DAILY_GAS_LINK_PRICE_UNIT = 7019
      INTEGER (KIND=2) , PARAMETER ::  MONTHLY_GAS_LINK_PRICE_UNIT = 7020
      INTEGER (KIND=2) , PARAMETER ::  DAILY_GAS_AVE_PRICE_UNIT = 7021
      INTEGER (KIND=2) , PARAMETER ::  MONTHLY_GAS_BALANCE_UNIT = 7022
      INTEGER (KIND=2) , PARAMETER ::  DAILY_GAS_STORAGE_UNIT = 7023
      INTEGER (KIND=2) , PARAMETER ::  NEW_SUPPLY_CURVE_UNIT = 7024
      INTEGER (KIND=2) , PARAMETER ::  DAILY_SURPLUS_DEFICIT_UNIT = 7025
      INTEGER (KIND=2) , PARAMETER ::  DAILY_GAS_LINK_CF_UNIT = 7026
      INTEGER (KIND=2) , PARAMETER ::  TRANS_DEPTH_MARKET_UNIT = 7027
      INTEGER (KIND=2) , PARAMETER ::  STATE_RPS_UNIT = 7029
      INTEGER (KIND=2) , PARAMETER ::  CO2_ABATEMENT_UNIT = 7030
      INTEGER (KIND=2) , PARAMETER ::  GRX_DETAILED_RESOURCE_UNIT = 7031
      INTEGER (KIND=2) , PARAMETER ::  GAS_PIPE_EXPANSION_UNIT = 7032
      INTEGER (KIND=2) , PARAMETER ::  GRX_8761_UNIT = 7035
      INTEGER (KIND=2) , PARAMETER ::  MARGINAL_UNIT_TECH_UNIT = 7034
      INTEGER (KIND=2) , PARAMETER ::  DAILY_THERMAL_UNIT_NO = 7036
      INTEGER (KIND=2) , PARAMETER ::  UV_HOURLY_NO = 7037
      INTEGER (KIND=2) , PARAMETER ::  DAILY_TG_PM_NO = 7038
      INTEGER (KIND=2) , PARAMETER ::  TRAN_PROD_FUEL_UNIT = 7039
      INTEGER (KIND=2) , PARAMETER ::  RPS_PROGRAMS_UNIT = 7048
      INTEGER (KIND=2) , PARAMETER ::  RPS_CURVE_UNIT = 7049
      INTEGER (KIND=2) , PARAMETER ::  HOURLY_STORAGE_UNIT = 7050
!
! EXTENSION CODES FOR DETAILED REPORTS
!
! NOTE EXTENSIONS BCD USED IN CLASS_FINANCE_DETAIL_RPT
      CHARACTER (LEN=4) , PARAMETER ::  CPL_ECAP_CODE=".CED"
      CHARACTER (LEN=4) , PARAMETER ::  CPL_PAEN_CODE=".PED"
      CHARACTER (LEN=4) , PARAMETER ::  CPL_DEFERRED_FUEL_CODE=".DFD"
      CHARACTER (LEN=4) , PARAMETER ::  CPL_TAX_REPORTING_CODE=".TXD"
      CHARACTER (LEN=4) , PARAMETER ::  WABASH_VALLEY_POWER_COST_CODE = ".WVD"
      CHARACTER (LEN=4) , PARAMETER ::  WABASH_VALLEY_POWER_DSM_CODE = ".WDD"
      CHARACTER (LEN=4) , PARAMETER ::  WV_AREA_CODE = ".WCD"
      CHARACTER (LEN=4) , PARAMETER ::  WVPA_CONTROL_REPT_CODE = ".WOD"
      CHARACTER (LEN=4) , PARAMETER ::  WVPA_MORTGAGE_SUMRY_REPT_CODE =".WSD"
      CHARACTER (LEN=4) , PARAMETER ::  WVPA_WO_EXPENSES_REPT_CODE = ".WED"
      CHARACTER (LEN=4) , PARAMETER ::  WVPA_WO_SUMMARY_REPT_CODE = ".WRD"
      CHARACTER (LEN=4) , PARAMETER ::  TRANS_TIE_CODE = ".TID"
      CHARACTER (LEN=4) , PARAMETER ::  DAILY_PROD_CODE = ".DPD"
      CHARACTER (LEN=4) , PARAMETER ::  SCENARIO_MAKER_CODE = ".LGD"
      CHARACTER (LEN=4) , PARAMETER ::  REGIONAL_MAKER_CODE = ".LRD"
      CHARACTER (LEN=4) , PARAMETER ::  MONTHLY_FUEL_DERIV_CODE = ".ZOD"
      CHARACTER (LEN=4) , PARAMETER ::  TRANS_DEL_CODE = ".TDD"
      CHARACTER (LEN=4) , PARAMETER ::  TRANS_ANN_CODE = ".TBD"
      CHARACTER (LEN=4) , PARAMETER ::  MON_TRANC_CODE = ".TVD"
      CHARACTER (LEN=4) , PARAMETER ::  MON_POSIT_CODE = ".SVD"
      CHARACTER (LEN=4) , PARAMETER ::  TRANS_PRI_CODE = ".TPD"
      CHARACTER (LEN=4) , PARAMETER ::  TRANS_SCA_CODE = ".SDD"
      CHARACTER (LEN=4) , PARAMETER ::  TRANS_MCB_CODE = ".TND"
      CHARACTER (LEN=4) , PARAMETER ::  MARKET_AREA_CODE = ".MAD"
      CHARACTER (LEN=4) , PARAMETER ::  TRANS_HMP_CODE = ".HMD"
      CHARACTER (LEN=4) , PARAMETER ::  TRANS_LMD_CODE = ".LMD"
      CHARACTER (LEN=4) , PARAMETER ::  TRANS_LBH_CODE = ".BHD"
      CHARACTER (LEN=4) , PARAMETER ::  TRANS_WH_CODE  = ".WHD"
      CHARACTER (LEN=4) , PARAMETER ::  TRANS_LDS_CODE = ".TLD"
      CHARACTER (LEN=4) , PARAMETER ::  TRANS_LAS_CODE = ".TOD"
      CHARACTER (LEN=4) , PARAMETER ::  TRANS_MRK_CODE = ".TKD"
      CHARACTER (LEN=4) , PARAMETER ::  TRANS_CON_CODE = ".TCD"
      CHARACTER (LEN=4) , PARAMETER ::  TRANS_PB4_CODE = ".PBD"
      CHARACTER (LEN=4) , PARAMETER ::  TRANS_TRN_CODE = ".QRD"
      CHARACTER (LEN=4) , PARAMETER ::  TRANS_PAF_CODE = ".PAD"
      CHARACTER (LEN=4) , PARAMETER ::  TRANS_CAP_CODE = ".HCD"
      CHARACTER (LEN=4) , PARAMETER ::  TRANS_DER_CODE = ".DVD"
      CHARACTER (LEN=4) , PARAMETER ::  TRANS_EUE_CODE = ".EUD"
      CHARACTER (LEN=4) , PARAMETER ::  TRANS_INC_CODE = ".PID"
      CHARACTER (LEN=4) , PARAMETER ::  TRANS_TRM_CODE = ".TRD"
      CHARACTER (LEN=4) , PARAMETER ::  TRANS_EXC_CODE = ".TQD"
      CHARACTER (LEN=4) , PARAMETER ::  TRANS_FUL_CODE = ".TZD"
      CHARACTER (LEN=4) , PARAMETER ::  TRANS_STATE_CODE = ".TWD"
      CHARACTER (LEN=4) , PARAMETER ::  TRANS_PROD_CODE = ".UZD"
      CHARACTER (LEN=4) , PARAMETER ::  NEW_SUPPLY_CURVE_CODE = ".UTD"
      CHARACTER (LEN=4) , PARAMETER ::  DAILY_THERMAL_UNIT_CODE = ".UUD"
      CHARACTER (LEN=4) , PARAMETER ::  DAILY_TG_PM_CODE = ".UKD"
      CHARACTER (LEN=4) , PARAMETER ::  UV_HOURLY_CODE = ".UVD"
      CHARACTER (LEN=4) , PARAMETER ::  TRANS_PROD_PROD_CODE = ".ZZD"
      CHARACTER (LEN=4) , PARAMETER ::  TRANS_PROD_MW_CODE = ".ZBD"
      CHARACTER (LEN=4) , PARAMETER ::  TRANS_PROD_FUEL_CODE = ".ZAD"
      CHARACTER (LEN=4) , PARAMETER ::  TRANS_INTR_CODE = ".AZD"
      CHARACTER (LEN=4) , PARAMETER ::  DAY_WEEK_CODE =  ".DWD"
      CHARACTER (LEN=4) , PARAMETER ::  TRANS_CCO_CODE = ".COD"
      CHARACTER (LEN=4) , PARAMETER ::  EVAL_HR_CODE = ".VHD"
      CHARACTER (LEN=4) , PARAMETER ::  EVAL_DA_CODE = ".VDD"
      CHARACTER (LEN=4) , PARAMETER ::  EVAL_MO_CODE = ".VMD"
      CHARACTER (LEN=4) , PARAMETER ::  EVAL_OT_CODE = ".VOT"
      CHARACTER (LEN=4) , PARAMETER ::  MONTH_GROUP_CODE = ".MZD"
      CHARACTER (LEN=4) , PARAMETER ::  MON_CL_TRANS_CODE = ".TED"
      CHARACTER (LEN=4) , PARAMETER ::  MON_DV_TRANS_CODE = ".TFD"
      CHARACTER (LEN=4) , PARAMETER ::  MON_NU_TRANS_CODE = ".TGD"
      CHARACTER (LEN=4) , PARAMETER ::  TECH_SCAR_CODE = ".THD"
      CHARACTER (LEN=4) , PARAMETER ::  ECITY_OBJ_CODE = ".TJD"
      CHARACTER (LEN=4) , PARAMETER ::  MARKET_DURATION_CODE = ".PDD"
      CHARACTER (LEN=4) , PARAMETER ::  USER_DURATION_CODE = ".UDD"
      CHARACTER (LEN=4) , PARAMETER ::  NUC_FUEL_REPORTING_CODE = ".NFD"
      CHARACTER (LEN=4) , PARAMETER ::  EA_REPORTING_CODE = ".AED"
      CHARACTER (LEN=4) , PARAMETER ::  FA_REPORTING_CODE = ".AFD"
      CHARACTER (LEN=4) , PARAMETER ::  DD_REPORTING_CODE = ".DDD"
      CHARACTER (LEN=4) , PARAMETER ::  DB_REPORTING_CODE = ".DBD"
      CHARACTER (LEN=4) , PARAMETER ::  HOURLY_ECAP_CODE  = ".EHD"
      CHARACTER (LEN=4) , PARAMETER ::  HOUR_DIAG_CODE = ".FHD"
      CHARACTER (LEN=4) , PARAMETER ::  HOUR_JDA_CODE = ".JDD"
      CHARACTER (LEN=4) , PARAMETER ::  DEPTH_MARKET_CODE = ".DMD"
      CHARACTER (LEN=4) , PARAMETER ::  TRANS_DEPTH_MARKET_CODE = ".FMD"
      CHARACTER (LEN=4) , PARAMETER ::  C_DEPTH_MARKET_CODE = ".XMD"
      CHARACTER (LEN=4) , PARAMETER ::  C_DEPTH_MARGIN_CODE = ".YMD"
      CHARACTER (LEN=4) , PARAMETER ::  C_HOURLY_COST_CODE = ".JXD"
      CHARACTER (LEN=4) , PARAMETER ::  C_TG_HOURLY_SUMMARY_CODE = ".AXD"
      CHARACTER (LEN=4) , PARAMETER ::  DEPTH_HOURLY_LAMBDA_CODE = ".GYD"
      CHARACTER (LEN=4) , PARAMETER ::  C_HOURLY_MWH_COST_CODE = ".NXD"
      CHARACTER (LEN=4) , PARAMETER ::  C_HOURLY_SUMMARY_CODE = ".PXD"
      CHARACTER (LEN=4) , PARAMETER ::  DYNAMIC_JURIS_CODE = ".DJD"
      CHARACTER (LEN=4) , PARAMETER ::  CPL_SALES_GEN_CODE = ".CZD"
      CHARACTER (LEN=4) , PARAMETER ::  ASSET_PROD_CODE = ".APD"
      CHARACTER (LEN=4) , PARAMETER ::  ANNUAL_TRANSACTIONS_CODE = ".SAD"
      CHARACTER (LEN=4) , PARAMETER ::  FINANCIAL_INCOME_DRILLING_CODE = ".DID"
      CHARACTER (LEN=4) , PARAMETER ::  FINANCIAL_CASH_DRILLING_CODE = ".CDD"
      CHARACTER (LEN=4) , PARAMETER ::  FINANCIAL_TAX_DRILLING_CODE = ".XDD"
      CHARACTER (LEN=4) , PARAMETER ::  FINANCIAL_BALANCE_DRILLING_CODE = ".BDD"
      CHARACTER (LEN=4) , PARAMETER ::  FINANCIAL_MONTHLY_INCOME_CODE = ".MID"
      CHARACTER (LEN=4) , PARAMETER ::  FINANCIAL_MONTHLY_CASH_CODE = ".MMD"
      CHARACTER (LEN=4) , PARAMETER ::  FINANCIAL_MONTHLY_BALANCE_CODE = ".MBD"
      CHARACTER (LEN=4) , PARAMETER ::  FINANCIAL_MONTHLY_TAX_CODE = ".MTD"
      CHARACTER (LEN=4) , PARAMETER ::  MON_CUSTOMER_SUM_CODE = ".CCD"
      CHARACTER (LEN=4) , PARAMETER ::  MX_ANNUAL_ALT_CODE = ".MXD"
      CHARACTER (LEN=4) , PARAMETER ::  MX_ICAP_ANNUAL_ALT_CODE = ".IXD"
      CHARACTER (LEN=4) , PARAMETER ::  CX_DAILY_CODE = ".CXD"
      CHARACTER (LEN=4) , PARAMETER ::  HX_HOURLY_CODE = ".HXD"
      CHARACTER (LEN=4) , PARAMETER ::  AJ_HOURLY_CODE = ".AJD"
      CHARACTER (LEN=4) , PARAMETER ::  AK_HOURLY_CODE = ".AKD"
      CHARACTER (LEN=4) , PARAMETER ::  XX_HOURLY_CODE = ".XXD"
      CHARACTER (LEN=4) , PARAMETER ::  KX_HOURLY_CODE = ".KXD"
      CHARACTER (LEN=4) , PARAMETER ::  QX_HOURLY_CODE = ".QXD"
      CHARACTER (LEN=4) , PARAMETER ::  WX_HOURLY_CODE = ".WXD"
      CHARACTER (LEN=4) , PARAMETER ::  CM_MAINT_CODE = ".CMD"
      CHARACTER (LEN=4) , PARAMETER ::  HOURLY_FLOW_ANALYST_CODE = ".ZXD"
      CHARACTER (LEN=4) , PARAMETER ::  HOURLY_FLOW_CONSTRAINT_CODE = ".YXD"
      CHARACTER (LEN=4) , PARAMETER ::  DX_HOURLY_CODE = ".DXD"
      CHARACTER (LEN=4) , PARAMETER ::  OX_HOURLY_CODE = ".OXD"
      CHARACTER (LEN=4) , PARAMETER ::  HEC_HOURLY_CODE = ".HED"
      CHARACTER (LEN=4) , PARAMETER ::  HYDRO_AG_HOURLY_CODE = ".HAD"
      CHARACTER (LEN=4) , PARAMETER ::  MONTHLY_DISPATCH_RPT_CODE = ".MSD"
      CHARACTER (LEN=4) , PARAMETER ::  RC_REV_FORECAST_CODE = ".RCD"
      CHARACTER (LEN=4) , PARAMETER ::  TG_RESERVE_MARGIN_CODE=".RXD"
      CHARACTER (LEN=4) , PARAMETER ::  LOAD_BY_BLOCK_CODE=".SXD"
      CHARACTER (LEN=4) , PARAMETER ::  HOURLY_CUST_MARGIN_CODE=".BXD"
      CHARACTER (LEN=4) , PARAMETER ::  IPL_FAC_CODE=".UXD"
      CHARACTER (LEN=4) , PARAMETER ::  T12MO_REPORTING_CODE=".TMD"
      CHARACTER (LEN=4) , PARAMETER ::  IPL_REG_REVENUE_CODE=".RRD"
      CHARACTER (LEN=4) , PARAMETER ::  MONTHLY_GAS_DEMAND_CODE = ".GFD"
      CHARACTER (LEN=4) , PARAMETER ::  DAILY_CUST_GAS_CODE = ".GGD"
      CHARACTER (LEN=4) , PARAMETER ::  DAILY_TRANS_GAS_CODE = ".GHD"
      CHARACTER (LEN=4) , PARAMETER ::  MONTHLY_GAS_SUPPLY_CODE = ".GSD"
      CHARACTER (LEN=4) , PARAMETER ::  DAILY_GAS_SELL_BUY_CODE = ".GDD"
      CHARACTER (LEN=4) , PARAMETER ::  DAILY_GAS_PRICE_CODE = ".GPD"
      CHARACTER (LEN=4) , PARAMETER ::  DAILY_GAS_NODE_VOLUME_CODE = ".GTD"
      CHARACTER (LEN=4) , PARAMETER ::  DAILY_GAS_SUPPLY_CODE = ".GQD"
      CHARACTER (LEN=4) , PARAMETER ::  DAILY_GAS_LINK_LIMIT_CODE = ".GOD"
      CHARACTER (LEN=4) , PARAMETER ::  MONTHLY_GAS_PRICE_CODE = ".GMD"
      CHARACTER (LEN=4) , PARAMETER ::  DAILY_GAS_LINK_CODE = ".GJD"
      CHARACTER (LEN=4) , PARAMETER ::  MONTHLY_GAS_DIFFER_CODE = ".GKD"
      CHARACTER (LEN=4) , PARAMETER ::  GAS_BASIN_CODE = ".GLD"
      CHARACTER (LEN=4) , PARAMETER ::  DAILY_GAS_DIFFER_CODE = ".GND"
      CHARACTER (LEN=4) , PARAMETER ::  MONTHLY_GAS_BASIN_CODE =".GBD"
      CHARACTER (LEN=4) , PARAMETER ::  MONTHLY_GAS_SELL_BUY_CODE = ".GCD"
      CHARACTER (LEN=4) , PARAMETER ::  MONTHLY_GAS_LINK_CODE = ".GED"
      CHARACTER (LEN=4) , PARAMETER ::  MONTHLY_GAS_RESERVE_CODE = ".GID"
      CHARACTER (LEN=4) , PARAMETER ::  DAILY_GAS_LINK_PRICE_CODE = ".GWD"
      CHARACTER (LEN=4) , PARAMETER ::  MONTHLY_GAS_LINK_PRICE_CODE = ".GXD"
      CHARACTER (LEN=4) , PARAMETER ::  DAILY_GAS_AVE_PRICE_CODE = ".GZD"
      CHARACTER (LEN=4) , PARAMETER ::  MONTHLY_GAS_BALANCE_CODE = ".GVD"
      CHARACTER (LEN=4) , PARAMETER ::  DAILY_GAS_STORAGE_CODE = ".GAD"
      CHARACTER (LEN=4) , PARAMETER ::  DAILY_SURPLUS_DEFICIT_CODE = ".GRD"
      CHARACTER (LEN=4) , PARAMETER ::  DAILY_GAS_LINK_CF_CODE = ".GUD"
      CHARACTER (LEN=4) , PARAMETER ::  STATE_RPS_CODE = ".RQD"
      CHARACTER (LEN=4) , PARAMETER ::  CO2_ABATEMENT_CODE = ".CBD"
      CHARACTER (LEN=4) , PARAMETER ::  GRX_DETAILED_RESOURCE_CODE = ".HQD"
      CHARACTER (LEN=4) , PARAMETER ::  GAS_PIPE_EXPANSION_CODE = ".HPD"
      CHARACTER (LEN=4) , PARAMETER ::  GRX_8761_CODE = ".VAD"
      CHARACTER (LEN=4) , PARAMETER ::  MARGINAL_UNIT_TECH_CODE = ".VBD"
      CHARACTER (LEN=4) , PARAMETER ::  TRAN_PROD_FUEL_CODE = ".VCD"
      CHARACTER (LEN=4) , PARAMETER ::  RPS_PROGRAMS_CODE = ".VLD"
      CHARACTER (LEN=4) , PARAMETER ::  RPS_CURVE_CODE = ".VND"
      CHARACTER (LEN=4) , PARAMETER ::  HOURLY_STORAGE_CODE = ".VOD"

!
!
!
! CALCULATED ONCE, BEFORE THE END POINT OR YEAR LOOP
      CHARACTER (len=130) ::  BANNER_LINE,UTIL_STUDY_LINE
      CHARACTER (len=60) ::  STUDY
      CHARACTER (len=40) ::  UTILITY_NAME
      CHARACTER (len=8) ::  RUN_TIME
      CHARACTER (len=8) ::  RUN_DATE
! CALCULATED FOR EVERY NEW END POINT
      CHARACTER (len=20) ::  RUN_END_POINT
! CALCULATED FOR EVERY NEW YEAR
      CHARACTER (len=25) ::  FORECAST_YEAR
      CHARACTER (len=256) ::  RPT_BASE_FAMILY_NAME,RPT_PROJECT_NAME
!
      COMMON /REPORT_HEADER/ BANNER_LINE,UTILITY_NAME,
     +   STUDY,FORECAST_YEAR,RUN_DATE,RUN_END_POINT,RUN_TIME,
     +   UTIL_STUDY_LINE,RPT_BASE_FAMILY_NAME,RPT_PROJECT_NAME
!
! RESERVED LMP REPORT EXTENSIONS:
!       VXD, VYD, VZD
! RESERVED CAPEX EXTENSIONS:
!       XCD, XBD 3247, XED 3248, LUD, LYD, LZD
! RESERVED WEEKLY HYDRO EXTENSION 3246
! RESERVED CLREPORT EXTENSION 4444
! RESERVED GAS_OBJT EXTENSION 4433 NB, QS,
! RESERVED 7101 FOR SIMSTATUS.LOG
! RESERVED FQD FOR FORE_MONTH, FDD, RAD, FAD, DTD, MDD, DCD, ALD, AOD,
!                              ARD, LDD, LED, LOD, LCD, CAD, RMD, NAD,
!                              FXD, FID, TAD, TMD, TSD, CMD, PSD, TTD,
!                              STD, EAD, SCD, UMD, WMD, MCD, MGD,
!                              ECD, DOD, XCD, AID, WPD, CCD, WAD, WDD,
!                              RTD, EPD, RCD
! RESERVED EMD (WEATHER?)
!
! RESERVED K# WHERE # = 0-9 (K0D, K1D, K2D, K3D...K9D) SOD AND S1D FOR
!                       CAPEX
!
! RESERVED FOR HOROIZONS:
!
