      module ac_elmqeq
      implicit none

      REAL (kind=4) ::  VARIABLE(0:500)
      REAL ::  BASE_RATES_REVENUES
      REAL ::  REAL ::  ADJUSTMENT_CLAUSE_REVENUES
      REAL ::  REAL ::  SECONDARY_SALES_REVENUES
      REAL ::  REAL ::  REVENUES_OTHER
      REAL ::  REAL ::  REFERENCE_BASE_REVENUES
      REAL ::  REAL ::  OPERATING_METHOD_ADJUSTMENT
      REAL ::  REAL ::  REVENUES_OPERATING
      REAL ::  !
! CASH EXPENSES
!
      REAL ::  FUEL_EXPENSE
      REAL ::  REAL ::  PURCHASE_POWER_EXPENSE
      REAL ::  REAL ::  VARIABLE_EXPENSE
      REAL ::  REAL ::  FIXED_EXPENSE
      REAL ::  REAL ::  SERVICE_TRANSACTION_EXPENSE
      REAL ::  REAL ::  OTHER_EXPENSE_1
      REAL ::  REAL ::  OTHER_EXPENSE_2
      REAL ::  REAL ::  OTHER_EXPENSE_3
      REAL ::  REAL ::  ATL_LEASE_PAYMENTS
      REAL ::  REAL ::  DSM_EXPENSE
      REAL ::  REAL ::  DSM_REBATE
      REAL ::  REAL ::  EMISSION_CREDIT_EXPENSE
      REAL ::  REAL ::  CLASS_NUCLEAR_FUEL_EXPENSE
      REAL ::  REAL ::  OWNED_NF_BURN
      REAL ::  REAL ::  BOOK_DEPRECIATION
      REAL ::  REAL ::  AMORTIZATION_EXPENSE
      REAL ::  REAL ::  CIAC_AMORTIZATION
      REAL ::  REAL ::  TOTAL_EXPENSES_B4_TAXES
      REAL ::  !
! TAX ITEMS
!
      REAL ::  OPERATING_REVENUE_TAX
      REAL ::  REAL ::  OTHER_AND_ENVIRONMENTAL_TAXES
      REAL ::  REAL ::  ENVIRONMENTAL_TAX
      REAL ::  REAL ::  CLASS_PROPERTY_TAXES
      REAL ::  REAL ::  OTHER_TAXES
      REAL ::  REAL ::  LOCAL_TAXES
      REAL ::  REAL ::  ATL_STATE_TAXES
      REAL ::  REAL ::  STATE_TAX_ON_CAPITAL
      REAL ::  REAL ::  ATL_FEDERAL_TAXES
      REAL ::  REAL ::  FEDERAL_TAX_ON_CAPITAL
      REAL ::  REAL ::  DEFERRED_TAXES_DR
      REAL ::  REAL ::  DEFERRED_TAXES_CR
      REAL ::  REAL ::  TAX_CREDITS
      REAL ::  REAL ::  TOTAL_EXPENSE_AND_TAXES
      REAL ::  REAL ::  OPERATING_INCOME
      REAL ::  REAL ::  DEFERRED_REVENUES
      REAL ::  REAL ::  CLASS_BTL_REVENUES
      REAL ::  REAL ::  INVESTMENT_INCOME
      REAL ::  REAL ::  CLASS_BTL_EXPENSES
      REAL ::  REAL ::  BTL_INCOME_TAXES
      REAL ::  REAL ::  AFUDC_EQUITY
      REAL ::  REAL ::  INCOME_B4_INTEREST
      REAL ::  REAL ::  INTEREST_ON_LONG_TERM_DEBT
      REAL ::  REAL ::  STD_INTEREST
      REAL ::  REAL ::  AFUDC_BORROWED
      REAL ::  REAL ::  INCOME_AFTER_INTEREST
      REAL ::  REAL ::  SUBSIDIARY_INCOME
      REAL ::  REAL ::  NET_OF_TAX_EXEXP
      REAL ::  REAL ::  NET_PROFIT_OR_LOSS
      REAL ::  REAL ::  PREFERRED_DIVIDENDS
      REAL ::  REAL ::  EARNINGS_AVAILABLE_TO_COMMON
      REAL ::  REAL ::  COMMON_DIVIDENDS
      REAL ::  REAL ::  RETAINED_EARNINGS
      REAL ::  REAL ::  STOCK_BOOK_VALUE
      REAL ::  REAL ::  STOCK_MARKET_PRICE
      REAL ::  REAL ::  AVERAGE_SHARES
      REAL ::  REAL ::  MARKET_2_BOOK
      REAL ::  REAL ::  EARNINGS_PER_SHARE
      REAL ::  REAL ::  DIVIDEND_PER_SHARE
      REAL ::  REAL ::  DIVIDEND_PAYOUT
      REAL ::  REAL ::  RETURN_ON_EQUITY
      REAL ::  REAL ::  AVERAGE_EQUITY
      REAL ::  !
! TAX STUFF
!
      REAL ::  TAXABLE_INCOME
      REAL ::  REAL ::  CAPITIALIZED_INTEREST
      REAL ::  REAL ::  INCOME_TAX_DEPRECIATION
      REAL ::  REAL ::  STATE_TAXABLE_INCOME
      REAL ::  REAL ::  STATE_TAXABLE_INCOME_AFTER_NOLS
      REAL ::  REAL ::  STATE_INCOME_TAX_DEDUCTIONS
      REAL ::  REAL ::  ADJ_2_STATE_TAXES
      REAL ::  REAL ::  STATE_TAXES
      REAL ::  REAL ::  FEDERAL_TAXABLE_INCOME
      REAL ::  REAL ::  FED_TAXABLE_INCOME_AFTER_NOLS
      REAL ::  REAL ::  FED_INCOME_TAX_DEDUCTIONS
      REAL ::  REAL ::  ADJ_2_FEDERAL_TAXES
      REAL ::  REAL ::  FEDERAL_TAXES
      REAL ::  REAL ::  AMTINCOME
      REAL ::  REAL ::  TOTAL_INCOME_TAXES
      REAL ::  REAL ::  STATE_TAX_RATE
      REAL ::  REAL ::  FEDERAL_INCOME_TAX_RATE
      REAL ::  REAL ::  TAX_PAYMENTS_2_PARENT_FROM_SUB
      REAL ::  REAL ::  TAXABLE_INCOME_B4_DEDUCTIONS
      REAL ::  REAL ::  TAX_DEDUCTIBLE_EXPENSES_BOOK
      REAL ::  !
! RATEBASE ITEMS
!
      REAL ::  RETURN_ON_RATEBASE
      REAL ::  REAL ::   ASSET_CLASS_RATE_BASE
      REAL ::  REAL ::   RATE_BASE_PLANT_IN_SERVICE
      REAL ::  REAL ::   RATE_BASE_DEF_TAXES
      REAL ::  REAL ::   ADDENDUM_2_RATE_BASE
      REAL ::  REAL ::   RATE_BASE_DEFERRED_DEBITS
      REAL ::  REAL ::   RATE_BASE_NUC_FUEL
      REAL ::  REAL ::   RATE_BASE_CWIP
      REAL ::  REAL ::   RATE_BASE_DEF_ITC
      REAL ::  REAL ::   RATE_BASE_NUC_DECOM
      REAL ::  REAL ::   RATE_BASE_CIAC
      REAL ::  REAL ::   RATE_BASE_ASSET_NEC
      REAL ::  REAL ::   RATE_BASE_CAPITIALIZED_LEASES
      REAL ::  ! BALANCE SHEET ASSETS (63-100
      REAL ::  GROSS_PLANT_VALUE
      REAL ::  REAL ::   CWIP
      REAL ::  REAL ::   GROSS_PLANT_VALUE_PLUS_CWIP
      REAL ::  REAL ::   CUMULATIVE_DEPRECIATION
      REAL ::  REAL ::   NET_NF_VALUE
      REAL ::  REAL ::   UTILITY_PLANT_NET
      REAL ::  REAL ::   ASSETS_OTHER
      REAL ::  REAL ::   SUBSIDIARY_INVESTMENT
      REAL ::  REAL ::   LEASES_CAPITIALZIED
      REAL ::  REAL ::   DECOMMISIONING_FUND_BAL
      REAL ::  REAL ::   DD_BALANCE_NET
      REAL ::  REAL ::   DEFERRED_REVENUES_CUM
      REAL ::  REAL ::   DEFERRED_TAXES_DR_BAL
      REAL ::  REAL ::   CASH_BALANCE
      REAL ::  REAL ::   ASSET_NEC
      REAL ::  REAL ::   TOTAL_ASSETS
      REAL ::  REAL ::   COMMON_STOCK_BAL
      REAL ::  REAL ::   RETAINED_EARNINGS_BAL
      REAL ::  REAL ::   COMMON_EQUITY_BAL
      REAL ::  REAL ::   PREFERRED_STOCK_BAL
      REAL ::  REAL ::   LONG_TERM_DEBT_BAL
      REAL ::  REAL ::   TOTAL_CAPITIAL_BAL
      REAL ::  REAL ::   OTHER_LT_LIABILITY_BAL
      REAL ::  REAL ::   SHORT_TERM_DEBT_BAL
      REAL ::  REAL ::   CUSTOMER_DEPOSITS_BALANCE
      REAL ::  REAL ::   CIAC_BAL
      REAL ::  REAL ::   DEF_TAX_CR_BAL
      REAL ::  REAL ::   DEF_ITC_BAL
      REAL ::  REAL ::   LIABILITIES_NEC
      REAL ::  REAL ::   TOTAL_LIABILITIES
      REAL ::  REAL ::   COMMON_STOCK_ISSUED
      REAL ::  REAL ::   LONG_TERM_DEBT_ISSUED
      REAL ::  REAL ::   PREFERRED_STOCK_ISSUED
      REAL ::  REAL ::   SHORT_TERM_DEBT_ISSUED
      REAL ::  REAL ::   INCOME_BEFORE_CAPITAL_SERVICE
      REAL ::  REAL ::   CASH_FROM_SALE_OF_ASSETS
      REAL ::  REAL ::   DIVIDEND_FROM_SUBSIDIARY
      REAL ::  REAL ::   INCOME_TAXES_CONSOLIDATED
      REAL ::  REAL ::   TAXES_PAID_BY_PARENT
      REAL ::  REAL ::   CIAC_CASH
      REAL ::  REAL ::   CUSTOMER_DEPOSITS
      REAL ::  REAL ::   FUNDS_FROM_OPERATIONS
      REAL ::  !
      REAL ::  FA_CASH
      REAL ::  REAL ::   NF_CASH
      REAL ::  REAL ::   NEW_SUBSIDIARY_INVESTMENT
      REAL ::  REAL ::   INVESTMENT_SALVAGE_OTHER
      REAL ::  REAL ::   CAPITIALIZED_LEASE_ADDITIONS
      REAL ::  REAL ::   CONSTRUCTION_AND_NET_INVESTMENT
      REAL ::  REAL ::   LEASED_NF_BURN
      REAL ::  REAL ::   NUCL_DECOM_FUND
      REAL ::  REAL ::   CHANGE_IN_WORKING_CAPITIAL
      REAL ::  REAL ::   LONG_TERM_DEBT_RETIREMENTS
      REAL ::  REAL ::   PREFERRED_STOCK_RETIREMENTS
      REAL ::  REAL ::   COMMON_STOCK_BOUGHT
      REAL ::  REAL ::   DEFERRED_EXPENSE_CASH
      REAL ::  REAL ::   CHANGE_IN_FUNDS_B4_FINANCING
      REAL ::  REAL ::   LEASE_RECEIPTS
      REAL ::  REAL ::   EXTERNAL_FINANCING_PERFORMED
      REAL ::  REAL ::   CHANGE_IN_CASH
      REAL ::  REAL ::   ELIMINATION_CASH_ADJUSTMENT
      REAL (kind=4) ::  ATL_AMORTIZATION
      REAL (kind=4) ::  BTL_AMORTIZATION
      REAL (kind=4) ::  LTD_INTEREST_AND_AMORTIZATION
      REAL (kind=4) ::  BTL_DEF_TAXES
      REAL (kind=4) ::  TOTAL_DEF_TAXES_CR
      REAL (kind=4) ::  NET_DERIVATIVES_INCOME
!
!
      EQUIVALENCE (VARIABLE(0),BASE_RATES_REVENUES),
     +            (VARIABLE(1),ADJUSTMENT_CLAUSE_REVENUES),
     +            (VARIABLE(2),SECONDARY_SALES_REVENUES),
     +            (VARIABLE(3),REVENUES_OTHER),
     +            (VARIABLE(252),REFERENCE_BASE_REVENUES),
     +            (VARIABLE(253),OPERATING_METHOD_ADJUSTMENT),
     +            (VARIABLE(4),REVENUES_OPERATING),
!
! CASH EXPENSES
!
     +            (VARIABLE(5),FUEL_EXPENSE),
     +            (VARIABLE(6),PURCHASE_POWER_EXPENSE),
     +            (VARIABLE(7),VARIABLE_EXPENSE),
     +            (VARIABLE(8),FIXED_EXPENSE),
     +            (VARIABLE(9),SERVICE_TRANSACTION_EXPENSE),
     +            (VARIABLE(10),OTHER_EXPENSE_1),
     +            (VARIABLE(11),OTHER_EXPENSE_2),
     +            (VARIABLE(12),OTHER_EXPENSE_3),
     +            (VARIABLE(60),ATL_LEASE_PAYMENTS),
     +            (VARIABLE(13),DSM_EXPENSE),
     +            (VARIABLE(14),DSM_REBATE),
     +            (VARIABLE(15),EMISSION_CREDIT_EXPENSE),
     +            (VARIABLE(16),CLASS_NUCLEAR_FUEL_EXPENSE),
     +            (VARIABLE(116),LEASED_NF_BURN),
     +            (VARIABLE(219),OWNED_NF_BURN),
     +            (VARIABLE(17),BOOK_DEPRECIATION),
     +            (VARIABLE(18),AMORTIZATION_EXPENSE),
     +            (VARIABLE(19),CIAC_AMORTIZATION),
     +            (VARIABLE(20),TOTAL_EXPENSES_B4_TAXES),
!
! TAX ITEMS
!
     +            (VARIABLE(21),OPERATING_REVENUE_TAX),
     +            (VARIABLE(22),OTHER_AND_ENVIRONMENTAL_TAXES),
     +            (VARIABLE(216),ENVIRONMENTAL_TAX),
     +            (VARIABLE(217),CLASS_PROPERTY_TAXES),
     +            (VARIABLE(218),OTHER_TAXES),
     +            (VARIABLE(23),LOCAL_TAXES),
     +            (VARIABLE(24),ATL_STATE_TAXES),
     +            (VARIABLE(25),STATE_TAX_ON_CAPITAL),
     +            (VARIABLE(26),ATL_FEDERAL_TAXES),
     +            (VARIABLE(27),FEDERAL_TAX_ON_CAPITAL),
     +            (VARIABLE(28),DEFERRED_TAXES_DR),
     +            (VARIABLE(29),DEFERRED_TAXES_CR),
     +            (VARIABLE(50),TAX_CREDITS),
     +            (VARIABLE(30),TOTAL_EXPENSE_AND_TAXES),
     +            (VARIABLE(31),OPERATING_INCOME),
     +            (VARIABLE(32),DEFERRED_REVENUES),
     +            (VARIABLE(33),CLASS_BTL_REVENUES),
     +            (VARIABLE(34),INVESTMENT_INCOME),
     +            (VARIABLE(35),CLASS_BTL_EXPENSES),
     +            (VARIABLE(36),BTL_INCOME_TAXES),
     +            (VARIABLE(37),AFUDC_EQUITY),
     +            (VARIABLE(38),INCOME_B4_INTEREST),
     +            (VARIABLE(39),INTEREST_ON_LONG_TERM_DEBT),
     +            (VARIABLE(40),STD_INTEREST),
     +            (VARIABLE(41),AFUDC_BORROWED),
     +            (VARIABLE(42),INCOME_AFTER_INTEREST),
     +            (VARIABLE(43),SUBSIDIARY_INCOME),
     +            (VARIABLE(44),NET_OF_TAX_EXEXP),
     +            (VARIABLE(45),NET_PROFIT_OR_LOSS),
     +            (VARIABLE(46),PREFERRED_DIVIDENDS),
     +            (VARIABLE(47),EARNINGS_AVAILABLE_TO_COMMON),
     +            (VARIABLE(48),COMMON_DIVIDENDS),
     +            (VARIABLE(49),RETAINED_EARNINGS),
     +            (VARIABLE(51),STOCK_BOOK_VALUE),
     +            (VARIABLE(52),STOCK_MARKET_PRICE),
     +            (VARIABLE(53),AVERAGE_SHARES),
     +            (VARIABLE(54),MARKET_2_BOOK),
     +            (VARIABLE(55),EARNINGS_PER_SHARE),
     +            (VARIABLE(56),DIVIDEND_PER_SHARE),
     +            (VARIABLE(57),DIVIDEND_PAYOUT),
     +            (VARIABLE(58),RETURN_ON_EQUITY),
     +            (VARIABLE(59),AVERAGE_EQUITY),
!
! TAX STUFF
!
     +            (VARIABLE(128),TAXABLE_INCOME),
     +            (VARIABLE(129),CAPITIALIZED_INTEREST),
     +            (VARIABLE(130),INCOME_TAX_DEPRECIATION),
     +            (VARIABLE(131),STATE_TAXABLE_INCOME),
     +            (VARIABLE(132),STATE_TAXABLE_INCOME_AFTER_NOLS),
     +            (VARIABLE(133),STATE_INCOME_TAX_DEDUCTIONS),
     +            (VARIABLE(134),ADJ_2_STATE_TAXES),
     +            (VARIABLE(212),STATE_TAXES),
     +            (VARIABLE(135),FEDERAL_TAXABLE_INCOME),
     +            (VARIABLE(136),FED_TAXABLE_INCOME_AFTER_NOLS),
     +            (VARIABLE(137),FED_INCOME_TAX_DEDUCTIONS),
     +            (VARIABLE(138),ADJ_2_FEDERAL_TAXES),
     +            (VARIABLE(211),FEDERAL_TAXES),
     +            (VARIABLE(139),AMTINCOME),
     +            (VARIABLE(140),TOTAL_INCOME_TAXES),
     +            (VARIABLE(141),STATE_TAX_RATE),
     +            (VARIABLE(213),FEDERAL_INCOME_TAX_RATE),
     +            (VARIABLE(209),TAXABLE_INCOME_B4_DEDUCTIONS),
     +            (VARIABLE(210),TAX_DEDUCTIBLE_EXPENSES_BOOK),
!
! RATEBASE ITEMS
!
     +            (VARIABLE(61),RETURN_ON_RATEBASE),
     +            (VARIABLE(62),ASSET_CLASS_RATE_BASE),
     +            (VARIABLE(143),RATE_BASE_PLANT_IN_SERVICE),
     +            (VARIABLE(144),RATE_BASE_DEF_TAXES),
     +            (VARIABLE(145),ADDENDUM_2_RATE_BASE),
     +            (VARIABLE(146),RATE_BASE_DEFERRED_DEBITS),
     +            (VARIABLE(147),RATE_BASE_NUC_FUEL),
     +            (VARIABLE(148),RATE_BASE_CWIP),
     +            (VARIABLE(149),RATE_BASE_DEF_ITC),
     +            (VARIABLE(150),RATE_BASE_NUC_DECOM),
     +            (VARIABLE(151),RATE_BASE_CIAC),
     +            (VARIABLE(152),RATE_BASE_ASSET_NEC),
     +            (VARIABLE(153),RATE_BASE_CAPITIALIZED_LEASES),
! BALANCE SHEET ASSETS (63-100)
     +            (VARIABLE(63),GROSS_PLANT_VALUE),
     +            (VARIABLE(64),CWIP),
     +            (VARIABLE(65),GROSS_PLANT_VALUE_PLUS_CWIP),
     +            (VARIABLE(66),CUMULATIVE_DEPRECIATION),
     +            (VARIABLE(67),NET_NF_VALUE),
     +            (VARIABLE(68),UTILITY_PLANT_NET),
     +            (VARIABLE(69),ASSETS_OTHER),
     +            (VARIABLE(91),SUBSIDIARY_INVESTMENT),
     +            (VARIABLE(92),LEASES_CAPITIALZIED),
     +            (VARIABLE(70),DECOMMISIONING_FUND_BAL),
     +            (VARIABLE(71),DD_BALANCE_NET),
     +            (VARIABLE(72),DEFERRED_REVENUES_CUM),
     +            (VARIABLE(73),DEFERRED_TAXES_DR_BAL),
     +            (VARIABLE(74),CASH_BALANCE),
     +            (VARIABLE(75),ASSET_NEC),
     +            (VARIABLE(76),TOTAL_ASSETS),
     +            (VARIABLE(77),COMMON_STOCK_BAL),
     +            (VARIABLE(78),RETAINED_EARNINGS_BAL),
     +            (VARIABLE(79),COMMON_EQUITY_BAL),
     +            (VARIABLE(80),PREFERRED_STOCK_BAL),
     +            (VARIABLE(81),LONG_TERM_DEBT_BAL),
     +            (VARIABLE(82),TOTAL_CAPITIAL_BAL),
     +            (VARIABLE(83),OTHER_LT_LIABILITY_BAL),
     +            (VARIABLE(84),SHORT_TERM_DEBT_BAL),
     +            (VARIABLE(85),CUSTOMER_DEPOSITS_BALANCE),
     +            (VARIABLE(86),CIAC_BAL),
     +            (VARIABLE(87),DEF_TAX_CR_BAL),
     +            (VARIABLE(88),DEF_ITC_BAL),
     +            (VARIABLE(89),LIABILITIES_NEC),
     +            (VARIABLE(90),TOTAL_LIABILITIES),
     +            (VARIABLE(101),COMMON_STOCK_ISSUED),
     +            (VARIABLE(102),LONG_TERM_DEBT_ISSUED),
     +            (VARIABLE(103),PREFERRED_STOCK_ISSUED),
     +            (VARIABLE(104),SHORT_TERM_DEBT_ISSUED),
     +            (VARIABLE(105),INCOME_BEFORE_CAPITAL_SERVICE),
     +            (VARIABLE(106),CASH_FROM_SALE_OF_ASSETS),
     +            (VARIABLE(107),DIVIDEND_FROM_SUBSIDIARY),
     +            (VARIABLE(108),TAX_PAYMENTS_2_PARENT_FROM_SUB ),
     +            (VARIABLE(214),INCOME_TAXES_CONSOLIDATED),
     +            (VARIABLE(215),TAXES_PAID_BY_PARENT),
     +            (VARIABLE(113),CIAC_CASH),
     +            (VARIABLE(125),CUSTOMER_DEPOSITS),
     +            (VARIABLE(109),FUNDS_FROM_OPERATIONS),
     +            (VARIABLE(142),ELIMINATION_CASH_ADJUSTMENT),
!
     +            (VARIABLE(110),FA_CASH),
     +            (VARIABLE(111),NF_CASH),
     +            (VARIABLE(126),NEW_SUBSIDIARY_INVESTMENT),
     +            (VARIABLE(112),INVESTMENT_SALVAGE_OTHER),
     +            (VARIABLE(114),CAPITIALIZED_LEASE_ADDITIONS),
     +            (VARIABLE(115),CONSTRUCTION_AND_NET_INVESTMENT),
     +            (VARIABLE(117),NUCL_DECOM_FUND),
     +            (VARIABLE(118),CHANGE_IN_WORKING_CAPITIAL),
     +            (VARIABLE(119),LONG_TERM_DEBT_RETIREMENTS),
     +            (VARIABLE(154),PREFERRED_STOCK_RETIREMENTS),
     +            (VARIABLE(120),COMMON_STOCK_BOUGHT),
     +            (VARIABLE(127),DEFERRED_EXPENSE_CASH),
     +            (VARIABLE(121),CHANGE_IN_FUNDS_B4_FINANCING),
     +            (VARIABLE(122),LEASE_RECEIPTS),
     +            (VARIABLE(123),EXTERNAL_FINANCING_PERFORMED),
     +            (VARIABLE(124),CHANGE_IN_CASH),
     +            (VARIABLE(291),ATL_AMORTIZATION),
     +            (VARIABLE(292),BTL_AMORTIZATION),
     +            (VARIABLE(293),LTD_INTEREST_AND_AMORTIZATION),
     +            (VARIABLE(294),BTL_DEF_TAXES),
     +            (VARIABLE(295),TOTAL_DEF_TAXES_CR),
     +            (VARIABLE(448),NET_DERIVATIVES_INCOME)

       end module ac_elmque
!
!
