!     ******************************************************************
!     DE_OBJT.FOR
!     Copyright(c) M.S. Gerber & Associates 2000
!
!     Created: 12/26/2002 10:32:01 AM
!     Author : MARK S GERBER
!     Last change: msg 11/21/2021 10:20:42 AM
!     ******************************************************************

! ***********************************************************************
!
      SUBROUTINE DE_OBJECT
!
! ***********************************************************************
      use prod_arrays_dimensions
      use spindriftlib
      use csvdat
      USE SIZECOM
!
      INTEGER(kind=2) :: IREC,INUNIT,DELETE,YEAR,LRECL=214 ! 112121 ! 123118 ! 121618
      INTEGER :: IOS

      CHARACTER(len=1) :: FORECAST_REPORT,EXPANSION_REPORT, &
                DISPATCH_REPORT*2,ALLOCATION_REPORT,ENRG_LIMIT_REPORT, &
                LOAD_PROB_PLOT,ANNUAL_UNIT_OUTPUT_REPORT, &
                DSM_FINANCIAL_REPORT
      LOGICAL(kind=4) :: FILE_EXISTS
      CHARACTER(len=1) :: UNIT_OUTPUT_REPORT
      CHARACTER(len=5) :: DETAILED_REPORT_FILE,OVERLAY_FAMILY_NAME
      CHARACTER(len=50) :: COMMENT
      CHARACTER(len=256) :: FILE_NAME
      CHARACTER(len=256) :: BASE_FILE_DIRECTORY
      CHARACTER(len=256) :: OUTPUT_DIRECTORY
      CHARACTER(len=256) :: DATA_DRIVE,SELECTED_DISPATCH_RPT_MONTHS*30,&
                    SELECT_NEW_SUPPLY_RPT_MONTHS*30
!  DECLARATION FOR DBREAD COMMON BLOCK
      CHARACTER(len=1024) :: RECLN
!  DECLARATION FOR RUN SPECS
      CHARACTER(len=1) :: CSV_REPORT,KEPCO_REPORTS,CONTRACT_REPORT, &
         FUEL_USAGE_REPORT,LM_DAYS_REPORT,WABASH_POWER_COST_REPORT, &
         MAINTENANCE_REPORT,ECONOMY_REPORT,SERVICE_REPORT, &
         LOLP_REPORT,EXISTING_ASSETS_REPORT,FUTURE_ASSETS_REPORT, &
         NUCLEAR_FUEL_REPORT,DEBT_REPORT,ASSET_CLASS_REPORTS, &
         REPORTING_ASSET_CLASS*4,TRANSACT_UNIT_REPORT, &
         TRANSACT_HOURLY_REPORTS,TRANS_TRANSMISSION_REPORTS, &
         TRANSACT_MONTHLY_REPORTS,MARKET_DURATION_REPORT, &
         FINANCIAL_DRILLING,EXPENSE_REVENUES_REPORT, &
         TRANSACT_DAILY_REPORTS,TF_CLASS_SUMMARY_REPORTS, &
         DEBITS_REPORT,HOURLY_ECAP_REPORT,TRANSACT_FUEL_REPORT, &
         DYNAMIC_JURIS_ALLOC,MONTHLY_GROUP_REPORT,HOURLY_PRICE_REPORT, &
         DISPATCH_RPT_TYPE,HOURLY_LOAD_BEFORE_HYDRO,TRANS_HOURLY_DIAG, &
         HYDRO_SALES_AS_NEGATIVE,DEPTH_OF_MARKET,HOURLY_COMMITMENT, &
         DAILY_COMMITMENT,HOURLY_OUTAGE,HOURLY_SPIN_REPORT, &
         MARGINAL_UNIT_REPORT,WEEKLY_HYDRO_REPORT, &
         HOURLY_CAPACITY_REPORT,HOURLY_CAPACITY_COST_REPORT, &
         HOURLY_DERIVATIVES_REPORT,HOURLY_LOAD_AFTER_HYDRO_REPORT, &
         HOURLY_LOAD_AFTER_TRANS_REPORT,HOURLY_TRANSACTION_REPORT, &
         FLOW_ANALYST_REPORT_GROUP,MARKET_MATCH_REPORT_GROUP
      CHARACTER(len=1) :: &
         RESERVED_REPORT_GROUP,FISCAL_YEAR_ACTIVE,MONTHLY_DERIVATIVES, &
         NEW_UNITS_REPORT,WRITE_DAILY_PATHS_REPORTS, &
         MONTHLY_FUEL_DERIV_REPORT,MONTHLY_SCEN_MAKER_REPORT, &
         TECH_SCAR_REPORT,POWERWORLD_REPORT,LOAD_MARKET_AREAS_REPORT, &
         PORT_MARKET_AREAS_REPORT,MONTHLY_LOAD_N_RESOURCES, &
         IPL_FAC_REPORT,HOURLY_JDA_REPORT,MONTHLY_TRANC_REPORT, &
         HOURLY_UNIT_FUEL_REPORT,HOURLY_CUST_MARGIN_REPORT, &
         DAILY_DISPATCH_ORDER_REPORT,TRANSACT_PROD_REPORT, &
         TRANSACT_MW_REPORT,TRANS_INTR_REPORT,TRANS_TO_FROM_REPORT, &
         MONTHLY_GAS_DEMAND_REPORT,MONTHLY_COAL_DEMAND_REPORT, &
         DAILY_GAS_DEMAND_REPORT,MONTHLY_GAS_SUPPLY_REPORT, &
         MONTHLY_COAL_SUPPLY_REPORT,DAILY_GAS_SELL_BUY_REPORT, &
         MONTHLY_GAS_SELL_BUY_REPORT,MONTHLY_GAS_LINK_REPORT, &
         NEW_SUPPLY_CURVE_REPORT*2,CO2_ABATEMENT_REPORT_ACTIVE, &
         GRX_8761_REPORT,MARGINAL_UNIT_BY_TECH_REPORT, &
         DERIVATIVE_CUSTOMER_MARGINS,DAILY_THERMAL_UNIT_REPORT, &
         TEMP_REPORT_1,TEMP_REPORT_2,RPS_PROGRAMS_REPORT, &
         OLD_RPS_PROGRAMS_REPORT,RPS_CURVE_REPORT, &
         HOURLY_GRX_STORAGE_REPORT
      INTEGER(kind=2) :: NUMBER_OF_INTERVALS, &
                DEPTH_TARGET_GROUP, &
                DIAGNOSTIC_DAY_OF_MONTH, &
                BEGIN_FISCAL_YEAR
      INTEGER(kind=4) :: &
                DATE_THERMAL_REPORT_BEGINS, &
                DATE_THERMAL_REPORT_ENDS
      REAL(kind=4) :: INTERVAL_SIZE
      CHARACTER(len=22) :: FILE_TYPE='Detailed Reports      '
      CHARACTER(len=2) :: DET_RPT_OL='BC',R_DET_RPT_OL
      LOGICAL(kind=1) :: LAHEY_LF95
      CHARACTER(len=5) :: DEPTH_MARKET_FILE
      CHARACTER(len=30) :: SCREEN_OUTPUT

! ***********************************************************************
!
!  ROUTINE TO CONVERT METAFILE FILES TO DIRECT ACCESS BINARY
!           COPYRIGHT (C) 1983-95  M.S. GERBER & ASSOCIATES, INC.
!
! ***********************************************************************
!
!  CONVERT DETAILED REPORTS
      ENTRY DE_MAKEBIN
         DATA_DRIVE = OUTPUT_DIRECTORY()
         FILE_NAME = trim(BASE_FILE_DIRECTORY())// &
                           "DEB"//trim(DETAILED_REPORT_FILE())//".DAT"
         INQUIRE(FILE=FILE_NAME,EXIST=FILE_EXISTS)
         OPEN(11,FILE=trim(DATA_DRIVE)//"BCDETRPT.BIN", &
                            ACCESS="DIRECT",STATUS="UNKNOWN",RECL=LRECL)
         IF(FILE_EXISTS) THEN
            OPEN(10,FILE=FILE_NAME)
            IF(LAHEY_LF95()) THEN
               SCREEN_OUTPUT = trim(FILE_TYPE)//'-'// &
                                                  DETAILED_REPORT_FILE()
               CALL MG_LOCATE_WRITE(16,30,SCREEN_OUTPUT,ALL_VERSIONS,0)
            ELSE
               CALL MG_LOCATE_WRITE(16,30,DETAILED_REPORT_FILE(), &
                                                         ALL_VERSIONS,0)
               CALL MG_CLEAR_LINE_WRITE(17,9,36,FILE_TYPE, &
                                                         ALL_VERSIONS,0)
            ENDIF
         ENDIF

         FORECAST_REPORT = 'F'
         EXPANSION_REPORT = 'F'
         DISPATCH_REPORT = 'F'
         ALLOCATION_REPORT = 'F'
         ENRG_LIMIT_REPORT = 'F'
         LOAD_PROB_PLOT = 'F'
         ANNUAL_UNIT_OUTPUT_REPORT = 'F'
         DSM_FINANCIAL_REPORT = 'F'
!
         UNIT_OUTPUT_REPORT = 'N'
         ASSET_CLASS_REPORTS = 'T'
         REPORTING_ASSET_CLASS = 'Pare'
         CSV_REPORT = 'F'
         KEPCO_REPORTS = 'F'
         WABASH_POWER_COST_REPORT = 'F'
         CSV_BY_UNIT(0) = .FALSE.
         CONTRACT_REPORT = 'F'
         FUEL_USAGE_REPORT = 'F'
         MAINTENANCE_REPORT = 'F'
         ECONOMY_REPORT = 'F'
         SERVICE_REPORT = 'F'
         LM_DAYS_REPORT = 'F'
         LOLP_REPORT = 'F'
         EXISTING_ASSETS_REPORT = 'F'
         FUTURE_ASSETS_REPORT = 'F'
         NUCLEAR_FUEL_REPORT = 'F'
         DEBT_REPORT = 'O'
         TRANSACT_UNIT_REPORT = 'F'
         TRANSACT_HOURLY_REPORTS = 'F'
         TRANS_TRANSMISSION_REPORTS = 'F'
         TRANSACT_MONTHLY_REPORTS = 'F'
         MARKET_DURATION_REPORT = 'F'
         FINANCIAL_DRILLING = 'O'
         EXPENSE_REVENUES_REPORT = 'O'
         TRANSACT_DAILY_REPORTS = 'F'
         TF_CLASS_SUMMARY_REPORTS = 'F'
         DEBITS_REPORT = 'O'
         HOURLY_ECAP_REPORT = 'F'
         TRANSACT_FUEL_REPORT = 'F'
         DYNAMIC_JURIS_ALLOC = 'F'
         MONTHLY_GROUP_REPORT = 'F'
         HOURLY_PRICE_REPORT = 'F'
         SELECTED_DISPATCH_RPT_MONTHS = '1,4,7,10'
         SELECT_NEW_SUPPLY_RPT_MONTHS = '1,4,7,10'
         DISPATCH_RPT_TYPE = 'A'
         HOURLY_LOAD_BEFORE_HYDRO = 'F'
         TRANS_HOURLY_DIAG = 'F'
         HYDRO_SALES_AS_NEGATIVE = 'F'
!
         DEPTH_OF_MARKET = 'F'
         HOURLY_COMMITMENT = 'F'
         DAILY_COMMITMENT = 'F'
         HOURLY_OUTAGE = 'F'
         HOURLY_SPIN_REPORT = 'F'
         MARGINAL_UNIT_REPORT = 'F'
         WEEKLY_HYDRO_REPORT = 'F'
!
         HOURLY_CAPACITY_REPORT = 'F'
         HOURLY_CAPACITY_COST_REPORT = 'F'
         HOURLY_DERIVATIVES_REPORT = 'F'
         HOURLY_LOAD_AFTER_HYDRO_REPORT = 'F'
         HOURLY_LOAD_AFTER_TRANS_REPORT = 'F'
         HOURLY_TRANSACTION_REPORT = 'F'
!

         FLOW_ANALYST_REPORT_GROUP = 'F'
         MARKET_MATCH_REPORT_GROUP = 'F'
         RESERVED_REPORT_GROUP = 'F'
!
         NUMBER_OF_INTERVALS = 3
         INTERVAL_SIZE = 100
         DEPTH_TARGET_GROUP = 0
         DIAGNOSTIC_DAY_OF_MONTH = 1
!
         FISCAL_YEAR_ACTIVE = 'F'
         MONTHLY_DERIVATIVES = 'F'
         NEW_UNITS_REPORT = 'F'
         WRITE_DAILY_PATHS_REPORTS = 'F'
         MONTHLY_FUEL_DERIV_REPORT = 'F'
         MONTHLY_SCEN_MAKER_REPORT = 'F'
         TECH_SCAR_REPORT = 'F'
         POWERWORLD_REPORT = 'F'
         LOAD_MARKET_AREAS_REPORT = 'F'
         PORT_MARKET_AREAS_REPORT = 'F'
         MONTHLY_LOAD_N_RESOURCES = 'F'
         IPL_FAC_REPORT = 'F'
         HOURLY_JDA_REPORT = 'F'
         MONTHLY_TRANC_REPORT = 'F'
         HOURLY_UNIT_FUEL_REPORT = 'F'
         HOURLY_CUST_MARGIN_REPORT = 'F'
         DAILY_DISPATCH_ORDER_REPORT = 'F'
         TRANSACT_PROD_REPORT = 'F'
         TRANSACT_MW_REPORT = 'F'
         TRANS_INTR_REPORT = 'F'
         TRANS_TO_FROM_REPORT = 'F'
         MONTHLY_GAS_DEMAND_REPORT = 'F'
         DAILY_GAS_DEMAND_REPORT = 'F'
         MONTHLY_GAS_SUPPLY_REPORT = 'F'
         DAILY_GAS_SELL_BUY_REPORT = 'F'
         MONTHLY_GAS_SELL_BUY_REPORT = 'F'
         MONTHLY_GAS_LINK_REPORT = 'F'
         NEW_SUPPLY_CURVE_REPORT = 'F'
         BEGIN_FISCAL_YEAR = 1
         MONTHLY_COAL_DEMAND_REPORT = 'F'
         MONTHLY_COAL_SUPPLY_REPORT = 'F'
         CO2_ABATEMENT_REPORT_ACTIVE = 'F'
         GRX_8761_REPORT = 'F'
         MARGINAL_UNIT_BY_TECH_REPORT = 'F'
         DERIVATIVE_CUSTOMER_MARGINS = 'F'
         DAILY_THERMAL_UNIT_REPORT = 'F'
         RPS_PROGRAMS_REPORT = 'F'
         OLD_RPS_PROGRAMS_REPORT = 'F'
         RPS_CURVE_REPORT = 'F'
         HOURLY_GRX_STORAGE_REPORT = 'F'
         DATE_THERMAL_REPORT_BEGINS = -99
         DATE_THERMAL_REPORT_ENDS = -99
!
         DEPTH_MARKET_FILE = '     '
!
         IREC = 1
         IF(FILE_EXISTS) READ(10,*) DELETE
         DO
            IF(FILE_EXISTS) THEN
               READ(10,1000,IOSTAT=IOS) RECLN
!               IF(IOS /=0 .AND. IREC > MAX_SIMULATION_YEARS) EXIT
               IF(IOS == 0) THEN
                  RECLN = trim(RECLN)//',,,,,,,,,,,,,,,,,,,,,,,,,,,,,' &
                                       //',,,,,,,,,,,,,,,,,,,,,,,,,,,,,'
                  READ(RECLN,*) DELETE,YEAR,FORECAST_REPORT, &
           EXPANSION_REPORT,DISPATCH_REPORT,ALLOCATION_REPORT, &
           ENRG_LIMIT_REPORT,LOAD_PROB_PLOT,UNIT_OUTPUT_REPORT, &
           ANNUAL_UNIT_OUTPUT_REPORT,DSM_FINANCIAL_REPORT, &
           CSV_REPORT,KEPCO_REPORTS,CONTRACT_REPORT, &
           FUEL_USAGE_REPORT,LM_DAYS_REPORT,WABASH_POWER_COST_REPORT, &
           MAINTENANCE_REPORT,SERVICE_REPORT,ECONOMY_REPORT,COMMENT, &
           LOLP_REPORT,EXISTING_ASSETS_REPORT,FUTURE_ASSETS_REPORT, &
           NUCLEAR_FUEL_REPORT,DEBT_REPORT,ASSET_CLASS_REPORTS, &
           REPORTING_ASSET_CLASS,TRANSACT_UNIT_REPORT, &
           TRANSACT_HOURLY_REPORTS,TRANS_TRANSMISSION_REPORTS, &
           TRANSACT_MONTHLY_REPORTS,MARKET_DURATION_REPORT, &
           FINANCIAL_DRILLING,EXPENSE_REVENUES_REPORT, &
           TRANSACT_DAILY_REPORTS,TF_CLASS_SUMMARY_REPORTS, &
           DEBITS_REPORT,HOURLY_ECAP_REPORT,TRANSACT_FUEL_REPORT, &
          DYNAMIC_JURIS_ALLOC,MONTHLY_GROUP_REPORT,HOURLY_PRICE_REPORT,&
           SELECTED_DISPATCH_RPT_MONTHS,DISPATCH_RPT_TYPE, &
           HOURLY_LOAD_BEFORE_HYDRO,TRANS_HOURLY_DIAG, &
           HYDRO_SALES_AS_NEGATIVE,DEPTH_OF_MARKET,NUMBER_OF_INTERVALS,&
           INTERVAL_SIZE,HOURLY_COMMITMENT,DAILY_COMMITMENT, &
           DEPTH_TARGET_GROUP,HOURLY_OUTAGE,DIAGNOSTIC_DAY_OF_MONTH, &
           MARGINAL_UNIT_REPORT,WEEKLY_HYDRO_REPORT, &
           HOURLY_CAPACITY_REPORT,HOURLY_CAPACITY_COST_REPORT, &
           HOURLY_DERIVATIVES_REPORT,HOURLY_LOAD_AFTER_HYDRO_REPORT, &
           HOURLY_LOAD_AFTER_TRANS_REPORT,FISCAL_YEAR_ACTIVE, &
           BEGIN_FISCAL_YEAR,FLOW_ANALYST_REPORT_GROUP,  & !  65
           MARKET_MATCH_REPORT_GROUP,  & !  66
           RESERVED_REPORT_GROUP, & !  67
           RESERVED_REPORT_GROUP, & !  68
           RESERVED_REPORT_GROUP, & !  69
           MONTHLY_DERIVATIVES,NEW_UNITS_REPORT,DEPTH_MARKET_FILE, &
           WRITE_DAILY_PATHS_REPORTS, & !  73
           MONTHLY_FUEL_DERIV_REPORT,MONTHLY_SCEN_MAKER_REPORT, &
           TECH_SCAR_REPORT,POWERWORLD_REPORT,LOAD_MARKET_AREAS_REPORT,&
           PORT_MARKET_AREAS_REPORT,MONTHLY_LOAD_N_RESOURCES,   & !  80
           HOURLY_JDA_REPORT,MONTHLY_TRANC_REPORT, &
           HOURLY_UNIT_FUEL_REPORT,HOURLY_TRANSACTION_REPORT, &
           IPL_FAC_REPORT,HOURLY_SPIN_REPORT,HOURLY_CUST_MARGIN_REPORT,&
           DAILY_DISPATCH_ORDER_REPORT,TRANSACT_PROD_REPORT, &
           TRANS_INTR_REPORT,          & !  90
           TRANS_TO_FROM_REPORT,MONTHLY_GAS_DEMAND_REPORT, &
           DAILY_GAS_DEMAND_REPORT,MONTHLY_GAS_SUPPLY_REPORT, &
           DAILY_GAS_SELL_BUY_REPORT,TRANSACT_MW_REPORT, &
           MONTHLY_GAS_SELL_BUY_REPORT,MONTHLY_GAS_LINK_REPORT, &
           NEW_SUPPLY_CURVE_REPORT,SELECT_NEW_SUPPLY_RPT_MONTHS, &
           MONTHLY_COAL_DEMAND_REPORT,MONTHLY_COAL_SUPPLY_REPORT, &
           CO2_ABATEMENT_REPORT_ACTIVE,GRX_8761_REPORT, & !  104
           MARGINAL_UNIT_BY_TECH_REPORT,DERIVATIVE_CUSTOMER_MARGINS, &
           DAILY_THERMAL_UNIT_REPORT,DATE_THERMAL_REPORT_BEGINS, &
           DATE_THERMAL_REPORT_ENDS,TEMP_REPORT_1,TEMP_REPORT_2, &
          RPS_PROGRAMS_REPORT,OLD_RPS_PROGRAMS_REPORT,RPS_CURVE_REPORT,&
           HOURLY_GRX_STORAGE_REPORT
               ENDIF
            ENDIF
            WRITE(11,REC=IREC) &
            DELETE,YEAR,FORECAST_REPORT,EXPANSION_REPORT, &
            DISPATCH_REPORT,ALLOCATION_REPORT,ENRG_LIMIT_REPORT, &
            LOAD_PROB_PLOT,UNIT_OUTPUT_REPORT, &
            ANNUAL_UNIT_OUTPUT_REPORT,DSM_FINANCIAL_REPORT, &
            CSV_REPORT,KEPCO_REPORTS,CONTRACT_REPORT, &
            FUEL_USAGE_REPORT,LM_DAYS_REPORT, &
            WABASH_POWER_COST_REPORT,MAINTENANCE_REPORT, &
            SERVICE_REPORT,ECONOMY_REPORT,LOLP_REPORT, &
            EXISTING_ASSETS_REPORT,FUTURE_ASSETS_REPORT, &
            NUCLEAR_FUEL_REPORT,DEBT_REPORT,ASSET_CLASS_REPORTS, &
            REPORTING_ASSET_CLASS,TRANSACT_UNIT_REPORT, &
            TRANSACT_HOURLY_REPORTS,TRANS_TRANSMISSION_REPORTS, &
            TRANSACT_MONTHLY_REPORTS,MARKET_DURATION_REPORT, &
            FINANCIAL_DRILLING,EXPENSE_REVENUES_REPORT, &
            TRANSACT_DAILY_REPORTS,TF_CLASS_SUMMARY_REPORTS, &
            DEBITS_REPORT,HOURLY_ECAP_REPORT,TRANSACT_FUEL_REPORT, &
            DYNAMIC_JURIS_ALLOC,MONTHLY_GROUP_REPORT, &
            HOURLY_PRICE_REPORT,SELECTED_DISPATCH_RPT_MONTHS, &
            DISPATCH_RPT_TYPE,HOURLY_LOAD_BEFORE_HYDRO, &
            TRANS_HOURLY_DIAG,HYDRO_SALES_AS_NEGATIVE,DEPTH_OF_MARKET, &
            NUMBER_OF_INTERVALS,INTERVAL_SIZE,HOURLY_COMMITMENT, &
            DAILY_COMMITMENT,DEPTH_TARGET_GROUP,HOURLY_OUTAGE, &
            DIAGNOSTIC_DAY_OF_MONTH,MARGINAL_UNIT_REPORT, &
            WEEKLY_HYDRO_REPORT,HOURLY_CAPACITY_REPORT, &
            HOURLY_CAPACITY_COST_REPORT,HOURLY_DERIVATIVES_REPORT, &
            HOURLY_LOAD_AFTER_HYDRO_REPORT, &
            HOURLY_LOAD_AFTER_TRANS_REPORT,FISCAL_YEAR_ACTIVE, &
            BEGIN_FISCAL_YEAR,FLOW_ANALYST_REPORT_GROUP,  & !  65
            MARKET_MATCH_REPORT_GROUP,  & !  66
            RESERVED_REPORT_GROUP, & !  67
            RESERVED_REPORT_GROUP, & !  68
            RESERVED_REPORT_GROUP, & !  69
            MONTHLY_DERIVATIVES,NEW_UNITS_REPORT,DEPTH_MARKET_FILE, &
            WRITE_DAILY_PATHS_REPORTS,MONTHLY_FUEL_DERIV_REPORT, &
            MONTHLY_SCEN_MAKER_REPORT,TECH_SCAR_REPORT, &
            POWERWORLD_REPORT,LOAD_MARKET_AREAS_REPORT, &
            PORT_MARKET_AREAS_REPORT,MONTHLY_LOAD_N_RESOURCES, &
            HOURLY_JDA_REPORT,MONTHLY_TRANC_REPORT, &
            HOURLY_UNIT_FUEL_REPORT,HOURLY_TRANSACTION_REPORT, &
           IPL_FAC_REPORT,HOURLY_SPIN_REPORT,HOURLY_CUST_MARGIN_REPORT,&
            DAILY_DISPATCH_ORDER_REPORT,TRANSACT_PROD_REPORT, &
            TRANS_INTR_REPORT,TRANS_TO_FROM_REPORT, &
            MONTHLY_GAS_DEMAND_REPORT,DAILY_GAS_DEMAND_REPORT, &
            MONTHLY_GAS_SUPPLY_REPORT,DAILY_GAS_SELL_BUY_REPORT, &
            TRANSACT_MW_REPORT,MONTHLY_GAS_SELL_BUY_REPORT, &
            MONTHLY_GAS_LINK_REPORT,NEW_SUPPLY_CURVE_REPORT, &
            SELECT_NEW_SUPPLY_RPT_MONTHS,MONTHLY_COAL_DEMAND_REPORT, &
            MONTHLY_COAL_SUPPLY_REPORT,CO2_ABATEMENT_REPORT_ACTIVE, &
            GRX_8761_REPORT,MARGINAL_UNIT_BY_TECH_REPORT, &
            DERIVATIVE_CUSTOMER_MARGINS,DAILY_THERMAL_UNIT_REPORT, &
            DATE_THERMAL_REPORT_BEGINS,DATE_THERMAL_REPORT_ENDS, &
            TEMP_REPORT_1,TEMP_REPORT_2,RPS_PROGRAMS_REPORT, &
            OLD_RPS_PROGRAMS_REPORT,RPS_CURVE_REPORT, &
            HOURLY_GRX_STORAGE_REPORT
!
            CSV_BY_UNIT(IREC) = CSV_REPORT=='U' .OR. CSV_REPORT=='B'
            CSV_BY_UNIT(0) = CSV_BY_UNIT(0) .OR. CSV_BY_UNIT(IREC)
            IREC = IREC + 1

            IF(IREC > AVAIL_DATA_YEARS) EXIT ! needed to cover extension period 11/06/06 Dr.G
         ENDDO
         IF(FILE_EXISTS) CLOSE(10)
         CLOSE(11)
      RETURN
! ***********************************************************************
!
!  OVERLAY DETAILED REPORTS
!
      ENTRY DE_MAKEOVL(OVERLAY_FAMILY_NAME)
! ***********************************************************************

      IF(LAHEY_LF95()) THEN
         SCREEN_OUTPUT = trim(FILE_TYPE)//'-'//OVERLAY_FAMILY_NAME
         CALL MG_LOCATE_WRITE(17,9,SCREEN_OUTPUT,ALL_VERSIONS,0)
      ELSE
         CALL MG_CLEAR_LINE_WRITE(17,9,36,FILE_TYPE,ALL_VERSIONS,0)
         CALL LOCATE(10,51)
      ENDIF
      DATA_DRIVE = OUTPUT_DIRECTORY()
      FILE_NAME = trim(DATA_DRIVE)//"DEO"// &
                                     trim(OVERLAY_FAMILY_NAME)//".DAT"
      OPEN(10,FILE=FILE_NAME)
      READ(10,*) DELETE
      INUNIT = 12
      IF(DET_RPT_OL == 'BC') THEN
         OPEN(11,FILE=trim(DATA_DRIVE)//"BCDETRPT.BIN", &
                                             ACCESS="DIRECT",RECL=LRECL)
         INUNIT = 11
      ENDIF
      OPEN(12,FILE=trim(DATA_DRIVE)//"OLDETRPT.BIN",ACCESS="DIRECT", &
                                            STATUS="UNKNOWN",RECL=LRECL)
      CSV_BY_UNIT(0) = .FALSE.
      IREC = 0
      DO
         IREC = IREC + 1
         READ(INUNIT,REC=IREC,IOSTAT=IOS) DELETE,YEAR, &
              FORECAST_REPORT,EXPANSION_REPORT,DISPATCH_REPORT, &
              ALLOCATION_REPORT,ENRG_LIMIT_REPORT,LOAD_PROB_PLOT, &
              UNIT_OUTPUT_REPORT,ANNUAL_UNIT_OUTPUT_REPORT, &
              DSM_FINANCIAL_REPORT,CSV_REPORT,KEPCO_REPORTS, &
              CONTRACT_REPORT,FUEL_USAGE_REPORT,LM_DAYS_REPORT, &
              WABASH_POWER_COST_REPORT,MAINTENANCE_REPORT, &
              SERVICE_REPORT,ECONOMY_REPORT,LOLP_REPORT, &
              EXISTING_ASSETS_REPORT,FUTURE_ASSETS_REPORT, &
              NUCLEAR_FUEL_REPORT,DEBT_REPORT,ASSET_CLASS_REPORTS, &
              REPORTING_ASSET_CLASS,TRANSACT_UNIT_REPORT, &
              TRANSACT_HOURLY_REPORTS,TRANS_TRANSMISSION_REPORTS, &
              TRANSACT_MONTHLY_REPORTS,MARKET_DURATION_REPORT, &
              FINANCIAL_DRILLING,EXPENSE_REVENUES_REPORT, &
              TRANSACT_DAILY_REPORTS,TF_CLASS_SUMMARY_REPORTS, &
              DEBITS_REPORT,HOURLY_ECAP_REPORT,TRANSACT_FUEL_REPORT, &
              DYNAMIC_JURIS_ALLOC,MONTHLY_GROUP_REPORT, &
              HOURLY_PRICE_REPORT,SELECTED_DISPATCH_RPT_MONTHS, &
              DISPATCH_RPT_TYPE,HOURLY_LOAD_BEFORE_HYDRO, &
              TRANS_HOURLY_DIAG,HYDRO_SALES_AS_NEGATIVE, &
              DEPTH_OF_MARKET,NUMBER_OF_INTERVALS,INTERVAL_SIZE, &
              HOURLY_COMMITMENT,DAILY_COMMITMENT,DEPTH_TARGET_GROUP, &
              HOURLY_OUTAGE,DIAGNOSTIC_DAY_OF_MONTH, &
              MARGINAL_UNIT_REPORT,WEEKLY_HYDRO_REPORT, &
              HOURLY_CAPACITY_REPORT,HOURLY_CAPACITY_COST_REPORT, &
              HOURLY_DERIVATIVES_REPORT,HOURLY_LOAD_AFTER_HYDRO_REPORT,&
              HOURLY_LOAD_AFTER_TRANS_REPORT,FISCAL_YEAR_ACTIVE, &
              BEGIN_FISCAL_YEAR,FLOW_ANALYST_REPORT_GROUP,  & !  65
              MARKET_MATCH_REPORT_GROUP,  & !  66
              RESERVED_REPORT_GROUP, & !  67
              RESERVED_REPORT_GROUP, & !  68
              RESERVED_REPORT_GROUP, & !  69
              MONTHLY_DERIVATIVES,NEW_UNITS_REPORT,DEPTH_MARKET_FILE, &
              WRITE_DAILY_PATHS_REPORTS,MONTHLY_FUEL_DERIV_REPORT, &
              MONTHLY_SCEN_MAKER_REPORT,TECH_SCAR_REPORT, &
              POWERWORLD_REPORT,LOAD_MARKET_AREAS_REPORT, &
              PORT_MARKET_AREAS_REPORT,MONTHLY_LOAD_N_RESOURCES, &
              HOURLY_JDA_REPORT,MONTHLY_TRANC_REPORT, &
              HOURLY_UNIT_FUEL_REPORT,HOURLY_TRANSACTION_REPORT, &
              IPL_FAC_REPORT,HOURLY_SPIN_REPORT, &
              HOURLY_CUST_MARGIN_REPORT,DAILY_DISPATCH_ORDER_REPORT, &
              TRANSACT_PROD_REPORT,TRANS_INTR_REPORT, &
              TRANS_TO_FROM_REPORT,MONTHLY_GAS_DEMAND_REPORT, &
              DAILY_GAS_DEMAND_REPORT,MONTHLY_GAS_SUPPLY_REPORT, &
              DAILY_GAS_SELL_BUY_REPORT,TRANSACT_MW_REPORT, &
              MONTHLY_GAS_SELL_BUY_REPORT,MONTHLY_GAS_LINK_REPORT, &
              NEW_SUPPLY_CURVE_REPORT,SELECT_NEW_SUPPLY_RPT_MONTHS, &
              MONTHLY_COAL_DEMAND_REPORT,MONTHLY_COAL_SUPPLY_REPORT, &
              CO2_ABATEMENT_REPORT_ACTIVE,GRX_8761_REPORT, &
              MARGINAL_UNIT_BY_TECH_REPORT,DERIVATIVE_CUSTOMER_MARGINS,&
              DAILY_THERMAL_UNIT_REPORT,DATE_THERMAL_REPORT_BEGINS, &
              DATE_THERMAL_REPORT_ENDS,TEMP_REPORT_1,TEMP_REPORT_2, &
              RPS_PROGRAMS_REPORT,OLD_RPS_PROGRAMS_REPORT, &
              RPS_CURVE_REPORT,HOURLY_GRX_STORAGE_REPORT
         IF(IOS /= 0) EXIT
         READ(10,1000,IOSTAT=IOS) RECLN
         IF(IOS == 0) THEN
            RECLN = trim(RECLN)// &
                             ',,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,'
          READ(RECLN,*,IOSTAT=IOS) DELETE,YEAR,FORECAST_REPORT, &
          EXPANSION_REPORT,DISPATCH_REPORT,ALLOCATION_REPORT, &
          ENRG_LIMIT_REPORT,LOAD_PROB_PLOT,UNIT_OUTPUT_REPORT, &
          ANNUAL_UNIT_OUTPUT_REPORT,DSM_FINANCIAL_REPORT,CSV_REPORT, &
          KEPCO_REPORTS,CONTRACT_REPORT,FUEL_USAGE_REPORT, &
          LM_DAYS_REPORT,WABASH_POWER_COST_REPORT,MAINTENANCE_REPORT, &
          SERVICE_REPORT,ECONOMY_REPORT,COMMENT,LOLP_REPORT, &
          EXISTING_ASSETS_REPORT,FUTURE_ASSETS_REPORT, &
          NUCLEAR_FUEL_REPORT,DEBT_REPORT,ASSET_CLASS_REPORTS, &
          REPORTING_ASSET_CLASS,TRANSACT_UNIT_REPORT, &
          TRANSACT_HOURLY_REPORTS,TRANS_TRANSMISSION_REPORTS, &
          TRANSACT_MONTHLY_REPORTS,MARKET_DURATION_REPORT, &
          FINANCIAL_DRILLING,EXPENSE_REVENUES_REPORT, &
          TRANSACT_DAILY_REPORTS,TF_CLASS_SUMMARY_REPORTS, &
          DEBITS_REPORT,HOURLY_ECAP_REPORT,TRANSACT_FUEL_REPORT, &
          DYNAMIC_JURIS_ALLOC,MONTHLY_GROUP_REPORT, &
          HOURLY_PRICE_REPORT,SELECTED_DISPATCH_RPT_MONTHS, &
          DISPATCH_RPT_TYPE,HOURLY_LOAD_BEFORE_HYDRO,TRANS_HOURLY_DIAG,&
          HYDRO_SALES_AS_NEGATIVE,DEPTH_OF_MARKET,NUMBER_OF_INTERVALS, &
          INTERVAL_SIZE,HOURLY_COMMITMENT,DAILY_COMMITMENT, &
          DEPTH_TARGET_GROUP,HOURLY_OUTAGE,DIAGNOSTIC_DAY_OF_MONTH, &
          MARGINAL_UNIT_REPORT,WEEKLY_HYDRO_REPORT, &
          HOURLY_CAPACITY_REPORT,HOURLY_CAPACITY_COST_REPORT, &
          HOURLY_DERIVATIVES_REPORT,HOURLY_LOAD_AFTER_HYDRO_REPORT, &
          HOURLY_LOAD_AFTER_TRANS_REPORT,FISCAL_YEAR_ACTIVE, &
          BEGIN_FISCAL_YEAR,FLOW_ANALYST_REPORT_GROUP,  & !  65
          MARKET_MATCH_REPORT_GROUP,  & !  66
          RESERVED_REPORT_GROUP, & !  67
          RESERVED_REPORT_GROUP, & !  68
          RESERVED_REPORT_GROUP, & !  69
          MONTHLY_DERIVATIVES,NEW_UNITS_REPORT,DEPTH_MARKET_FILE, &
          WRITE_DAILY_PATHS_REPORTS,MONTHLY_FUEL_DERIV_REPORT, &
          MONTHLY_SCEN_MAKER_REPORT,TECH_SCAR_REPORT,POWERWORLD_REPORT,&
          LOAD_MARKET_AREAS_REPORT,PORT_MARKET_AREAS_REPORT, &
          MONTHLY_LOAD_N_RESOURCES,HOURLY_JDA_REPORT, &
          MONTHLY_TRANC_REPORT,HOURLY_UNIT_FUEL_REPORT, &
          HOURLY_TRANSACTION_REPORT,IPL_FAC_REPORT,HOURLY_SPIN_REPORT, &
          HOURLY_CUST_MARGIN_REPORT,DAILY_DISPATCH_ORDER_REPORT, &
          TRANSACT_PROD_REPORT,TRANS_INTR_REPORT,TRANS_TO_FROM_REPORT, &
          MONTHLY_GAS_DEMAND_REPORT,DAILY_GAS_DEMAND_REPORT, &
          MONTHLY_GAS_SUPPLY_REPORT,DAILY_GAS_SELL_BUY_REPORT, &
          TRANSACT_MW_REPORT,MONTHLY_GAS_SELL_BUY_REPORT, &
          MONTHLY_GAS_LINK_REPORT,NEW_SUPPLY_CURVE_REPORT, &
          SELECT_NEW_SUPPLY_RPT_MONTHS,MONTHLY_COAL_DEMAND_REPORT, &
          MONTHLY_COAL_SUPPLY_REPORT,CO2_ABATEMENT_REPORT_ACTIVE, &
          GRX_8761_REPORT,MARGINAL_UNIT_BY_TECH_REPORT, &
          DERIVATIVE_CUSTOMER_MARGINS,DAILY_THERMAL_UNIT_REPORT, &
          DATE_THERMAL_REPORT_BEGINS,DATE_THERMAL_REPORT_ENDS, &
          TEMP_REPORT_1,TEMP_REPORT_2,RPS_PROGRAMS_REPORT, &
          OLD_RPS_PROGRAMS_REPORT,RPS_CURVE_REPORT, &
          HOURLY_GRX_STORAGE_REPORT
         ENDIF
         WRITE(12,REC=IREC) DELETE,YEAR,FORECAST_REPORT, &
          EXPANSION_REPORT,DISPATCH_REPORT,ALLOCATION_REPORT, &
          ENRG_LIMIT_REPORT,LOAD_PROB_PLOT,UNIT_OUTPUT_REPORT, &
          ANNUAL_UNIT_OUTPUT_REPORT,DSM_FINANCIAL_REPORT,CSV_REPORT, &
          KEPCO_REPORTS,CONTRACT_REPORT,FUEL_USAGE_REPORT, &
          LM_DAYS_REPORT,WABASH_POWER_COST_REPORT,MAINTENANCE_REPORT, &
          SERVICE_REPORT,ECONOMY_REPORT,LOLP_REPORT, &
          EXISTING_ASSETS_REPORT,FUTURE_ASSETS_REPORT, &
          NUCLEAR_FUEL_REPORT,DEBT_REPORT,ASSET_CLASS_REPORTS, &
          REPORTING_ASSET_CLASS,TRANSACT_UNIT_REPORT, &
          TRANSACT_HOURLY_REPORTS,TRANS_TRANSMISSION_REPORTS, &
          TRANSACT_MONTHLY_REPORTS,MARKET_DURATION_REPORT, &
          FINANCIAL_DRILLING,EXPENSE_REVENUES_REPORT, &
         TRANSACT_DAILY_REPORTS,TF_CLASS_SUMMARY_REPORTS,DEBITS_REPORT,&
          HOURLY_ECAP_REPORT,TRANSACT_FUEL_REPORT,DYNAMIC_JURIS_ALLOC, &
          MONTHLY_GROUP_REPORT,HOURLY_PRICE_REPORT, &
          SELECTED_DISPATCH_RPT_MONTHS,DISPATCH_RPT_TYPE, &
          HOURLY_LOAD_BEFORE_HYDRO,TRANS_HOURLY_DIAG, &
          HYDRO_SALES_AS_NEGATIVE,DEPTH_OF_MARKET,NUMBER_OF_INTERVALS, &
          INTERVAL_SIZE,HOURLY_COMMITMENT,DAILY_COMMITMENT, &
          DEPTH_TARGET_GROUP,HOURLY_OUTAGE,DIAGNOSTIC_DAY_OF_MONTH, &
          MARGINAL_UNIT_REPORT,WEEKLY_HYDRO_REPORT, &
          HOURLY_CAPACITY_REPORT,HOURLY_CAPACITY_COST_REPORT, &
          HOURLY_DERIVATIVES_REPORT,HOURLY_LOAD_AFTER_HYDRO_REPORT, &
          HOURLY_LOAD_AFTER_TRANS_REPORT,FISCAL_YEAR_ACTIVE, &
          BEGIN_FISCAL_YEAR,FLOW_ANALYST_REPORT_GROUP,  & !  65
          MARKET_MATCH_REPORT_GROUP,  & !  66
          RESERVED_REPORT_GROUP, & !  67
          RESERVED_REPORT_GROUP, & !  68
          RESERVED_REPORT_GROUP, & !  69
          MONTHLY_DERIVATIVES,NEW_UNITS_REPORT,DEPTH_MARKET_FILE, &
          WRITE_DAILY_PATHS_REPORTS,MONTHLY_FUEL_DERIV_REPORT, &
          MONTHLY_SCEN_MAKER_REPORT,TECH_SCAR_REPORT,POWERWORLD_REPORT,&
          LOAD_MARKET_AREAS_REPORT,PORT_MARKET_AREAS_REPORT, &
          MONTHLY_LOAD_N_RESOURCES,HOURLY_JDA_REPORT, &
          MONTHLY_TRANC_REPORT,HOURLY_UNIT_FUEL_REPORT, &
          HOURLY_TRANSACTION_REPORT,IPL_FAC_REPORT,HOURLY_SPIN_REPORT, &
          HOURLY_CUST_MARGIN_REPORT,DAILY_DISPATCH_ORDER_REPORT, &
          TRANSACT_PROD_REPORT,TRANS_INTR_REPORT,TRANS_TO_FROM_REPORT, &
          MONTHLY_GAS_DEMAND_REPORT,DAILY_GAS_DEMAND_REPORT, &
          MONTHLY_GAS_SUPPLY_REPORT,DAILY_GAS_SELL_BUY_REPORT, &
          TRANSACT_MW_REPORT,MONTHLY_GAS_SELL_BUY_REPORT, &
          MONTHLY_GAS_LINK_REPORT,NEW_SUPPLY_CURVE_REPORT, &
          SELECT_NEW_SUPPLY_RPT_MONTHS,MONTHLY_COAL_DEMAND_REPORT, &
          MONTHLY_COAL_SUPPLY_REPORT,CO2_ABATEMENT_REPORT_ACTIVE, &
          GRX_8761_REPORT,MARGINAL_UNIT_BY_TECH_REPORT, &
          DERIVATIVE_CUSTOMER_MARGINS,DAILY_THERMAL_UNIT_REPORT, &
          DATE_THERMAL_REPORT_BEGINS,DATE_THERMAL_REPORT_ENDS, &
          TEMP_REPORT_1,TEMP_REPORT_2,RPS_PROGRAMS_REPORT, &
          OLD_RPS_PROGRAMS_REPORT,RPS_CURVE_REPORT, &
          HOURLY_GRX_STORAGE_REPORT
!
         CSV_BY_UNIT(IREC) = CSV_REPORT == 'U' .OR. CSV_REPORT == 'B'
         CSV_BY_UNIT(0) = CSV_BY_UNIT(0) .OR. CSV_BY_UNIT(IREC)
      ENDDO
      CLOSE(10)
      CLOSE(12)
      IF(DET_RPT_OL == 'BC') CLOSE(11)
      DET_RPT_OL = 'OL'
      RETURN
!
      ENTRY RETURN_DET_RPT_OL(R_DET_RPT_OL)
         R_DET_RPT_OL = DET_RPT_OL
      RETURN
!
      ENTRY RESET_DET_RPT_OL
         DET_RPT_OL = 'BC'
      RETURN
!
      ENTRY OPEN_DETAILED_REPORT_FILE
         FILE_NAME = trim(OUTPUT_DIRECTORY())//DET_RPT_OL &
                                                          //"DETRPT.BIN"
         OPEN(67,FILE=FILE_NAME,ACCESS="DIRECT",RECL=LRECL)
      RETURN
!
 1000 FORMAT(A)
 1010 FORMAT('&',A)
      END
! ***********************************************************************
!
!         DETAILED_REPORTS_OBJECT READ THE DETAILED REPORTS FILE AND
!         RETURNS THE APPROPRIATE VALUES TO THE CALLING PROGRAM
!
!         COPYRIGHT (C) 1995 M.S. GERBER & ASSOCIATES, INC.
!                          ALL RIGHTS RESERVED
! ***********************************************************************
!
      FUNCTION DETAILED_REPORTS_OBJECT()
!
      use SpinDriftLib
      use prod_arrays_dimensions
      USE SIZECOM
      CHARACTER(len=2) :: DET_RPT_OL
      INTEGER(kind=2) :: YEAR,OPYEAR
      INTEGER :: IOS
      LOGICAL(kind=1) :: DETAILED_REPORTS_OBJECT, &
                RETURN_DET_RPTS_FOR_ASSETS, &
                RETURN_DETAILED_REPORTS, &
                CLOSE_DETAILED_REPORTS_FILE,VOID_LOGICAL
      CHARACTER(len=1) :: HYDRO_FILES_ARE_ACTIVE
!
      CHARACTER(len=1) :: FORECAST_REPORT_STR, &
                  EXPANSION_REPORT_STR, &
                  DISPATCH_REPORT_STR*2, &
                  ALLOCATION_REPORT_STR, &
                  ENRG_LIMIT_REPORT_STR, &
                  LOAD_PROB_PLOT_STR, &
                  ANNUAL_UNIT_OUTPUT_REPORT_STR, &
                  DSM_FINANCIAL_REPORT_STR
      INTEGER(kind=2) :: DELETE,IREC
      CHARACTER(len=256) :: FILE_NAME,OUTPUT_DIRECTORY
      CHARACTER(len=128) :: MONTHS_ARRAY
      CHARACTER(len=1) :: LM_DAYS_REPORT_ACTIVE=' '
      CHARACTER(len=1) :: CSV_REPORT_ACTIVE=' '
      CHARACTER(len=1) :: KEPCO_REPORTS_ACTIVE=' '
      CHARACTER(len=1) :: WABASH_POWER_COST_REPORT_ACTIVE=' '
      LOGICAL(kind=1) :: SPREAD_SHEET,SPREAD_SHEET_ACTIVE=.FALSE.
      LOGICAL(kind=1) :: FUEL_USAGE_REPORT
      CHARACTER(len=1) :: FUEL_USAGE_REPORT_ACTIVE=' '
      LOGICAL(kind=1) :: MAINTENANCE_REPORT
      CHARACTER(len=1) :: MAINTENANCE_REPORT_ACTIVE=' '
      LOGICAL(kind=1) :: ECONOMY_REPORT
      CHARACTER(len=1) :: ECONOMY_REPORT_ACTIVE=' '
      LOGICAL(kind=1) :: MARKET_MATCH_REPORTS_ACTIVE=.FALSE., &
                FLOW_ANALYST_REPORTS_ACTIVE=.FALSE.

      LOGICAL(kind=1) :: LOLP_REPORT,EXISTING_ASSETS_REPORT, &
                FUTURE_ASSETS_REPORT,NUCLEAR_FUEL_REPORT,DEBT_REPORT, &
                DEBIT_REPORT,HOURLY_ECAP_REPORT,TRANSACT_FUEL_REPORT, &
                DYNAMIC_JURIS_ALLOC,MONTHLY_GROUP_REPORT, &
                HOURLY_PRICE_REPORT,ASSET_CLASS_REPORTS, &
                TRANSACT_UNIT_MONTHLY_REPORT, &
                TRANSACT_UNIT_ANNUAL_REPORT,TRANSACT_HOURLY_REPORTS, &
                TRANSACT_MONTHLY_REPORTS,MARKET_DURATION_REPORT, &
                TRANS_TRANSMISSION_REPORTS,EXPENSE_REVENUES_REPORT, &
                TRANSACT_DAILY_REPORTS,TF_CLASS_SUMMARY_REPORTS, &
                HOURLY_LOAD_BEFORE_HYDRO,TRANS_HOURLY_DIAG, &
                HYDRO_SALES_AS_NEGATIVE,DEPTH_OF_MARKET, &
                HOURLY_COMMITMENT,DAILY_COMMITMENT,HOURLY_OUTAGE, &
                MARGINAL_UNIT_REPORT,WEEKLY_HYDRO_REPORT, &
                HOURLY_CAPACITY_REPORT,HOURLY_CAPACITY_COST_REPORT, &
                HOURLY_DERIVATIVES_REPORT,HOURLY_AFTER_HYDRO_REPORT, &
                HOURLY_AFTER_TRANS_REPORT,IS_FISCAL_YEAR_ACTIVE, &
                MONTHLY_DERIVATIVES_ACTIVE,SUPPRESS_DERIVATIVES_ACTIVE,&
                NEW_UNITS_REPORT_ACTIVE,DEPTH_MARKET_REPORTS_ACTIVE, &
                YES_WRITE_DAILY_PATHS_REPORTS
      LOGICAL(kind=1) :: &
                YES_MONTHLY_FUEL_DERIV_REPORT, &
                YES_MONTHLY_SCEN_MAKER_REPORT,YES_TECH_SCAR_REPORT, &
                YES_POWERWORLD_REPORT,YES_POWERWORLD_NEW_REPORT, &
                YES_REFERENCE_CASE_REPORT,YES_LOAD_MARKET_AREAS_REPORT,&
                YES_PORT_MARKET_AREAS_REPORT, &
                YES_MONTHLY_LOAD_N_RESOURCES,YES_IPL_FAC_REPORT, &
                HOURLY_SPIN_REPORT,HOURLY_CUST_MARGIN_REPORT, &
                DAILY_DISPATCH_ORDER_REPORT,TRANSACT_PROD_REPORT, &
                TRANS_INTR_REPORT,TRANS_TO_FROM_REPORT, &
                MONTHLY_GAS_DEMAND_REPORT,DAILY_GAS_DEMAND_REPORT, &
                MONTHLY_GAS_SUPPLY_REPORT,DAILY_GAS_SELL_BUY_REPORT, &
                MONTHLY_GAS_SELL_BUY_REPORT,MONTHLY_GAS_LINK_REPORT, &
                NEW_SUPPLY_CURVE_REPORT,TRANSACT_MW_REPORT, &
                GET_ALLOC_COSTS_BY_UNIT,YES_HOURLY_JDA_REPORT, &
                YES_MONTHLY_TRANC_REPORT,YES_HOURLY_UNIT_FUEL_REPORT, &
                YES_HOURLY_TRANSACTION_REPORT, &
                YES_USE_MARKET_AREA_REPORT_ID,R_ONLY_FISCAL_YEAR, &
                MODEL_ISSUED_DEBT_REPORT,MONTHLY_COAL_DEMAND_REPORT, &
                MONTHLY_COAL_SUPPLY_REPORT,CO2_ABATEMENT_REPORT_ACTIVE
      LOGICAL(kind=1) :: &
                GRX_8761_REPORT_ACTIVE,MARGINAL_UNIT_BY_TECH_ACTIVE, &
                DAILY_THERMAL_REPORT_ACTIVE, &
                YES_REPORT_DAILY_PRIME_MOVER,YES_REPORT_DAILY_THERMAL, &
                YES_RPS_PROGRAMS_REPORT,YES_OLD_RPS_PROGRAMS_REPORT, &
                YES_RPS_CURVE_REPORT,YES_HOURLY_GRX_STORAGE_REPORT
      CHARACTER(len=1) :: FINANCIAL_DRILLING, &
         SELECTED_DISPATCH_RPT_MONTHS*30, &
         SELECT_NEW_SUPPLY_RPT_MONTHS*30, &
         MONTHLY_COAL_DEMAND_REPORT_STR='F', &
         MONTHLY_COAL_SUPPLY_REPORT_STR='F', &
         CO2_ABATEMENT_REPORT_ACTIVE_STR='F',GRX_8761_REPORT_STR='F', &
         MARGINAL_UNIT_BY_TECH_STR='F', &
         DERIVATIVE_CUSTOMER_MARGINS_STR='F', &
         DAILY_THERMAL_UNIT_REPORT_STR='F',RPS_PROGRAMS_REPORT_STR='F',&
         OLD_RPS_PROGRAMS_REPORT_STR='F',RPS_CURVE_REPORT_STR='F', &
         HOURLY_GRX_STORAGE_REPORT_STR='F',TEMP_REPORT_1_STR='F', &
         TEMP_REPORT_2_STR='F',DISPATCH_RPT_TYPE,DISPATCH_RPT_TYPE_STR,&
         HOURLY_LOAD_BEFORE_HYDRO_STR='F',TRANS_HOURLY_DIAG_STR='F', &
         HYDRO_SALES_AS_NEGATIVE_STR='F',DEPTH_OF_MARKET_STR='F', &
         HOURLY_COMMITMENT_STR='F',DAILY_COMMITMENT_STR='F', &
         HOURLY_OUTAGE_STR='F',MARGINAL_UNIT_REPORT_STR='F', &
         WEEKLY_HYDRO_REPORT_STR='F',HOURLY_CAPACITY_REPORT_STR='F', &
         HOURLY_CAP_COST_REPORT_STR='F', &
         HOURLY_DERIVATIVES_REPORT_STR='F', &
         HOURLY_AFTER_HYDRO_REPORT_STR='F'
      CHARACTER(len=1) :: &
         HOURLY_AFTER_TRANS_REPORT_STR='F',FISCAL_YEAR_ACTIVE_STR='F', &
         MONTHLY_DERIVATIVES_STR='F',NEW_UNITS_REPORT_STR='F', &
         WRITE_DAILY_PATHS_REPORTS_STR='F', &
         MONTHLY_FUEL_DERIV_REPORT_STR='F', &
         MONTHLY_SCEN_MAKER_REPORT_STR='F',TECH_SCAR_REPORT_STR='F', &
         POWERWORLD_REPORT_STR='F',LOAD_MARKET_AREAS_REPORT_STR='F', &
         PORT_MARKET_AREAS_REPORT_STR='F', &
         MONTHLY_LOAD_N_RESOURCES_STR='F',IPL_FAC_REPORT_STR='F', &
         HOURLY_SPIN_REPORT_STR='F',HOURLY_CUST_MARGIN_REPORT_STR='F', &
         DAILY_DISPATCH_ORDER_REPORT_STR='F', &
         TRANSACT_PROD_REPORT_STR='F',TRANS_INTR_REPORT_STR='F', &
        TRANS_TO_FROM_REPORT_STR='F',MONTHLY_GAS_DEMAND_REPORT_STR='F',&
         DAILY_GAS_DEMAND_REPORT_STR='F', &
         MONTHLY_GAS_SUPPLY_REPORT_STR='F', &
        DAILY_GAS_SELL_BUY_REPORT_STR='F',MONTHLY_GAS_SELL_BUY_STR='F',&
         MONTHLY_GAS_LINK_STR='F',TRANSACT_MW_REPORT_STR='F', &
         HOURLY_JDA_REPORT_STR='F',MONTHLY_TRANC_REPORT_STR='F', &
         HOURLY_UNIT_FUEL_REPORT_STR='F', &
         HOURLY_TRANSACTION_REPORT_STR='F'
      CHARACTER(len=1) :: &
         FLOW_ANALYST_REPORT_GROUP='F',  & !  65
         MARKET_MATCH_REPORT_GROUP='F',  & !  66
         RESERVED_REPORT_GROUP='F' ! 67
!
      CHARACTER(len=2) :: NEW_SUPPLY_CURVE_STR='F'
      CHARACTER(len=5) :: &
                  DEPTH_MARKET_FILE_STR='     ', &
                  R_DEPTH_MARKET_FILE_STR
!
      INTEGER(kind=2) ::   NUMBER_OF_INTERVALS=0, &
                  R_NUMBER_OF_INTERVALS, &
                  DEPTH_TARGET_GROUP=0, &
                  DIAGNOSTIC_DAY_OF_MONTH=1, &
                  R_DEPTH_TARGET_GROUP, &
                  GET_DIAGNOSTIC_DAY_OF_MONTH, &
                  BEGIN_FISCAL_YEAR=0, &
                  R_BEGIN_FISCAL_YEAR
      INTEGER(kind=4) :: &
                  R_START_DATE,DATE_THERMAL_REPORT_BEGINS, &
                  R_STOP_DATE,DATE_THERMAL_REPORT_ENDS
      REAL(kind=4) :: INTERVAL_SIZE=0., &
                  R_INTERVAL_SIZE
!
      SAVE DISPATCH_RPT_TYPE_STR
      LOGICAL(kind=1) :: R_REPORT_ALL_ACCOUNTS
      CHARACTER(len=1) :: LOLP_REPORT_ACTIVE=' ', &
                  EXISTING_ASSETS_REPORT_ACTIVE=' ', &
                  FUTURE_ASSETS_REPORT_ACTIVE=' ', &
                  NUCLEAR_FUEL_REPORT_ACTIVE=' ', &
                  DEBT_REPORT_ACTIVE=' ',DEBIT_REPORT_ACTIVE=' ', &
                  HOURLY_ECAP_REPORT_ACTIVE=' ', &
                  TRANSACT_FUEL_REPORT_ACTIVE=' ', &
                  DYNAMIC_JURIS_ALLOC_ACTIVE=' ', &
                  MONTHLY_GROUP_REPORT_ACTIVE=' ', &
                  HOURLY_PRICE_REPORT_ACTIVE=' ', &
                  ASSET_CLASS_REPORTS_ACTIVE=' ', &
                  TRANSACT_UNIT_REPORT_ACTIVE=' ', &
                  TRANSACT_HOURLY_REPORTS_ACTIVE=' ', &
                  TRANSACT_MONTHLY_REPORTS_ACTIVE=' ', &
                  MARKET_DURATION_REPORT_ACTIVE=' ', &
                  TRANSMISSION_REPORTS_ACTIVE=' ', &
                  FINANCIAL_DRILLING_ACTIVE=' ', &
                  EXPENSE_REVENUES_ACTIVE=' ', &
                  TRANSACT_DAILY_REPORTS_ACTIVE=' ', &
                  TF_CLASS_SUM_REPORTS_ACTIVE=' '
      CHARACTER(len=4) :: REPORTING_ASSET_CLASS_STR='Cons'
      CHARACTER(len=1) :: SERVICE_REPORT_ACTIVE=' ', &
                  VOID_CHR,SAVE_CHR_DETAILED_RPT_SWITCHES
      LOGICAL(kind=1) :: LM_DAYS_REPORT
      CHARACTER(len=1) :: CONTRACT_REPORT,CONTRACT_REPORT_TYPE='F'
      LOGICAL(kind=1) :: DISPATCH_REPORT,DISPATCH_REPORT_ACTIVE=.FALSE.
      LOGICAL(kind=1) :: SEASONAL_DISPATCH_REPORT, &
                           SEASONAL_DISPATCH_REPORT_ACTIVE=.FALSE.
      LOGICAL(kind=1) :: ENRG_LIMIT_REPORT, &
                         ENRG_LIMIT_REPORT_ACTIVE=.FALSE.
      LOGICAL(kind=1) :: LOAD_PROB_PLOT,LOAD_PROB_PLOT_ACTIVE=.FALSE.
      LOGICAL(kind=1) :: UNIT_OUTPUT_REPORT, &
                         UNIT_OUTPUT_REPORT_ACTIVE=.FALSE.
      CHARACTER(len=1) :: MONTHLY_UNIT_OUTPUT_REPORT
      LOGICAL(kind=1) :: MONTHLY_SUMMARY_REPORT, &
                                  MONTHLY_SUMMARY_REPORT_ACTIVE=.FALSE.
      LOGICAL(kind=1) :: ANNUAL_UNIT_OUTPUT_REPORT, &
                               ANNUAL_UNIT_REPORT_ACTIVE=.FALSE.
      LOGICAL(kind=1) :: FORECAST_REPORT,FORECAST_REPORT_ACTIVE=.FALSE.
      LOGICAL(kind=1) :: ALLOCATION_REPORT, &
                         ALLOCATION_REPORT_ACTIVE=.FALSE.
      LOGICAL(kind=1) :: EXPANSION_REPORT, &
                         EXPANSION_REPORT_ACTIVE=.FALSE.
      LOGICAL(kind=1) :: DSM_FINANCIAL_REPORT, &
                                    DSM_FINANCIAL_REPORT_ACTIVE=.FALSE.
      INTEGER(kind=2) :: DISPATCH_RPT_MONTHS(12)
      LOGICAL(kind=1) :: DISPATCH_RPT_THIS_MONTH(12), &
                DISP_NEW_SUPPLY_THIS_MONTH(12)
      SAVE DISPATCH_RPT_THIS_MONTH,DISP_NEW_SUPPLY_THIS_MONTH
      INTEGER(kind=2) :: MO,ISO
      INTEGER(kind=2) :: VOID_INT2,SAVE_REPORTING_ASSET_CLASS_STR
      LOGICAL(kind=1) :: REPORT_THIS_DISPATCH_PERIOD, &
                         REPORT_NEW_SUPPLY_PERIOD
      INTEGER(kind=2) :: R_MO
      LOGICAL (KIND=1) :: SP_CAPEX_ACTIVE
!
         CALL OPEN_DETAILED_REPORT_FILE
!
         DETAILED_REPORTS_OBJECT = .TRUE.
      RETURN
      ENTRY RETURN_DET_RPTS_FOR_ASSETS
!         VOID_LOGICAL = DETAILED_REPORTS_OBJECT()
         CALL OPEN_DETAILED_REPORT_FILE
         READ(67,REC=1) DELETE,OPYEAR,FORECAST_REPORT_STR, &
         EXPANSION_REPORT_STR,DISPATCH_REPORT_STR, &
        ALLOCATION_REPORT_STR,ENRG_LIMIT_REPORT_STR,LOAD_PROB_PLOT_STR,&
         MONTHLY_UNIT_OUTPUT_REPORT,ANNUAL_UNIT_OUTPUT_REPORT_STR, &
         DSM_FINANCIAL_REPORT_STR,CSV_REPORT_ACTIVE, &
         KEPCO_REPORTS_ACTIVE,CONTRACT_REPORT_TYPE, &
         FUEL_USAGE_REPORT_ACTIVE,LM_DAYS_REPORT_ACTIVE, &
         WABASH_POWER_COST_REPORT_ACTIVE,MAINTENANCE_REPORT_ACTIVE, &
         SERVICE_REPORT_ACTIVE,ECONOMY_REPORT_ACTIVE, &
         LOLP_REPORT_ACTIVE,EXISTING_ASSETS_REPORT_ACTIVE, &
         FUTURE_ASSETS_REPORT_ACTIVE,NUCLEAR_FUEL_REPORT_ACTIVE, &
         DEBT_REPORT_ACTIVE,ASSET_CLASS_REPORTS_ACTIVE, &
         REPORTING_ASSET_CLASS_STR,TRANSACT_UNIT_REPORT_ACTIVE, &
         TRANSACT_HOURLY_REPORTS_ACTIVE,TRANSMISSION_REPORTS_ACTIVE, &
         TRANSACT_MONTHLY_REPORTS_ACTIVE,MARKET_DURATION_REPORT_ACTIVE,&
         FINANCIAL_DRILLING_ACTIVE,EXPENSE_REVENUES_ACTIVE, &
         TRANSACT_DAILY_REPORTS_ACTIVE,TF_CLASS_SUM_REPORTS_ACTIVE, &
         DEBIT_REPORT_ACTIVE,HOURLY_ECAP_REPORT_ACTIVE, &
         TRANSACT_FUEL_REPORT_ACTIVE,DYNAMIC_JURIS_ALLOC_ACTIVE, &
         MONTHLY_GROUP_REPORT_ACTIVE,HOURLY_PRICE_REPORT_ACTIVE, &
         SELECTED_DISPATCH_RPT_MONTHS,DISPATCH_RPT_TYPE_STR, &
         HOURLY_LOAD_BEFORE_HYDRO_STR,TRANS_HOURLY_DIAG_STR, &
         HYDRO_SALES_AS_NEGATIVE_STR,DEPTH_OF_MARKET_STR, &
         NUMBER_OF_INTERVALS,INTERVAL_SIZE,HOURLY_COMMITMENT_STR, &
         DAILY_COMMITMENT_STR,DEPTH_TARGET_GROUP,HOURLY_OUTAGE_STR, &
         DIAGNOSTIC_DAY_OF_MONTH,MARGINAL_UNIT_REPORT_STR, &
         WEEKLY_HYDRO_REPORT_STR,HOURLY_CAPACITY_REPORT_STR, &
         HOURLY_CAP_COST_REPORT_STR,HOURLY_DERIVATIVES_REPORT_STR, &
         HOURLY_AFTER_HYDRO_REPORT_STR,HOURLY_AFTER_TRANS_REPORT_STR, &
         FISCAL_YEAR_ACTIVE_STR,BEGIN_FISCAL_YEAR, &
         FLOW_ANALYST_REPORT_GROUP,  & !  65
         MARKET_MATCH_REPORT_GROUP,  & !  66
         RESERVED_REPORT_GROUP, & !  67
         RESERVED_REPORT_GROUP, & !  68
         RESERVED_REPORT_GROUP,  & !  69
         MONTHLY_DERIVATIVES_STR,NEW_UNITS_REPORT_STR, &
         DEPTH_MARKET_FILE_STR,WRITE_DAILY_PATHS_REPORTS_STR, &
         MONTHLY_FUEL_DERIV_REPORT_STR,MONTHLY_SCEN_MAKER_REPORT_STR, &
         TECH_SCAR_REPORT_STR,POWERWORLD_REPORT_STR, &
         LOAD_MARKET_AREAS_REPORT_STR,PORT_MARKET_AREAS_REPORT_STR, &
         MONTHLY_LOAD_N_RESOURCES_STR,HOURLY_JDA_REPORT_STR, &
         MONTHLY_TRANC_REPORT_STR,HOURLY_UNIT_FUEL_REPORT_STR, &
         HOURLY_TRANSACTION_REPORT_STR,IPL_FAC_REPORT_STR, &
         HOURLY_SPIN_REPORT_STR,HOURLY_CUST_MARGIN_REPORT_STR, &
         DAILY_DISPATCH_ORDER_REPORT_STR,TRANSACT_PROD_REPORT_STR, &
         TRANS_INTR_REPORT_STR,TRANS_TO_FROM_REPORT_STR, &
         MONTHLY_GAS_DEMAND_REPORT_STR,DAILY_GAS_DEMAND_REPORT_STR, &
         MONTHLY_GAS_SUPPLY_REPORT_STR,DAILY_GAS_SELL_BUY_REPORT_STR, &
         TRANSACT_MW_REPORT_STR,MONTHLY_GAS_SELL_BUY_STR, &
         MONTHLY_GAS_LINK_STR,NEW_SUPPLY_CURVE_STR, &
         SELECT_NEW_SUPPLY_RPT_MONTHS,MONTHLY_COAL_DEMAND_REPORT_STR, &
        MONTHLY_COAL_SUPPLY_REPORT_STR,CO2_ABATEMENT_REPORT_ACTIVE_STR,&
         GRX_8761_REPORT_STR,MARGINAL_UNIT_BY_TECH_STR, &
         DERIVATIVE_CUSTOMER_MARGINS_STR,DAILY_THERMAL_UNIT_REPORT_STR,&
         DATE_THERMAL_REPORT_BEGINS,DATE_THERMAL_REPORT_ENDS, &
         TEMP_REPORT_1_STR,TEMP_REPORT_2_STR,RPS_PROGRAMS_REPORT_STR, &
         OLD_RPS_PROGRAMS_REPORT_STR,RPS_CURVE_REPORT_STR, &
         HOURLY_GRX_STORAGE_REPORT_STR
         CLOSE(67)
         VOID_INT2 = SAVE_REPORTING_ASSET_CLASS_STR( &
                                              REPORTING_ASSET_CLASS_STR)
         VOID_CHR = SAVE_CHR_DETAILED_RPT_SWITCHES( &
                                        DISPATCH_RPT_TYPE_STR, &
                                        CONTRACT_REPORT_TYPE, &
                                        FINANCIAL_DRILLING_ACTIVE, &
                                        SERVICE_REPORT_ACTIVE, &
                                        CSV_REPORT_ACTIVE, &
                                        KEPCO_REPORTS_ACTIVE, &
                                        WABASH_POWER_COST_REPORT_ACTIVE)
         FORECAST_REPORT_ACTIVE = FORECAST_REPORT_STR == 'T'
         EXPANSION_REPORT_ACTIVE = EXPANSION_REPORT_STR == 'T'
         ALLOCATION_REPORT_ACTIVE = ALLOCATION_REPORT_STR == 'T'
         ENRG_LIMIT_REPORT_ACTIVE = ENRG_LIMIT_REPORT_STR == 'T'
         LOAD_PROB_PLOT_ACTIVE = LOAD_PROB_PLOT_STR == 'T'
         ANNUAL_UNIT_REPORT_ACTIVE = ANNUAL_UNIT_OUTPUT_REPORT_STR=='T'
         DSM_FINANCIAL_REPORT_ACTIVE = DSM_FINANCIAL_REPORT_STR == 'T'
!
         DISPATCH_REPORT_ACTIVE = DISPATCH_REPORT_STR(1:1) == 'A' .OR. &
                                   DISPATCH_REPORT_STR(1:1) == 'T'
         SEASONAL_DISPATCH_REPORT_ACTIVE = &
                                  DISPATCH_REPORT_STR(1:1) == 'S' .OR. &
                                  DISPATCH_REPORT_STR(1:1) == 'M'
         MARKET_MATCH_REPORTS_ACTIVE = MARKET_MATCH_REPORT_GROUP == 'T'
         FLOW_ANALYST_REPORTS_ACTIVE = FLOW_ANALYST_REPORT_GROUP == 'T'
!
         DISPATCH_RPT_THIS_MONTH = .FALSE.
!
         IF(SP_CAPEX_ACTIVE()) THEN
            DISPATCH_RPT_THIS_MONTH = .TRUE.
         ELSEIF(DISPATCH_REPORT_STR == 'Sp') THEN
            MONTHS_ARRAY = trim(SELECTED_DISPATCH_RPT_MONTHS)// &
                                  ',,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,'
            DISPATCH_RPT_MONTHS = 13
            READ(MONTHS_ARRAY,*,IOSTAT=IOS) DISPATCH_RPT_MONTHS
            IF(IOS == 0) THEN
               DO MO = 1, 12
                  IF(DISPATCH_RPT_MONTHS(MO) > 12 .OR. &
                                      DISPATCH_RPT_MONTHS (MO)< 1) CYCLE
                  DISPATCH_RPT_THIS_MONTH(DISPATCH_RPT_MONTHS(MO)) = &
                                                               .TRUE.
               ENDDO
            ENDIF
         ELSEIF(DISPATCH_REPORT_STR == 'Se') THEN
            DISPATCH_RPT_THIS_MONTH(1) = .TRUE.
            DISPATCH_RPT_THIS_MONTH(4) = .TRUE.
            DISPATCH_RPT_THIS_MONTH(7) = .TRUE.
            DISPATCH_RPT_THIS_MONTH(10) = .TRUE.
         ELSEIF(DISPATCH_REPORT_STR == 'Mo') THEN
            DISPATCH_RPT_THIS_MONTH = .TRUE.
         ENDIF

         DISP_NEW_SUPPLY_THIS_MONTH = .FALSE.
!
         IF(NEW_SUPPLY_CURVE_STR == 'Sp') THEN
            MONTHS_ARRAY = trim(SELECT_NEW_SUPPLY_RPT_MONTHS)// &
                                  ',,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,'
            DISPATCH_RPT_MONTHS = 13
            READ(MONTHS_ARRAY,*,IOSTAT=IOS) DISPATCH_RPT_MONTHS
            IF(IOS == 0) THEN
               DO MO = 1, 12
                  IF(DISPATCH_RPT_MONTHS(MO) > 12 .OR. &
                                      DISPATCH_RPT_MONTHS (MO)< 1) CYCLE
                 DISP_NEW_SUPPLY_THIS_MONTH(DISPATCH_RPT_MONTHS(MO)) = &
                                                               .TRUE.
               ENDDO
            ENDIF
         ELSEIF(NEW_SUPPLY_CURVE_STR == 'Se') THEN
            DISP_NEW_SUPPLY_THIS_MONTH(1) = .TRUE.
            DISP_NEW_SUPPLY_THIS_MONTH(4) = .TRUE.
            DISP_NEW_SUPPLY_THIS_MONTH(7) = .TRUE.
            DISP_NEW_SUPPLY_THIS_MONTH(10) = .TRUE.
         ELSEIF(NEW_SUPPLY_CURVE_STR == 'Mo' .OR. &
                                      NEW_SUPPLY_CURVE_STR == 'Tr') THEN
            DISP_NEW_SUPPLY_THIS_MONTH = .TRUE.
         ENDIF
!
         RETURN_DET_RPTS_FOR_ASSETS = .TRUE.
      RETURN
!
      ENTRY RETURN_DETAILED_REPORTS(YEAR)
!
         RETURN_DETAILED_REPORTS = .TRUE.


         ! needed to cover extension period Dr.G
         IREC = MIN(YEAR,AVAIL_DATA_YEARS) ! needed to cover extension period Dr.G
         READ(67,REC=IREC) DELETE,OPYEAR, &
          FORECAST_REPORT_STR,EXPANSION_REPORT_STR,DISPATCH_REPORT_STR,&
          ALLOCATION_REPORT_STR,ENRG_LIMIT_REPORT_STR, &
          LOAD_PROB_PLOT_STR,MONTHLY_UNIT_OUTPUT_REPORT, &
          ANNUAL_UNIT_OUTPUT_REPORT_STR,DSM_FINANCIAL_REPORT_STR, &
          CSV_REPORT_ACTIVE,KEPCO_REPORTS_ACTIVE,CONTRACT_REPORT_TYPE, &
          FUEL_USAGE_REPORT_ACTIVE,LM_DAYS_REPORT_ACTIVE, &
          WABASH_POWER_COST_REPORT_ACTIVE,MAINTENANCE_REPORT_ACTIVE, &
          SERVICE_REPORT_ACTIVE,ECONOMY_REPORT_ACTIVE, &
          LOLP_REPORT_ACTIVE,EXISTING_ASSETS_REPORT_ACTIVE, &
          FUTURE_ASSETS_REPORT_ACTIVE,NUCLEAR_FUEL_REPORT_ACTIVE, &
          DEBT_REPORT_ACTIVE,ASSET_CLASS_REPORTS_ACTIVE, &
          REPORTING_ASSET_CLASS_STR,TRANSACT_UNIT_REPORT_ACTIVE, &
          TRANSACT_HOURLY_REPORTS_ACTIVE,TRANSMISSION_REPORTS_ACTIVE, &
         TRANSACT_MONTHLY_REPORTS_ACTIVE,MARKET_DURATION_REPORT_ACTIVE,&
          FINANCIAL_DRILLING_ACTIVE,EXPENSE_REVENUES_ACTIVE, &
          TRANSACT_DAILY_REPORTS_ACTIVE,TF_CLASS_SUM_REPORTS_ACTIVE, &
          DEBIT_REPORT_ACTIVE,HOURLY_ECAP_REPORT_ACTIVE, &
          TRANSACT_FUEL_REPORT_ACTIVE,DYNAMIC_JURIS_ALLOC_ACTIVE, &
          MONTHLY_GROUP_REPORT_ACTIVE,HOURLY_PRICE_REPORT_ACTIVE, &
          SELECTED_DISPATCH_RPT_MONTHS,DISPATCH_RPT_TYPE_STR, &
          HOURLY_LOAD_BEFORE_HYDRO_STR,TRANS_HOURLY_DIAG_STR, &
          HYDRO_SALES_AS_NEGATIVE_STR,DEPTH_OF_MARKET_STR, &
          NUMBER_OF_INTERVALS,INTERVAL_SIZE,HOURLY_COMMITMENT_STR, &
          DAILY_COMMITMENT_STR,DEPTH_TARGET_GROUP,HOURLY_OUTAGE_STR, &
          DIAGNOSTIC_DAY_OF_MONTH,MARGINAL_UNIT_REPORT_STR, &
          WEEKLY_HYDRO_REPORT_STR,HOURLY_CAPACITY_REPORT_STR, &
          HOURLY_CAP_COST_REPORT_STR,HOURLY_DERIVATIVES_REPORT_STR, &
          HOURLY_AFTER_HYDRO_REPORT_STR,HOURLY_AFTER_TRANS_REPORT_STR, &
          FISCAL_YEAR_ACTIVE_STR,BEGIN_FISCAL_YEAR, &
          FLOW_ANALYST_REPORT_GROUP,  & !  65
          MARKET_MATCH_REPORT_GROUP,  & !  66
          RESERVED_REPORT_GROUP, & !  67
          RESERVED_REPORT_GROUP, & !  68
          RESERVED_REPORT_GROUP,  & !  69
          MONTHLY_DERIVATIVES_STR,NEW_UNITS_REPORT_STR, &
          DEPTH_MARKET_FILE_STR,WRITE_DAILY_PATHS_REPORTS_STR, &
          MONTHLY_FUEL_DERIV_REPORT_STR,MONTHLY_SCEN_MAKER_REPORT_STR, &
          TECH_SCAR_REPORT_STR,POWERWORLD_REPORT_STR, &
          LOAD_MARKET_AREAS_REPORT_STR,PORT_MARKET_AREAS_REPORT_STR, &
          MONTHLY_LOAD_N_RESOURCES_STR,HOURLY_JDA_REPORT_STR, &
          MONTHLY_TRANC_REPORT_STR,HOURLY_UNIT_FUEL_REPORT_STR, &
          HOURLY_TRANSACTION_REPORT_STR,IPL_FAC_REPORT_STR, &
          HOURLY_SPIN_REPORT_STR,HOURLY_CUST_MARGIN_REPORT_STR, &
          DAILY_DISPATCH_ORDER_REPORT_STR,TRANSACT_PROD_REPORT_STR, &
          TRANS_INTR_REPORT_STR,TRANS_TO_FROM_REPORT_STR, &
          MONTHLY_GAS_DEMAND_REPORT_STR,DAILY_GAS_DEMAND_REPORT_STR, &
          MONTHLY_GAS_SUPPLY_REPORT_STR,DAILY_GAS_SELL_BUY_REPORT_STR, &
          TRANSACT_MW_REPORT_STR,MONTHLY_GAS_SELL_BUY_STR, &
          MONTHLY_GAS_LINK_STR,NEW_SUPPLY_CURVE_STR, &
          SELECT_NEW_SUPPLY_RPT_MONTHS,MONTHLY_COAL_DEMAND_REPORT_STR, &
          MONTHLY_COAL_SUPPLY_REPORT_STR, &
          CO2_ABATEMENT_REPORT_ACTIVE_STR,GRX_8761_REPORT_STR, &
          MARGINAL_UNIT_BY_TECH_STR,DERIVATIVE_CUSTOMER_MARGINS_STR, &
          DAILY_THERMAL_UNIT_REPORT_STR, & !  107
          DATE_THERMAL_REPORT_BEGINS,DATE_THERMAL_REPORT_ENDS, &
          TEMP_REPORT_1_STR,TEMP_REPORT_2_STR, &
          RPS_PROGRAMS_REPORT_STR,OLD_RPS_PROGRAMS_REPORT_STR, &
          RPS_CURVE_REPORT_STR,HOURLY_GRX_STORAGE_REPORT_STR
!
         VOID_INT2 = SAVE_REPORTING_ASSET_CLASS_STR( &
                                              REPORTING_ASSET_CLASS_STR)
         VOID_CHR = SAVE_CHR_DETAILED_RPT_SWITCHES( &
                                        DISPATCH_RPT_TYPE_STR, &
                                        CONTRACT_REPORT_TYPE, &
                                        FINANCIAL_DRILLING_ACTIVE, &
                                        SERVICE_REPORT_ACTIVE, &
                                        CSV_REPORT_ACTIVE, &
                                        KEPCO_REPORTS_ACTIVE, &
                                        WABASH_POWER_COST_REPORT_ACTIVE)
         IF(MONTHLY_UNIT_OUTPUT_REPORT == 'T' .OR. &
                                 MONTHLY_UNIT_OUTPUT_REPORT == 'U') THEN
            UNIT_OUTPUT_REPORT_ACTIVE = .TRUE.
            MONTHLY_SUMMARY_REPORT_ACTIVE = .TRUE.
         ELSE
            UNIT_OUTPUT_REPORT_ACTIVE = .FALSE.
            MONTHLY_SUMMARY_REPORT_ACTIVE = .FALSE.
            IF(MONTHLY_UNIT_OUTPUT_REPORT == 'S') &
                                  MONTHLY_SUMMARY_REPORT_ACTIVE = .TRUE.
         ENDIF
!
         SPREAD_SHEET_ACTIVE = INDEX('YBU',CSV_REPORT_ACTIVE) /= 0
         FORECAST_REPORT_ACTIVE = FORECAST_REPORT_STR == 'T'
         EXPANSION_REPORT_ACTIVE = EXPANSION_REPORT_STR == 'T'
         ALLOCATION_REPORT_ACTIVE = ALLOCATION_REPORT_STR == 'T'
         ENRG_LIMIT_REPORT_ACTIVE = ENRG_LIMIT_REPORT_STR == 'T'
         LOAD_PROB_PLOT_ACTIVE = LOAD_PROB_PLOT_STR == 'T'
         ANNUAL_UNIT_REPORT_ACTIVE = ANNUAL_UNIT_OUTPUT_REPORT_STR=='T'
         DSM_FINANCIAL_REPORT_ACTIVE = DSM_FINANCIAL_REPORT_STR == 'T'
!
         DISPATCH_REPORT_ACTIVE = DISPATCH_REPORT_STR(1:1) == 'A' .OR. &
                                   DISPATCH_REPORT_STR(1:1) == 'T'
         SEASONAL_DISPATCH_REPORT_ACTIVE = &
                                  DISPATCH_REPORT_STR(1:1) == 'S' .OR. &
                                  DISPATCH_REPORT_STR(1:1) == 'M'
         DISPATCH_RPT_THIS_MONTH = .FALSE.
         IF(SP_CAPEX_ACTIVE()) THEN
            DISPATCH_RPT_THIS_MONTH = .TRUE.
         ELSEIF(DISPATCH_REPORT_STR == 'Sp') THEN
            MONTHS_ARRAY = trim(SELECTED_DISPATCH_RPT_MONTHS)// &
                                  ',,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,'
            DISPATCH_RPT_MONTHS = 13
            READ(MONTHS_ARRAY,*,IOSTAT=IOS) DISPATCH_RPT_MONTHS
            IF(IOS == 0) THEN
               DO MO = 1, 12
                  IF(DISPATCH_RPT_MONTHS(MO) > 12 .OR. &
                                    DISPATCH_RPT_MONTHS(MO) < 1) CYCLE
                  DISPATCH_RPT_THIS_MONTH(DISPATCH_RPT_MONTHS(MO)) = &
                                                               .TRUE.
               ENDDO
            ENDIF
         ELSEIF(DISPATCH_REPORT_STR == 'Se') THEN
            DISPATCH_RPT_THIS_MONTH(1) = .TRUE.
            DISPATCH_RPT_THIS_MONTH(4) = .TRUE.
            DISPATCH_RPT_THIS_MONTH(7) = .TRUE.
            DISPATCH_RPT_THIS_MONTH(10) = .TRUE.
         ELSEIF(DISPATCH_REPORT_STR == 'Mo') THEN
            DISPATCH_RPT_THIS_MONTH = .TRUE.
         ENDIF
!
         DISP_NEW_SUPPLY_THIS_MONTH = .FALSE.
!
         IF(NEW_SUPPLY_CURVE_STR == 'Sp') THEN
            MONTHS_ARRAY = trim(SELECT_NEW_SUPPLY_RPT_MONTHS)// &
                                  ',,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,'
            DISPATCH_RPT_MONTHS = 13
            READ(MONTHS_ARRAY,*,IOSTAT=IOS) DISPATCH_RPT_MONTHS
            IF(IOS == 0) THEN
               DO MO = 1, 12
                  IF(DISPATCH_RPT_MONTHS(MO) > 12 .OR. &
                                    DISPATCH_RPT_MONTHS (MO)< 1) CYCLE
                  DISP_NEW_SUPPLY_THIS_MONTH(DISPATCH_RPT_MONTHS(MO)) = &
                                                               .TRUE.
               ENDDO
            ENDIF
         ELSEIF(NEW_SUPPLY_CURVE_STR == 'Se') THEN
            DISP_NEW_SUPPLY_THIS_MONTH(1) = .TRUE.
            DISP_NEW_SUPPLY_THIS_MONTH(4) = .TRUE.
            DISP_NEW_SUPPLY_THIS_MONTH(7) = .TRUE.
            DISP_NEW_SUPPLY_THIS_MONTH(10) = .TRUE.
         ELSEIF(NEW_SUPPLY_CURVE_STR == 'Mo' .OR. &
                                      NEW_SUPPLY_CURVE_STR == 'Tr') THEN
            DISP_NEW_SUPPLY_THIS_MONTH = .TRUE.
         ENDIF
!
      RETURN
! ***********************************************************************
      ENTRY TRANSACT_UNIT_MONTHLY_REPORT
! ***********************************************************************
         TRANSACT_UNIT_MONTHLY_REPORT = &
                                      TRANSACT_UNIT_REPORT_ACTIVE == 'M'
      RETURN
! ***********************************************************************
      ENTRY TRANSACT_UNIT_ANNUAL_REPORT
! ***********************************************************************
         TRANSACT_UNIT_ANNUAL_REPORT = &
                               TRANSACT_UNIT_REPORT_ACTIVE == 'M' .OR. &
                               TRANSACT_UNIT_REPORT_ACTIVE == 'A'
      RETURN
! ***********************************************************************
      ENTRY TRANSACT_HOURLY_REPORTS
! ***********************************************************************
       TRANSACT_HOURLY_REPORTS = TRANSACT_HOURLY_REPORTS_ACTIVE == 'T' &
                                      .OR. MARKET_MATCH_REPORTS_ACTIVE &
                                      .OR. FLOW_ANALYST_REPORTS_ACTIVE
      RETURN
! ***********************************************************************
      ENTRY TRANSACT_MONTHLY_REPORTS
! ***********************************************************************
         TRANSACT_MONTHLY_REPORTS = &
                                  TRANSACT_MONTHLY_REPORTS_ACTIVE == 'T'
      RETURN
! ***********************************************************************
      ENTRY MARKET_DURATION_REPORT ! 2/11/98. GAT.
! ***********************************************************************
         MARKET_DURATION_REPORT = MARKET_DURATION_REPORT_ACTIVE == 'T'
      RETURN
! ***********************************************************************
      ENTRY TRANS_TRANSMISSION_REPORTS
! ***********************************************************************
         TRANS_TRANSMISSION_REPORTS = TRANSMISSION_REPORTS_ACTIVE == 'T'
      RETURN
! ***********************************************************************
      ENTRY FORECAST_REPORT
! ***********************************************************************
         FORECAST_REPORT = FORECAST_REPORT_ACTIVE
      RETURN
! ***********************************************************************
      ENTRY ALLOCATION_REPORT
! ***********************************************************************
         ALLOCATION_REPORT = ALLOCATION_REPORT_ACTIVE
      RETURN
! ***********************************************************************
      ENTRY EXPANSION_REPORT
! ***********************************************************************
         EXPANSION_REPORT = EXPANSION_REPORT_ACTIVE
      RETURN
! ***********************************************************************
      ENTRY DSM_FINANCIAL_REPORT
! ***********************************************************************
         DSM_FINANCIAL_REPORT = DSM_FINANCIAL_REPORT_ACTIVE
      RETURN
! ***********************************************************************
      ENTRY DISPATCH_REPORT
! ***********************************************************************
         DISPATCH_REPORT = DISPATCH_REPORT_ACTIVE
      RETURN
! ***********************************************************************
      ENTRY SEASONAL_DISPATCH_REPORT
! ***********************************************************************
         SEASONAL_DISPATCH_REPORT = SEASONAL_DISPATCH_REPORT_ACTIVE
      RETURN
! ***********************************************************************
      ENTRY REPORT_THIS_DISPATCH_PERIOD(R_MO)
! ***********************************************************************
         REPORT_THIS_DISPATCH_PERIOD = DISPATCH_RPT_THIS_MONTH(R_MO)
      RETURN
! ***********************************************************************
      ENTRY REPORT_NEW_SUPPLY_PERIOD(R_MO)
! ***********************************************************************
         REPORT_NEW_SUPPLY_PERIOD = DISP_NEW_SUPPLY_THIS_MONTH(R_MO)
      RETURN
! ***********************************************************************
      ENTRY HOURLY_LOAD_BEFORE_HYDRO
! ***********************************************************************
        HOURLY_LOAD_BEFORE_HYDRO = HOURLY_LOAD_BEFORE_HYDRO_STR == 'T' &
                                       .OR. MARKET_MATCH_REPORTS_ACTIVE
      RETURN
! ***********************************************************************
      ENTRY TRANS_HOURLY_DIAG
! ***********************************************************************
         TRANS_HOURLY_DIAG = TRANS_HOURLY_DIAG_STR == 'T'
      RETURN
! ***********************************************************************
      ENTRY HYDRO_SALES_AS_NEGATIVE
! ***********************************************************************
         HYDRO_SALES_AS_NEGATIVE = HYDRO_SALES_AS_NEGATIVE_STR == 'T'
      RETURN
! ***********************************************************************
      ENTRY DEPTH_OF_MARKET(R_NUMBER_OF_INTERVALS,R_INTERVAL_SIZE, &
                              R_DEPTH_TARGET_GROUP)
! ***********************************************************************
         DEPTH_OF_MARKET = DEPTH_OF_MARKET_STR == 'T'
         R_NUMBER_OF_INTERVALS = NUMBER_OF_INTERVALS
         R_INTERVAL_SIZE = INTERVAL_SIZE
         R_DEPTH_TARGET_GROUP = DEPTH_TARGET_GROUP
      RETURN
! ***********************************************************************
      ENTRY GET_DIAGNOSTIC_DAY_OF_MONTH
! ***********************************************************************
         GET_DIAGNOSTIC_DAY_OF_MONTH = DIAGNOSTIC_DAY_OF_MONTH
      RETURN
! ***********************************************************************
      ENTRY HOURLY_COMMITMENT
! ***********************************************************************
         HOURLY_COMMITMENT = HOURLY_COMMITMENT_STR == 'T'
      RETURN
! ***********************************************************************
      ENTRY DAILY_COMMITMENT
! ***********************************************************************
         DAILY_COMMITMENT = DAILY_COMMITMENT_STR == 'T'
      RETURN
! ***********************************************************************
      ENTRY HOURLY_OUTAGE
! ***********************************************************************
         HOURLY_OUTAGE = HOURLY_OUTAGE_STR == 'T'
      RETURN
! ***********************************************************************
      ENTRY WEEKLY_HYDRO_REPORT
! ***********************************************************************
         WEEKLY_HYDRO_REPORT = WEEKLY_HYDRO_REPORT_STR == 'T'
      RETURN
! ***********************************************************************
      ENTRY MARGINAL_UNIT_REPORT
! ***********************************************************************
         MARGINAL_UNIT_REPORT = MARGINAL_UNIT_REPORT_STR == 'T'
      RETURN
! ***********************************************************************
      ENTRY IS_FISCAL_YEAR_ACTIVE( &
                                 R_BEGIN_FISCAL_YEAR,R_ONLY_FISCAL_YEAR)
! ***********************************************************************
         R_BEGIN_FISCAL_YEAR = BEGIN_FISCAL_YEAR
         R_ONLY_FISCAL_YEAR =    FISCAL_YEAR_ACTIVE_STR == 'O'
         IS_FISCAL_YEAR_ACTIVE = FISCAL_YEAR_ACTIVE_STR /= 'F'
      RETURN
! ***********************************************************************
      ENTRY MONTHLY_DERIVATIVES_ACTIVE
! ***********************************************************************
         MONTHLY_DERIVATIVES_ACTIVE =  MONTHLY_DERIVATIVES_STR /= 'F'
      RETURN
! ***********************************************************************
      ENTRY SUPPRESS_DERIVATIVES_ACTIVE
! ***********************************************************************
         SUPPRESS_DERIVATIVES_ACTIVE =  MONTHLY_DERIVATIVES_STR == 'S'
      RETURN
! ***********************************************************************
      ENTRY NEW_UNITS_REPORT_ACTIVE
! ***********************************************************************
         NEW_UNITS_REPORT_ACTIVE =  NEW_UNITS_REPORT_STR /= 'F'
      RETURN
! ***********************************************************************
      ENTRY YES_WRITE_DAILY_PATHS_REPORTS
! ***********************************************************************
         YES_WRITE_DAILY_PATHS_REPORTS = &
                           WRITE_DAILY_PATHS_REPORTS_STR /= 'F'
       RETURN
! ***********************************************************************
      ENTRY YES_MONTHLY_FUEL_DERIV_REPORT
! ***********************************************************************
         YES_MONTHLY_FUEL_DERIV_REPORT = &
                                    MONTHLY_FUEL_DERIV_REPORT_STR /= 'F'
      RETURN
! ***********************************************************************
      ENTRY YES_MONTHLY_SCEN_MAKER_REPORT
! ***********************************************************************
         YES_MONTHLY_SCEN_MAKER_REPORT = &
                                    MONTHLY_SCEN_MAKER_REPORT_STR /= 'F'
      RETURN
! ***********************************************************************
      ENTRY YES_LOAD_MARKET_AREAS_REPORT
! ***********************************************************************
         YES_LOAD_MARKET_AREAS_REPORT = &
                                     LOAD_MARKET_AREAS_REPORT_STR /= 'F'
      RETURN
! ***********************************************************************
      ENTRY YES_USE_MARKET_AREA_REPORT_ID
! ***********************************************************************
         YES_USE_MARKET_AREA_REPORT_ID = &
                                     LOAD_MARKET_AREAS_REPORT_STR == 'I'
      RETURN
! ***********************************************************************
      ENTRY HOURLY_SPIN_REPORT
! ***********************************************************************
         HOURLY_SPIN_REPORT =    HOURLY_SPIN_REPORT_STR == 'T'
      RETURN
! ***********************************************************************
      ENTRY TRANSACT_PROD_REPORT
! ***********************************************************************
         TRANSACT_PROD_REPORT =  TRANSACT_PROD_REPORT_STR == 'T'
      RETURN
! ***********************************************************************
      ENTRY TRANS_INTR_REPORT
! ***********************************************************************
         TRANS_INTR_REPORT =  TRANS_INTR_REPORT_STR == 'T'
      RETURN
! ***********************************************************************
      ENTRY MONTHLY_GAS_DEMAND_REPORT
! ***********************************************************************
          MONTHLY_GAS_DEMAND_REPORT = &
                                    MONTHLY_GAS_DEMAND_REPORT_STR == 'T'
      RETURN
! ***********************************************************************
      ENTRY MONTHLY_COAL_DEMAND_REPORT
! ***********************************************************************
          MONTHLY_COAL_DEMAND_REPORT = &
                                   MONTHLY_COAL_DEMAND_REPORT_STR == 'T'
      RETURN
! ***********************************************************************
      ENTRY DAILY_GAS_DEMAND_REPORT
! ***********************************************************************
          DAILY_GAS_DEMAND_REPORT = &
                                    DAILY_GAS_DEMAND_REPORT_STR == 'T'
      RETURN
! ***********************************************************************
      ENTRY DAILY_GAS_SELL_BUY_REPORT
! ***********************************************************************
         DAILY_GAS_SELL_BUY_REPORT = &
                                    DAILY_GAS_SELL_BUY_REPORT_STR == 'T'
      RETURN
! ***********************************************************************
      ENTRY MONTHLY_GAS_SELL_BUY_REPORT
! ***********************************************************************
         MONTHLY_GAS_SELL_BUY_REPORT =   MONTHLY_GAS_SELL_BUY_STR == 'T'
      RETURN
! ***********************************************************************
      ENTRY MONTHLY_GAS_LINK_REPORT
! ***********************************************************************
         MONTHLY_GAS_LINK_REPORT =       MONTHLY_GAS_LINK_STR == 'T'
      RETURN
! ***********************************************************************
      ENTRY NEW_SUPPLY_CURVE_REPORT
! ***********************************************************************
         NEW_SUPPLY_CURVE_REPORT =      NEW_SUPPLY_CURVE_STR(1:1) /= 'F'
      RETURN
! ***********************************************************************
      ENTRY TRANSACT_MW_REPORT
! ***********************************************************************
         TRANSACT_MW_REPORT = TRANSACT_MW_REPORT_STR == 'T'
      RETURN
! ***********************************************************************
      ENTRY MONTHLY_GAS_SUPPLY_REPORT
! ***********************************************************************
         MONTHLY_GAS_SUPPLY_REPORT = &
                                    MONTHLY_GAS_SUPPLY_REPORT_STR == 'T'
      RETURN
! ***********************************************************************
      ENTRY YES_RPS_PROGRAMS_REPORT
! ***********************************************************************
         YES_RPS_PROGRAMS_REPORT = RPS_PROGRAMS_REPORT_STR == 'T'
      RETURN
! ***********************************************************************
      ENTRY YES_HOURLY_GRX_STORAGE_REPORT
! ***********************************************************************
         YES_HOURLY_GRX_STORAGE_REPORT = &
                     HOURLY_GRX_STORAGE_REPORT_STR == 'T'
      RETURN
! ***********************************************************************
      ENTRY YES_RPS_CURVE_REPORT
! ***********************************************************************
         YES_RPS_CURVE_REPORT = RPS_CURVE_REPORT_STR == 'T'
      RETURN
! ***********************************************************************
      ENTRY YES_OLD_RPS_PROGRAMS_REPORT
! ***********************************************************************
         YES_OLD_RPS_PROGRAMS_REPORT = &
                                      OLD_RPS_PROGRAMS_REPORT_STR == 'T'
      RETURN
! ***********************************************************************
      ENTRY YES_REPORT_DAILY_PRIME_MOVER
! ***********************************************************************
         YES_REPORT_DAILY_PRIME_MOVER = &
                            DAILY_THERMAL_UNIT_REPORT_STR == 'T' .OR. &
                            DAILY_THERMAL_UNIT_REPORT_STR == 'P'
      RETURN
! ***********************************************************************
      ENTRY YES_REPORT_DAILY_THERMAL
! ***********************************************************************
         YES_REPORT_DAILY_THERMAL = &
                            DAILY_THERMAL_UNIT_REPORT_STR == 'T' .OR. &
                            DAILY_THERMAL_UNIT_REPORT_STR == 'U'
      RETURN
! ***********************************************************************
      ENTRY DAILY_THERMAL_REPORT_ACTIVE(R_START_DATE,R_STOP_DATE)
! ***********************************************************************
         DAILY_THERMAL_REPORT_ACTIVE = &
                            DAILY_THERMAL_UNIT_REPORT_STR /= 'F'
         R_START_DATE = DATE_THERMAL_REPORT_BEGINS
         R_STOP_DATE = DATE_THERMAL_REPORT_ENDS
      RETURN
! ***********************************************************************
      ENTRY MARGINAL_UNIT_BY_TECH_ACTIVE
! ***********************************************************************
         MARGINAL_UNIT_BY_TECH_ACTIVE = &
                                        MARGINAL_UNIT_BY_TECH_STR == 'T'
      RETURN
! ***********************************************************************
      ENTRY GRX_8761_REPORT_ACTIVE
! ***********************************************************************
         GRX_8761_REPORT_ACTIVE =  GRX_8761_REPORT_STR == 'T'
      RETURN
! ***********************************************************************
      ENTRY CO2_ABATEMENT_REPORT_ACTIVE
! ***********************************************************************
         CO2_ABATEMENT_REPORT_ACTIVE = &
                                  CO2_ABATEMENT_REPORT_ACTIVE_STR == 'T'
      RETURN
! ***********************************************************************
      ENTRY MONTHLY_COAL_SUPPLY_REPORT
! ***********************************************************************
         MONTHLY_COAL_SUPPLY_REPORT = &
                                   MONTHLY_COAL_SUPPLY_REPORT_STR == 'T'
      RETURN
! ***********************************************************************
      ENTRY TRANS_TO_FROM_REPORT
! ***********************************************************************
          TRANS_TO_FROM_REPORT =  TRANS_TO_FROM_REPORT_STR == 'T'
      RETURN
! ***********************************************************************
      ENTRY DAILY_DISPATCH_ORDER_REPORT
! ***********************************************************************
         DAILY_DISPATCH_ORDER_REPORT = &
                                  DAILY_DISPATCH_ORDER_REPORT_STR == 'T'
      RETURN
! ***********************************************************************
      ENTRY HOURLY_CUST_MARGIN_REPORT
! ***********************************************************************
         HOURLY_CUST_MARGIN_REPORT = &
                                    HOURLY_CUST_MARGIN_REPORT_STR == 'T'
      RETURN
! ***********************************************************************
      ENTRY YES_IPL_FAC_REPORT
! ***********************************************************************
         YES_IPL_FAC_REPORT =  IPL_FAC_REPORT_STR == 'T'
      RETURN
! ***********************************************************************
      ENTRY YES_MONTHLY_LOAD_N_RESOURCES
! ***********************************************************************
         YES_MONTHLY_LOAD_N_RESOURCES = &
                                     MONTHLY_LOAD_N_RESOURCES_STR /= 'F'
      RETURN
! ***********************************************************************
      ENTRY GET_ALLOC_COSTS_BY_UNIT
! ***********************************************************************
         GET_ALLOC_COSTS_BY_UNIT = &
                                     MONTHLY_LOAD_N_RESOURCES_STR == 'U'
      RETURN
! ***********************************************************************
      ENTRY YES_HOURLY_JDA_REPORT
! ***********************************************************************
         YES_HOURLY_JDA_REPORT = HOURLY_JDA_REPORT_STR /= 'F'
      RETURN
! ***********************************************************************
      ENTRY YES_HOURLY_TRANSACTION_REPORT
! ***********************************************************************
         YES_HOURLY_TRANSACTION_REPORT = &
                                    HOURLY_TRANSACTION_REPORT_STR /= 'F'
      RETURN
! ***********************************************************************
      ENTRY YES_HOURLY_UNIT_FUEL_REPORT
! ***********************************************************************
         YES_HOURLY_UNIT_FUEL_REPORT = &
                                      HOURLY_UNIT_FUEL_REPORT_STR /= 'F'
      RETURN
! ***********************************************************************
      ENTRY YES_MONTHLY_TRANC_REPORT
! ***********************************************************************
         YES_MONTHLY_TRANC_REPORT = MONTHLY_TRANC_REPORT_STR /= 'F'
      RETURN
! ***********************************************************************
      ENTRY YES_PORT_MARKET_AREAS_REPORT
! ***********************************************************************
         YES_PORT_MARKET_AREAS_REPORT = &
                                     PORT_MARKET_AREAS_REPORT_STR /= 'F'
      RETURN
! ***********************************************************************
      ENTRY YES_POWERWORLD_REPORT
! ***********************************************************************
         YES_POWERWORLD_REPORT = POWERWORLD_REPORT_STR == 'T'
      RETURN
! ***********************************************************************
      ENTRY YES_REFERENCE_CASE_REPORT
! ***********************************************************************
         YES_REFERENCE_CASE_REPORT =  POWERWORLD_REPORT_STR == 'R'
      RETURN
! ***********************************************************************
      ENTRY YES_POWERWORLD_NEW_REPORT
! ***********************************************************************
         YES_POWERWORLD_NEW_REPORT = POWERWORLD_REPORT_STR == 'N'
      RETURN
! ***********************************************************************
      ENTRY YES_TECH_SCAR_REPORT
! ***********************************************************************
         YES_TECH_SCAR_REPORT = TECH_SCAR_REPORT_STR /= 'F'
      RETURN
! ***********************************************************************
      ENTRY DEPTH_MARKET_REPORTS_ACTIVE(R_DEPTH_MARKET_FILE_STR)
! ***********************************************************************
         R_DEPTH_MARKET_FILE_STR = DEPTH_MARKET_FILE_STR
         DEPTH_MARKET_REPORTS_ACTIVE = .TRUE.
      RETURN
! ***********************************************************************
      ENTRY HOURLY_AFTER_TRANS_REPORT
! ***********************************************************************
         HOURLY_AFTER_TRANS_REPORT = &
                                    HOURLY_AFTER_TRANS_REPORT_STR == 'T'
      RETURN
! ***********************************************************************
      ENTRY HOURLY_AFTER_HYDRO_REPORT
! ***********************************************************************
         HOURLY_AFTER_HYDRO_REPORT = &
                                  HOURLY_AFTER_HYDRO_REPORT_STR == 'T' &
                                        .OR. MARKET_MATCH_REPORTS_ACTIVE
      RETURN
! ***********************************************************************
      ENTRY HOURLY_DERIVATIVES_REPORT
! ***********************************************************************
         HOURLY_DERIVATIVES_REPORT = &
                                    HOURLY_DERIVATIVES_REPORT_STR == 'T'
      RETURN
! ***********************************************************************
      ENTRY HOURLY_CAPACITY_REPORT
! ***********************************************************************
         HOURLY_CAPACITY_REPORT = HOURLY_CAPACITY_REPORT_STR == 'T' &
                                        .OR. MARKET_MATCH_REPORTS_ACTIVE
      RETURN
! ***********************************************************************
      ENTRY HOURLY_CAPACITY_COST_REPORT
! ***********************************************************************
         HOURLY_CAPACITY_COST_REPORT = HOURLY_CAP_COST_REPORT_STR == 'T'
      RETURN
! ***********************************************************************
      ENTRY ENRG_LIMIT_REPORT
! ***********************************************************************
         ENRG_LIMIT_REPORT = ENRG_LIMIT_REPORT_ACTIVE .AND. &
                                        HYDRO_FILES_ARE_ACTIVE() == 'T'
      RETURN
! ***********************************************************************
      ENTRY LOAD_PROB_PLOT
! ***********************************************************************
         LOAD_PROB_PLOT = LOAD_PROB_PLOT_ACTIVE
      RETURN
! ***********************************************************************
      ENTRY UNIT_OUTPUT_REPORT
! ***********************************************************************
         UNIT_OUTPUT_REPORT = UNIT_OUTPUT_REPORT_ACTIVE
      RETURN
! ***********************************************************************
      ENTRY MONTHLY_SUMMARY_REPORT
! ***********************************************************************
         MONTHLY_SUMMARY_REPORT = MONTHLY_SUMMARY_REPORT_ACTIVE
      RETURN
! ***********************************************************************
      ENTRY ANNUAL_UNIT_OUTPUT_REPORT
! ***********************************************************************
         ANNUAL_UNIT_OUTPUT_REPORT = ANNUAL_UNIT_REPORT_ACTIVE
      RETURN
! ***********************************************************************
      ENTRY FUEL_USAGE_REPORT
! ***********************************************************************
         FUEL_USAGE_REPORT = FUEL_USAGE_REPORT_ACTIVE == 'T'
      RETURN
! ***********************************************************************
      ENTRY MAINTENANCE_REPORT
! ***********************************************************************
         MAINTENANCE_REPORT = MAINTENANCE_REPORT_ACTIVE == 'T'
      RETURN
      ENTRY ECONOMY_REPORT
         ECONOMY_REPORT = ECONOMY_REPORT_ACTIVE == 'T'
      RETURN
      ENTRY LOLP_REPORT
         LOLP_REPORT = INDEX('YT',LOLP_REPORT_ACTIVE) /= 0
      RETURN
      ENTRY EXISTING_ASSETS_REPORT(R_REPORT_ALL_ACCOUNTS)
       EXISTING_ASSETS_REPORT = EXISTING_ASSETS_REPORT_ACTIVE=='T'.OR. &
                             EXISTING_ASSETS_REPORT_ACTIVE == 'M' .OR. &
                             EXISTING_ASSETS_REPORT_ACTIVE == 'A'
       R_REPORT_ALL_ACCOUNTS=EXISTING_ASSETS_REPORT_ACTIVE == 'A' .OR. &
                             EXISTING_ASSETS_REPORT_ACTIVE == 'T'
      RETURN
      ENTRY FUTURE_ASSETS_REPORT(R_REPORT_ALL_ACCOUNTS)
       FUTURE_ASSETS_REPORT = FUTURE_ASSETS_REPORT_ACTIVE == 'T' .OR. &
                              FUTURE_ASSETS_REPORT_ACTIVE == 'M' .OR. &
                              FUTURE_ASSETS_REPORT_ACTIVE == 'A'
       R_REPORT_ALL_ACCOUNTS = FUTURE_ASSETS_REPORT_ACTIVE == 'A' .OR. &
                               FUTURE_ASSETS_REPORT_ACTIVE == 'T'
      RETURN
      ENTRY NUCLEAR_FUEL_REPORT(R_REPORT_ALL_ACCOUNTS)
        NUCLEAR_FUEL_REPORT = NUCLEAR_FUEL_REPORT_ACTIVE == 'T' .OR. &
                               NUCLEAR_FUEL_REPORT_ACTIVE == 'M' .OR. &
                               NUCLEAR_FUEL_REPORT_ACTIVE == 'A'
        R_REPORT_ALL_ACCOUNTS = NUCLEAR_FUEL_REPORT_ACTIVE == 'A' .OR. &
                               NUCLEAR_FUEL_REPORT_ACTIVE == 'T'
      RETURN
      ENTRY DEBT_REPORT(R_REPORT_ALL_ACCOUNTS)
         DEBT_REPORT = DEBT_REPORT_ACTIVE == 'T' .OR. &
                       DEBT_REPORT_ACTIVE == 'M' .OR. &
                       DEBT_REPORT_ACTIVE == 'A'
         R_REPORT_ALL_ACCOUNTS = DEBT_REPORT_ACTIVE == 'A' .OR. &
                                 DEBT_REPORT_ACTIVE == 'T'
      RETURN
      ENTRY MODEL_ISSUED_DEBT_REPORT()
         MODEL_ISSUED_DEBT_REPORT = DEBT_REPORT_ACTIVE == 'T' .OR. &
                                    DEBT_REPORT_ACTIVE == 'M' .OR. &
                                    DEBT_REPORT_ACTIVE == 'A'
      RETURN
      ENTRY DEBIT_REPORT(R_REPORT_ALL_ACCOUNTS)
         DEBIT_REPORT = DEBIT_REPORT_ACTIVE == 'M' .OR. &
                        DEBIT_REPORT_ACTIVE == 'A'
         R_REPORT_ALL_ACCOUNTS = DEBIT_REPORT_ACTIVE == 'A' .OR. &
                                 DEBIT_REPORT_ACTIVE == 'T'
      RETURN
      ENTRY EXPENSE_REVENUES_REPORT(R_REPORT_ALL_ACCOUNTS)
         EXPENSE_REVENUES_REPORT = EXPENSE_REVENUES_ACTIVE == 'A' .OR. &
                                   EXPENSE_REVENUES_ACTIVE == 'M'
         R_REPORT_ALL_ACCOUNTS = EXPENSE_REVENUES_ACTIVE == 'A'
      RETURN
      ENTRY ASSET_CLASS_REPORTS
         ASSET_CLASS_REPORTS = ASSET_CLASS_REPORTS_ACTIVE == 'T'
      RETURN
      ENTRY TRANSACT_DAILY_REPORTS
         TRANSACT_DAILY_REPORTS = TRANSACT_DAILY_REPORTS_ACTIVE == 'T'
      RETURN
      ENTRY TF_CLASS_SUMMARY_REPORTS
         TF_CLASS_SUMMARY_REPORTS = TF_CLASS_SUM_REPORTS_ACTIVE == 'T'
      RETURN
      ENTRY LM_DAYS_REPORT
         LM_DAYS_REPORT = LM_DAYS_REPORT_ACTIVE == 'T'
      RETURN
      ENTRY SPREAD_SHEET
         SPREAD_SHEET = SPREAD_SHEET_ACTIVE
      RETURN
      ENTRY HOURLY_ECAP_REPORT
         HOURLY_ECAP_REPORT = HOURLY_ECAP_REPORT_ACTIVE == 'T'
      RETURN
      ENTRY DYNAMIC_JURIS_ALLOC
         DYNAMIC_JURIS_ALLOC = DYNAMIC_JURIS_ALLOC_ACTIVE== 'T'
      RETURN
      ENTRY MONTHLY_GROUP_REPORT
         MONTHLY_GROUP_REPORT = MONTHLY_GROUP_REPORT_ACTIVE == 'T'
      RETURN
      ENTRY HOURLY_PRICE_REPORT
         HOURLY_PRICE_REPORT = HOURLY_PRICE_REPORT_ACTIVE == 'T' &
                                      .OR. MARKET_MATCH_REPORTS_ACTIVE &
                                      .OR. FLOW_ANALYST_REPORTS_ACTIVE
      RETURN
      ENTRY TRANSACT_FUEL_REPORT
         TRANSACT_FUEL_REPORT = TRANSACT_FUEL_REPORT_ACTIVE == 'T'
      RETURN
      ENTRY CLOSE_DETAILED_REPORTS_FILE
         CLOSE(67)
         CLOSE_DETAILED_REPORTS_FILE = .TRUE.
      RETURN
      END
! ***********************************************************************
      FUNCTION SAVE_CHR_DETAILED_RPT_SWITCHES(R_DISPATCH_RPT_TYPE_STR, &
                                         R_CONTRACT_REPORT_TYPE, &
                                         R_FINANCIAL_DRILLING_ACTIVE, &
                                         R_SERVICE_REPORT_ACTIVE, &
                                         R_CSV_REPORT_ACTIVE, &
                                         R_KEPCO_REPORTS_ACTIVE, &
                                         R_WABASH_POWER_COST_RPT_ACTIVE)
! ***********************************************************************
!
      USE prod_arrays_dimensions
      use spindriftlib
      CHARACTER(len=1) :: DISPATCH_RPT_TYPE,DISPATCH_RPT_TYPE_STR, &
                  CONTRACT_REPORT,CONTRACT_REPORT_TYPE, &
                  FINANCIAL_DRILLING,FINANCIAL_DRILLING_ACTIVE, &
                  R_DISPATCH_RPT_TYPE_STR, &
                  R_CONTRACT_REPORT_TYPE, &
                  R_FINANCIAL_DRILLING_ACTIVE, &
                  SAVE_CHR_DETAILED_RPT_SWITCHES, &
                  SERVICE_REPORT,SERVICE_REPORT_ACTIVE, &
                  R_SERVICE_REPORT_ACTIVE, &
                  CSV_REPORT,CSV_REPORT_ACTIVE,R_CSV_REPORT_ACTIVE, &
                  KEPCO_REPORTS,KEPCO_REPORTS_ACTIVE, &
                WABASH_POWER_COST_RPT,WABASH_POWER_COST_REPORT_ACTIVE, &
                  R_KEPCO_REPORTS_ACTIVE, &
                  R_WABASH_POWER_COST_RPT_ACTIVE
      LOGICAL (KIND=1) :: SP_CAPEX_ACTIVE
      SAVE DISPATCH_RPT_TYPE_STR,CONTRACT_REPORT_TYPE, &
           FINANCIAL_DRILLING_ACTIVE,SERVICE_REPORT_ACTIVE, &
           WABASH_POWER_COST_REPORT_ACTIVE,KEPCO_REPORTS_ACTIVE
!
         DISPATCH_RPT_TYPE_STR = R_DISPATCH_RPT_TYPE_STR
         CONTRACT_REPORT_TYPE = R_CONTRACT_REPORT_TYPE
         FINANCIAL_DRILLING_ACTIVE = R_FINANCIAL_DRILLING_ACTIVE
         SERVICE_REPORT_ACTIVE = R_SERVICE_REPORT_ACTIVE
         CSV_REPORT_ACTIVE = R_CSV_REPORT_ACTIVE
         KEPCO_REPORTS_ACTIVE = R_KEPCO_REPORTS_ACTIVE
         WABASH_POWER_COST_REPORT_ACTIVE =R_WABASH_POWER_COST_RPT_ACTIVE
         SAVE_CHR_DETAILED_RPT_SWITCHES = 'X'
      RETURN
!
! ***********************************************************************
      ENTRY DISPATCH_RPT_TYPE
! ***********************************************************************
         IF(SP_CAPEX_ACTIVE()) THEN
            DISPATCH_RPT_TYPE = "T"
         ELSE
            DISPATCH_RPT_TYPE = DISPATCH_RPT_TYPE_STR
         ENDIF
      RETURN
! ***********************************************************************
      ENTRY CONTRACT_REPORT
! ***********************************************************************
         CONTRACT_REPORT = CONTRACT_REPORT_TYPE
      RETURN
! ***********************************************************************
      ENTRY CSV_REPORT
! ***********************************************************************
         CSV_REPORT = CSV_REPORT_ACTIVE
      RETURN
      ENTRY KEPCO_REPORTS
         KEPCO_REPORTS = KEPCO_REPORTS_ACTIVE
      RETURN
      ENTRY WABASH_POWER_COST_RPT
         WABASH_POWER_COST_RPT = WABASH_POWER_COST_REPORT_ACTIVE
      RETURN
! ***********************************************************************
      ENTRY FINANCIAL_DRILLING
! ***********************************************************************
!
!  REMOVE THIS CODE WHEN CLASS LEVEL DRILLING IS AVAILABLE
!
         IF(FINANCIAL_DRILLING_ACTIVE == 'C' .OR. &
                                  FINANCIAL_DRILLING_ACTIVE == 'B') THEN
            IF(MONTHLY_MIDAS_ACTIVE) THEN
               FINANCIAL_DRILLING_ACTIVE = 'M'
            ELSE
               FINANCIAL_DRILLING_ACTIVE = 'A'
            ENDIF
         ENDIF
         FINANCIAL_DRILLING = FINANCIAL_DRILLING_ACTIVE
      RETURN
! ***********************************************************************
      ENTRY SERVICE_REPORT
! ***********************************************************************
         SERVICE_REPORT = SERVICE_REPORT_ACTIVE
      RETURN
      END
! ***********************************************************************
      FUNCTION REPORTING_ASSET_CLASS()
! ***********************************************************************
!
      INTEGER(kind=2) :: REPORTING_ASSET_CLASS, &
                         SAVE_REPORTING_ASSET_CLASS_STR
      INTEGER :: IOS
      CHARACTER(len=4) :: REPORTING_ASSET_CLASS_STR='Cons', &
                  R_REPORTING_ASSET_CLASS_STR

         IF(INDEX(REPORTING_ASSET_CLASS_STR,'Cons') /= 0) THEN
            REPORTING_ASSET_CLASS = -2
         ELSEIF(INDEX(REPORTING_ASSET_CLASS_STR,'Pare') /= 0) THEN
            REPORTING_ASSET_CLASS = -1
         ELSEIF(INDEX(REPORTING_ASSET_CLASS_STR,'SUB') /= 0) THEN
            REPORTING_ASSET_CLASS = -3
         ELSEIF(INDEX(REPORTING_ASSET_CLASS_STR,'SBU') /= 0) THEN
            REPORTING_ASSET_CLASS = -4
         ELSE
            READ(REPORTING_ASSET_CLASS_STR,*,IOSTAT=IOS) &
                                                 REPORTING_ASSET_CLASS
            IF(IOS /= 0) THEN
               REPORTING_ASSET_CLASS = -1
            ELSE
               REPORTING_ASSET_CLASS = REPORTING_ASSET_CLASS + 1
            ENDIF
         ENDIF
      RETURN
      ENTRY SAVE_REPORTING_ASSET_CLASS_STR(R_REPORTING_ASSET_CLASS_STR)
         REPORTING_ASSET_CLASS_STR = R_REPORTING_ASSET_CLASS_STR
         SAVE_REPORTING_ASSET_CLASS_STR = 1
      RETURN
      END

