MODULE ESCALATION_VARIABLES
	INTEGER (KIND=2), PARAMETER :: MAX_ESC_FILES=6,LRECL_ES=512
	CHARACTER (LEN=2) :: ESCAL_OL(0:MAX_ESC_FILES-1)
	CHARACTER (LEN=2) :: ESC_FILE_CODES(0:MAX_ESC_FILES-1)=(/ &
	   'ES','N1','N2','N3','N4','N5'/)
	CHARACTER (LEN=11):: ESC_FILE_BINARY_NAMES(0:MAX_ESC_FILES-1)=(/ &
	   'ESCAL      ', 'ESCALATION1', 'ESCALATION2', 'ESCALATION3', &
	    'ESCALATION4', 'ESCALATION5'/)
	LOGICAL (KIND=1) :: ESCAL_BASE_FILE_ACTIVE(0:MAX_ESC_FILES-1)
	INTEGER (KIND=2) :: MAX_VECTOR_NUM=0
	INTEGER (KIND=4) :: BASE_INPUT_RECORDS(0:MAX_ESC_FILES-1), &
	    OVERLAY_INPUT_RECORDS(0:MAX_ESC_FILES-1)
END MODULE
