!     *****************************************************************
!     MUNIREV.FOR
!     Copyright(c)  2000
!
!     Created: 11/8/2006 1:58:49 PM
!     Author : MARK S GERBER
!     Last change: MSG 11/8/2006 1:58:49 PM
!     *****************************************************************

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!                                                                     !
!                      MUNICIPAL_REVENUES                             !
!          Copyright (c) 1992 M.S. Gerber & Associates, Inc.          !
!                      All Rights Reserved                            !
!                                                                     !
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!                                                                     !
!     Purpose:  This subroutine calculates revenues and cash flows    !
!               for a municipal utility.  The orginal version was     !
!               developed in January, 1992 based on the City of Palo  !
!               Alto's method of calculating revenues and transfers.  !
!                                                                     !
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!
      SUBROUTINE MUNICIPAL_REVENUES(RUN_YEAR,OPMETH,
     +                              PURCHASED_COSTS_PROD,
     +                              LTDINT,LTDRET,
     +                              INC_DSM_EXPENSE,INC_DSM_REBATE,
     +                              INC_FUEL_EXPENSE,INC_VAROM_EXPENSE,
     +                              INC_FIXEDOM_EXPENSE,
     +                              TOTAL_ENRG_LIMITED_VAR_COST,
     +                              FIXED_OM_COSTS,
     +                              TOTAL_ENERGY_LIMITED_FIXED_COST,
     +                              ANNUAL_ECONOMY_COST,
     +                              ANNUAL_ECONOMY_REVENUE,
     +                              COST_OF_SERVICE_REVENUES,
     +                              INC_SALES_REVENUES,
     +                              MMBTU_FEDERAL_TAX,
     +                              WRITE_THE_RESULTS)
C
      use SpinDriftLib
      use prod_arrays_dimensions
      use servcom
      USE SIZECOM

      LOGICAL*4 WRITE_THE_RESULTS
C
C SHORT FORM ITEMS
C
      INTEGER*4 ERROR
C     INCLUDE 'SHRTFORM.MON'
      INTEGER*2 LAST_VARIABLE,RUN_YEARS
      REAL VARIABLE_VALUE(:)
      ALLOCATABLE :: VARIABLE_VALUE
C
C ARGUMENT VARIABLES
C
      INTEGER*2 RUN_YEAR,BASE_YEAR
      CHARACTER*1 OPMETH
      CHARACTER*256 FILE_NAME,OUTPUT_DIRECTORY
      REAL SALES,PURCHASED_COSTS_PROD,ADD_OTHER_DEBT_SERVICE,
     +     ADD_DSM_EXPENDITURES,MMBTU_FEDERAL_TAX
      INTEGER*2 YEAR,DELETE
      REAL*8 GET_VAR_COST,GET_FUEL_COST
      REAL TOTAL_ENRG_LIMITED_VAR_COST,FIXED_OM_COSTS,
     +     TOTAL_ENERGY_LIMITED_FIXED_COST,
     +     ANNUAL_ECONOMY_COST,ANNUAL_ECONOMY_REVENUE,
     +     BASE_REVENUE,COST_OF_SERVICE_REVENUES,
     +     LAST_YEAR_REVENUES,
     +     OTHR_REVENUE_LAST_YEAR_SALES,
     +     ABOVE_TARGET,ABOVE_MINIMUM,
     +     CALAVERAS_WITHDRAWAL,
     +     CALAVERAS_TARGET_BALANCE,
     +     CALAVERAS_MINIMUM_BALANCE,
     +     MIN_RESERV_SALES,
     +     MIN_RESERV_GF_TRANSFER,
     +     MIN_RESERV_CALAVERAS,
     +     MIN_RESERV_FIXED_ASSEST,
     +     MIN_RESERV_CIP,
     +     MAX_RESERV_SALES,
     +     MAX_RESERV_GF_TRANSFER,
     +     MAX_RESERV_CALAVERAS,
     +     MAX_RESERV_FIXED_ASSEST,
     +     MAX_RESERV_CIP,
     +     TRG_RESERV_SALES,
     +     TRG_RESERV_GF_TRANSFER,
     +     TRG_RESERV_CALAVERAS,
     +     TRG_RESERV_FIXED_ASSEST,
     +     TRG_RESERV_CIP,
     +     MIN_RESERV_DSM_LM,
     +     TRG_RESERV_DSM_LM,
     +     MAX_RESERV_DSM_LM,
     +     PASS_THOURGH_VALUES(7)           ! SEVEN NEW VARIABLES
C
C EXPENSE FILE VARIABLES
C
      REAL FFEXP,PPEXP,OPEXP,MNEXP,INC_OTHER1_EXPENSE,
     +     INC_OTHER2_EXPENSE,INC_OTHER3_EXPENSE,NF_OWNED,NF_LEASED,
     +     ADD_CLAUSE_EXP,BASE_RATE_EXP,NOT_COLLECTED_EXP,
     +     NF_EXPENSE_RATEBASE
C
      INCLUDE 'PALTOCOM.MON'
C FINANIAL COMMON BLOCK ITEMS
      REAL LTDINT(0:*),LTDRET(0:*),INC_DSM_EXPENSE,INC_DSM_REBATE,
     +     INC_FUEL_EXPENSE,INC_VAROM_EXPENSE,INC_FIXEDOM_EXPENSE,
     +     INC_SALES_REVENUES
      REAL DUMMY,LTSINK
      INCLUDE 'DSMFRCOM.MON'
      INCLUDE 'RETLSCOM.MON'
C
C
C INTERNAL VARIABLES
C
      INTEGER*2 CURRENT_YEAR,I,PARM_UNIT,ASSET_UNIT
C
      REAL ZERO,NOT_AVAIL
      PARAMETER(ASSET_UNIT=40,PARM_UNIT=41,ZERO=0.,NOT_AVAIL=0.)
C     SAVE ADD_OTHER_DEBT_SERVICE,ADD_DSM_EXPENDITURES
      SAVE LAST_YEAR_REVENUES
C
      IF(RUN_YEAR == 1) THEN
         CALL OPEN_INITIZATION_FILE
         READ(10,REC=1) DELETE,CURRENT_YEAR,TOTAL_RESERVE_BALANCE(1),
     +              FIXED_ASSETS(1),SYSTEM_AVERAGE_RATE(1),
     +              SPECIAL_RESERVE_BALANCE(1),
     +              LAST_YEAR_REVENUES,
     +              CALAVERAS_RESERVE_BALANCE
         CALL CLOSE_INIIZATION_FILE
C
C READ ASSET FILE
C
         CALL RETURN_MUNI_DEBT_INFO(LTDRET,LTDINT)
C
C WRITE FIRST RECORD OF CURRENT ENDPOINT
C
         IF(WRITE_THE_RESULTS) THEN
            ALLOCATE(VARIABLE_VALUE(0:LAST_VARIABLE()),STAT=ERROR)
            CALL CINITD(VARIABLE_VALUE,INT(LAST_VARIABLE()+1),0.)
            VARIABLE_VALUE(36) = FIXED_ASSETS(1)           
            VARIABLE_VALUE(59) = TOTAL_RESERVE_BALANCE(1)  
            VARIABLE_VALUE(63) = SPECIAL_RESERVE_BALANCE(1)
            VARIABLE_VALUE(65) = SYSTEM_AVERAGE_RATE(1)    
            VARIABLE_VALUE(77) = CALAVERAS_RESERVE_BALANCE 
            CALL OUTPUT_RESULTS(VARIABLE_VALUE,BASE_YEAR())
            DEALLOCATE(VARIABLE_VALUE,STAT=ERROR)
         ENDIF
C
C OPEN PALO ALTO PARAMETER FILE
C
         CALL OPEN_FINANICAL_PARAMETER_FILE(PARM_UNIT)
      ENDIF
C
C READ MASTER FILE INFORMATION
C
       CALL RETURN_TOTAL_EXPENSE_ITEMS(RUN_YEAR+1,FFEXP,PPEXP,
     +               OPEXP,MNEXP,INC_OTHER1_EXPENSE,INC_OTHER2_EXPENSE,
     +               INC_OTHER3_EXPENSE,NF_OWNED,NF_LEASED,
     +               ADD_CLAUSE_EXP,BASE_RATE_EXP,NOT_COLLECTED_EXP,
     +               NF_EXPENSE_RATEBASE,INC_DSM_EXPENSE,INC_DSM_REBATE)
C
C READ SINKING FUND REQUIREMENTS WHICH ARE PRINCIPAL PAYMENTS
C
      CALL MUNI_BONDS_ISSUED(RUN_YEAR+1,BONDS_ISSUED,LTSINK)
C
C READ PARAMETER FILE INFORMATION
C
      READ(PARM_UNIT,REC=RUN_YEAR) DELETE,YEAR,
     +     RETURN_ON_RESERVES,CPA_SHARE_OF_NCPA_DS,CPA_SHARE_OF_TANC_DS,
     +     ADD_OTHER_DEBT_SERVICE,MINIMUM_RESERVE_BALANCE,
     +     MAXIMUM_RESERVE_BALANCE,TARGET_RESERVE_BALANCE,
     +     SYSTEM_AVERAGE_RATE(2),MINIMUM_ANNUAL_RATE_ADJUSTMENT,
     +     MAXIMUM_ANNUAL_RATE_ADJUSTMENT,ADDENDUM_TO_SALES_REVENUE,
     +     ADDENDUM_TO_INTEREST_REVENUE,OTHER_REVENUE,
     +     REVENUE_CONTRACTING_AGENCIES,BOND_REVENUE,
     +     ADDENDUM_TO_PURCHASE_EXPENSES,PURCHASE_EXPENSES_IN_WC,
     +     OPERATING_EXPENSES,OPERATING_EXPENSES_IN_WC,
     +     CONTINGENCY_EXPENSES,CONTINGENCY_EXPENSES_IN_WC,
     +     ADMINISTRATION_EXPENSES,ADMINISTRATION_EXPENSES_IN_WC,
     +     ALLOCATED_EXPENSES,ALLOCATED_EXPENSES_IN_WC,
     +     OTHER_EXPENSE,OTHER_EXPENSE_IN_WC,
     +     CIP_TO_GENERAL_FUND,RENT_EXPENSE,
     +     RENT_IN_WORKING_CAPITAL,ALLOCATED_CHARGES,
     +     ALLOCATED_CHARGES_IN_WC,OTHER_TRANSFER,
     +     OTHER_TRANSFER_IN_WC,TOTAL_CIP_EXPENDITURES,
     +     CIP_ALLOCATED_TO_RATE_BASE,DEPRECIATION_RATE,
     +     ADDENDUM_TO_DEPRECIATION,ADDENDUM_TO_WORKING_CAPITAL,
     +     TRANSFER_TO_GENERAL_FUND_RATE,
     +     CIP_ALLOCATED_TO_WC,
     +     ADD_DSM_EXPENDITURES,DSM_IN_WC,
     +     LOAD_MANAGEMENT_EXPENDITURES,LOAD_MANAGEMENT_IN_WC,
     +     X_PRICE_MUNI_1,X_PRICE_MUNI_2,X_PRICE_MUNI_3,
     +     OTHR_REVENUE_LAST_YEAR_SALES,
     +     MIN_RESERV_SALES,
     +     MIN_RESERV_GF_TRANSFER,
     +     MIN_RESERV_CALAVERAS,
     +     MIN_RESERV_FIXED_ASSEST,
     +     MIN_RESERV_CIP,
     +     MAX_RESERV_SALES,
     +     MAX_RESERV_GF_TRANSFER,
     +     MAX_RESERV_CALAVERAS,
     +     MAX_RESERV_FIXED_ASSEST,
     +     MAX_RESERV_CIP,
     +     TRG_RESERV_SALES,
     +     TRG_RESERV_GF_TRANSFER,
     +     TRG_RESERV_CALAVERAS,
     +     TRG_RESERV_FIXED_ASSEST,
     +     TRG_RESERV_CIP,
     +     MIN_RESERV_DSM_LM,
     +     TRG_RESERV_DSM_LM,
     +     MAX_RESERV_DSM_LM,
     +     PASS_THOURGH_VALUES           ! SEVEN NEW VARIABLES
C
C EXPENSES
C
      INC_FUEL_EXPENSE = FFEXP + GET_FUEL_COST()/1000000. + 
     +                                                 MMBTU_FEDERAL_TAX
      INC_VAROM_EXPENSE = (GET_VAR_COST() +
     +                             TOTAL_ENRG_LIMITED_VAR_COST)/1000000.
      INC_FIXEDOM_EXPENSE = MNEXP + (FIXED_OM_COSTS +
     +                         TOTAL_ENERGY_LIMITED_FIXED_COST)/1000000. 
      PURCHASED_EXPENSES = PURCHASED_COSTS_PROD/1000000. +
     +                     ADDENDUM_TO_PURCHASE_EXPENSES +
     +                     PPEXP +
     +                     ANNUAL_ECONOMY_COST/1000000. - 
     +                     ANNUAL_ECONOMY_REVENUE/1000000.
      OPERATING_EXPENSES = OPERATING_EXPENSES + OPEXP
C     CONTINGENCY_EXPENSES = CONTINGENCY_EXPENSES + MNEXP
      ADMINISTRATION_EXPENSES=ADMINISTRATION_EXPENSES+INC_OTHER1_EXPENSE
      ALLOCATED_EXPENSES = ALLOCATED_EXPENSES + INC_OTHER2_EXPENSE
      RENT_EXPENSE = RENT_EXPENSE + INC_OTHER3_EXPENSE
      EXPENSES = PURCHASED_EXPENSES +
     +           OPERATING_EXPENSES +
     +           CONTINGENCY_EXPENSES +
     +           ADMINISTRATION_EXPENSES +
     +           ALLOCATED_EXPENSES +
     +           OTHER_EXPENSE +
     +           INC_FUEL_EXPENSE +
     +           INC_VAROM_EXPENSE +
     +           INC_FIXEDOM_EXPENSE +
     +           SERVICE_EXPENSES/1000.
C
C CASH TRANSFERS
C
      CASH_TRANSFERS = RENT_EXPENSE +
     +                 CIP_TO_GENERAL_FUND +
     +                 ALLOCATED_CHARGES +
     +                 OTHER_TRANSFER
C
C DEBT SERVICE CALCULATION
C
      OTHER_DEBT_SERVICE = ADD_OTHER_DEBT_SERVICE + LTDINT(RUN_YEAR) +
     +                     LTDRET(RUN_YEAR) + LTSINK
      DEBT_SERVICE = CPA_SHARE_OF_NCPA_DS + CPA_SHARE_OF_TANC_DS +
     +               OTHER_DEBT_SERVICE
C
C DSM CASH EXPENDITURES
C
      INC_DSM_EXPENSE =  INC_DSM_EXPENSE + DSM_EXPENSE_COLECTION(1) +
     +                                     DSM_EXPENSE_COLECTION(2) +
     +                                     DSM_EXPENSE_COLECTION(3)
      INC_DSM_REBATE =  INC_DSM_REBATE + DSM_REBATE_COLECTION(1) +
     +                                   DSM_REBATE_COLECTION(2) +
     +                                   DSM_REBATE_COLECTION(3)
      DSM_EXPENDITURES = ADD_DSM_EXPENDITURES + INC_DSM_EXPENSE +
     +                   INC_DSM_REBATE + DSM_CASH
      TOTAL_DSM_EXPENDITURES = DSM_EXPENDITURES +
     +                         LOAD_MANAGEMENT_EXPENDITURES
C
C RATE BASE CALCULATION
C
      DEPRECIATION = DEPRECIATION_RATE * FIXED_ASSETS(1)/100. +
     +                                          ADDENDUM_TO_DEPRECIATION
      CONTRIBUTED_CIP_IN_RB = TOTAL_CIP_EXPENDITURES * 
     +                                   CIP_ALLOCATED_TO_RATE_BASE/100.
      FIXED_ASSETS(2) = FIXED_ASSETS(1) + CONTRIBUTED_CIP_IN_RB -
     +                                                      DEPRECIATION
      AVERAGE_FIXED_ASSETS = (FIXED_ASSETS(1) + FIXED_ASSETS(2))/2.
      WORKING_CAPITAL_IN_RB =
     +     (INC_FUEL_EXPENSE + PURCHASED_EXPENSES - INC_SALES_REVENUES)*
     +                                    PURCHASE_EXPENSES_IN_WC/100. +
     +     (OPERATING_EXPENSES+INC_VAROM_EXPENSE+INC_FIXEDOM_EXPENSE) *
     +                                   OPERATING_EXPENSES_IN_WC/100. +
     +     CONTINGENCY_EXPENSES * CONTINGENCY_EXPENSES_IN_WC/100. +
     +     ADMINISTRATION_EXPENSES*ADMINISTRATION_EXPENSES_IN_WC/100. +
     +     ALLOCATED_EXPENSES * ALLOCATED_EXPENSES_IN_WC/100. +
     +     OTHER_EXPENSE * OTHER_EXPENSE_IN_WC/100. +
     +     RENT_EXPENSE * RENT_IN_WORKING_CAPITAL/100. +
     +     ALLOCATED_CHARGES * ALLOCATED_CHARGES_IN_WC/100. +
     +     OTHER_TRANSFER * OTHER_TRANSFER_IN_WC/100. +
     +     TOTAL_CIP_EXPENDITURES * CIP_ALLOCATED_TO_WC/100. +
     +     DSM_EXPENDITURES * DSM_IN_WC/100. +
     +     LOAD_MANAGEMENT_EXPENDITURES * LOAD_MANAGEMENT_IN_WC/100. +
     +     ADDENDUM_TO_WORKING_CAPITAL
      RATE_BASE = AVERAGE_FIXED_ASSETS + WORKING_CAPITAL_IN_RB
      TRANSFER_TO_GENERAL_FUND = RATE_BASE * 
     +                           TRANSFER_TO_GENERAL_FUND_RATE/100. -
     +                           OTHER_DEBT_SERVICE
C
C INTEREST REVENUE
C
      INTEREST_REVENUE = ADDENDUM_TO_INTEREST_REVENUE + 
     +              TOTAL_RESERVE_BALANCE(1) * RETURN_ON_RESERVES/100. +
     +              SPECIAL_RESERVE_BALANCE(1) * RETURN_ON_RESERVES/100.
C
C REVENUES
C
      SALES = RETAIL_SALES_BY_CLASS(7) - DELTA_CLASS_SALES_FROM_DSM(7)
      IF(OPMETH == 'O') THEN
         SALES_REVENUES = (SALES * SYSTEM_AVERAGE_RATE(2))/1000000.
      ELSE
         SALES_REVENUES = (SALES * SYSTEM_AVERAGE_RATE(1))/1000000.
      ENDIF
      OTHER_REVENUE = OTHER_REVENUE + LAST_YEAR_REVENUES *
     +                               OTHR_REVENUE_LAST_YEAR_SALES/100.
      REVENUES = SALES_REVENUES +
     +           ADDENDUM_TO_SALES_REVENUE +
     +           OTHER_REVENUE +
     +           REVENUE_CONTRACTING_AGENCIES +
     +           BOND_REVENUE +
     +           INC_SALES_REVENUES +
     +           SERVICE_REVENUES/1000.
C
C TOTAL USES
C
      TOTAL_USES = EXPENSES + CASH_TRANSFERS +
     +             TRANSFER_TO_GENERAL_FUND + DEBT_SERVICE +
     +             TOTAL_CIP_EXPENDITURES +
     +             TOTAL_DSM_EXPENDITURES
C
C CASH BALANCE
C
      CHANGE_IN_RESERVES = (1./(1.-RETURN_ON_RESERVES/200.)) *
     +                       (REVENUES + INTEREST_REVENUE -
     +                        TOTAL_USES + BONDS_ISSUED)
C
      FROM_RESERVES = 0.
      TO_RESERVES = 0.
      TO_SPECIAL_RESERVE = 0.
      ADDITIONAL_REVENUES = 0.
      RATE_CHANGE = 0.
C
C CALCULATION RESERVE BALANCES
C
      MINIMUM_RESERVE_BALANCE = MINIMUM_RESERVE_BALANCE +
     +          SALES_REVENUES * MIN_RESERV_SALES/100. +
     +          TRANSFER_TO_GENERAL_FUND * MIN_RESERV_GF_TRANSFER/100. +
     +          CALAVERAS_RESERVE_BALANCE * MIN_RESERV_CALAVERAS/100. +
     +          FIXED_ASSETS(2) * MIN_RESERV_FIXED_ASSEST/100. +
     +          TOTAL_CIP_EXPENDITURES * MIN_RESERV_CIP/100. +
     +          (DSM_EXPENDITURES + LOAD_MANAGEMENT_EXPENDITURES) * 
     +                                            MIN_RESERV_DSM_LM/100.
      TARGET_RESERVE_BALANCE = TARGET_RESERVE_BALANCE +
     +          SALES_REVENUES * TRG_RESERV_SALES/100. +
     +          TRANSFER_TO_GENERAL_FUND * TRG_RESERV_GF_TRANSFER/100. +
     +          CALAVERAS_RESERVE_BALANCE * TRG_RESERV_CALAVERAS/100. +
     +          FIXED_ASSETS(2) * TRG_RESERV_FIXED_ASSEST/100. +
     +          TOTAL_CIP_EXPENDITURES * TRG_RESERV_CIP/100. +
     +          (DSM_EXPENDITURES + LOAD_MANAGEMENT_EXPENDITURES) * 
     +                                            TRG_RESERV_DSM_LM/100.
      MAXIMUM_RESERVE_BALANCE = MAXIMUM_RESERVE_BALANCE +
     +          SALES_REVENUES * MAX_RESERV_SALES/100. +
     +          TRANSFER_TO_GENERAL_FUND * MAX_RESERV_GF_TRANSFER/100. +
     +          CALAVERAS_RESERVE_BALANCE * MAX_RESERV_CALAVERAS/100. +
     +          FIXED_ASSETS(2) * MAX_RESERV_FIXED_ASSEST/100. +
     +          TOTAL_CIP_EXPENDITURES * MAX_RESERV_CIP/100. +
     +          (DSM_EXPENDITURES + LOAD_MANAGEMENT_EXPENDITURES) * 
     +                                            MAX_RESERV_DSM_LM/100.
C
      TOTAL_RESERVE_BALANCE(2) = TOTAL_RESERVE_BALANCE(1) +
     +                                                CHANGE_IN_RESERVES
      IF(OPMETH /= 'O') THEN
         IF(OPMETH == 'T') THEN
            DESIRED_RESERVE_BALANCE = TARGET_RESERVE_BALANCE
         ELSE
            DESIRED_RESERVE_BALANCE = MINIMUM_RESERVE_BALANCE
         ENDIF
         IF(TOTAL_RESERVE_BALANCE(2) < DESIRED_RESERVE_BALANCE) THEN
C CHANGE RATES TO BALANCE THE NEED FOR CASH
            ADDITIONAL_REVENUES = TOTAL_USES - (REVENUES + 
     +                                          BONDS_ISSUED +
     +                                    ADDENDUM_TO_INTEREST_REVENUE +
     +            RETURN_ON_RESERVES/100. * SPECIAL_RESERVE_BALANCE(1) + 
     +         (1.+RETURN_ON_RESERVES/200.) * TOTAL_RESERVE_BALANCE(1) -
     +         (1.-RETURN_ON_RESERVES/200.) * DESIRED_RESERVE_BALANCE)
            RATE_CHANGE = 100. * ABS(ADDITIONAL_REVENUES)/
     +                          (SALES_REVENUES + .000001)
            IF(RATE_CHANGE > MAXIMUM_ANNUAL_RATE_ADJUSTMENT) THEN
               RATE_CHANGE = MAXIMUM_ANNUAL_RATE_ADJUSTMENT
            ELSEIF(RATE_CHANGE < MINIMUM_ANNUAL_RATE_ADJUSTMENT) THEN
               RATE_CHANGE = MINIMUM_ANNUAL_RATE_ADJUSTMENT
            ENDIF
            ADDITIONAL_REVENUES = RATE_CHANGE * SALES_REVENUES/100.
            CHANGE_IN_RESERVES = (1./(1.-RETURN_ON_RESERVES/200.)) *
     +                           (REVENUES + INTEREST_REVENUE -
     +                            TOTAL_USES + BONDS_ISSUED +
     +                            ADDITIONAL_REVENUES)
            TOTAL_RESERVE_BALANCE(2) = TOTAL_RESERVE_BALANCE(1) +
     +                                                CHANGE_IN_RESERVES
C           IF(ADDITIONAL_REVENUES .GT. ABS(CHANGE_IN_RESERVES)) THEN
C              TO_RESERVES = ABS(CHANGE_IN_RESERVES + 
C    +               (1.+RETURN_ON_RESERVES/200.) * ADDITIONAL_REVENUES)
C           ELSEIF(ADDITIONAL_REVENUES .LT. ABS(CHANGE_IN_RESERVES))THEN
C              FROM_RESERVES=ABS(CHANGE_IN_RESERVES +
C    +               (1.+RETURN_ON_RESERVES/200.) * ADDITIONAL_REVENUES)
C           ENDIF
C           TOTAL_RESERVE_BALANCE(2) = TOTAL_RESERVE_BALANCE(2) +
C    +                                               ADDITIONAL_REVENUES
C           CHANGE_IN_RESERVES = CHANGE_IN_RESERVES + 
C    +              (1. + RETURN_ON_RESERVES/200.) * ADDITIONAL_REVENUES
         ENDIF
      ENDIF
C
C SUPLUS CASH ADD TO RESERVES
C
      IF(TOTAL_RESERVE_BALANCE(2) > MAXIMUM_RESERVE_BALANCE) THEN
         TO_SPECIAL_RESERVE = TOTAL_RESERVE_BALANCE(2) -
     +                                        MAXIMUM_RESERVE_BALANCE
         CHANGE_IN_RESERVES = CHANGE_IN_RESERVES - TO_SPECIAL_RESERVE
         TOTAL_RESERVE_BALANCE(2) = MAXIMUM_RESERVE_BALANCE
      ENDIF
      IF(CHANGE_IN_RESERVES >= 0.) THEN
         TO_RESERVES = CHANGE_IN_RESERVES
      ELSE
         FROM_RESERVES = ABS(CHANGE_IN_RESERVES)
      ENDIF
      SPECIAL_RESERVE_BALANCE(2) = SPECIAL_RESERVE_BALANCE(1) +
     +                                                TO_SPECIAL_RESERVE
C
C END RESERVE BALANCES
C
      INTEREST_REVENUE = ADDENDUM_TO_INTEREST_REVENUE + 
     +        (TOTAL_RESERVE_BALANCE(2) + TOTAL_RESERVE_BALANCE(1)) * 
     +                                         RETURN_ON_RESERVES/200. +
     +       (SPECIAL_RESERVE_BALANCE(2) + SPECIAL_RESERVE_BALANCE(1)) *
     +                                           RETURN_ON_RESERVES/200.
      REVENUES = REVENUES + INTEREST_REVENUE + ADDITIONAL_REVENUES
      SYSTEM_AVERAGE_RATE(2) = 1000000.*(SALES_REVENUES +
     +                           ADDITIONAL_REVENUES)/(SALES + .0000001)
      BASE_REVENUE = SALES_REVENUES + ADDITIONAL_REVENUES +
     +                           ADDENDUM_TO_SALES_REVENUE
      CALL STORE_REVENUE(BASE_REVENUE,0.) 
      COST_OF_SERVICE_REVENUES = REVENUES
      LAST_YEAR_REVENUES = REVENUES
      IF(FROM_RESERVES > 0.) THEN
         ABOVE_TARGET = TOTAL_RESERVE_BALANCE(1)-TARGET_RESERVE_BALANCE
         ABOVE_MINIMUM=TOTAL_RESERVE_BALANCE(1)-MINIMUM_RESERVE_BALANCE
         CALAVERAS_TARGET_BALANCE = CALAVERAS_RESERVE_BALANCE * 
     +                                         TRG_RESERV_CALAVERAS/100.
         CALAVERAS_MINIMUM_BALANCE = CALAVERAS_RESERVE_BALANCE * 
     +                                         MIN_RESERV_CALAVERAS/100.
         IF(ABOVE_TARGET .GE. FROM_RESERVES) THEN
            CALAVERAS_WITHDRAWAL = FROM_RESERVES * 
     +          (CALAVERAS_RESERVE_BALANCE - CALAVERAS_TARGET_BALANCE)/ 
     +                             ABOVE_TARGET
         ELSEIF(ABOVE_MINIMUM .GE. FROM_RESERVES) THEN
            CALAVERAS_WITHDRAWAL = FROM_RESERVES * 
     +         (CALAVERAS_RESERVE_BALANCE - CALAVERAS_MINIMUM_BALANCE)/
     +                             ABOVE_MINIMUM
         ELSE
            CALAVERAS_WITHDRAWAL = MIN(FROM_RESERVES,
     +          (CALAVERAS_RESERVE_BALANCE - CALAVERAS_MINIMUM_BALANCE))
         ENDIF
      ELSE
         CALAVERAS_WITHDRAWAL = 0.
      ENDIF
      CALAVERAS_RESERVE_BALANCE = CALAVERAS_RESERVE_BALANCE * 
     +                                  (1. + RETURN_ON_RESERVES/100.) -
     +                            CALAVERAS_WITHDRAWAL
      RETURN
      END
!
!
