grep -i "BTL_Monthly_Expenses"                       ~/wrk/Midas/ABBICAP/*.* 
grep -i "BTL_Monthly_Income_Taxes"                   ~/wrk/Midas/ABBICAP/*.* 
grep -i "BTL_Monthly_NoTax_Other_Income"             ~/wrk/Midas/ABBICAP/*.* 
grep -i "BTL_Monthly_STInvestmet_Income"             ~/wrk/Midas/ABBICAP/*.* 
grep -i "Cash_ATL_Lease_Cash"                        ~/wrk/Midas/ABBICAP/*.* 
grep -i "Cash_From_Trust_Fund_Earnings"              ~/wrk/Midas/ABBICAP/*.* 
grep -i "Cash_Prior_Years_Method_Adj"                ~/wrk/Midas/ABBICAP/*.* 
grep -i "Cash_Prior_level_Method_Adj"                ~/wrk/Midas/ABBICAP/*.* 
grep -i "Cash_TOTAL_EXPENSE_PAYMENTS"                ~/wrk/Midas/ABBICAP/*.* 
grep -i "Cash_TOTAL_OPERATING_RECEIPTS"              ~/wrk/Midas/ABBICAP/*.* 
grep -i "IMPA_Depreciation_Add_Back"                 ~/wrk/Midas/ABBICAP/*.* 
grep -i "Monthly_Booked_PS_Dividends"                ~/wrk/Midas/ABBICAP/*.* 
grep -i "Monthly_CIAC_Amort"                         ~/wrk/Midas/ABBICAP/*.* 
grep -i "Monthly_Common_Dividends"                   ~/wrk/Midas/ABBICAP/*.* 
grep -i "Monthly_EBIT"                               ~/wrk/Midas/ABBICAP/*.* 
grep -i "Monthly_EBITAD"                             ~/wrk/Midas/ABBICAP/*.* 
grep -i "Monthly_Earnings_2_Common"                  ~/wrk/Midas/ABBICAP/*.* 
grep -i "Monthly_Earnings_per_Share"                 ~/wrk/Midas/ABBICAP/*.* 
grep -i "Monthly_Extraordinary_Items"                ~/wrk/Midas/ABBICAP/*.* 
grep -i "Monthly_FASB_143_Amort"                     ~/wrk/Midas/ABBICAP/*.* 
grep -i "Monthly_Federal_Tax_on_Capital"             ~/wrk/Midas/ABBICAP/*.* 
grep -i "Monthly_INCOME_AFTER_INTEREST"              ~/wrk/Midas/ABBICAP/*.* 
grep -i "Monthly_INCOME_BEFORE_INTEREST"             ~/wrk/Midas/ABBICAP/*.* 
grep -i "Monthly_Income_Tax_Deferrals_Dr"            ~/wrk/Midas/ABBICAP/*.* 
grep -i "Monthly_LTD_Amort_Interest"                 ~/wrk/Midas/ABBICAP/*.* 
grep -i "Monthly_LTD_Cash_Interest"                  ~/wrk/Midas/ABBICAP/*.* 
grep -i "Monthly_Lease_BTL_Amort_Expense"            ~/wrk/Midas/ABBICAP/*.* 
grep -i "Monthly_Lease_Interest_Expense"             ~/wrk/Midas/ABBICAP/*.* 
grep -i "Monthly_MIPS_Dividends"                     ~/wrk/Midas/ABBICAP/*.* 
grep -i "Monthly_Net_Income"                         ~/wrk/Midas/ABBICAP/*.* 
grep -i "Monthly_Nuclear_Fuel_Expense"               ~/wrk/Midas/ABBICAP/*.* 
grep -i "Monthly_Op_Income"                          ~/wrk/Midas/ABBICAP/*.* 
grep -i "Monthly_Other"                              ~/wrk/Midas/ABBICAP/*.* 
grep -i "Monthly_Other_Debit_Amort"                  ~/wrk/Midas/ABBICAP/*.* 
grep -i "Monthly_RETAINED_EARNINGS"                  ~/wrk/Midas/ABBICAP/*.* 
grep -i "Monthly_Regular_PS_Dividends"               ~/wrk/Midas/ABBICAP/*.* 
grep -i "Monthly_Shares_Outstanding"                 ~/wrk/Midas/ABBICAP/*.* 
grep -i "Monthly_State_Tax_on_Capital"               ~/wrk/Midas/ABBICAP/*.* 
grep -i "Monthly_Strom_Reserve"                      ~/wrk/Midas/ABBICAP/*.* 
grep -i "Monthly_Total_Taxes_Expense"                ~/wrk/Midas/ABBICAP/*.* 
grep -i "Monthly_Unused_Fed_Tax_Credits"             ~/wrk/Midas/ABBICAP/*.* 
grep -i "Price_of_Issued_Shares"                     ~/wrk/Midas/ABBICAP/*.* 
grep -i "Quarterly_Earnings_per_Share"               ~/wrk/Midas/ABBICAP/*.* 
grep -i "WVPA_Member_Energy_Sales"                   ~/wrk/Midas/ABBICAP/*.* 
grep -i "WVPA_Member_Margin"                         ~/wrk/Midas/ABBICAP/*.* 
grep -i "WVPA_Member_Rates_with_SDI"                 ~/wrk/Midas/ABBICAP/*.* 
grep -i "WVPA_Member_Rates_without_SDI"              ~/wrk/Midas/ABBICAP/*.* 
grep -i "WVPA_Non_Member_Margin"                     ~/wrk/Midas/ABBICAP/*.* 
grep -i "WVPA_SDI_Energy_Sales"                      ~/wrk/Midas/ABBICAP/*.* 
