grep -i "BTL_Monthly_Expenses"                       mthnmcom.mon
grep -i "BTL_Monthly_Income_Taxes"                   mthnmcom.mon
grep -i "BTL_Monthly_NoTax_Other_Income"             mthnmcom.mon
grep -i "BTL_Monthly_STInvestmet_Income"             mthnmcom.mon
grep -i "Cash_ATL_Lease_Cash"                        mthnmcom.mon
grep -i "Cash_From_Trust_Fund_Earnings"              mthnmcom.mon
grep -i "Cash_Prior_Years_Method_Adj"                mthnmcom.mon
grep -i "Cash_Prior_level_Method_Adj"                mthnmcom.mon
grep -i "Cash_TOTAL_EXPENSE_PAYMENTS"                mthnmcom.mon
grep -i "Cash_TOTAL_OPERATING_RECEIPTS"              mthnmcom.mon
grep -i "IMPA_Depreciation_Add_Back"                 mthnmcom.mon
grep -i "Monthly_Booked_PS_Dividends"                mthnmcom.mon
grep -i "Monthly_CIAC_Amort"                         mthnmcom.mon
grep -i "Monthly_Common_Dividends"                   mthnmcom.mon
grep -i "Monthly_EBIT"                               mthnmcom.mon
grep -i "Monthly_EBITAD"                             mthnmcom.mon
grep -i "Monthly_Earnings_2_Common"                  mthnmcom.mon
grep -i "Monthly_Earnings_per_Share"                 mthnmcom.mon
grep -i "Monthly_Extraordinary_Items"                mthnmcom.mon
grep -i "Monthly_FASB_143_Amort"                     mthnmcom.mon
grep -i "Monthly_Federal_Tax_on_Capital"             mthnmcom.mon
grep -i "Monthly_INCOME_AFTER_INTEREST"              mthnmcom.mon
grep -i "Monthly_INCOME_BEFORE_INTEREST"             mthnmcom.mon
grep -i "Monthly_Income_Tax_Deferrals_Dr"            mthnmcom.mon
grep -i "Monthly_LTD_Amort_Interest"                 mthnmcom.mon
grep -i "Monthly_LTD_Cash_Interest"                  mthnmcom.mon
grep -i "Monthly_Lease_BTL_Amort_Expense"            mthnmcom.mon
grep -i "Monthly_Lease_Interest_Expense"             mthnmcom.mon
grep -i "Monthly_MIPS_Dividends"                     mthnmcom.mon
grep -i "Monthly_Net_Income"                         mthnmcom.mon
grep -i "Monthly_Nuclear_Fuel_Expense"               mthnmcom.mon
grep -i "Monthly_Op_Income"                          mthnmcom.mon
grep -i "Monthly_Other"                              mthnmcom.mon
grep -i "Monthly_Other_Debit_Amort"                  mthnmcom.mon
grep -i "Monthly_RETAINED_EARNINGS"                  mthnmcom.mon
grep -i "Monthly_Regular_PS_Dividends"               mthnmcom.mon
grep -i "Monthly_Shares_Outstanding"                 mthnmcom.mon
grep -i "Monthly_State_Tax_on_Capital"               mthnmcom.mon
grep -i "Monthly_Strom_Reserve"                      mthnmcom.mon
grep -i "Monthly_Total_Taxes_Expense"                mthnmcom.mon
grep -i "Monthly_Unused_Fed_Tax_Credits"             mthnmcom.mon
grep -i "Price_of_Issued_Shares"                     mthnmcom.mon
grep -i "Quarterly_Earnings_per_Share"               mthnmcom.mon
grep -i "WVPA_Member_Energy_Sales"                   mthnmcom.mon
grep -i "WVPA_Member_Margin"                         mthnmcom.mon
grep -i "WVPA_Member_Rates_with_SDI"                 mthnmcom.mon
grep -i "WVPA_Member_Rates_without_SDI"              mthnmcom.mon
grep -i "WVPA_Non_Member_Margin"                     mthnmcom.mon
grep -i "WVPA_SDI_Energy_Sales"                      mthnmcom.mon
