GAS_objt.for                  ,grep -i "Gas_Storage"                                ~/wrk/Midas/ABBICAP/*.* 
msgmmadm.f90                  ,grep -i "ARO_Accretion_Amount"                       ~/wrk/Midas/ABBICAP/*.* 
msgmmadm.f90                  ,grep -i "Balance_Deferred_Taxes"                     ~/wrk/Midas/ABBICAP/*.* 
msgmmadm.f90                  ,grep -i "Decommissioning_Rate"                       ~/wrk/Midas/ABBICAP/*.* 
msgmmadm.f90                  ,grep -i "Economic_Assets_Adjustment"                 ~/wrk/Midas/ABBICAP/*.* 
msgmmadm.f90                  ,grep -i "Equity_Risk_Adjustment"                     ~/wrk/Midas/ABBICAP/*.* 
msgmmadm.f90                  ,grep -i "Gas_Storage"                                ~/wrk/Midas/ABBICAP/*.* 
msgmmadm.f90                  ,grep -i "Interest_Payments"                          ~/wrk/Midas/ABBICAP/*.* 
msgmmadm.f90                  ,grep -i "Operating_Profits_Adjustment"               ~/wrk/Midas/ABBICAP/*.* 
msgmmadm.f90                  ,grep -i "Post_Retirement_Rate"                       ~/wrk/Midas/ABBICAP/*.* 
msgmmadm.f90                  ,grep -i "Salvage_Value"                              ~/wrk/Midas/ABBICAP/*.* 
msgmmdbt.for                  ,grep -i "Cash_Dividend_Earnings"                     ~/wrk/Midas/ABBICAP/*.* 
msgmmdbt.for                  ,grep -i "Cash_Interest_Earnings"                     ~/wrk/Midas/ABBICAP/*.* 
msgmmdbt.for                  ,grep -i "Cash_Interest_Payments"                     ~/wrk/Midas/ABBICAP/*.* 
msgmmdbt.for                  ,grep -i "Dividend_70"                                ~/wrk/Midas/ABBICAP/*.* 
msgmmdbt.for                  ,grep -i "Interest_Earnings"                          ~/wrk/Midas/ABBICAP/*.* 
msgmmdbt.for                  ,grep -i "Interest_Payments"                          ~/wrk/Midas/ABBICAP/*.* 
msgmmdbt.for                  ,grep -i "Intra_Company_Interest_Earnings"            ~/wrk/Midas/ABBICAP/*.* 
msgmmsb6.for                  ,grep -i "ARO_Liabilities"                            ~/wrk/Midas/ABBICAP/*.* 
msgmmsb6.for                  ,grep -i "ARO_Net_Assets"                             ~/wrk/Midas/ABBICAP/*.* 
msgmmsb6.for                  ,grep -i "Other_Deferred_Credits"                     ~/wrk/Midas/ABBICAP/*.* 
msgmmsb6.for                  ,grep -i "Reaquired_Debt_Gain"                        ~/wrk/Midas/ABBICAP/*.* 
msgmmsb6.for                  ,grep -i "Regulatory_Deferred_Credits"                ~/wrk/Midas/ABBICAP/*.* 
namescom.f90                  ,grep -i "ARO_Accretion_Amount"                       ~/wrk/Midas/ABBICAP/*.* 
namescom.f90                  ,grep -i "ARO_Cash_Payment"                           ~/wrk/Midas/ABBICAP/*.* 
namescom.f90                  ,grep -i "ARO_Cash_to_Bal_Sheet_Trust"                ~/wrk/Midas/ABBICAP/*.* 
namescom.f90                  ,grep -i "ARO_Discount_Rate"                          ~/wrk/Midas/ABBICAP/*.* 
namescom.f90                  ,grep -i "ARO_Liabilities"                            ~/wrk/Midas/ABBICAP/*.* 
namescom.f90                  ,grep -i "ARO_Net_Assets"                             ~/wrk/Midas/ABBICAP/*.* 
namescom.f90                  ,grep -i "ATL_Debit_Amortization"                     ~/wrk/Midas/ABBICAP/*.* 
namescom.f90                  ,grep -i "Actual_ATL_Fed_Income_Taxes"                ~/wrk/Midas/ABBICAP/*.* 
namescom.f90                  ,grep -i "Actual_ATL_State_Income_Taxes"              ~/wrk/Midas/ABBICAP/*.* 
namescom.f90                  ,grep -i "Actual_BTL_Fed_Income_Taxes"                ~/wrk/Midas/ABBICAP/*.* 
namescom.f90                  ,grep -i "Actual_BTL_State_Income_Taxes"              ~/wrk/Midas/ABBICAP/*.* 
namescom.f90                  ,grep -i "Actual_Deferred_Taxes_Cr"                   ~/wrk/Midas/ABBICAP/*.* 
namescom.f90                  ,grep -i "Actual_Deferred_Taxes_Dr"                   ~/wrk/Midas/ABBICAP/*.* 
namescom.f90                  ,grep -i "Actual_Fed_Income_Taxes"                    ~/wrk/Midas/ABBICAP/*.* 
namescom.f90                  ,grep -i "Actual_State_Income_Taxes"                  ~/wrk/Midas/ABBICAP/*.* 
namescom.f90                  ,grep -i "Addedum_to_Book_Gain_Loss"                  ~/wrk/Midas/ABBICAP/*.* 
namescom.f90                  ,grep -i "Addendum_Payable_Accounts"                  ~/wrk/Midas/ABBICAP/*.* 
namescom.f90                  ,grep -i "Addendum_Receivable_Accounts"               ~/wrk/Midas/ABBICAP/*.* 
namescom.f90                  ,grep -i "Annual_Deferred_Taxes"                      ~/wrk/Midas/ABBICAP/*.* 
namescom.f90                  ,grep -i "Annualized_Interest"                        ~/wrk/Midas/ABBICAP/*.* 
namescom.f90                  ,grep -i "Assets_NEC_Addendum"                        ~/wrk/Midas/ABBICAP/*.* 
namescom.f90                  ,grep -i "Assets_NEC_Adjustment"                      ~/wrk/Midas/ABBICAP/*.* 
namescom.f90                  ,grep -i "BAAN_Additions"                             ~/wrk/Midas/ABBICAP/*.* 
namescom.f90                  ,grep -i "BAAN_Annualized_Interest"                   ~/wrk/Midas/ABBICAP/*.* 
namescom.f90                  ,grep -i "BAAN_Interest_Payments"                     ~/wrk/Midas/ABBICAP/*.* 
namescom.f90                  ,grep -i "BAAN_Reductions"                            ~/wrk/Midas/ABBICAP/*.* 
namescom.f90                  ,grep -i "BTL_Debt_Amortization"                      ~/wrk/Midas/ABBICAP/*.* 
namescom.f90                  ,grep -i "Balance_Deferred_Taxes"                     ~/wrk/Midas/ABBICAP/*.* 
namescom.f90                  ,grep -i "Balance_Deferred_Taxes_Dr"                  ~/wrk/Midas/ABBICAP/*.* 
namescom.f90                  ,grep -i "CD_Addendum"                                ~/wrk/Midas/ABBICAP/*.* 
namescom.f90                  ,grep -i "CD_Balance_as_PC_of_Revenues"               ~/wrk/Midas/ABBICAP/*.* 
namescom.f90                  ,grep -i "CIAC_Addendum_to_Amortization"              ~/wrk/Midas/ABBICAP/*.* 
namescom.f90                  ,grep -i "CIAC_Amortization_Rate"                     ~/wrk/Midas/ABBICAP/*.* 
namescom.f90                  ,grep -i "CIAC_Cash_Contributions"                    ~/wrk/Midas/ABBICAP/*.* 
namescom.f90                  ,grep -i "CWIP_Balance"                               ~/wrk/Midas/ABBICAP/*.* 
namescom.f90                  ,grep -i "Capitial_Recovery_EXCLUDED_OPAT"            ~/wrk/Midas/ABBICAP/*.* 
namescom.f90                  ,grep -i "Cash_Dividend_Earnings"                     ~/wrk/Midas/ABBICAP/*.* 
namescom.f90                  ,grep -i "Cash_Interest_Earnings"                     ~/wrk/Midas/ABBICAP/*.* 
namescom.f90                  ,grep -i "Cash_Interest_Payments"                     ~/wrk/Midas/ABBICAP/*.* 
namescom.f90                  ,grep -i "Cash_Minimum_Balance"                       ~/wrk/Midas/ABBICAP/*.* 
namescom.f90                  ,grep -i "Cash_Received"                              ~/wrk/Midas/ABBICAP/*.* 
namescom.f90                  ,grep -i "Cost_of_Removal"                            ~/wrk/Midas/ABBICAP/*.* 
namescom.f90                  ,grep -i "Cumulated_Plant_Depreciation"               ~/wrk/Midas/ABBICAP/*.* 
namescom.f90                  ,grep -i "Cumulative_Depreciation"                    ~/wrk/Midas/ABBICAP/*.* 
namescom.f90                  ,grep -i "Customer_Deposits_Rate"                     ~/wrk/Midas/ABBICAP/*.* 
namescom.f90                  ,grep -i "Decommissioning_Rate"                       ~/wrk/Midas/ABBICAP/*.* 
namescom.f90                  ,grep -i "Deferred_Debit_Adjustment"                  ~/wrk/Midas/ABBICAP/*.* 
namescom.f90                  ,grep -i "Deferred_ITCs_Balance"                      ~/wrk/Midas/ABBICAP/*.* 
namescom.f90                  ,grep -i "Deferred_Tax_Adjustment"                    ~/wrk/Midas/ABBICAP/*.* 
namescom.f90                  ,grep -i "Dividend_70"                                ~/wrk/Midas/ABBICAP/*.* 
namescom.f90                  ,grep -i "Earnings_Decommissioning_Fund"              ~/wrk/Midas/ABBICAP/*.* 
namescom.f90                  ,grep -i "Earnings_LT_Investments"                    ~/wrk/Midas/ABBICAP/*.* 
namescom.f90                  ,grep -i "Earnings_Post_Retirement_Fund"              ~/wrk/Midas/ABBICAP/*.* 
namescom.f90                  ,grep -i "Earnings_ST_Investments"                    ~/wrk/Midas/ABBICAP/*.* 
namescom.f90                  ,grep -i "Economic_Assets_Adjustment"                 ~/wrk/Midas/ABBICAP/*.* 
namescom.f90                  ,grep -i "Equity_Risk_Adjustment"                     ~/wrk/Midas/ABBICAP/*.* 
namescom.f90                  ,grep -i "Extra_Ordinary_Expense"                     ~/wrk/Midas/ABBICAP/*.* 
namescom.f90                  ,grep -i "FABS87_Pension_Liab_Adj"                    ~/wrk/Midas/ABBICAP/*.* 
namescom.f90                  ,grep -i "FASB87_Intangible_Asset_Adj"                ~/wrk/Midas/ABBICAP/*.* 
namescom.f90                  ,grep -i "Fuel_Inventory_Change"                      ~/wrk/Midas/ABBICAP/*.* 
namescom.f90                  ,grep -i "Fuel_Inventory_Change_Out"                  ~/wrk/Midas/ABBICAP/*.* 
namescom.f90                  ,grep -i "Gas_Storage"                                ~/wrk/Midas/ABBICAP/*.* 
namescom.f90                  ,grep -i "Gas_Storage_Out"                            ~/wrk/Midas/ABBICAP/*.* 
namescom.f90                  ,grep -i "Gross_Book_Value"                           ~/wrk/Midas/ABBICAP/*.* 
namescom.f90                  ,grep -i "Gross_Plant_Value"                          ~/wrk/Midas/ABBICAP/*.* 
namescom.f90                  ,grep -i "Interest_Earnings"                          ~/wrk/Midas/ABBICAP/*.* 
namescom.f90                  ,grep -i "Interest_Payments"                          ~/wrk/Midas/ABBICAP/*.* 
namescom.f90                  ,grep -i "Intra_Company_Interest_Earnings"            ~/wrk/Midas/ABBICAP/*.* 
namescom.f90                  ,grep -i "LTI_Rate"                                   ~/wrk/Midas/ABBICAP/*.* 
namescom.f90                  ,grep -i "LT_Liabilities_Balance"                     ~/wrk/Midas/ABBICAP/*.* 
namescom.f90                  ,grep -i "Liabilities_NEC_Addendum"                   ~/wrk/Midas/ABBICAP/*.* 
namescom.f90                  ,grep -i "Materials_Supplies"                         ~/wrk/Midas/ABBICAP/*.* 
namescom.f90                  ,grep -i "Materials_Supplies_Out"                     ~/wrk/Midas/ABBICAP/*.* 
namescom.f90                  ,grep -i "Minibond_Annualized_Interest"               ~/wrk/Midas/ABBICAP/*.* 
namescom.f90                  ,grep -i "Minibond_Interest_Deposit"                  ~/wrk/Midas/ABBICAP/*.* 
namescom.f90                  ,grep -i "Minibond_Interest_Payment"                  ~/wrk/Midas/ABBICAP/*.* 
namescom.f90                  ,grep -i "Minibond_Principal_Deposit"                 ~/wrk/Midas/ABBICAP/*.* 
namescom.f90                  ,grep -i "Minibond_Principal_Payment"                 ~/wrk/Midas/ABBICAP/*.* 
namescom.f90                  ,grep -i "Net_Nuclear_Fuel"                           ~/wrk/Midas/ABBICAP/*.* 
namescom.f90                  ,grep -i "Net_Removal"                                ~/wrk/Midas/ABBICAP/*.* 
namescom.f90                  ,grep -i "Non_Cash_Pension"                           ~/wrk/Midas/ABBICAP/*.* 
namescom.f90                  ,grep -i "NucDecom_Discount_Rate"                     ~/wrk/Midas/ABBICAP/*.* 
namescom.f90                  ,grep -i "NucDecom_Liability_Addendum"                ~/wrk/Midas/ABBICAP/*.* 
namescom.f90                  ,grep -i "OCI_Adjustment"                             ~/wrk/Midas/ABBICAP/*.* 
namescom.f90                  ,grep -i "OCI_Decommissioning_Rate"                   ~/wrk/Midas/ABBICAP/*.* 
namescom.f90                  ,grep -i "OCI_Deferred_Tax_Adj"                       ~/wrk/Midas/ABBICAP/*.* 
namescom.f90                  ,grep -i "OCI_Post_Retirement_Rate"                   ~/wrk/Midas/ABBICAP/*.* 
namescom.f90                  ,grep -i "OUC_Fuel_Inventory"                         ~/wrk/Midas/ABBICAP/*.* 
namescom.f90                  ,grep -i "OUC_Materials_Inventory"                    ~/wrk/Midas/ABBICAP/*.* 
namescom.f90                  ,grep -i "OUC_Prepayments"                            ~/wrk/Midas/ABBICAP/*.* 
namescom.f90                  ,grep -i "Operating_Profits_Adjustment"               ~/wrk/Midas/ABBICAP/*.* 
namescom.f90                  ,grep -i "Other_Deferred_Credits"                     ~/wrk/Midas/ABBICAP/*.* 
namescom.f90                  ,grep -i "Paid_in_Capital"                            ~/wrk/Midas/ABBICAP/*.* 
namescom.f90                  ,grep -i "Plant_in_Service_Adjustment"                ~/wrk/Midas/ABBICAP/*.* 
namescom.f90                  ,grep -i "Post_Retirement_Rate"                       ~/wrk/Midas/ABBICAP/*.* 
namescom.f90                  ,grep -i "Rate_Assets_NEC"                            ~/wrk/Midas/ABBICAP/*.* 
namescom.f90                  ,grep -i "Rate_Base_Adjustment"                       ~/wrk/Midas/ABBICAP/*.* 
namescom.f90                  ,grep -i "Rate_Liabilities_NEC"                       ~/wrk/Midas/ABBICAP/*.* 
namescom.f90                  ,grep -i "Rate_Payable_Accounts"                      ~/wrk/Midas/ABBICAP/*.* 
namescom.f90                  ,grep -i "Rate_Receivable_Accounts"                   ~/wrk/Midas/ABBICAP/*.* 
namescom.f90                  ,grep -i "Reaquired_Debt_Gain"                        ~/wrk/Midas/ABBICAP/*.* 
namescom.f90                  ,grep -i "Regulatory_Deferred_Credits"                ~/wrk/Midas/ABBICAP/*.* 
namescom.f90                  ,grep -i "Retained_Earnings"                          ~/wrk/Midas/ABBICAP/*.* 
namescom.f90                  ,grep -i "STD_Minimum_Balance"                        ~/wrk/Midas/ABBICAP/*.* 
namescom.f90                  ,grep -i "STI_Rate"                                   ~/wrk/Midas/ABBICAP/*.* 
namescom.f90                  ,grep -i "Sale_ATL_Amortization"                      ~/wrk/Midas/ABBICAP/*.* 
namescom.f90                  ,grep -i "Sale_Deferred_Taxes_Adjustment"             ~/wrk/Midas/ABBICAP/*.* 
namescom.f90                  ,grep -i "Salvage_Value"                              ~/wrk/Midas/ABBICAP/*.* 
