MODULE namescom

  !******************************************************************
  ! Module : namescom
  ! Author : Mark S Gerber
  ! Created: 7/2/2011 6:23:20 PM
  ! Last change: MSG 11/2/2011 12:01:16 PM
  !******************************************************************

  ! DRILLING REPORT NAMES
  CHARACTER*1, PARAMETER :: BALANCE_SHEET_ITEM = 'B'
  CHARACTER*1, PARAMETER :: INCOME_REPORT_ITEM = 'I'
  CHARACTER*1, PARAMETER :: CASH_REPORT_ITEM = 'C'
  CHARACTER*1, PARAMETER :: TAX_REPORT_ITEM = 'T'
  CHARACTER*1, PARAMETER :: BALANCE_SHEET_ANNUAL_ITEM = 'A'

  ! NOTE IF THE EXPENSE FOR REVENUE IS IN THE EXPENSE FILE PUT THE NAME HERE
  INTEGER(KIND=2), PARAMETER :: ODEC_NA3_ID = 401
  INTEGER(KIND=2), PARAMETER :: LAST_INCOME_LINE = 80
  INTEGER(KIND=4), PARAMETER :: EXP_OFFSET_LINE = 30

  ! REVENUES TYPES
  INTEGER(KIND=2), PARAMETER :: BASE_RATES = 1
  INTEGER(KIND=2), PARAMETER :: ADJUSTMENT_CLAUSE = 2
  INTEGER(KIND=2), PARAMETER :: SECONDARY_SALES = 3
  INTEGER(KIND=2), PARAMETER :: OTHER_REVENUE = 4
  INTEGER(KIND=2), PARAMETER :: BTL_REVENUES = 5
  INTEGER(KIND=2), PARAMETER :: CATAWBA_REVENUES = 6
  INTEGER(KIND=2), PARAMETER :: GAS_REVENUES = 7
  INTEGER(KIND=2), PARAMETER :: UNBILLED_REVENUES = 8
  INTEGER(KIND=2), PARAMETER :: DEFERRED_REVENUES = 9
  INTEGER(KIND=2), PARAMETER :: RELATIONSHIP_REVENUES = 10
  INTEGER(KIND=2), PARAMETER :: CUSTOMER_REVENUES = 10
  INTEGER(KIND=2), PARAMETER :: RESIDENTIAL = 11
  INTEGER(KIND=2), PARAMETER :: COMMERCIAL = 12
  INTEGER(KIND=2), PARAMETER :: INDUSTRIAL = 13
  INTEGER(KIND=2), PARAMETER :: LIGHTING = 14
  INTEGER(KIND=2), PARAMETER :: BULK_POWER = 15
  INTEGER(KIND=2), PARAMETER :: NET_OF_TAX_BTL_REVENUES = 16
  INTEGER(KIND=2), PARAMETER :: CAPACITY_SALES = 17
  INTEGER(KIND=2), PARAMETER :: GOVERNMENT = 18
  INTEGER(KIND=2), PARAMETER :: PGA_ADJUSTMENT = 19
  INTEGER(KIND=2), PARAMETER :: COMPETITIVE_SALES = 20
  INTEGER(KIND=2), PARAMETER :: UTILITY_SALES = 21
  INTEGER(KIND=2), PARAMETER :: PRIOR_YEARS_METHOD_ADJUSTMENT = 26
  INTEGER(KIND=2), PARAMETER :: PRIOR_LEVEL_METHOD_ADJUSTMENT = 27
  INTEGER(KIND=2), PARAMETER :: OPERATING_METHOD_ADJUSTMENT = 28
  INTEGER(KIND=2), PARAMETER :: TOTAL_BASE_REVENUES = 29
  INTEGER(KIND=2), PARAMETER :: TOTAL_OPERATING_REVENUES = 30
  INTEGER(KIND=2), PARAMETER :: GAS_WHOLESALE_REVENUES = 31
  INTEGER(KIND=2), PARAMETER :: DERIVATIVE_PHYSICAL_REV_VARIABLE = 32
  INTEGER(KIND=2), PARAMETER :: DERIVATIVE_PHYSICAL_REV_FIXED = 33
  INTEGER(KIND=2), PARAMETER :: DERIVATIVE_FINANCIAL_REV_VARIABLE = 34
  INTEGER(KIND=2), PARAMETER :: DERIVATIVE_FINANCIAL_REV_FIXED = 35
  INTEGER(KIND=2), PARAMETER :: PAYROLL_TAXES = 65
  INTEGER(KIND=2), PARAMETER :: MARK_TO_MARKET = 66
  INTEGER(KIND=2), PARAMETER :: AFUDC_EQUITY = 67
  INTEGER(KIND=2), PARAMETER :: AFUDC_BORROWED = 68
  INTEGER(KIND=2), PARAMETER :: PCA_BTL_REVENUES = 69
  INTEGER(KIND=2), PARAMETER :: ASSOCIATED_COMPANY_INTEREST = 7
  INTEGER(KIND=2), PARAMETER :: PJM_MISO_RETAIL_TRANSMISSION = 10
  INTEGER(KIND=2), PARAMETER :: PJM_MISO_FES_TRANSMISSION = 19
  INTEGER(KIND=2), PARAMETER :: ASSOCIATED_COMPANY = 31
  INTEGER(KIND=2), PARAMETER :: PJM_MISO_REVENUES = 36
  INTEGER(KIND=2), PARAMETER :: FORFEITED_DISCOUNTS_RENTS = 37
  INTEGER(KIND=2), PARAMETER :: MISCELLANEOUS_SERVICE_REVENUES = 38
  INTEGER(KIND=2), PARAMETER :: RETAIL_GENERATION = 39
  INTEGER(KIND=2), PARAMETER :: WHOLESALE_GENERATION = 40
  INTEGER(KIND=2), PARAMETER :: ENERGY_EFFICIENCY = 41
  INTEGER(KIND=2), PARAMETER :: NET_INTERCO_SALE_LEASEBACK = 42
  INTEGER(KIND=2), PARAMETER :: TRANSITIONS = 43
  INTEGER(KIND=2), PARAMETER :: SLB_WHOLESALE_ASSOCIATED_CO = 44
  INTEGER(KIND=2), PARAMETER :: PJM_CONTRA = 45
  INTEGER(KIND=2), PARAMETER :: INTEREST_DIVIDEND_INCOME = 46

  ! EXPENSE TYPES
  INTEGER(KIND=2), PARAMETER :: LAST_EXPENSE_ITEM = 100
  INTEGER(KIND=2), PARAMETER :: TOTAL_EXPENSES_B4_TAXES = 1
  INTEGER(KIND=2), PARAMETER :: BTL_DECOMMISSIONING_LIABILITY = 8
  INTEGER(KIND=2), PARAMETER :: EXP_COLLECTION_IN_ADJ_CLAUSE = 9
  INTEGER(KIND=2), PARAMETER :: BTL_LEASE_CASH = 10
  INTEGER(KIND=2), PARAMETER :: FOSSIL_FUEL = 11
  INTEGER(KIND=2), PARAMETER :: PURCHASED_POWER = 12
  INTEGER(KIND=2), PARAMETER :: VARIABLE_OANDM = 13
  INTEGER(KIND=2), PARAMETER :: FIXED_OANDM = 14
  INTEGER(KIND=2), PARAMETER :: OTHER_OANDM = 15
  INTEGER(KIND=2), PARAMETER :: PURCHASED_GAS = 16
  INTEGER(KIND=2), PARAMETER :: PURCHASED_CAPACITY_TO_LEVEL_RM = 16
  INTEGER(KIND=2), PARAMETER :: OTHER = 17
  INTEGER(KIND=2), PARAMETER :: OWNED_NUCLEAR_FUEL = 18
  INTEGER(KIND=2), PARAMETER :: LEASED_NUCLEAR_FUEL = 19
  INTEGER(KIND=2), PARAMETER :: TOTAL_NUCLEAR_FUEL = 19
  INTEGER(KIND=2), PARAMETER :: DSM_EXPENSE = 20
  INTEGER(KIND=2), PARAMETER :: DSM_REBATE = 21
  INTEGER(KIND=2), PARAMETER :: ATL_BOOK_LEASE_EXPENSE = 22
  INTEGER(KIND=2), PARAMETER :: SERVICE_TRANSACTIONS = 23
  INTEGER(KIND=2), PARAMETER :: EMISSION_CREDITS = 24
  INTEGER(KIND=2), PARAMETER :: DOE_DECOMMISSIONING = 25
  INTEGER(KIND=2), PARAMETER :: DOE_DISPOSAL = 26
  INTEGER(KIND=2), PARAMETER :: CATAWBA_EXPENSES = 27
  INTEGER(KIND=2), PARAMETER :: BTL_EXPENSES = 28
  INTEGER(KIND=2), PARAMETER :: TRANSMISSION_OPERATION = 29
  INTEGER(KIND=2), PARAMETER :: TRANSMISSION_MAINTENANCE = 30
  INTEGER(KIND=2), PARAMETER :: DISTRIBUTION_OPERATION = 31
  INTEGER(KIND=2), PARAMETER :: DISTRIBUTION_MAINTENANCE = 32
  INTEGER(KIND=2), PARAMETER :: CUSTOMER_ACCOUNTS = 33
  INTEGER(KIND=2), PARAMETER :: CUSTOMER_SERVICES = 34
  INTEGER(KIND=2), PARAMETER :: SALES_EXPENSE = 35
  INTEGER(KIND=2), PARAMETER :: AG_OPERATIONS = 36
  INTEGER(KIND=2), PARAMETER :: AG_MAINTENANCE = 37
  INTEGER(KIND=2), PARAMETER :: AMORTIZATION = 38
  INTEGER(KIND=2), PARAMETER :: DEFERRED_REVENUE_AMORTIZATION = 39
  INTEGER(KIND=2), PARAMETER :: ATL_LEASE_AMORTIZATION = 40
  INTEGER(KIND=2), PARAMETER :: BTL_LEASE_AMORTIZATION = 41
  INTEGER(KIND=2), PARAMETER :: BOOK_DEPRECIATION = 42
  INTEGER(KIND=2), PARAMETER :: FEDERAL_TAX = 43
  INTEGER(KIND=2), PARAMETER :: STATE_TAX = 44
  INTEGER(KIND=2), PARAMETER :: LOCAL_TAX = 45
  INTEGER(KIND=2), PARAMETER :: PROPERTY_TAX = 46
  INTEGER(KIND=2), PARAMETER :: OTHER_TAX = 47
  INTEGER(KIND=2), PARAMETER :: CREDITS = 48
  INTEGER(KIND=2), PARAMETER :: INTEREST_EXPENSE = 49
  INTEGER(KIND=2), PARAMETER :: AFUDC_EQUITY = 50
  INTEGER(KIND=2), PARAMETER :: AFUDC_DEBT = 51
  INTEGER(KIND=2), PARAMETER :: INTEREST_ON_DEBT = 52
  INTEGER(KIND=2), PARAMETER :: DIVIDEND = 53
  INTEGER(KIND=2), PARAMETER :: TOTAL_EXPENSES = 54

  ! ADDITIONAL TYPES
  INTEGER(KIND=2), PARAMETER :: FIXED_CAPACITY_CHARGE = 1
  INTEGER(KIND=2), PARAMETER :: VARIABLE_OANDM_CHARGE = 2
  INTEGER(KIND=2), PARAMETER :: INVESTMENT_RETURN = 3
  INTEGER(KIND=2), PARAMETER :: FUEL_CHARGE = 4
  INTEGER(KIND=2), PARAMETER :: NUCLEAR_FUEL_CHARGE = 5
  INTEGER(KIND=2), PARAMETER :: PURCHASED_POWER_CHARGE = 6
  INTEGER(KIND=2), PARAMETER :: PURCHASED_CAPACITY_CHARGE = 7
  INTEGER(KIND=2), PARAMETER :: MISCELLANEOUS_OANDM_CHARGE = 8
  INTEGER(KIND=2), PARAMETER :: ARO_ACCRUAL = 9
  INTEGER(KIND=2), PARAMETER :: DEFERRED_ROA = 10
  INTEGER(KIND=2), PARAMETER :: STORM_COSTS = 11
  INTEGER(KIND=2), PARAMETER :: UNCOLLECTIBLES = 12

END MODULE namescom

