grep "BTL_Monthly_Interest_Income" ~/wrk/Midas/ABBICAP/*.*
grep "BTL_Monthly_Total_Other_Income" ~/wrk/Midas/ABBICAP/*.*
grep "Cash_Interest_on_Notes_Payable" ~/wrk/Midas/ABBICAP/*.*
grep "Monthly_Dividend_70_Earnings" ~/wrk/Midas/ABBICAP/*.*
grep "Monthly_Investment_Earnings" ~/wrk/Midas/ABBICAP/*.*
grep "Monthly_Issue_Expense_Amorts" ~/wrk/Midas/ABBICAP/*.*
grep "Monthly_LTD_Booked_Interest" ~/wrk/Midas/ABBICAP/*.*
grep "Monthly_LTD_Premium_Amort" ~/wrk/Midas/ABBICAP/*.*
grep "Monthly_LTD_Total_Interest" ~/wrk/Midas/ABBICAP/*.*
grep "Monthly_PS_Amort_Dividends" ~/wrk/Midas/ABBICAP/*.*
grep "Monthly_PS_Premium_Amort" ~/wrk/Midas/ABBICAP/*.*
grep "Monthly_Total_PS_Dividends" ~/wrk/Midas/ABBICAP/*.*
